### ISSUE TITLE
API invoke need authentication information

### ISSUE THREAD

**Issue by clojurians-org** [linkedin/datahub#1518]
i try to call api by reading the doc: 
  https://github.com/linkedin/WhereHows/tree/datahub/datahub-frontend
 
but it response with 401 Unauthorized
how i can pass the authentication information?
i have little knowledge for ember.js framework.
```
[op@my-200 WhereHows]$ curl -v http://localhost:9001/api/v2/browse?type=dataset
* About to connect() to localhost port 9001 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 9001 (#0)
> GET /api/v2/browse?type=dataset HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9001
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Date: Thu, 19 Dec 2019 01:52:54 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

**Comment by keremsahin1** [comment]
Hi @clojurians-org 

All mid-tier APIs require authentication. `@Security.Authenticated(Secured.class)`

If you first sign-in to DataHub and then paste that line to your web browser, you will be able to see the API response. Via `curl`, you are getting `401` because of missing authorization. Not sure how to send this through curl. This is actually a [Play](https://www.playframework.com/) endpoint rather than `ember.js`.

**Comment by clojurians-org** [comment]
thanks, i got it. 
i just want to simulate the ember.js call from datahub-web previously.
i will use web browser way. and i can display related info from rest.li interface for most situation.

i already read the most code, it's the datahub-web[ember.js+ts] -> datahub-frontend[play framework] -> gms[rest.li] -> metadata-dao-impl[metadata-restli-resource]

so another related question: how to configure ember.js's play api host-port.
current the datahub-frontend pack the datahub-web.
i only want to develop each module seperatedly by different port at first, then package it together to deploy. as the most web develop has the hot-load mechanism to quick visual feedback.

**Comment by cptran777** [comment]
Hey @clojurians-org , what you want to do is use the command within `datahub-web/packages/data-portal`: `ember s --proxy=<hostname>:<port>` which will allow you to develop UI code only and will include hot reload. We'll be sure to add this in the documentation in a future rollout.

**Comment by mars-lan** [comment]
@cptran777 I don't think it solve the authentication issue, but it sure is a good tip to be added to https://github.com/linkedin/datahub/tree/master/datahub-frontend

**Comment by cptran777** [comment]
Oooooh hahaha I misread based on the later comment of wanting to develop individually and getting hot reloading for each module. 

I think that the authentication module uses like a secured token so if you try and login through the browser and then send a request from browser it has that token, so to do the same thing with the curli call I assume you can simulate the attached token to whatever part of the browser version of the request contains that session information.

**Comment by mars-lan** [comment]
@cptran777 let's update [the doc](https://github.com/linkedin/datahub/tree/master/datahub-frontend) to include a section on this. A few screenshots will help.

**Comment by emailstonl** [comment]
one option can be as below
1. Authenticate and write cookie in text file 
2. use cookie from file to call api.

user@machine:~/git/datahub/docker$ curl -i -c cookie1.txt -d '{"username":"datahub", "password":"datahub"}' -H 'Content-Type: application/json' http://localhost:9001/authenticate
HTTP/1.1 200 OK
Set-Cookie: PLAY_SESSION=50dd1d9ea331dad76338731f6dd3bac7a12a58f7-auth_token=ZGF0YWh1YjoxNjAwNzYxMTUwMTgxOjcwN0UyOUU5QkFCRkYxMkRFOEJBNjAyMDI4NkM0M0E1MzgxRkNDMkY1NDkwNTZCQTY0Q0U0NzRCMjIwN0MwMzY%3D&uuid=3b8bcdaa-5340-4731-a205-fcbc5f44e083&user=datahub; SameSite=Lax; Path=/; HTTPOnly
Date: Tue, 22 Sep 2020 07:52:30 GMT
Content-Type: application/json
Content-Length: 91

{"status":"ok","data":{"username":"datahub","uuid":"3b8bcdaa-5340-4731-a205-fcbc5f44e083"}}user@machine:~/git/datahub/docker$ curl -i -b cookie1.txt http://localhost:9001/api/v2/browse?type=dataset&path=/prod
[1] 30079
user@machine:~/git/datahub/docker$ HTTP/1.1 200 OK
Date: Tue, 22 Sep 2020 07:52:58 GMT
Content-Type: application/json
Content-Length: 101

{"elements":[],"start":0,"count":0,"total":0,"metadata":{"totalNumEntities":0,"path":"","groups":[]}}

**Comment by mars-lan** [comment]
@emailstonl thanks for sharing the snippet. @igbopie could you help update the frontend doc with this info?

**Comment by emailstonl** [comment]
crated script to run all api listed in readme - https://github.com/emailstonl/datahub/blob/master/datahub-frontend/test/script/apiTest.sh

**Comment by mars-lan** [comment]
> script to run all api listed in readme - https://github.com/emailstonl/datahub/blob/master/datahub-frontend/test/script/apiTest.sh

Thanks. Updated the doc to include this info: https://github.com/linkedin/datahub/blob/master/datahub-frontend/README.md#api-debugging

Closing this issue now.
