### ISSUE TITLE
Searching for datasets with an embedded slash trigger an error

### ISSUE THREAD

**Issue by ben5448** [linkedin/datahub#1543]
**Describe the bug**
My hdfs datasets often have a path. When the path contains a slash, the query will fail with an internal server error. The problem appears to be the query sent to elastic is not being escaped. I verified the data is in elastic, mysql and neo4j. If I search in kibana using a term like foo/bar, it will generate an error. Searching with foo@2fbar works as it should.

**To Reproduce**
Steps to reproduce the behavior in DataHub:
1. Launch DataHub.
2. Turn on developer tools to see requests and responses.
3. Search for a dataset like "foo/bar".
4. The search will fail with status 500, internal server error.

Steps to reproduce the problem in gms:
1. Launch back end services and gms.
2. Send a curl request such as: curl "http://localhost:8080/datasets?q=search&input=foo%2fbar" -X GET -H 'X-RestLi-Protocol-Version: 2.0.0' -H 'X-RestLi-Method: finder' | jq
3. See an error like below:
{
  "exceptionClass": "com.linkedin.restli.server.RestLiServiceException",
  "message": "INTERNAL SERVER ERROR",
  "stackTrace": "com.linkedin.restli.server.RestLiServiceException [HTTP Status:500]: INTERNAL SERVER ERROR\n\tat com.linkedin.restli.internal.server.RestLiMethodInvoker.doInvoke(RestLiMethodInvoker.java:191)\n\tat com.linkedin.restli.internal.server.RestLiMethodInvoker.invoke(RestLiMethodInvoker.java:290)\n\tat com.linkedin.restli.internal.server.filter.FilterChainDispatcherImpl.onRequestSuccess(FilterChainDispatcherImpl.java:47)\n\tat com.linkedin.restli.internal.server.filter.RestLiFilterChainIterator.onRequest(RestLiFilterChainIterator.java:81)\n\tat com.linkedin.restli.internal.server.filter.RestLiFilterChain.onRequest(RestLiFilterChain.java:56)\n\tat com.linkedin.restli.server.BaseRestLiServer.handleResourceRequest(BaseRestLiServer.java:208)\n\tat com.linkedin.restli.server.RestRestLiServer.handleResourceRequest(RestRestLiServer.java:167)\n\tat com.linkedin.restli.server.RestRestLiServer.handleResourceRequest(RestRestLiServer.java:136)\n\tat com.linkedin.restli.server.RestRestLiServer.doHandleRequest(RestRestLiServer.java:119)\n\tat com.linkedin.restli.server.RestRestLiServer.handleRequest(RestRestLiServer.java:95)\n\tat com.linkedin.restli.server.RestLiServer.handleRequest(RestLiServer.java:130)\n\tat com.linkedin.restli.server.DelegatingTransportDispatcher.handleRestRequest(DelegatingTransportDispatcher.java:70)\n\tat com.linkedin.r2.filter.transport.DispatcherRequestFilter.onRestRequest(DispatcherRequestFilter.java:66)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:59)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.TimedNextFilter.onRequest(TimedNextFilter.java:55)\n\tat com.linkedin.r2.filter.transport.ServerQueryTunnelFilter.onRestRequest(ServerQueryTunnelFilter.java:58)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:59)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.TimedNextFilter.onRequest(TimedNextFilter.java:55)\n\tat com.linkedin.r2.filter.message.rest.RestFilter.onRestRequest(RestFilter.java:50)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:59)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.FilterChainImpl.onRestRequest(FilterChainImpl.java:96)\n\tat com.linkedin.r2.filter.transport.FilterChainDispatcher.handleRestRequest(FilterChainDispatcher.java:70)\n\tat com.linkedin.r2.transport.http.server.HttpDispatcher.handleRequest(HttpDispatcher.java:95)\n\tat com.linkedin.r2.transport.http.server.AbstractR2Servlet.service(AbstractR2Servlet.java:105)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat com.linkedin.restli.server.spring.ParallelRestliHttpRequestHandler.handleRequest(ParallelRestliHttpRequestHandler.java:76)\n\tat org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:72)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:505)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)\n\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.linkedin.metadata.dao.exception.ESQueryException: Search query failed:\n\tat com.linkedin.metadata.dao.search.ESSearchDAO.executeAndExtract(ESSearchDAO.java:101)\n\tat com.linkedin.metadata.dao.search.ESSearchDAO.search(ESSearchDAO.java:117)\n\tat com.linkedin.metadata.restli.BaseSearchableEntityResource.search(BaseSearchableEntityResource.java:106)\n\tat com.linkedin.dataset.rest.resources.Datasets.search(Datasets.java:190)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat com.linkedin.restli.internal.server.RestLiMethodInvoker.doInvoke(RestLiMethodInvoker.java:159)\n\t... 68 more\nCaused by: ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]\n\tat org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)\n\tat org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:526)\n\tat org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:502)\n\tat org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:409)\n\tat org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:382)\n\tat org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:323)\n\tat com.linkedin.metadata.dao.search.ESSearchDAO.executeAndExtract(ESSearchDAO.java:96)\n\t... 76 more\n\tSuppressed: org.elasticsearch.client.ResponseException: POST http://localhost:9200/datasetdocument/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512: HTTP/1.1 400 Bad Request\n{\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\":\"Failed to parse query [foo/bar]\",\"index_uuid\":\"GjUDL87sTPWdm2K-xvGiag\",\"index\":\"datasetdocument\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"datasetdocument\",\"node\":\"U62pI_-AR4qCnrokwk8chw\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"Failed to parse query [foo/bar]\",\"index_uuid\":\"GjUDL87sTPWdm2K-xvGiag\",\"index\":\"datasetdocument\",\"caused_by\":{\"type\":\"parse_exception\",\"reason\":\"Cannot parse 'foo/bar': Lexical error at line 1, column 8.  Encountered: <EOF> after : \\\"/bar\\\"\",\"caused_by\":{\"type\":\"token_mgr_error\",\"reason\":\"Lexical error at line 1, column 8.  Encountered: <EOF> after : \\\"/bar\\\"\"}}}}]},\"status\":400}\n\t\tat org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)\n\t\tat org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)\n\t\tat org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)\n\t\tat org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)\n\t\tat org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)\n\t\tat org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)\n\t\tat org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)\n\t\tat org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)\n\t\tat org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)\n\t\tat org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)\n\t\tat org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)\n\t\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)\n\t\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)\n\t\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)\n\t\tat org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)\n\t\tat org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)\n\t\t... 1 more\n",
  "status": 500
}

**Expected behavior**
The search should return any matching datasets the same way as if you entered "foo".

**Desktop (please complete the following information):**
 - OS: Linux 18.04
 - Chrome
 - Version 79.0.3945.130 (Official Build) (64-bit)
- curl
- Version 7.65.3 (x86_64-conda_cos6-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1d zlib/1.2.11 libssh2/1.8.2 Release-Date: 2019-07-19

**Additional context**

**Comment by keremsahin1** [comment]
Hi @ben5448 
Thanks for creating the issue. You are absolutely right. Elasticsearch needs forward slash be escaped. This issue has been addressed for LinkedIn internal DataHub but fix wasn't able to reach to Github yet. Just pushed the fix right now and this should be solved.

**Comment by ben5448** [comment]
The patch only addresses the forward slash character. Elasticsearch has quite a few special characters. I think a better fix would be to encode the filter strings. Elasticsearch already decodes the strings.

**Comment by keremsahin1** [comment]
This is definitely a quick work-around for forward slash character. That is the only case which caused trouble for us as well because of path searches.

However, there is more to the story and simply escaping all reserved characters is not a viable solution either.  Escaping all reserved characters are killing the regex search functionality which can be achived using those characters. DataHub allows you to run regex queries and we don't want to give up on that by escaping all reserved characters. However, for the time being, we just decided not to allow usage of forward slash as a regex query.

https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-query-string-query.html#_regular_expressions

The long term solution that's in our backlog for this is to separate out text search & regex search APIs and change UX to allow for that. Users should be able to decide if they want to run a text search or regex search using a checkmark, or any better design. By this way, text search backend API will be able to safely assume that every reserved character should be escaped.

Would you like to contribute this feature? A good starting point would be this file:
https://github.com/linkedin/datahub/blob/master/metadata-dao/src/main/java/com/linkedin/metadata/dao/BaseSearchDAO.java

**Comment by ben5448** [comment]
I didn't notice your question above. I am interested in contributing features to the product. Handling these characters is useful, but not a high priority for me at this point. Once I see your roadmap, there might be some areas I can help with as I get more familiar with the code. Right now I am evaluating whether this is the right platform for our data catalog.

**Comment by ben5448** [comment]
Since you have the regex plan on the roadmap, I am going to close the issue dealing specifically with the slash character. That character now works.
