### ISSUE TITLE
Is there a product roadmap

### ISSUE THREAD

**Issue by ben5448** [linkedin/datahub#1544]
Is there a planned set of features and release plan (at least rough plan)? This would help understand whether the project might be suitable for my needs. It would also prevent submitting feature requests for items already on the schedule.

**Comment by keremsahin1** [comment]
Thanks @ben5448. We'll be releasing our 2020 roadmap for DataHub within next week. Will ping you once it is out.

**Comment by keremsahin1** [comment]
Hi @ben5448 , rough roadmap for 2020 is out.
https://github.com/linkedin/datahub/blob/master/docs/roadmap.md
