### ISSUE TITLE
Enrich bootstrap data with a good user story

### ISSUE THREAD

**Issue by keremsahin1** [linkedin/datahub#1547]

**Comment by mars-lan** [comment]
Assign to @nagarjunakanamarlapudi to open source our internal demo bootstrap scripts

**Comment by jjoyce0510** [comment]
@nagarjunakanamarlapudi Is this ticket still relevant? 

What exactly is in scope here?

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
