### ISSUE TITLE
Move Docker containers under /linkedin or /datahub account

### ISSUE THREAD

**Issue by keremsahin1** [linkedin/datahub#1548]
Right now, all Docker images are deployed to my personal Docker Hub account. This is not quite maintainable and doesn't look professional as well. At the time, I wasn't able to use Linkedin's organization account (owner left the company) to deploy images, therefore, I've deployed under my personal repo.

@mars-lan is now one of the owner of LinkedIn organization account in Docker Hub. We should consider starting to deploy Docker images to there. Alternatively, we can create a new organization called DataHub and deploy images there.

**Comment by keremsahin1** [comment]
GitHub Packages + Actions seem like a compelling alternative to Docker Hub. We should definitely 
consider that rather than managing a 3rd party integration.

https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/using-github-packages-with-github-actions#publishing-a-package-using-an-action

Burrow folks seem to be using this:
https://github.com/orgs/linkedin/packages

WDTY @mars-lan ?

**Comment by mars-lan** [comment]
Yeah definitely seems like the new trend. Let's give it a try.

**Comment by keremsahin1** [comment]
@mars-lan Wanna keep this open for "GitHub Packages" change as well or are you planning to create a new issue for that?

**Comment by mars-lan** [comment]
Actually the benefit of using GitHub Packages over Docker Hub isn't very clear to me that's why I decided not to do it in the same PR. Let's keep the discussion open here.

**Comment by keremsahin1** [comment]
Hmmm, I also don't think it's a must. The only benefit I can think of is that we have everything (code+images) together in one repo. Github repo will show those packages under /packages tab. They will be easily searchable on Github (package search). You can also deploy other artifacts to Github package registry (npm, maven). Although we don't have a req to deploy such artifacts, in case we want it, all deployables will be under same repo.

I'm not exactly sure about Docker images but I saw it for other Github packages that Github shows the users of a specific package as well. It might be good to see what other repos are depending on our Docker images.

**Comment by mars-lan** [comment]
The current setup seems to work reasonably well. Let's close this issue and reopen it in the future if we choose to migrate from Docker Hub to GitHub Packages

**Comment by mars-lan** [comment]
@jplaisted FYI

Turns out that it's not currently possible to use docker-compose to pull from GH Packages!!! 

https://github.com/containerd/containerd/issues/3291

However, the GH folks are working on a fix. Will wait for that rollout before making the changes in the quickstart script.
