### ISSUE TITLE
Make mae-consumer-job container wait for Elasticsearch & Neo4j

### ISSUE THREAD

**Issue by keremsahin1** [linkedin/datahub#1550]

**Comment by arunvasudevan** [comment]
I think Mae-consumer-job waiting for Neo4j is handled in #1628

**Comment by keremsahin1** [comment]
Yes, thank you for that. Would you be interested in taking this and #1549 and send a PR? Should be fairly trivial.

**Comment by mars-lan** [comment]
Fixed by https://github.com/linkedin/datahub/pull/1687
