### ISSUE TITLE
User urn does not handle dashes consistently

### ISSUE THREAD

**Issue by ben5448** [linkedin/datahub#1554]
**Describe the bug**
Dashes are accepted as part of the user urn in most cases, but are treated as invalid when processing owners in the mae job. The problem comes from the regex expression used to extract urn. As a result, the mae job will throw an exception when processing owners for any owner where ther owner's urn contains a dash.

A patch is attached.

[patchfile.txt](https://github.com/linkedin/datahub/files/4188566/patchfile.txt)

**To Reproduce**
1. Create a user with a urn that contains a dash such as urn:li:corpuser:foo-bar.
2. Create a dataset record where the dataset is owned by urn:li:corpuser:foo-bar.
3. MAE job throws an exception:
ERROR c.l.m.builders.search.BuilderUtils.getCorpUserOwners(47) - CorpuserUrn syntax error

**Expected behavior**
The urn should not trigger an exception.

**Desktop (please complete the following information):**
 - Ubuntu 18.04

**Comment by mars-lan** [comment]
Thanks. The patch looks reasonable. @ben5448  could you create a PR directly so we can merge the change in?

**Comment by keremsahin1** [comment]
Thanks for PR @ben5448 !
