### ISSUE TITLE
Allow users to search by tags

### ISSUE THREAD

**Issue by ben5448** [linkedin/datahub#1556]
**Is your feature request related to a problem? Please describe.**
The tags array in teh DatasetProperties property is a convenient place to stash information about the dataset that is not stored elsewhere. For example I am storing information about the job that created the stream. It would be great to be able to find the dataset based on searching for that data.

**Describe the solution you'd like**
I would like to be able to search for datasets based on the property. For example I could have job 12345 that creates a dataset. By searching for tags:job=12345, I can see which dataset was impacted by a failure in that job and all the downstream datasets.

**Describe alternatives you've considered**
The fix requires the mae job to store tags in elastic so they can be searched. Depending on how this information is formatted, the search string might need to be escaped. For example:

***Option 1: separate tag name and value using a colon
The colon is commonly used to separate a name and value. For example: job:1234, product:foo... If we wanted to go this route, the required changes are:
1. Add "tags" to elastic datasetdocument schema
2. Change MAE job to populate tags using the colon as a separator.
3. Escape the incoming colon search character so users can enter "tags:job:1234" or change the query to escape search strings when sent to elastic. This is a little tricky because the "tags" colon needs to be preserved.
4. Add "tags" as a searchable term in DataHub search dropdown with origin, name, owners and platform. (Should add "hasSchema", "hasOwners" and "description" at the same time since those are also searchable).

One negative of this approach is the search term "tags:job:1234" has 2 colons which looks odd.

***Option 2: separate tag name and value using another character such as equals sign
We can use another character to separate a name and value that is not a special character for elastic. For example: job=1234, product=foo... If we wanted to go this route, the required changes are:
1. Add "tags" to elastic datasetdocument schema
2. Change MAE job to populate tags using an equals sign as a separator.
3. The search query "tags:job=1234" does not need to be escaped.
4. Add "tags" as a searchable term in DataHub search dropdown with origin, name, owners and platform. (Should add "hasSchema", "hasOwners" and "description" at the same time since those are also searchable).

**Additional context**
I can provide a patch with the equal operator solution. Have not looked into handling the colon between name and value without impacting the search filter (tags) or any other terms in the search.

**Comment by keremsahin1** [comment]
Hi @ben5448 
Thanks for this carefully thought suggestion. I will take one step back here and suggest some other approaches.

First of all, `job` seems like a separate entity for your use case. Although we don't have this in the open source DataHub, we have this in LinkedIn internal DataHub. Modeling `job` as an entity in `GMA` would be your first priority. Refer to https://github.com/linkedin/datahub/blob/master/docs/how/entity-onboarding.md.

After doing that, the rest will be fairly easier. Essentially, you need to setup relationship between two entities, `dataset` and `job`. Rather than overloading `tags`, I would suggest you to model this relationship as a separate [aspect](https://github.com/linkedin/datahub/blob/master/docs/what/aspect.md) for either `dataset` or `job`.

After storing this metadata in your data store, you need to decide how to serve your queries. You have two options: search or graph queries. If you only try to have 1-hop queries, search is fine like in your case: `give me downstream datasets of this job` or `give me upstream jobs for this dataset` etc. If you want to extend your use cases to 2+ hops, graph is the right way to go such as `give me all datasets this user impacted`. You need to connect users to jobs and jobs to datasets.

Hope this answers your question,
Kerem

**Comment by mars-lan** [comment]
Agree with @keremsahin1  that jobs might need to be made a first class entity (which they are inside of LinkedIn). That said, adding the general tag-based search capability definitely seems like a no-brainer. 

IMHO using `=` or `:` as separator seems like a bit of a hack though. We should support indexing of map-of-primitives through the use of `Object` type in ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html That, however, is a much bigger job :P

**Comment by mars-lan** [comment]
Related issue: https://github.com/linkedin/datahub/issues/1730

**Comment by cobolbaby** [comment]
Custom fields can already be displayed currently, can we advance the development of this feature?

- Search and filter according to Tags
- Search results page displays Tags

**Comment by camelliazhang** [comment]
@mars-lan yes, so far our search model support primitive datatypes or array of primitive datatypes,  maps are harder and I would suggest not go down this road (to support map). Looking  at #1730, customProperties is a map [string, string], I wonder what are the use case that motivate such fields in the first place?

As a mid-term solution, we can certainly add a tags field for search document model, as an array of strings. The tag should belong to one categories though. Good examples are: owners for a dataset, skills for a person. These are all well supported today. Essentially, we are breaking up the map to a few arrays with a fixed key. 

For @ben5448's use case, I would suggest not mixing the relationship into the search document. 
If graph is not something you would consider, one solution with search could be: 
- Add a jobs tag field for dataset document as array of strings, example jobs field for a dataset [job1, job2, job3], then if you can search all the datasets that tagged with a specific job such as job1. 
- Add a product tag field for dataset document as array of strings, similar to the above.
- ...

**Comment by mars-lan** [comment]
@cobolbaby I'd also encourage to join our [slack workspace](https://join.slack.com/t/datahubspace/shared_invite/zt-dkzbxfck-dzNl96vBzB06pJpbRwP6RA) (if haven't done so already) to interact with the rest of the community.

**Comment by mars-lan** [comment]
> As a mid-term solution, we can certainly add a tags field for search document model, as an array of strings. The tag should belong to one categories though. Good examples are: owners for a dataset, skills for a person. These are all well supported today. Essentially, we are breaking up the map to a few arrays with a fixed key.

Alternatively we can concat tag name & value into a string, e.g. `tag:val`, and stuff them into a single array.

**Comment by jjoyce0510** [comment]
Hi @keremsahin1. 

Is this issue still relevant?

Since the date of opening, we have added formal support for Tags as top-level entities and provide capability to search based on entity-level tag associations.

John

**Comment by shirshanka** [comment]
Closing this, since Tags are now supported as a top-level entity. 
https://datahubproject.io/docs/features#tags
