### ISSUE TITLE
Pagination in datasets folder with more 100 datasets doesn't work

### ISSUE THREAD

**Issue by afranzi** [linkedin/datahub#1560]
**Describe the bug**
We are testing the Datahub solution having a dataset folder with more than 100 datasets. 

The API call
```
http://our_host:9001/api/v2/browse?type=dataset&path=/prod/dwh/public&count=100&start=0
```

And the response:
```
   "elements": ...
   "start":0,
   "count":320,
   "total":320,
   "metadata":{ 
      "totalNumEntities":320,
      "path":"/prod/dwh/public",
      "groups":[ 

      ]
   }
```

It seems that the count field is wrong since it's using the total value instead of the current page.

**Comment by keremsahin1** [comment]
Hi @afranzi, thanks for reporting this. I was able to reproduce this issue on my end. I will work on a fix.

**Comment by keremsahin1** [comment]
This should be fixed by https://github.com/linkedin/datahub/commit/3d64c45fa6d3d4dbac283c5e78073c6fef91d501

**Comment by afranzi** [comment]
Hi @keremsahin1 , I've tried the fix 3d64c45, but the page buttons are not working.

**Comment by keremsahin1** [comment]
Hi @afranzi 
Can you please share the error log you're getting on `datahub-frontend` container if page buttons are not working?

**Comment by keremsahin1** [comment]
@afranzi 
Are you referring to this https://github.com/linkedin/datahub/issues/1563 for page buttons? If that's the case, I believe these two issues are not related. Another fix is needed for that.

**Comment by mars-lan** [comment]
Let's close this for now and track the page button issue separately in https://github.com/linkedin/datahub/issues/1563
