### ISSUE TITLE
Show Dataset Description in the dataset view

### ISSUE THREAD

**Issue by afranzi** [linkedin/datahub#1561]
It would be great to show the dataset description in the dataset view.

Currently, the dataset description is being shown at the Search view.

<img width="516" alt="Screenshot 2020-02-16 at 21 56 02" src="https://user-images.githubusercontent.com/3647015/74612638-6804fe00-5107-11ea-8ba4-f906f6fb28d8.png">

It would be great if it's already shown at the dataset view too.

<img width="1170" alt="Screenshot 2020-02-16 at 21 56 27" src="https://user-images.githubusercontent.com/3647015/74612647-8539cc80-5107-11ea-960c-964a33c5aefa.png">

**Comment by mars-lan** [comment]
@chris-blanco seems like a reasonable request?

**Comment by keremsahin1** [comment]
Thanks for PR @afranzi !
