### ISSUE TITLE
Pagination in userownership-datasets view doesn't work

### ISSUE THREAD

**Issue by afranzi** [linkedin/datahub#1563]
**Describe the bug**
It seems that the **userownership-datasets** view pagination doesn't work. It shows the proper number of pages but it doesn't trigger any action.

Also, If I navigate to `http://host:9001/#/user/urn:li:corpuser:airflow/userownership-datasets?page=4`

The search query doesn't take into account the page.
```
http://host:9001/api/v2/search?input=owners%3Aairflow&type=dataset&start=0&count=10
```

```
{
  "count": 10,
  "elements": [....],
  "searchResultMetadatas": [
    {
      "aggregations": { "dwh": 87 },
      "name": "platform"
    },
    {
      "aggregations": { "prod": 87 },
      "name": "origin"
    }
  ],
  "start": 0,
  "total": 87
}
```

**Comment by mars-lan** [comment]
Likely related to https://github.com/linkedin/datahub/issues/1560?

**Comment by keremsahin1** [comment]
Hi @theseyi 
Seems like page number doesn't change search API call. Whatever the page number is, it's always `start=0&count=10`. Can you take a look at this?

**Comment by theseyi** [comment]
@afranzi we will take a look at this asap

**Comment by theseyi** [comment]
@afranzi for this view, the current page is not currently serialized in the url, the navigating using the url will not produce the desired effect. This needs to be implemented first, so we will update this internally then move port here. Thanks for filing

**Comment by cptran777** [comment]
Looks like this should have actually been resolved by [this PR](https://github.com/linkedin/datahub/pull/1806) . Please re-open if it's still an issue.
