### ISSUE TITLE
Handle autocollected information and hand-curated data gracefully

### ISSUE THREAD

**Issue by ben5448** [linkedin/datahub#1578]
**Is your feature request related to a problem? Please describe.**
When a facet is updated, the new facet replaces the old facet. This means if a script gathers data to build a facet and submits that, the new definition replaces any existing information. Some examples where this causes issues are on the ownership and documentation links pages where users can add/remove items.

Key requirements:
- Be able to update autocollected information without overwriting hand-curated changes.
- Still have the ability for users to edit data manually.
- Search both autocollected data and hand-curated data together.

**Describe the solution you'd like**
One option is to create 2 facets, much like the CorpUser and CorpEditableUser info facets. A difference here is the facets will have the same type data (owners, doc links). The data would be merged in elastic for integrated query capabilities. Autocollected data would not be editable (Maybe we should have an ability to hide an item. Deleting would be ineffective because the item would just be recreated on the next collection cycle.) The facets would have to be merged for display purposes.

**Describe alternatives you've considered**
Another option would be to tag each item to indicate whether the items are auto-collected or hand-curated. The MCE job would have to pull the existing record (if it exists) and update the auto-collected information. Hand-curated data would be editable as it is now. If we support "delete" on auto-collected information, that would really need to hide the item and we would need a mechanism to see the hidden items in case we needed to restore them.

**Additional context**

**Comment by mars-lan** [comment]
The general pattern we use internally for this is to have 2 aspects, one for static/auto-collected and one for dynamic/user-provided, and either have the UI or a special endpoint to perform the "resolution". Given that the resolution logic is likely to be very domain-specific, providing a general solution for this may be difficult.

**Comment by nagarjunakanamarlapudi** [comment]
Yes, we internally we intend to have UserEditableInfo as an aspect for any metadata that can be edited by users. 
E.g., CorpUser can have an aspect CorpUserEditableInformation. This can hold metadata which is editable by a user. 

This will enable us to track the versions of both system provided metadata and user edited metadata independently. The frontend can be made editable only for the user editable information. 

Search can be enabled on both of these fields. One potential way to do that is using copy_to functionality of ES https://www.elastic.co/guide/en/elasticsearch/reference/current/copy-to.html

**Comment by cobolbaby** [comment]
Is there a specific case or demo?

**Comment by jjoyce0510** [comment]
Hi there! 

@ben5448 We have continued to use the approach ^ to solve these cases, wherein we have a UI-Editable and Non-Editable version of some piece of Metadata. For example, EditableSchemaMetadata.pdl and SchemaMetadata.pdl.

Are there other pieces of information you'd especially like to see this applied to? What I'm reading above is...
- Ownership
- Documentation

Please let us know so we can prioritize accordingly.

Thanks
John

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
