### ISSUE TITLE
Support markdown in the description

### ISSUE THREAD

**Issue by ben5448** [linkedin/datahub#1579]
**Is your feature request related to a problem? Please describe.**
Descriptions would be easier to read/understand if they supported formatting such as markdown. It would also be great if users could edit the description to add details.

**Describe the solution you'd like**
Use a control for displaying descriptions that support markdown and editing.

**Describe alternatives you've considered**
Would like to see a solution that merges auto-collected descriptions and hand-curated.

**Additional context**

**Comment by keremsahin1** [comment]
Hi @ben5448 
Are you talking about descriptions for `dataset`?

**Comment by ben5448** [comment]
Yes. I should have been more specific. That field is now shown at the top of all the datasets pages, but there is no way to edit it. Some of the text I am pulling in is in markdown, but it gets turned into just a block of text.

**Comment by keremsahin1** [comment]
I see. The description field for a dataset is generally parsed from the SOT platform. It gets updated automatically if this is updated at the SOT. This is the approach we take when modelling things. Only user curated metadata is editable through DataHub and in this case, DataHub becomes the SOT for this metadata. What you're suggesting is to update same metadata both from SOT and through DataHub UI. For data consistency, in this case DataHub should go ahead and update the platform which this metadata is extracted from which is SOT? For user created documentation, we have a `Docs` tab which you can add any extra information about the dataset itself.

Supporting Markdown for description is definitely a good idea and we'll evaluate it. What do you think @theseyi ?

**Comment by mars-lan** [comment]
FYI we're already working on a similar feature internally.

**Comment by theseyi** [comment]
We can render Markdown content in the header, however there are challenges to be considered around layout and visual representation within the context of the header description. For example, Markdown text with title format may compete with the page title, at best we may support a Markdown subset. The `Docs` would be the better options for rich-text content.

However, once we resolve the details around this we will implement in a future release.

**Comment by shirshanka** [comment]
Closing now that this is done.
