### ISSUE TITLE
How to create fabric?

### ISSUE THREAD

**Issue by damon09273** [linkedin/datahub#1580]
I've used Restful API ref from [gms](https://github.com/linkedin/datahub/tree/master/gms)  to create dataset successfully, but how can I create another fabric type for dataset? e.g bigquery

According my testing, dataset created successfully by specify default fabric types(prod, dev, corp) or the creation will failed which mean even HTTP return 201, I can't see the dataset been created.

**Comment by mars-lan** [comment]
Seems like what you're referring (bigquery) to is the data platform not fabric. You should be able to specify that without explicit creation of the platform. Could you share your curl command that failed?

**Comment by damon09273** [comment]
Thank you for your response. 

The reason I consider to put bigquery as a fabric is because bigquery has the dataset which include many tables, but a data platform entity only one level for tables, so I can't grouping tables by a dataset, therefore I consider move bigquery to fabric level, same issue also happens on RDBMS, because RDBMS has the database which include may tables.

Table structure graph for platform to fabric level：
datasets > bigquery > dataset A > tables 
                                     > dataset B > tables

datasets > mysql > database A > tables 
                                > database B > tables

I’m appreciated if you have time to give another idea.

The curl command.
`curl 'http://localhost:8080/datasets/($params:(),name:cool,origin:BIGQUERY,platform:urn%3Ali%3AdataPlatform%3Afoo)/snapshot' -X POST -H 'X-RestLi-Method: create' -H 'X-RestLi-Protocol-Version:2.0.0' --data '{"aspects":[{"com.linkedin.common.Ownership":{"owners":[{"owner":"urn:li:corpuser:fbar","type":"DATAOWNER"}],"lastModified":{"time":0,"actor":"urn:li:corpuser:fbar"}}},{"com.linkedin.dataset.UpstreamLineage":{"upstreams":[{"auditStamp":{"time":0,"actor":"urn:li:corpuser:fbar"},"dataset":"urn:li:dataset:(urn:li:dataPlatform:foo,barUp,BIGQUERY)","type":"TRANSFORMED"}]}},{"com.linkedin.common.InstitutionalMemory":{"elements":[{"url":"https://www.linkedin.com","description":"Sample doc","createStamp":{"time":0,"actor":"urn:li:corpuser:fbar"}}]}},{"com.linkedin.schema.SchemaMetadata":{"schemaName":"FooEvent","platform":"urn:li:dataPlatform:foo","version":0,"created":{"time":0,"actor":"urn:li:corpuser:fbar"},"lastModified":{"time":0,"actor":"urn:li:corpuser:fbar"},"hash":"","platformSchema":{"com.linkedin.schema.KafkaSchema":{"documentSchema":"{\"type\":\"record\",\"name\":\"MetadataChangeEvent\",\"namespace\":\"com.linkedin.mxe\",\"doc\":\"Kafka event for proposing a metadata change for an entity.\",\"fields\":[{\"name\":\"auditHeader\",\"type\":{\"type\":\"record\",\"name\":\"KafkaAuditHeader\",\"namespace\":\"com.linkedin.avro2pegasus.events\",\"doc\":\"Header\"}}]}"}},"fields":[{"fieldPath":"foo","description":"Bar","nativeDataType":"string","type":{"type":{"com.linkedin.schema.StringType":{}}}}]}}],"urn":"urn:li:dataset:(urn:li:dataPlatform:foo,cool,BIGQUERY)"}' -v
`

**Comment by keremsahin1** [comment]
Hi @damon09273 
You can consider using seperators in the dataset name to capture the hierarchy rather than overloading fabric field in dataset URN.

Instead of `urn:li:dataset:(urn:li:dataPlatform:foo,cool,BIGQUERY)`, you could define it as `urn:li:dataset:(urn:li:dataPlatform: BIGQUERY, foo/cool,<<your_fabric>>)`.

**Comment by damon09273** [comment]
@keremsahin1 Thank you for your suggestion.

In this solution, how endpoint look like?  
I tried below command but return 400, it seems like that `members/dcard` in URI cause this problem.
 
`curl 'http://localhost:8080/datasets/($params:(),name:members/dcard,origin:PROD,platform:urn%3Ali%3AdataPlatform%3Abigquery)/snapshot' -X POST -H 'X-RestLi-Method: create' -H 'X-RestLi-Protocol-Version:2.0.0' --data '{"aspects":[{"com.linkedin.common.Ownership":{"owners":[{"owner":"urn:li:corpuser:fbar","type":"DATAOWNER"}],"lastModified":{"time":0,"actor":"urn:li:corpuser:fbar"}}},{"com.linkedin.dataset.UpstreamLineage":{"upstreams":[{"auditStamp":{"time":0,"actor":"urn:li:corpuser:fbar"},"dataset":"urn:li:dataset:(urn:li:dataPlatform:bigquery,barUp,PROD)","type":"TRANSFORMED"}]}},{"com.linkedin.common.InstitutionalMemory":{"elements":[{"url":"https://www.linkedin.com","description":"Sample doc","createStamp":{"time":0,"actor":"urn:li:corpuser:fbar"}}]}},{"com.linkedin.schema.SchemaMetadata":{"schemaName":"FooEvent","platform":"urn:li:dataPlatform:foo","version":0,"created":{"time":0,"actor":"urn:li:corpuser:fbar"},"lastModified":{"time":0,"actor":"urn:li:corpuser:fbar"},"hash":"","platformSchema":{"com.linkedin.schema.KafkaSchema":{"documentSchema":"{\"type\":\"record\",\"name\":\"MetadataChangeEvent\",\"namespace\":\"com.linkedin.mxe\",\"doc\":\"Kafka event for proposing a metadata change for an entity.\",\"fields\":[{\"name\":\"auditHeader\",\"type\":{\"type\":\"record\",\"name\":\"KafkaAuditHeader\",\"namespace\":\"com.linkedin.avro2pegasus.events\",\"doc\":\"Header\"}}]}"}},"fields":[{"fieldPath":"foo","description":"Bar","nativeDataType":"string","type":{"type":{"com.linkedin.schema.StringType":{}}}}]}}],"urn":"urn:li:dataset:(urn:li:dataPlatform:bigquery,members/dcard,PROD)"}' -v
`

**Comment by keremsahin1** [comment]
@damon09273 
You need to encode `/` in the dataset name for the query you shared. Please try below query:

```
curl 'http://localhost:8080/datasets?action=ingest' -X POST -H 'X-RestLi-Protocol-Version: 2.0.0' -d '{"snapshot": {"aspects":[{"com.linkedin.common.Ownership":{"owners":[{"owner":"urn:li:corpuser:fbar","type":"DATAOWNER"}],"lastModified":{"time":0,"actor":"urn:li:corpuser:fbar"}}},{"com.linkedin.dataset.UpstreamLineage":{"upstreams":[{"auditStamp":{"time":0,"actor":"urn:li:corpuser:fbar"},"dataset":"urn:li:dataset:(urn:li:dataPlatform:bigquery,barUp,PROD)","type":"TRANSFORMED"}]}},{"com.linkedin.common.InstitutionalMemory":{"elements":[{"url":"https://www.linkedin.com","description":"Sample doc","createStamp":{"time":0,"actor":"urn:li:corpuser:fbar"}}]}},{"com.linkedin.schema.SchemaMetadata":{"schemaName":"FooEvent","platform":"urn:li:dataPlatform:foo","version":0,"created":{"time":0,"actor":"urn:li:corpuser:fbar"},"lastModified":{"time":0,"actor":"urn:li:corpuser:fbar"},"hash":"","platformSchema":{"com.linkedin.schema.KafkaSchema":{"documentSchema":"{\"type\":\"record\",\"name\":\"MetadataChangeEvent\",\"namespace\":\"com.linkedin.mxe\",\"doc\":\"Kafka event for proposing a metadata change for an entity.\",\"fields\":[{\"name\":\"auditHeader\",\"type\":{\"type\":\"record\",\"name\":\"KafkaAuditHeader\",\"namespace\":\"com.linkedin.avro2pegasus.events\",\"doc\":\"Header\"}}]}"}},"fields":[{"fieldPath":"foo","description":"Bar","nativeDataType":"string","type":{"type":{"com.linkedin.schema.StringType":{}}}}]}}],"urn":"urn:li:dataset:(urn:li:dataPlatform:bigquery,members/dcard,PROD)"}}' -v
```

I realized that documentation didn't get updated recently. Because, we retired `snapshot` endpoints in the favor of `ingest` APIs recently. I will update the documentation to reflect that.

**Comment by damon09273** [comment]
@keremsahin1 Cool, it worked!  Thank you very much.
