### ISSUE TITLE
Exception when calling REST root? 

### ISSUE THREAD

**Issue by dlutz2** [linkedin/datahub#1582]
Calling the top of the REST tree without any path i.e.
`curl -H  'http://localhost:8080/'`
throws a `com.linkedin.restli.server.RestLiServiceException`
The rest of the REST calls operate as expected. Is this the desired behavior? I had expected some nominal JSON (perhaps including something like "tagline" : "You Know, for Metadata" ala Elasticsearch)

Deployed via the Quickstart instructions, Dockers as of 1 March
  thanks

**Comment by keremsahin1** [comment]
@dlutz2 
Thanks for reporting this. There is no default rest.li endpoint at the top level and this should be the desired behavior of any [rest.li](http://rest.li) service. 

Is there a specific reason why you want to call this directly? If it's for health check purposes, there is a default `admin` endpoint you can call which returns `GOOD` string as a response.

Try `curl -H 'http://localhost:8080/admin'`

**Comment by dlutz2** [comment]
No reason to call this directly. This came up in some "push every button and see what happens" test we were doing to familiarize ourselves with datahub.
