### ISSUE TITLE
Increase space for description in the Docs tab

### ISSUE THREAD

**Issue by ben5448** [linkedin/datahub#1583]
**Is your feature request related to a problem? Please describe.**
On the Docs tab the only data that really helps me know which links are worth following is the description. The URL is not usually helpful, but it could be a tooltip. Same for the author and date added. They are not bad pieces of information to show, but the room given to rendering them could be used to display the more useful description. 

**Describe the solution you'd like**
Replace URL column with an icon to navigate to the page. This icon or the description could have a tooltip that displays the URL, author and date added. This could change the description from about 30% of the text box to 80+%.

**Describe alternatives you've considered**

**Additional context**

**Comment by keremsahin1** [comment]
Thanks @ben5448 for the suggestion.
@theseyi What do you think about this?

**Comment by theseyi** [comment]
We will take a look at this with design and what it implies for the product @keremsahin1

**Comment by jjoyce0510** [comment]
cc. @gabe-lyons . This is something we will want to consider for the React UI as well

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
