### ISSUE TITLE
when run docker build , elasticsearch is not found

### ISSUE THREAD

**Issue by theseusyang** [linkedin/datahub#1589]
when run docker build , elasticsearch  is not found or elasticsearch default configuration of  ip address is wrong:

kibana                  | {"type":"log","@timestamp":"2020-03-10T23:45:35Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}

**Comment by keremsahin1** [comment]
Hi @theseusyang 
Please make sure that you have Docker configured as `Tested & confirmed config: 4 CPUs, 8GB RAM, 2GB Swap area.`.

Also, you can refer to https://github.com/linkedin/datahub/blob/master/docs/debugging.md page to debug why Elasticsearch is not up.

**Comment by theseusyang** [comment]
yes, when run docker container ls,  kibana is already setup.

8a525147fb1c        docker.elastic.co/kibana/kibana:5.6.8    "/bin/bash /usr/loca…"   2 hours ago         Up 15 minutes       0.0.0.0:5601->5601/tcp

**Comment by keremsahin1** [comment]
You should check the container logs of ES container to understand why it's not able to start. A good way to start debugging is that: Stop all Docker containers currently running and only start ES & Kibana by referring to https://github.com/linkedin/datahub/tree/master/docker/elasticsearch. This will help localizing the issue.

**Comment by theseusyang** [comment]
OK

**Comment by theseusyang** [comment]
If startup elasticsearch alone in docker , still elasticsearch can't be  accessed:

kibana                 | {"type":"log","@timestamp":"2020-03-11T00:55:04Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana                 | {"type":"log","@timestamp":"2020-03-11T00:55:04Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana                 | {"type":"log","@timestamp":"2020-03-11T00:55:07Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}

**Comment by keremsahin1** [comment]
Can you please share the full logs of ES container? This log only shows that Kibana is not able to connect to ES.

**Comment by mars-lan** [comment]
Assuming the issue has been resolved. Feel free to reopen otherwise.
