### ISSUE TITLE
Gradle Build Fails When Run in Parallel

### ISSUE THREAD

**Issue by RyanHolstien** [linkedin/datahub#1590]
**Describe the bug**
When running the full gradle build in parallel, the build fails on EventUtilsTests. This failure is due to missing .avsc files, this occurs only when running in parallel because the generation of the metadata-models jar happens before the Avro schemas get generated. To fix this a dependency needs to be added on the metadata-models build.gradle:

mainAvroSchemaJar.dependsOn generateAvroSchema

I have this change locally and I will put it up for review shortly.

**To Reproduce**
1. In terminal open up to the root of the datahub project
2. Run ./gradlew clean build --parallel
3. Wait for build to run to completion
4. Error occurs: IllegalArgumentException on EventUtilsTests

**Expected behavior**
Build should succeed in parallel.

**Screenshots**
`> Task :metadata-events:mxe-utils-avro-1.7:test

Gradle suite > Gradle test > com.linkedin.metadata.EventUtilsTests.testAvroToPegasusMAE FAILED
    java.lang.ExceptionInInitializerError at EventUtilsTests.java:30
        Caused by: java.lang.IllegalArgumentException at EventUtilsTests.java:30

Gradle suite > Gradle test > com.linkedin.metadata.EventUtilsTests.testAvroToPegasusMCE FAILED
    java.lang.NoClassDefFoundError at EventUtilsTests.java:42

Gradle suite > Gradle test > com.linkedin.metadata.EventUtilsTests.testPegasusToAvroFailedMCE FAILED
    java.lang.NoClassDefFoundError at EventUtilsTests.java:73

Gradle suite > Gradle test > com.linkedin.metadata.EventUtilsTests.testPegasusToAvroMAE FAILED
    java.lang.NoClassDefFoundError at EventUtilsTests.java:53

Gradle suite > Gradle test > com.linkedin.metadata.EventUtilsTests.testPegasusToAvroMCE FAILED
    java.lang.NoClassDefFoundError at EventUtilsTests.java:63

5 tests completed, 5 failed

> Task :metadata-events:mxe-utils-avro-1.7:test FAILED`

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Version master

**Additional context**
Reproduced on my own machine as well as my colleague's.

**Comment by keremsahin1** [comment]
Thanks for the fix @RyanHolstien !
