### ISSUE TITLE
datahub health check tool

### ISSUE THREAD

**Issue by clojurians-org** [linkedin/datahub#1593]
1. datahub depends many service, some connection issue may occur. 
2. some user didn't use docker, rather integrate existing database system.

so basically, the tool will do the port, user, schema check...,
and fix and setup it when the table and schema is missing if specifyed.

i'll explore it a little.

https://github.com/linkedin/datahub/blob/master/docs/debugging.md

**Comment by clojurians-org** [comment]
elk health check example:

https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/elk.nix

**Comment by mars-lan** [comment]
@clojurians-org do you plan to work on this further? If not we'll close this issue for now and maybe revisit it again in the future if needed.
