### ISSUE TITLE
How to generate MCE  by programmatically and manually?

### ISSUE THREAD

**Issue by damon09273** [linkedin/datahub#1600]
I have me some question about creating meta data processing flow, I’m appreciated if some have time to give ideas.

### In manually situation
Does non technical guys can CRUD metadata of dataset by UI?
I noticed that there's some behavior can be done by UI, but seems can't create complete metadata by UI.
e.g create an app_platform, dataset and setting schema, relationships, ownership of dataset.

### In programmatically situation
I'm using python to extracting schema from platform (Big Query), but how to covert json to a MCE file properly? 

I didn't know I need to use what kind of urn, and key name of MCE file, does any resource or example code?

**Comment by mars-lan** [comment]
Thanks for asking these great questions, @damon09273. I'll attempt to answer them without turning it into an essay :)

### In manually situation

[GMS](https://github.com/linkedin/datahub/blob/master/docs/what/gms.md) has a full set of APIs for CRUD operations, which is what the UI invokes ultimately. We intentionally chose to not expose the full CRUD capability in UI for all metadata aspects. This is because not all aspects are expected to be "editable" by users, e.g. schema should always come from the source systems instead. You can find examples on how to make a curl call against GMS APIs here: https://github.com/linkedin/datahub/blob/36a5d23e42d393c587f167647f1856f1153ab396/gms/README.md

### In programmatic situation

[URNs](https://github.com/linkedin/datahub/blob/master/docs/what/urn.md) are unique identifiers for an entity (dataset in your use case). When sending MCEs, it is expected that the producer and consumer agree on the URN convention, e.g. the `name` field is in the form `<db_name>.<table_name>` for hive datasets. You can find examples of how to build the MCE here: https://github.com/linkedin/datahub/tree/master/metadata-ingestion

**Comment by damon09273** [comment]
> Thanks for asking these great questions, @damon09273. I'll attempt to answer them without turning it into an essay :)
> 
> ### In manually situation
> [GMS](https://github.com/linkedin/datahub/blob/master/docs/what/gms.md) has a full set of APIs for CRUD operations, which is what the UI invokes ultimately. We intentionally chose to not expose the full CRUD capability in UI for all metadata aspects. This is because not all aspects are expected to be "editable" by users, e.g. schema should always come from the source systems instead. You can find examples on how to make a curl call against GMS APIs here: https://github.com/linkedin/datahub/blob/36a5d23e42d393c587f167647f1856f1153ab396/gms/README.md

Cool, the data always come from system is awesome  design.
- How will you ETL metadata from Big Query?  Even it's has ODBC driver,  but it seem's using native API seems's the better choice.
- Why MCEs and curl using diff key name to send metadata?

### MCEs using `proposedSnapshot`
`  MCE1: {"auditHeader": None, "proposedSnapshot": ("com.linkedin.metadata.snapshot.CorpUserSnapshot", {"urn": "urn:li:corpuser:foo", "aspects": [{"active": True,"email": "foo@linkedin.com"}]}), "proposedDelta": None}
`

### curl using `snapshot`
`curl 'http://localhost:8080/datasets?action=ingest' -X POST -H 'X-RestLi-Protocol-Version: 2.0.0' -d '{"snapshot": {"aspects":[{"com.linkedin.common.Ownership":{"owners":[{"owner":"urn:li:corpuser:fbar","type":"DATAOWNER"}],"lastModified":{"time":0,"actor":"urn:li:corpuser:fbar"}}},{"com.linkedin.dataset.UpstreamLineage":{"upstreams":[{"auditStamp":{"time":0,"actor":"urn:li:corpuser:fbar"},"dataset":"urn:li:dataset:(urn:li:dataPlatform:bigquery,barUp,PROD)","type":"TRANSFORMED"}]}},{"com.linkedin.common.InstitutionalMemory":{"elements":[{"url":"https://www.linkedin.com","description":"Sample doc","createStamp":{"time":0,"actor":"urn:li:corpuser:fbar"}}]}},{"com.linkedin.schema.SchemaMetadata":{"schemaName":"FooEvent","platform":"urn:li:dataPlatform:foo","version":0,"created":{"time":0,"actor":"urn:li:corpuser:fbar"},"lastModified":{"time":0,"actor":"urn:li:corpuser:fbar"},"hash":"","platformSchema":{"com.linkedin.schema.KafkaSchema":{"documentSchema":"{\"type\":\"record\",\"name\":\"MetadataChangeEvent\",\"namespace\":\"com.linkedin.mxe\",\"doc\":\"Kafka event for proposing a metadata change for an entity.\",\"fields\":[{\"name\":\"auditHeader\",\"type\":{\"type\":\"record\",\"name\":\"KafkaAuditHeader\",\"namespace\":\"com.linkedin.avro2pegasus.events\",\"doc\":\"Header\"}}]}"}},"fields":[{"fieldPath":"foo","description":"Bar","nativeDataType":"string","type":{"type":{"com.linkedin.schema.StringType":{}}}}]}}],"urn":"urn:li:dataset:(urn:li:dataPlatform:bigquery,members/dcard,PROD)"}}' -v`

> ### In programmatic situation
> [URNs](https://github.com/linkedin/datahub/blob/master/docs/what/urn.md) are unique identifiers for an entity (dataset in your use case). When sending MCEs, it is expected that the producer and consumer agree on the URN convention, e.g. the `name` field is in the form `<db_name>.<table_name>` for hive datasets. You can find examples of how to build the MCE here: https://github.com/linkedin/datahub/tree/master/metadata-ingestion

**Comment by mars-lan** [comment]
> - How will you ETL metadata from Big Query? Even it's has ODBC driver, but it seem's using native API seems's the better choice.
Yes, the native API is likely to provide richer metadata. However, if you're using other GCP services, you may want to consider to pull everything directly from [Google Cloud Data Catalog API](https://cloud.google.com/data-catalog/docs/reference/rest). As we don't use GCP ourselves, we'd really appreciate it if the community could contribute in this area.

> - Why MCEs and curl using diff key name to send metadata?
When you say "different key", do you mean `proposedSnapshot` in MCE vs `snapshot` in CRUD endpoint? For one, we'd like to denote specifically that the snapshot in MCE is a proposal (as it may be rejected for whatever reason). Also note that MCE contains another field called `proposedDelta` which is designated for [delta update](https://github.com/linkedin/datahub/blob/master/docs/what/delta.md) and would require a custom CRUD endpoint to support that.

**Comment by mars-lan** [comment]
@damon09273  Let me know if there's any more questions and whether we can close this issue.

**Comment by mars-lan** [comment]
Will close this issue assuming the questions have been answered. Feel free to reopen otherwise.

**Comment by damon09273** [comment]
@mars-lan Apology for my delay response. 

About the question of snapshot, yes, that's what I mean, so `snapshot` in curl represent an endpoint but `proposedSnapshot` in MCE represent that some thing like command of database migration which trying to update entity by URN specified.

Thanks you for your explanation.

**Comment by damon09273** [comment]
> Thanks for asking these great questions, @damon09273. I'll attempt to answer them without turning it into an essay :)
> 
> ### In manually situation
> [GMS](https://github.com/linkedin/datahub/blob/master/docs/what/gms.md) has a full set of APIs for CRUD operations, which is what the UI invokes ultimately. We intentionally chose to not expose the full CRUD capability in UI for all metadata aspects. This is because not all aspects are expected to be "editable" by users, e.g. schema should always come from the source systems instead. You can find examples on how to make a curl call against GMS APIs here: https://github.com/linkedin/datahub/blob/36a5d23e42d393c587f167647f1856f1153ab396/gms/README.md
> 
But how can I put metadata and schema together in datahub? if schema come from the source systems.
Say I have a table in postgres, I want to ETL schema and generating metadata.
In my current understanding, ETL schema can be done by [RDBMS ETL script](https://github.com/linkedin/datahub/tree/master/metadata-ingestion#ingest-metadata-from-rdbms-to-datahub), but I don't know how to merge schema with metadata.

Does I need generating an another MCE file to writing metadata after snapshot being created?

**Comment by mars-lan** [comment]
Each entity can have multiple "aspects" (https://github.com/linkedin/datahub/blob/master/docs/what/aspect.md), some of which are updated via MCE (e.g. schema), and some are updated via UI (e.g. description). Unfortunately the UI doesn't provide the ability to update all aspects, so some work will be needed to extend the UI when new editable aspects are added. Hope this answers your question.

**Comment by damon09273** [comment]
It's what I want,  thank you very much.
