### ISSUE TITLE
should use specific dependency versions?

### ISSUE THREAD

**Issue by jhsenjaliya** [linkedin/datahub#1603]
instead of mysql:latest, should we use mysql:5.7 ? the latest can have incompatible changes.
similarly, it would be good to know what exact dependency versions are exactly required to run the datahub.

**Comment by keremsahin1** [comment]
Hi @jhsenjaliya 
This is a good point. Except for `mysql`, we generally prefer to depend on specific versions. MySQL is pretty good with backward compatibility and this didn't create any issue so far. But you're definitely right, latest might have incompatible changes. I will update docker-compose scripts to depend on the specific version of MySQL.

**Comment by keremsahin1** [comment]
Fixed in https://github.com/linkedin/datahub/commit/6ab2ab6f78ebc8aec20a4e8b58094a3e19f42eba.

**Comment by mars-lan** [comment]
Also note that we purposely limit the implementation [EbeanLocalDAO](https://github.com/linkedin/datahub/blob/master/metadata-dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/EbeanLocalDAO.java) to  a small subset of common SQL features such that it should work on all recent versions (released in the past 5-10 years) of MySQL, Postgres, MariaDB, Oracle etc. Internally we run mostly on MySQL 5.6 & 5.7 but we welcome the community to test on other versions as well as DB systems.

**Comment by jhsenjaliya** [comment]
Thanks @mars-lan  and @keremsahin1 for clarification.
Actually mysql latest ( 8.x) has some compatibility issue with 5.7 clients. I had to login to container and run `ALTER USER 'datahub'@'%' IDENTIFIED WITH mysql_native_password BY 'datahub';` to connect it locally. specifying 5.7 would help avoid such issues for new user.

**Comment by mars-lan** [comment]
@jhsenjaliya argh that makes sense. The core is most likely compatible with MySQL 8 but the Docker setup may not be. Thanks for pointing that out.
