### ISSUE TITLE
schema not loaded during ingestion

### ISSUE THREAD

**Issue by animesh-jm** [linkedin/datahub#1606]
**Describe the bug**
tried hive-etl.py & mysql-stl.py in both tables name & db name published &. available in datahub
but somehow table schema not loaded
**To Reproduce**
run mysql-etl.py or hive-etl.py

mysql example schema

{'auditHeader': None, 'proposedSnapshot': ('com.linkedin.pegasus2avro.metadata.snapshot.DatasetSnapshot', {'urn': 'urn:li:dataset:(urn:li:dataPlatform:mysql,employees.titles,PROD)', 'aspects': [{'owners': [{'owner': 'urn:li:corpuser:datahub', 'type': 'DATAOWNER'}], 'lastModified': {'time': 0, 'actor': 'urn:li:corpuser:datahub'}}, {'schemaName': 'employees.titles', 'platform': 'urn:li:dataPlatform:mysql', 'version': 10, 'created': {'time': 1584854643.2544692, 'actor': 'urn:li:corpuser:datahub'}, 'lastModified': {'time': 1584854643.2544692, 'actor': 'urn:li:corpuser:datahub'}, 'hash': '', 'platformSchema': {'tableSchema': "[('emp_no', 'int', 'NO', 'PRI', None, ''), ('title', 'varchar(50)', 'NO', 'PRI', None, ''), ('from_date', 'date', 'NO', 'PRI', None, ''), ('to_date', 'date', 'YES', '', None, '')]"}, 'fields': [{'fieldPath': 'emp_no', 'nativeDataType': 'int', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'title', 'nativeDataType': 'varchar(50)', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'from_date', 'nativeDataType': 'date', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'to_date', 'nativeDataType': 'date', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}]}]}), 'proposedDelta': None}

it has schema in tableSchema key. but not loading in datahub.

**Comment by RealChrisL** [comment]
Hi @animesh-jm ,

From the example you provided, the time format doesn't seem correct. 
As illustrating in the [metadata-models](https://github.com/linkedin/datahub/blob/4cc6dd92b2dcb62e18717eff6699ce95896c7ad3/li-utils/src/main/pegasus/com/linkedin/common/Time.pdsc#L6), this field is **long** format, which should be already converted in the [mysql_etl.py](https://github.com/linkedin/datahub/blob/3fae73691e7d07fb0d05350eb460d9b0c9c8dbce/metadata-ingestion/mysql-etl/mysql_etl.py#L22).

Verified against the following `MetadataChangeEvent` is able to populate the schema to the DataHub.
```
{'auditHeader': None, 'proposedSnapshot': ('com.linkedin.pegasus2avro.metadata.snapshot.DatasetSnapshot', {'urn': 'urn:li:dataset:(urn:li:dataPlatform:mysql,employees.titles,PROD)', 'aspects': [{'owners': [{'owner': 'urn:li:corpuser:datahub', 'type': 'DATAOWNER'}], 'lastModified': {'time': 0, 'actor': 'urn:li:corpuser:datahub'}}, {'schemaName': 'employees.titles', 'platform': 'urn:li:dataPlatform:mysql', 'version': 10, 'created': {'time': 1584854643L, 'actor': 'urn:li:corpuser:datahub'}, 'lastModified': {'time': 1584854643L, 'actor': 'urn:li:corpuser:datahub'}, 'hash': '', 'platformSchema': {'tableSchema': "[('emp_no', 'int', 'NO', 'PRI', None, ''), ('title', 'varchar(50)', 'NO', 'PRI', None, ''), ('from_date', 'date', 'NO', 'PRI', None, ''), ('to_date', 'date', 'YES', '', None, '')]"}, 'fields': [{'fieldPath': 'emp_no', 'nativeDataType': 'int', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'title', 'nativeDataType': 'varchar(50)', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'from_date', 'nativeDataType': 'date', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'to_date', 'nativeDataType': 'date', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}]}]}), 'proposedDelta': None}
```

**Comment by mars-lan** [comment]
Assuming the issue has been resolved. Feel free to reopen otherwise.
