### ISSUE TITLE
Docker Quickstart - Sample Data Loading Error

### ISSUE THREAD

**Issue by klashe1977** [linkedin/datahub#1612]
### **Describe the bug**
Running the Sample data ingestion commands produces an error:  

> Collecting avro-python3==1.8.2
>   Downloading avro-python3-1.8.2.tar.gz (36 kB)
>     ERROR: Command errored out with exit status 1:
>     ...
>     Complete output (7 lines):
>     Traceback (most recent call last):
>       ...
>       File "/tmp/pip-install-gmtSqW/avro-python3/setup.py", line 114, in Main
>         ('Python version >= 3 required, got %r' % sys.version_info)
>     **AssertionError: Python version >= 3 required, got sys.version_info(major=2, minor=7, micro=17, releaselevel='final', serial=0)**

### **To Reproduce**
1. Successfully run the Quickstart.sh script
2. Run the commands to import sample data:   
>docker build -t ingestion -f docker/ingestion/Dockerfile . && cd docker/ingestion && docker-compose up

### **Expected behavior**
Sample Data is loaded into DataHub

### **Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS -  4.15.0-91-generic #92-Ubuntu 
 - Browser N/A
 - Version 18.04.4

### **Additional context**
I got around the above error by modifying the datahub/docker/ingestion/Dockerfile line "--from=python:2.7"  --> "--from=python:3.6" and rerunning the docker build ingestion command again.  

The container was successfully built but when the container started, I received a different error message:  

> Attaching to ingestion
> ingestion    | Traceback (most recent call last):
> ingestion    |   File "mce_cli.py", line 3, in <module>
> ingestion    |     from confluent_kafka import avro
> ingestion    |   File "/root/.local/lib/python3.6/site-packages/confluent_kafka/avro/__init__.py", line 9, in <module>
> ingestion    |     from confluent_kafka.avro.cached_schema_registry_client import CachedSchemaRegistryClient
> ingestion    |   File "/root/.local/lib/python3.6/site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 27, in <module>
> ingestion    |     from requests import Session, utils
> ingestion    | ModuleNotFoundError: No module named 'requests'
> ingestion exited with code 1`

Then I got around that error by adding a line to the the datahub/metadata-ingestion/mce-cli/requirements.txt ->  "requests==2.23.0"

Again, container built, ingestion container ran, but I received the error:  

> ingestion    | avro.io.AvroTypeException: The datum {'auditHeader': None, 'proposedSnapshot': ('com.linkedin.pegasus2avro.metadata.snapshot.CorpUserSnapshot', {'urn': 'urn:li:corpuser:datahub', 'aspects': [{'active': True, 'displayName': 'Data Hub', 'fullName': 'Data Hub', 'email': 'datahub@linkedin.com', 'title': 'CEO'}, {}]}), 'proposedDelta': None} is not an example of the schema

At this point I gave up, because I was mucking with too many components.

**Comment by klashe1977** [comment]
I also tried running the manual steps to ingest the sample data that's on this page: https://github.com/linkedin/datahub/tree/master/metadata-ingestion 
and received the same error.

It seems to indicate that the bootstrap_mce.dat does not conform to Kafka's schema.

**Comment by mars-lan** [comment]
Thanks for reporting. Could you try install Python 3 on your system?

**Comment by klashe1977** [comment]
When I encountered this error I had Python 3.6 as well as Python 2.7 installed on the Docker host.

**Comment by RealChrisL** [comment]
Hi @klashe1977 ,
This issue is due to the recent PR to fix [Python 3.7 with python Avro library in confluent-kafka](https://github.com/linkedin/datahub/pull/1605).

However, the ingestion docker and scripts are based on Python 2.7, which leads to the library mismatching. I have updated the r[equirements.txt](https://github.com/linkedin/datahub/blob/master/metadata-ingestion/mce-cli/requirements.txt) to specify the Python version.

Feel free to run the ingestion docker command to see if the issue persists.
Thanks!

**Comment by skybabydad** [comment]
solved too.
step1: edit ingestion/Dockerfile, change python from 2.7 to 3.6 
```
#vi datahub/docker/ingestion/Dockerfile
FROM openjdk:8
COPY --from=python:3.6 / /
COPY . datahub-src
RUN cd datahub-src && ./gradlew :metadata-events:mxe-schemas:build \
    && cp -r metadata-ingestion/mce-cli . && cd metadata-ingestion/mce-cli \
    && pip install --user -r requirements.txt
```

step2: change /datahub/metadata-ingestion/mce-cl/requirements.txt as following
```
avro-python3==1.8.2; python_version == '3.7'
confluent-kafka==1.1.0; python_version == '3.7'
confluent-kafka[avro]==1.1.0; python_version < '3.7'
```

**Comment by RealChrisL** [comment]
Glad to hear it's working now! Feel free to reopen the issue if having further concerns.

**Comment by skybabydad** [comment]
> Glad to hear it's working now! Feel free to reopen the issue if having further concerns.

after ingestion docker image created successfully, new bugs come. when i docker-compose up, the following errors appear:

```
docker-compose up

Starting ingestion ... done
Attaching to ingestion
ingestion    | Producing MetadataChangeEvent records to topic MetadataChangeEvent. ^c to exit.
ingestion    | Traceback (most recent call last):
ingestion    |   File "mce_cli.py", line 108, in <module>
ingestion    |     main(parser.parse_args())
ingestion    |   File "mce_cli.py", line 88, in main
ingestion    |     produce(conf, args.data_file, args.schema_record)
ingestion    |   File "mce_cli.py", line 32, in produce
ingestion    |     producer.produce(topic=topic, value=content)
ingestion    |   File "/root/.local/lib/python3.6/site-packages/confluent_kafka/avro/__init__.py", line 80, in produce
ingestion    |     value = self._serializer.encode_record_with_schema(topic, value_schema, value)
ingestion    |   File "/root/.local/lib/python3.6/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 105, in encode_record_with_schema
ingestion    |     schema_id = self.registry_client.register(subject, schema)
ingestion    |   File "/root/.local/lib/python3.6/site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 216, in register
ingestion    |     body = {'schema': json.dumps(avro_schema.to_json())}
ingestion    |   File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
ingestion    |     return _default_encoder.encode(obj)
ingestion    |   File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
ingestion    |     chunks = self.iterencode(o, _one_shot=True)
ingestion    |   File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
ingestion    |     return _iterencode(o, 0)
ingestion    |   File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
ingestion    |     o.__class__.__name__)
ingestion    | TypeError: Object of type 'mappingproxy' is not JSON serializable
ingestion exited with code 1

```

**Comment by RealChrisL** [comment]
This is also due to the known [issue](https://github.com/confluentinc/confluent-kafka-python/issues/610) in confluent-kafka with python avro library.

Hence, the DataHub implemented ETL jobs and bootstrap_mce.dat  based on Python 2.7.

That is to say, if you keep the original Python version (2.7) in `Dockerfile`, the docker image should be able to populate the MCEs.

On the other hand, if you would like to leverage the Python 3.x, please downgrade the avro-python3 version and import confluent-kafka as well as modified the bootstrap_mce.dat.

We do plan to roll out the Python3 migration in the near future.

**Comment by klashe1977** [comment]
This works for me now.  thank you!
