### ISSUE TITLE
Not Able to log into the DataHub Dashboard with USERNAME : datahub & Password : datahub

### ISSUE THREAD

**Issue by Nickko04** [linkedin/datahub#1620]
**Login page flashes and logs out at the Datahub Dashboard Screen**
after running the Quickstart.sh -> opening the localhost:9091 (shows datahub page) 
-> when I try to login using the username and password as : datahub logs me in and again logs out.

**To Reproduce**

- Install docker and docker-compose (if using Linux). Make sure to allocate enough hardware resources for Docker engine. Tested & confirmed config: 2 CPUs, 8GB RAM, 2GB Swap area.

- Open Docker either from the command line or the desktop app and ensure it is up and running.

- Clone this repo and cd into the root directory of the cloned repository.

- Run the following command to download and run all Docker containers locally:

- cd docker/quickstart && source ./quickstart.sh

- This step takes a while to run the first time, and it may be difficult to tell if DataHub is fully up and running from the combined log. 

- At this point, you should be able to start DataHub by opening http://localhost:9001 in your browser. You can sign in using datahub as both username and password. However, you'll notice that no data has been ingested yet.

This step fails 

**Expected behavior**
The console should log me in and I should be able to view the DATASET Tile

**Screenshots**
containers state : 
![image](https://user-images.githubusercontent.com/19469942/78209031-91b19300-74c3-11ea-81fd-a349c7a82703.png)

-----

mysql localhost result 

![image-2](https://user-images.githubusercontent.com/19469942/78209136-d5a49800-74c3-11ea-8515-42ecf4a3456b.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

**Additional context**

I have tried these steps

1 Make sure mysql docker work well, you can test with the connection localhost:3306.  (Didn't work screenshot attached above)
2, Make sure init.sql executed. watch your datahub database.

I used original config for mysql docker in datahub, that lead to connection with other container is blocked. I found a method solve this problem:  
delete
"volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql"

**Comment by mars-lan** [comment]
My guess is that your MySQL isn't seeded with the initial data for user "datahub". Could you use mysql CLI or MySQLWorkbench to connect to localhost:3306 to see if there's any content in the `metadata_aspect` table?

**Comment by mars-lan** [comment]
Also could you make sure to test it against a stable tag, such as `v0.3.1` as there seems to be a separate but unrelated issue at HEAD right now.

**Comment by mars-lan** [comment]
Okay was able to reproduce this issue from HEAD, but `v0.3.1` works fine. Please use this tag for now while we work on a fix.

**Comment by jywadhwani** [comment]
@Nickko04 could you try the latest code on master branch. Please let us know if you still see the login issue. Thanks!

**Comment by Nickko04** [comment]
> @Nickko04 could you try the latest code on master branch. Please let us know if you still see the login issue. Thanks!

The New code works well, I just had to run the following as suggested by @mars-lan  
--

`docker exec -i mysql sh -c 'exec mysql datahub -udatahub -pdatahub' < docker/mysql/init.sql`
