### ISSUE TITLE
Optimize Docker image sizes

### ISSUE THREAD

**Issue by keremsahin1** [linkedin/datahub#1627]
Docker image sizes are unusually large (2GB+ for `datahub-frontend`). This could be lowered to a greater extent without any feature reduction.

We can refer to https://github.com/JanusGraph/janusgraph-docker/issues/27 .

**Comment by keremsahin1** [comment]
@bharatak 
Could you also do the same optimization for `datahub-mce-consumer` & `datahub-mae-consumer`? They are not terribly huge in size but definitely can benefit from this optimization.

**Comment by bharatak** [comment]
Sure.. will do
