### ISSUE TITLE
Convert MCE & MAE to a Springboot App to benefit from healthchecks and metrics endpoint

### ISSUE THREAD

**Issue by arunvasudevan** [linkedin/datahub#1628]
**Is your feature request related to a problem? Please describe.**
I would like to add a healthcheck and metrics endpoint to the MCE Application. 

**Describe the solution you'd like**
Converting the App to a springboot could utilize the readily available actuator endpoint to get healthcheck and metrics endpoints.

**Describe alternatives you've considered**
No

**Additional context**
Added info, healthcheck and metrics endpoints by enabling actuator.

**Comment by keremsahin1** [comment]
Can this be closed @arunvasudevan ? Are you planning any more work on this?

**Comment by arunvasudevan** [comment]
@keremsahin1 Yes this issue can be closed.
