### ISSUE TITLE
DataHub's Slack workspace invite link doesn't seem to be working

### ISSUE THREAD

**Issue by abhilash1in** [linkedin/datahub#1636]
DataHub's Slack workspace [invite link](https://datahubspace.slack.com/join/shared_invite/zt-cl60ng6o-6odCh_I~ejZKE~a9GG30PA) mentioned in [README](https://github.com/linkedin/datahub/blob/master/README.md) and [other places](https://github.com/linkedin/datahub/blob/master/docs/townhalls.md) doesn't seem to be working. How do I join the workspace?

**Comment by mars-lan** [comment]
Thanks for letting us know, @abhilash1in. We have fixed the links on those pages using a never-expiring invitation: https://app.slack.com/client/TUMKD5EGJ/C01040VS7CJ
