### ISSUE TITLE
when does Fine grain lineage feature come out?

### ISSUE THREAD

**Issue by geosmart** [linkedin/datahub#1649]
as[DataHub Features](https://github.com/linkedin/datahub/blob/66dccefd362cbbef43e76d0713a8b13d768045bf/docs/features.md) say:
* Coarse grain lineage: support for lineage at the dataset level, tabular & graphical visualization of downstreams/upstreams
* Fine grain lineage: support for lineage at the field level [coming soon]

apache atlas has powerful lineage,
we want to use datahub,but field level lineage  datahub has not come out;
so  can you tell me  how long is the [coming soon] ?

**Comment by mars-lan** [comment]
Please take a look at our [Roadmap](https://github.com/linkedin/datahub/blob/66dccefd362cbbef43e76d0713a8b13d768045bf/docs/roadmap.md) to get a sense of timing. There's a lot of interest for fine grain lineage so it's certainly one of the things we'd like to prioritize internally.

**Comment by mars-lan** [comment]
Let's concentrate the discussion in this issue: https://github.com/linkedin/datahub/issues/1731
