### ISSUE TITLE
Ingested data missing after restarting docker compose

### ISSUE THREAD

**Issue by Manjeri-Rajan** [linkedin/datahub#1650]
I have installed datahub in my machine and ingested Google Big Query data using my extraction script. But I am facing the below issue.
Due to less swap memory(980 MB), my system gets stuck after a certain time after data is ingested to datahub and I have to setup the docker compose again. This clears the already ingested data and I have run to the ingestion script again. 

- My understanding is that the volume sharing will save the ingested data locally. But the volume sharing for mysql and neo4j is not happening. 

- Also the elastic search volume sharing is giving me permission error(I had to comment out that piece of code to run the docker compose). 

Is there an approach to avoid ingesting the already ingested data.

**Comment by mars-lan** [comment]
Could you post the permission error you got for ES volume sharing?

**Comment by Manjeri-Rajan** [comment]
![Screenshot from 2020-04-15 17-58-45](https://user-images.githubusercontent.com/20423084/80403701-080c9f80-888e-11ea-8e27-7dcbfbb81d4e.png)

**Comment by mars-lan** [comment]
Are you using the [quickstart script](https://github.com/linkedin/datahub/blob/master/docker/quickstart/quickstart.sh) or manually doing `docker-compose up`?

**Comment by Manjeri-Rajan** [comment]
I am using the quickstart script.

**Comment by mars-lan** [comment]
I see. So did the script create `/tmp/datahub/elasticsearch` and set the permission to 777?

**Comment by Manjeri-Rajan** [comment]
Yes, it did.

**Comment by mars-lan** [comment]
Hum this is strange. I'm unable to reproduce this from my end. Are you running on Mac or Linux? 

Also could you try a clean checkout, [clean up your docker setup](https://github.com/linkedin/datahub/blob/master/docs/debugging.md#ive-messed-up-my-docker-setup-how-do-i-start-from-scratch) and retry the quickstart script again just to be safe?

**Comment by Manjeri-Rajan** [comment]
I am using linux system (Ubuntu 18.04.3 LTS).
docker compose version is 1.25.4.

I have tried after cleaning the docker containers but in vain.

**Comment by mars-lan** [comment]
@Manjeri-Rajan we have now changed the quickstart docker-compose from bind mount to named volume, which will hopefully fix this issue. Please give it a try and let us know how it goes.

**Comment by Manjeri-Rajan** [comment]
Thanks Mars. Will take try it.

**Comment by Manjeri-Rajan** [comment]
That worked. Thank you!

**Comment by mars-lan** [comment]
Great to hear!
