### ISSUE TITLE
What's FabricType in Dataset Entity definition

### ISSUE THREAD

**Issue by loftyet** [linkedin/datahub#1651]
Reading `[DatasetEntity.pdsc](https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/metadata/entity/DatasetEntity.pdsc)`, there is fields called `origin`:
```
{
      "name": "origin",
      "type": "com.linkedin.common.FabricType",
      "doc": "Fabric type where dataset belongs to or where it was generated.",
      "optional": true
    }
```
What's the `FabricType`? If a dataset is generated from a ETL job? should the FabricType be `a ETL job`?

**Comment by keremsahin1** [comment]
FabricType is the environment where a specific dataset lives. Please refer to the model for that.
https://github.com/linkedin/datahub/blob/master/li-utils/src/main/pegasus/com/linkedin/common/FabricType.pdsc
