### ISSUE TITLE
Urn coercion appears to be broken

### ISSUE THREAD

**Issue by mars-lan** [linkedin/datahub#1654]
User [reported on Slack](https://datahubspace.slack.com/archives/CV2KB471C/p1588192766062300) that the coercer not registered correctly and causes the following stacktrace in mae-consumer-job

```
com.linkedin.data.template.TemplateOutputCastException: Output urn:li:corpuser:datahub has type java.lang.String, but does not have a registered coercer and cannot be coerced to type com.linkedin.common.urn.Urn
```

Based on the [latest rest.li doc](https://linkedin.github.io/rest.li/java_binding#custom-java-class-binding-for-primitive-types), it seems that `coercerClass` is no longer supported and the registration should be moved to the URN class itself.

**Comment by dan13bauer** [comment]
As far as I see and understand, registration still seems to work for `CorpUserUrn` and `DatasetUrn` coercers. By applying the following ugly hack in `BaseGraphBuilder`, I do now get the expected output, i.e. entities being created in neo4j:

```
  // ugly hack.
  private static final Map<Class<? extends RecordTemplate>, Class<? extends Urn>> snapshot2UrnMap;
  static {
    Map<Class<? extends RecordTemplate>, Class<? extends Urn>> myMap = new HashMap<>();
    myMap.put(CorpUserSnapshot.class, CorpuserUrn.class);
    myMap.put(DatasetSnapshot.class, DatasetUrn.class);
    snapshot2UrnMap = Collections.unmodifiableMap(myMap);
  }

  @Nonnull
  @Override
  public GraphUpdates build(@Nonnull SNAPSHOT snapshot) {
    final Class<? extends Urn> targetClass = snapshot2UrnMap.get(snapshot.getClass());
    //final Urn urn = RecordUtils.getRecordTemplateField(snapshot, "urn", Urn.class);
    final Urn urn = RecordUtils.getRecordTemplateField(snapshot, "urn", targetClass);
```

**Comment by mars-lan** [comment]
It turns out that while `coercerClass` is still [supported](https://github.com/linkedin/rest.li/blob/master/data/src/main/java/com/linkedin/data/template/Custom.java#L53), but it requires that the URN typeref class to be initialized for the coercer to be properly registered. Given that we're doing reflection here, there's no guarantee that this will happen inside of https://github.com/linkedin/rest.li/blob/66e5abc68f28bbff2010a147f987c42e30579668/data/src/main/java/com/linkedin/data/template/RecordTemplate.java. The safest way is still combining the coercer with the actual URN class so it'll always get registered as long as the class is referenced.

**Comment by mars-lan** [comment]
@dan13bauer please give HEAD a try. Hopefully you can drop the ugly hack now. Thanks.

**Comment by dan13bauer** [comment]
Thanks, yes, works nicely now!
