### ISSUE TITLE
Documentation about DAO implementation while onboarding a new Entity

### ISSUE THREAD

**Issue by loftyet** [linkedin/datahub#1656]
**Is your feature request related to a problem? Please describe.**
Having issues when onboarding a new entity. Saw `localDao`, `searchDAo` or `browseDAO` not found error

**Describe the solution you'd like**
Add DAO implementation steps in [How to onboard an entity](https://github.com/linkedin/datahub/blob/master/docs/how/entity-onboarding.md)

**Additional context**

**Comment by mars-lan** [comment]
@loftyet I updated the doc with links to example factory classes for the DAOs.

**Comment by dan13bauer** [comment]
@mars-lan , can you please share some debugging tips for adding an entity?
I've been following the documentation as well as the existing entities and I've implemented the model (Urn, entity, aspects, snapshot, key, etc.) as well as the factories, search config & mapping etc.
Nevertheless, I do get a `org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'myEntitySearchDao' available` exception even though the dependency injection is correctly wired.
Any hint is greatly appreciated!

**Comment by mars-lan** [comment]
@dan13bauer looks like you also need to add your package to https://github.com/linkedin/datahub/blob/master/gms/war/src/main/webapp/WEB-INF/beans.xml#L7. I'll update the doc to include more info on DI.

**Comment by dan13bauer** [comment]
@mars-lan , thanks, indeed I was missing that!
