### ISSUE TITLE
Reorganize GMS factory namespace

### ISSUE THREAD

**Issue by mars-lan** [linkedin/datahub#1658]
**Is your feature request related to a problem? Please describe.**
With the [current directory layout](https://github.com/linkedin/datahub/tree/master/gms/factories/src/main/java/com/linkedin), factories for new entities will likely to end up in a brand new namespace and requires editing of https://github.com/linkedin/datahub/blob/master/gms/war/src/main/webapp/WEB-INF/beans.xml#L7 in order to be scanned correctly. See https://github.com/linkedin/datahub/issues/1656 for an example.

**Describe the solution you'd like**
All factories should share a common namespace, e.g. `com.linkedin.metadata.factories`, similar to the rest.li resources (`com.linkedin.metadata.resources`) so they can be automatically picked up from the DI framework.

**Comment by mars-lan** [comment]
Another option is to use the `@ComponentScan` annotation instead of manually specifying the package in `beans.xml`: https://www.baeldung.com/spring-component-scanning

**Comment by loftyet** [comment]
I just went through the whole process and am able to get it working. I am about to detail the process, and send a PR.

**Comment by mars-lan** [comment]
@loftyet thanks! Look forward to the PR. Feel free to expand https://github.com/linkedin/datahub/blob/master/docs/how/entity-onboarding.md.

**Comment by mars-lan** [comment]
@liangjun-jiang are you still working on that PR or do you want us to do the refactoring?
