### ISSUE TITLE
View as JSON doesn't show the schema

### ISSUE THREAD

**Issue by Manjeri-Rajan** [linkedin/datahub#1671]
I ingested data extracted from Google BigQuery to datahub. All functionalities except the view as json for schema field is working. I see it in tabular format, but not json. No error message was thrown.
Could you help to understand the requirement for viewing the schema as json?

**Comment by cptran777** [comment]
Hi @Manjeri-Rajan ,

This was a known bug that we have fixed internally but haven't pushed out yet. Please follow this ticket and I'll announce the release that comes with the fix.

**Comment by cptran777** [comment]
This should be fixed by [https://github.com/linkedin/datahub/pull/1806](https://github.com/linkedin/datahub/pull/1806).

**Comment by cptran777** [comment]
Please re-open this issue if there are still issues.
