### ISSUE TITLE
Update dependency 'vis'

### ISSUE THREAD

**Issue by mojoaxel** [linkedin/datahub#1674]
**Describe the bug**
The data-portal still uses a very outdated version [4.21 of vis](https://github.com/linkedin/datahub/blob/master/datahub-web/packages/data-portal/package.json#L133).
This version is not supported anymore!

Please update to the new libraries:
https://github.com/visjs

Feel free to contact us if you need any support during the transition :-)

**Comment by igbopie** [comment]
We have replaced Vis with another library (sorry!). We are not updating it due to that reason.
