### ISSUE TITLE
Ingest Dataset Owner

### ISSUE THREAD

**Issue by liangjun-jiang** [linkedin/datahub#1681]
In the `metadata-ingestion`, we have scripts to ingest LDAP user. In the reality, what's the flow to ingest a dataset owner?

My theory is that, by the time of ingesting a dataset, if the owner aspects of this dataset is not empty, we can parse this owner aspect urn, and find the name  - assume it's LDAP account name
```
"owners": [
          {
            "owner": "urn:li:corpuser:fbar",
            "type": "DATAOWNER"
          },
          {
            "owner": "urn:li:corpuser:ksahin",
            "type": "DATAOWNER"
          }
        ],
```
In this example, `fbar` and `ksahin` are the LDAP account name. 
MCE consumer job should parse the urn to obtain LDAP account name, then use account name to query LDAP server to find the details of this user - just like the `LDAP_ETL.py` does, and produce another MceChangeEvent message.

The whole idea is that we should passively ingest LDAP users unless there are ones associated with dataset. 
What do you think?

**Comment by liangjun-jiang** [comment]
I think it's the best to ingest dataset owner by the time of ingesting dataset, not let MCE consumer job handle this logic. 
for this reason, I will close the question.

**Comment by mars-lan** [comment]
I understand the concern of "dangling reference" here, but that's how DataHub is designed. All entities (including users) are referenced by URN, with the additional metadata (e.g. user profile) ingested independently. User will likely be used at multiple places beyond just ownership, so having MCE consumer intelligently fetch user profile isn't the best approach IMO.
