### ISSUE TITLE
Allow configuring frontend https certificate via environmental variables

### ISSUE THREAD

**Issue by mars-lan** [linkedin/datahub#1682]
**Is your feature request related to a problem? Please describe.**
Currently one must manually modify Play config file and rebuild docker image in order to [enabling https](https://www.playframework.com/documentation/2.8.x/ConfiguringHttps). 

**Describe the solution you'd like**
https should be enabled by default with the ability to config certificate via environmental variables

**Describe alternatives you've considered**
Map the entire Play config file to a local path through Docker - not as easy to use and expose too much of Play's internal.

**Comment by casperfrx** [comment]
Wouldn't it be better to use a different service that acts as the reverse proxy?

I did this myself, especially since the UI interfaces then also can be routed through the same reverse proxy.

**Comment by mars-lan** [comment]
@casperfrx We did the same at LinkedIn. However, it's understandable that people may opt for a simpler setup and wish to enable https on the frontend directly.

**Comment by jjoyce0510** [comment]
Wondering if this is still being addressed? If not, can we close due for inactivity?

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
