### ISSUE TITLE
Expose kafka SSL configs via environment variables

### ISSUE THREAD

**Issue by mars-lan** [linkedin/datahub#1684]
**Is your feature request related to a problem? Please describe.**
Currently there's no easy way to configure kafka SSL configs in mce-consumer-job & mae-consumer-job. 

**Describe the solution you'd like**
Expose [relevant configs](https://docs.confluent.io/current/kafka/authentication_ssl.html) via environment variables

**Additional context**

**Comment by mars-lan** [comment]
Reference: https://gist.github.com/itzg/e3ebfd7aec220bf0522e23a65b1296c8

**Comment by casperfrx** [comment]
A perhaps better reference from the Kafka creators themselves:

https://github.com/confluentinc/examples/tree/5.5.0-post/clients/cloud/java-springboot
