### ISSUE TITLE
Adopt Request For Comment (RFC) Process 

### ISSUE THREAD

**Issue by liangjun-jiang** [linkedin/datahub#1692]
**Is your feature request related to a problem? Please describe.**
With more features are requested, it is a good practice to have a formal document to understand more about the business case of a feature request, the design details and the implementation consideration. It will be easier for contributors to stay informed and contribute to the lifecycle of a feature. 

**Describe the solution you'd like**
I's suggest to adopt Request For Comment (RFC) process. Some existing examples such as [vue.js's rfc](https://github.com/vuejs/rfcs) 

**Describe alternatives you've considered**
Right now, we use github's `issues` feature to discuss a new feature

**Additional context**
Adopting a new feature for datahub sometime involves both frontend and backend development. Not all of those have both skills, a RFC will help get other developers having needed skillset involved.

**Comment by jplaisted** [comment]
Good idea, thanks!

My initial thought is maybe we don't need a separate repo like Vue's. Maybe just a label on the PR? This may also be a bit burdensome for more open ended discussion (why maintain a doc at the outset?). We should make it clear initial discussions may not need a doc / RFC, but as the proposal becomes more concrete it will need one.

@marslan-li any thoughts?

**Comment by jplaisted** [comment]
Closed with #1754.
