### ISSUE TITLE
list of requirements?

### ISSUE THREAD

**Issue by mmilano** [linkedin/datahub#1701]
is there a top-level list of core requirements necessary to run and use various datahub components including the various source ingestion paths (mysql, etc)?

**Comment by liangjun-jiang** [comment]
To run datahub application, the [quickstart](https://github.com/linkedin/datahub/tree/master/docker/quickstart) lists all necessary components. 
However, to ingest data into datahub by using `metadata-ingestion` scripts, you will need to set up another set of environment.  I wrote this [LinkIn Datahub Metadata Ingestion Scripts Unofficical Guide](https://medium.com/@liangjunjiang/linkin-datahub-etl-unofficical-guide-7c3949483f8b) to walk through some use cases I have played with. 
If your data source is MySQL, then look at the mysql-etl.py
If your data sources is Hive, then look at the hive-etl.py
Those ingestion scripts depends on what you have.

**Comment by mmilano** [comment]
thanks @liangjun-jiang. 
yes, the quickstart does work. 
there seems to be some ambiguity around the other steps though, and the pieces necessary for them. i had all sorts of unclear issues with trying to run the mySQL ingestion.

for example:
* which JDK is official? 
* which python version? your helpful unofficial doc mentions python3, but other references are to python2.
* can gradlew upgrade?

also, on a tangent, is there a script to add users?

**Comment by liangjun-jiang** [comment]
1. JDK 1.8 is the official one, as stated [here](https://github.com/linkedin/datahub/blob/master/docs/developers.md)
>While it may be possible to build and run DataHub using newer versions of Java, we currently only support Java 1.8 (aka Java 8).
2. For the `metadata-ingestion`, I have all the scripts working under python3. I am aware of there is one script needing Python2 from the documentation.
3. I think you can upgrade gradlew. 
`add users` you mean the users to log in the frontend app? there is a SQL script. If you refer to add `CorpUser` entity, you can also look at `ldap-etl` under `metadata-ingestion`.

**Comment by mars-lan** [comment]
> 2. For the `metadata-ingestion`, I have all the scripts working under python3. I am aware of there is one script needing Python2 from the documentation.

This should be addressed by https://github.com/linkedin/datahub/pull/1710

**Comment by mars-lan** [comment]
> * can gradlew upgrade?

In fact it looks like the `pegasus` plugin isn't compatible with gradle 6 yet so 5.6.4 is the latest we can use: https://github.com/linkedin/rest.li/issues/354

I'll close this issue now assuming all questions have been answered. Feel free to reopen otherwise.
