### ISSUE TITLE
kafka_etl to ZooKeeper: connection refused

### ISSUE THREAD

**Issue by minhdn90** [linkedin/datahub#1703]
I'm trying to run ingestion using kafka_etl.py, with ZOOKEEPER='localhost:2181'. For some reason it couldn't connect to the `zookeeper` container

ingestion    | Connection dropped: socket connection error: Cannot assign requested address
ingestion    | Connection dropped: socket connection error: Connection refused
ingestion    | Failed connecting to Zookeeper within the connection retry policy.
ingestion    | Traceback (most recent call last):
ingestion    |   File "kafka_etl.py", line 51, in <module>
ingestion    |     zk.start()
ingestion    |   File "/root/.local/lib/python3.7/site-packages/kazoo/client.py", line 560, in start
ingestion    |     raise self.handler.timeout_exception("Connection time-out")
ingestion    | kazoo.handlers.threading.KazooTimeoutError: Connection time-out
ingestion exited with code 1

When I run `docker container ls` it shows `zookeeper` is up and running at
`
2888/tcp, 0.0.0.0:2181->2181/tcp, 3888/tcp
`
How could I resolve this?

**Comment by mars-lan** [comment]
Can you check if you're able to connect to localhost:2181 using telnet or nc?
```
$ telnet localhost 2181
$ nc -vz localhost 2181
```

**Comment by mars-lan** [comment]
Assuming this issue has been resolved. Feel free to reopen otherwise.
