### ISSUE TITLE
Remove Legacy or Inactive Models

### ISSUE THREAD

**Issue by jsotelo** [linkedin/datahub#1719]
**Is your feature request related to a problem? Please describe.**
When a new developer attempts to familiarize themselves with the codebase, he/she will come across data models such as [DeploymentInfo](https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/dataset/DeploymentInfo.pdl) and [CorpGroupSnapshot](https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/metadata/snapshot/CorpGroupSnapshot.pdl) which are not currently used. This can lead to wasted time and confusion.

**Describe the solution you'd like**
Legacy or inactive data models should be removed from all subdirectories/components to make it easier to onboard new developers onto DataHub's codebase.

**Describe alternatives you've considered**
Alternatively, we could re-activate/fix said data models.

**Additional context**
Not applicable

**Comment by liangjun-jiang** [comment]
I think it is little bit too early to call `DeploymentInfo` and `CorpGroupSnapshot` legacy or inactive model. Some forks are using them .

**Comment by jsotelo** [comment]
I was informed by @keremsahin1 that DeploymentInfo was legacy via Slack. It's not linked from MCE/MAE [Snapshot](https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/metadata/snapshot/Snapshot.pdl). How are people using it? Did they fork and linked it themselves?

**Comment by mars-lan** [comment]
We actively use `CorpGroupSnapshot` internally and may open source the related code in the future. `DeploymentInfo` is a legacy model that will be replaced by a new entity known as `DatasetInstance`.
