### ISSUE TITLE
How to extract metadata from data sources

### ISSUE THREAD

**Issue by sauravsahu02** [linkedin/datahub#1720]
Where can I find the ETL scripts which extracts or crawls the metadata?
We have our data in various forms ex : in S3, CSV, parquets.
How can I feed or stream the metadata from these data sources to Kafka or Datahub system ?

My preference would be not to copy the data to external platforms.

**Comment by liangjun-jiang** [comment]
the sample scripts are under [metadata-ingestion](https://github.com/linkedin/datahub/tree/master/metadata-ingestion) folder 
By running any of those scripts, for example, `mysql-etl.py`, it will connect to MySQL database, find the database you specified, and find all table schemas, assemble the schemas into Kafka message that Datahub recognize, and publish the message into Kafka. 
Please take a look at the [architecture diagram](https://github.com/linkedin/datahub/blob/master/docs/architecture/architecture.md) to understand how the system works.

**Comment by mars-lan** [comment]
Assuming the question has been answered. Feel free to reopen otherwise.
