### ISSUE TITLE
Allow piwik to be disabled by default

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1723]
**Describe the bug**

I found that the browser console reported the `piwik.js` request exception. Is the http response appropriate?

![2020-07-08 10-07-40屏幕截图](https://user-images.githubusercontent.com/11460848/86866575-cefd7080-c103-11ea-82d2-0d723824c032.png)

**Comment by mars-lan** [comment]
The piwik configuration can be set here: https://github.com/linkedin/datahub/blob/master/datahub-frontend/conf/application.conf#L59. You can most probably set it via the `DATAHUB_PIWIK_URL` environmental variable in docker.

**Comment by cobolbaby** [comment]
@mars-lan , PIWIK is mainly for website visit statistics. As an internal enterprise application, datahub often does not consider configuring this option. However, the current program is not very friendly to this.

**Comment by mars-lan** [comment]
Agree. Changing this to a feature request.

**Comment by cptran777** [comment]
Currently this is fixed in our internal version and will be included in the push following the initial "catch up" PR for the UI

**Comment by cobolbaby** [comment]
Sound good. @cptran777  Thanks.

**Comment by mars-lan** [comment]
@cobolbaby this might have been fixed already at HEAD. Could you confirm, @cobolbaby?

**Comment by cobolbaby** [comment]
It's not fixed at master branch. Maybe it could be fixed by #1821

**Comment by cptran777** [comment]
@cobolbaby The latest master branch should have fixed this. (Verified with ./docker/quickstart.sh)

**Comment by cobolbaby** [comment]
Confirmed.
