### ISSUE TITLE
/api/v2/list/platforms endpoint not exist

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1725]
**Describe the bug**

When doing search in version v0.4.1, the /api/v2/list/platforms api endpoint doesn't exist

![2020-07-09 09-08-10屏幕截图](https://user-images.githubusercontent.com/11460848/86985573-2236f800-c1c4-11ea-9b0c-878278f1ff4d.png)

**Comment by liangjun-jiang** [comment]
@cobolbaby , the [readme.md](https://github.com/linkedin/datahub/tree/master/gms) gives a list of supported endpoint.

**Comment by cobolbaby** [comment]
So it should be the bug of datahub-frontend v0.4.1.

**Comment by keremsahin1** [comment]
@cobolbaby Thanks for reporting this.

`/api/v2/list/platforms` is a legacy mid-tier endpoint which doesn't exist now. I assume there is some legacy code in datahub-ui which is still calling this endpoint. Can you please confirm & fix this @cptran777 ?

You can check all existing mid-tier endpoint in https://github.com/linkedin/datahub/blob/master/datahub-frontend/conf/routes
