### ISSUE TITLE
UI support for customProperties in DatasetProperties aspect

### ISSUE THREAD

**Issue by jsotelo** [linkedin/datahub#1730]
**Is your feature request related to a problem? Please describe.**
The aspect `com.linkedin.pegasus2avro.dataset.DatasetProperties` has a field `customProperties` that is valuable in representing data properties that don't quite fit in any other (current) data model which is very valuable. However, the UI doesn't currently display any custom properties.

**Describe the solution you'd like**
Please add a UI representation (tab?) to convey all custom properties in that aspect. Perhaps similar to the Schema tab?

**Describe alternatives you've considered**
No other alternatives have been considered

**Additional context**
For the DataHub users/devs that are not able to afford forking the repo and creating their own data models, having basic support (UI display) for non-off-the-shelf data assets is extremely valuable because it can be used as a stop-gap while developing more explicit data models (or waiting for "official" DataHub models to be released). 

As DataHub begins to have a greater presence and influence in users'/devs' tech stack, more prioritization and resources can be allocated into developing code (or making open-source contributions) that enables them to move data out of `customProperties` and into a more explicit data model.

**Comment by jsotelo** [comment]
Link to slack discussion: https://datahubspace.slack.com/archives/CV2UXSE9L/p1594430884039000

**Comment by cobolbaby** [comment]
Such as some custom tags...

**Comment by jsotelo** [comment]
I was focused more on `customProperties` but it totally makes sense to also include `tags` as part of this, IMO.

**Comment by pmsrao** [comment]
may be we can look at two steps 

- display attributes in UI `customerProperties` & `tags` and 

- making it available for search
this issue can focus on the first aspect

**Comment by cobolbaby** [comment]
I really want to know the progress of this work, and I look forward to setting some tags on the dataset on the page.
