### ISSUE TITLE
Switch mysql db store to postgres  

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1734]
Considering the technology stack used, the company made it clear that pg should be used as a unified storage. 
So I need to switch mysql to pg. But when I start the gms service, it throws execption `No org.postgresql.Driver Class`.
Could the relevant dependencies be packaged in the compilation process to facilitate switching jdbc driver.

**Comment by keremsahin1** [comment]
This should ideally be pretty straightforward because we provide DAOs for Ebean. Make sure you update Ebean configs to access to your PostgreSQL server. You also need to replace below line for the JDBC connector dependency for PostgreSQL.

https://github.com/linkedin/datahub/blob/master/gms/war/build.gradle#L10

**Comment by mars-lan** [comment]
@cobolbaby did you have a chance to try @keremsahin1's suggestion? I also assume our Ebean-based DAO can talk to Postgres without much trouble.

**Comment by cobolbaby** [comment]
@clojurians-org has switched the postgresql db in the forked project. 

Commit:  https://github.com/clojurians-org/simple-datahub/commit/6e678bba87046401977f8427955043a96a9a5e98

We need to modify the code:

- related to `externalDependency.mysqlConnector`
- `EBEAN_DATASOURCE_DRIVER`
- `EBEAN_DATASOURCE_URL`

**Comment by mars-lan** [comment]
Cool. Could you confirm that the doc here is sufficient? https://github.com/linkedin/datahub/blob/master/gms/README.md

**Comment by cobolbaby** [comment]
After searching `externalDependency.mysqlConnector` globally, I found three places that need to be modified:

- datahub-frontend/play.gradle
- gms/war/build.gradle
- build.gradle

In addition, the field type in init.sql needs to be adjusted

**Comment by cobolbaby** [comment]
Is it possible to package the pg driver by default?

**Comment by mars-lan** [comment]
One option is to make it a gradle build option so you can choose to package mysql or pg (or any others DB systems in the future).

**Comment by cobolbaby** [comment]
If adopting this method, how to deliver docker images?

**Comment by mars-lan** [comment]
Good point. Let me think about it a bit more and create a proper PR for this.
