### ISSUE TITLE
Table lineage relationship description

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1735]
Although the UI has shown the tables lineage, the blood relationship lacks descriptive information to describe the blood line by which way, such as the stored procedures or flink jobs.

What information can I fill in to improve the relationship information?

**Comment by liangjun-jiang** [comment]
@cobolbaby , the `dataprocess` is actually used to represent the information `how` a dataset is generated. For instance, the `dataprocess` can be your `stored procedure`.
For the `flink job`, it will be in different feature and it is under the way.

**Comment by itc180016** [comment]
@liangjun-jiang,   I produced  a dataprocess message to my Datahub successfully. In addition, the datasets of input and output is already exists. But, I can't see anything about it on the UI.    
  
Where should I check this information on the UI?
  
dataprocess message:
```{
    'auditHeader': None,
    'proposedSnapshot': ('com.linkedin.pegasus2avro.metadata.snapshot.DataProcessSnapshot',
                         {
        'urn': 'urn:li:dataProcess:(platform,processname,DEV)',
        'aspects': [
            {
                'owners': [
                    {
                        'owner': 'urn:li:corpuser:xxx',
                        'type': 'DATAOWNER'
                    },
                    {
                        'owner': 'urn:li:corpuser:zzz',
                        'type': 'DATAOWNER'
                    }],
                'lastModified': {
                    'time': 1594962337000,
                    'actor': 'urn:li:corpuser:aaa'
                }
            },
            {
                'inputs': [
                    'urn:li:dataset:(urn:li:dataPlatform:platform,dataset1,DEV)',
                    'urn:li:dataset:(urn:li:dataPlatform:platform,dataset2,DEV)'],
                'outputs': [
                    'urn:li:dataset:(urn:li:dataPlatform:platform,dataset3,DEV)']
            }]
    }),
    'proposedDelta': None
}
```

**Comment by liangjun-jiang** [comment]
@itc180016 , as far as I know, the `dataprocess` has not been implemented in UI. I checked in the backend code. and I am not good at the technology used in the Datahub frontend.

**Comment by cobolbaby** [comment]
@mars-lan  Could you add the `feaure-request` tags?

**Comment by cobolbaby** [comment]
I hope to clarify the planned time of this function. When will the front-end service plan support the display of this information?

**Comment by jjoyce0510** [comment]
@cobolbaby The latest React UI support visualizing lineage between Datasets, DataJobs, and Dashboards. Does this suffice or are you looking for additional qualification? IE. descriptions on the edges themselves?

**Comment by cobolbaby** [comment]
It does meet the demand. I will try it out in the near future.

**Comment by shirshanka** [comment]
Closing as this has now been implemented
