### ISSUE TITLE
How can I add label description to the table or field

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1736]
How can I add label description to the table or field

**Comment by jywadhwani** [comment]
I believe we already have `description` field as part of `SchemaField` https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/schema/SchemaField.pdl#L28. This in turn is part of Dataset Aspect `SchemaMetadata`
Is this what you are looking for @cobolbaby ?

**Comment by cobolbaby** [comment]
Does this information support elasticsearch full-text indexing?

**Comment by camelliazhang2018** [comment]
You will need to define the search document model and follow the search-onboarding guide:  
https://github.com/linkedin/datahub/tree/master/metadata-models/src/main/pegasus/com/linkedin/metadata/search
https://github.com/linkedin/datahub/blob/master/docs/how/search-onboarding.md

Internally we have schema search index built, not available on open source world yet.

**Comment by cobolbaby** [comment]
> I believe we already have `description` field as part of `SchemaField` https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/schema/SchemaField.pdl#L28. This in turn is part of Dataset Aspect `SchemaMetadata`
> Is this what you are looking for @cobolbaby ?

After analyzing the `DatasetSnapshot` structure, it is found that the description information will be in 
`DatasetProperties` and `SchemaMetadata`:

- `DatasetProperties` includes table comment in db, 
- `SchemaMetadata` includes field comment in db.

In addition, I also want to customize some tags information for filtering, similar to lyft/amundsen core feature.

**Comment by cobolbaby** [comment]
> You will need to define the search document model and follow the search-onboarding guide:
> https://github.com/linkedin/datahub/tree/master/metadata-models/src/main/pegasus/com/linkedin/metadata/search
> https://github.com/linkedin/datahub/blob/master/docs/how/search-onboarding.md
> 
> Internally we have schema search index built, not available on open source world yet.

@camelliazhang2018,  Because the current model definition already contains the information I need, do I only need to modify the content defined in [index.json](https://github.com/linkedin/datahub/blob/master/docker/elasticsearch/dataset-index-config.json)

**Comment by camelliazhang2018** [comment]
@cobolbaby You need to add description field for both the [dataset document search model ](metadata-models/src/main/pegasus/com/linkedin/metadata/search/DatasetDocument.pdl) and dataset-index-config.json.

**Comment by camelliazhang2018** [comment]
"In addition, I also want to customize some tags information for filtering, similar to lyft/amundsen core feature." To do this, we can add "tags" field for the search index schema, & add it as a [facet](datahub-frontend/app/controllers/api/v2/Search.java) on frontend if needed.

**Comment by cobolbaby** [comment]
@camelliazhang2018  I found the dataset document search model has contained the `description` attribute. I doubt what this field refers to, is it the `description` of `DatasetProperties`?

If I want to add the field `description` of `DatasetProperties`? How should I do? Or maybe you could submit a PR.

In addition, does the search support Chinese word segmentation?

**Comment by cobolbaby** [comment]
> "In addition, I also want to customize some tags information for filtering, similar to lyft/amundsen core feature." To do this, we can add "tags" field for the search index schema, & add it as a [facet](datahub-frontend/app/controllers/api/v2/Search.java) on frontend if needed.

Good point.

**Comment by camelliazhang2018** [comment]
> @camelliazhang2018 I found the dataset document search model has contained the `description` attribute. I doubt what this field refers to, is it the `description` of `DatasetProperties`?
> 
> If I want to add the field `description` of `DatasetProperties`? How should I do? Or maybe you could submit a PR.
> 
> In addition, does the search support Chinese word segmentation?

We actually have description internally, we will submit a PR. You also raised a good question: most of time, the field in search document `maps` to a field from one aspect. Let's say you want to add another brand new field, you will need to (as I mentioned above) "add description field for both the dataset document search model and dataset-index-config.json."

**Comment by camelliazhang2018** [comment]
> In addition, does the search support Chinese word segmentation?

I would submit a new ticket for language support :) You may want to try [Smart Chinese Analysis plugin ](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-smartcn.html)

**Comment by cobolbaby** [comment]
I'm looking forward.

**Comment by jywadhwani** [comment]
@cobolbaby not sure if you have any more questions on the `description` field, but as mentioned, we do have the `description` field in search document model https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/dataset/DatasetProperties.pdl#L13, which is coming from `DatasetProperties` aspect https://github.com/linkedin/datahub/blob/master/metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DatasetIndexBuilder.java#L71.
I see you have a request for Chinese word segmentation which @camelliazhang will be working on. Is there anything else we can help you with, as far as this ticket is concerned @cobolbaby ?

**Comment by cobolbaby** [comment]
@jywadhwani As far as the current demand is concerned, I need to perform classified search based on the `description` property of the `DatasetProperties` aspect. But the current [search model](https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/metadata/search/DatasetDocument.pdl) does not contain the `DatasetProperties` aspect. Could you do me a favor?

Of course, if all the information contained in `DatasetProperties` aspect can also be included in the search scope, it would be perfect. such as description, tags.

**Comment by jywadhwani** [comment]
The current search model supports fields that are primitive types or an array of primitive types. So yes we don't support storing the entire aspect in search document model, but the individual (flattened) fields of the aspect, the extraction logic of which is in the `DatasetIndexBuilder`.

So we do have `description` in the search model (coming from `DatasetProperties` aspect). Is `tags` the only other field that you would like to have the search capability over?

**Comment by cobolbaby** [comment]
Yes. So far, the tags, description and table names are the basis for our search.

**Comment by cobolbaby** [comment]
![2020-07-28 10-23-32屏幕截图](https://user-images.githubusercontent.com/11460848/88611804-6bd87b80-d0bc-11ea-975d-41cce8ae1572.png)

![2020-07-28 10-27-40屏幕截图](https://user-images.githubusercontent.com/11460848/88612086-fc16c080-d0bc-11ea-9d2a-ce06475fb29f.png)

@jywadhwani @camelliazhang2018  As shown above, the current data set has a description, but when I search through the search box, I cannot find the result. Is this just because of Chinese word segmentation?

**Comment by camelliazhang2018** [comment]
@jywadhwani You demoed how to add a new field for search index in one of the town hall meetings, could you please share  that info in /demo, similar to https://github.com/linkedin/datahub/blob/master/docs/demo/graph-onboarding.md. 
We should allow users to customize their index mapping & query templates based on their need.

**Comment by camelliazhang2018** [comment]
@cobolbaby If you have a few fields to support, I would suggest you add them for your own dataset index mapping, we can help with instructions.

**Comment by mars-lan** [comment]
Closing this assuming it's been address by https://github.com/linkedin/datahub/pull/1791. Feel free to reopen otherwise.
