### ISSUE TITLE
AWS ElasticSearch

### ISSUE THREAD

**Issue by fabiofilz** [linkedin/datahub#1737]
Is it possible to use AWS Elasticsearch? If it is possible, what is the configuration needed?

**Comment by mars-lan** [comment]
It should be possible in theory. You can try changing the configs here: https://github.com/linkedin/datahub/blob/master/gms/factories/src/main/java/com/linkedin/common/factory/RestHighLevelClientFactory.java

**Comment by jplaisted** [comment]
Note that we're using 5.6.8 of the client API, which could cause issues. If you do get this working, please document what steps you had to take, if any weren't straight forward. That way we can either add a patch to make it easier in the future, or the very least add some documentation. Thanks!

**Comment by mars-lan** [comment]
Let's concentrate the discussion in this issue: https://github.com/linkedin/datahub/issues/1722
