### ISSUE TITLE
Improve the security of the kubernetes/helm charts

### ISSUE THREAD

**Issue by shakti-garg-saxo** [linkedin/datahub#1747]
**Is your feature request related to a problem? Please describe.**
We are trying to use helm charts in contrib module. First, deployment in dev failed due to some hardcodings. In the meantime, we also discovered it having some security vulnerabilities like passwords being passed in "verbatim", etc

**Describe the solution you'd like**
Secure and automated deployment of helm charts

**Describe alternatives you've considered**
1) move the password parameters from verbatim mode to kube-secrets
2) use configmaps to discover service configurations for easy deployment
3) initcontainer for initializing the mysql schema
4) remove hard-coded references like "datahub-gms-deployment-configmap"
5) refactorings for ex, removal of obsolete code like contrib/kubernetes/yaml

**Comment by mars-lan** [comment]
@bharatak could you help fix these issues?

**Comment by mars-lan** [comment]
Sorry some confusions here. @shakti-garg-saxo will be working on a PR for this.

**Comment by jsotelo** [comment]
@shakti-garg-saxo Are you planning on including support for creating RBAC resources too? For example:
```
rbac:
  # Specifies whether RBAC resources should be created
  create: true
```

**Comment by shakti-garg-saxo** [comment]
We are currently not trying to create service account as part of helm chart. We are going with assumption that serviceaccount (roles, clusterRole, etc) is pre-configured and is a parameter to LDH charts.

**Comment by mars-lan** [comment]
@shakti-garg-saxo do you plan to re-use this issue for further security improvements? If not please feel free to close it.
