### ISSUE TITLE
MCE & MAE consumers reading from Kerberos-authenticated kafka topics

### ISSUE THREAD

**Issue by shakti-garg-saxo** [linkedin/datahub#1749]
**Is your feature request related to a problem? Please describe.**
Reading/Writing to topics in the Kafka cluster needs SASL authentication mechanism. 

**Describe the solution you'd like**
A toggle in MCE and MAE consumers which can help them to switch to SASL authentication if needed.

**Describe alternatives you've considered**
1. Adding a toggle paramater to MCE and MAE consumers and option to provide a JAAS file.
2. updation of helm chars to read keytab and krb5 file from secrets.

**Comment by mars-lan** [comment]
@shakti-garg-saxo You might want to take part in this PR: https://github.com/linkedin/datahub/pull/1745

**Comment by shakti-garg-saxo** [comment]
Ok. closing this issue.

**Comment by mars-lan** [comment]
I didn't mean that the PR solve this exact issue as it only exposes SSL configs. It's more of a good reference on how to add Keberos support.

**Comment by mars-lan** [comment]
Actually never mind, looks like the SASL configs are exposed. Closing this issue now.

**Comment by shakti-garg-saxo** [comment]
Yes. I closed it after reviewing the PR. I will submit the helm related changes for it in PR for #1747
