### ISSUE TITLE
kafka consumer not showing any data

### ISSUE THREAD

**Issue by priyanka1555** [linkedin/datahub#1753]
Hi, I want to check  whether the data produced by mce_cli.py file is consumed by kafka consumer or not, so  I am trying to run the mce-cli.py file by using the produce and consume argument, mce_cli.py file produces the data, but while running the mce_cli.py file with consume option, it is not displaying any data.

**Comment by mars-lan** [comment]
Could you share the exact commands you ran for both producing & consuming?

**Comment by priyanka1555** [comment]
./gradlew :metadata-events:mxe-schemas:build
(which generate MetadataChangeEvent.avsc file)
python3 metadata-ingestion/mce-cli/mce_cli.py produce -d metadata-ingestion/mce-cli/bootstrap_mce.dat -b localhost:9092 -s http://localhost:8081
python3 metadata-ingestion/mce-cli/mce_cli.py consume -b localhost:9092 -s http://localhost:8081

**Comment by priyanka1555** [comment]
I am trying to print the subscribed topic also, but it is showing "None" 
    print(c.subscribe([topic]))
the  problem can be here also, it might be unable to subscribe the topic.

**Comment by RealChrisL** [comment]
Hi, @priyanka1555 

Due to the default CLI consuming is real-time behavior, please run the `consume` command in another terminal before you `produce` the records.

Meanwhile, if you leverage the CLI not under the path `datahub/metadata-ingestion/mce-cli`, you may need to specify the SCHEMA_RECORD with `-l`, 

e.g. if you produce & consume records with CLI under the project root path with the default Kafka config:
1. Generate the event schema: `./gradlew :metadata-events:mxe-schemas:build`
2. Open a new terminal to consume the events: `python3 metadata-ingestion/mce-cli/mce_cli.py consume -l metadata-events/mxe-schemas/src/renamed/avro/com/linkedin/mxe/MetadataChangeEvent.avsc`
3. Produce the events: `python3 metadata-ingestion/mce-cli/mce_cli.py produce -l metadata-events/mxe-schemas/src/renamed/avro/com/linkedin/mxe/MetadataChangeEvent.avsc -d metadata-ingestion/mce-cli/bootstrap_mce.dat`

**Comment by priyanka1555** [comment]
Hi,
It is still not showing any output.

**Comment by priyanka1555** [comment]
It is also unableto subscribe to topic

**Comment by RealChrisL** [comment]
Hi, @priyanka1555,
Are you able to capture the console output while you produce the records?
How did you find `unable to subscribe to the topic`? Would you be able to provide the error messages?
If you are referring to the [AvroConsumer](https://docs.confluent.io/current/clients/confluent-kafka-python/#avroconsumer-legacy), it is supposed to raise the error for invalid configurations.

**Comment by priyanka1555** [comment]
Hi,
I am recieving this output while running this command: python3 metadata-ingestion/mce-cli/mce_cli.py produce -l metadata-events/mxe-schemas/src/renamed/avro/com/linkedin/mxe/MetadataChangeEvent.avsc -d metadata-ingestion/mce-cli/bootstrap_mce.dat

Output:
Producing MetadataChangeEvent records to topic MetadataChangeEvent. ^c to exit.
  MCE1: {"auditHeader": None, "proposedSnapshot": ("com.linkedin.pegasus2avro.metadata.snapshot.CorpUserSnapshot", {"urn": "urn:li:corpuser:datahub", "aspects": [("com.linkedin.pegasus2avro.identity.CorpUserInfo", {"active": True, "displayName": "Data Hub", "fullName": "Data Hub", "email": "datahub@linkedin.com", "title": "CEO"})]}), "proposedDelta": None}

  MCE2: {"auditHeader": None, "proposedSnapshot": ("com.linkedin.pegasus2avro.metadata.snapshot.CorpUserSnapshot", {"urn": "urn:li:corpuser:jdoe", "aspects": [("com.linkedin.pegasus2avro.identity.CorpUserInfo", {"active": True, "displayName": "John Doe", "fullName": "John Doe", "email": "jdoe@linkedin.com", "title": "Software Engineer"})]}), "proposedDelta": None}

  MCE3: {"auditHeader": None, "proposedSnapshot": ("com.linkedin.pegasus2avro.metadata.snapshot.DatasetSnapshot", {"urn": "urn:li:dataset:(urn:li:dataPlatform:kafka,SampleKafkaDataset,PROD)", "aspects": [("com.linkedin.pegasus2avro.common.Ownership", {"owners":[{"owner":"urn:li:corpuser:jdoe","type":"DATAOWNER"}, {"owner":"urn:li:corpuser:datahub","type":"DATAOWNER"}],"lastModified":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"}}),("com.linkedin.pegasus2avro.common.InstitutionalMemory", {"elements":[{"url":"https://www.linkedin.com","description":"Sample doc","createStamp":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"}}]}), ("com.linkedin.pegasus2avro.schema.SchemaMetadata", {"schemaName":"SampleKafkaSchema","platform":"urn:li:dataPlatform:kafka","version":0,"created":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"},"lastModified":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"},"hash":"","platformSchema":{"documentSchema":"{\"type\":\"record\",\"name\":\"SampleKafkaSchema\",\"namespace\":\"com.linkedin.dataset\",\"doc\":\"Sample Kafka dataset\",\"fields\":[{\"name\":\"field_foo\",\"type\":[\"string\"]},{\"name\":\"field_bar\",\"type\":[\"boolean\"]}]}"},"fields":[{"fieldPath":"field_foo","description":"Foo field description","nativeDataType":"string","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"field_bar","description":"Bar field description","nativeDataType":"boolean","type":{"type":{"com.linkedin.pegasus2avro.schema.BooleanType":{}}}}]})]}), "proposedDelta": None}

  MCE4: {"auditHeader": None, "proposedSnapshot": ("com.linkedin.pegasus2avro.metadata.snapshot.DatasetSnapshot", {"urn": "urn:li:dataset:(urn:li:dataPlatform:hdfs,SampleHdfsDataset,PROD)", "aspects": [("com.linkedin.pegasus2avro.common.Ownership", {"owners":[{"owner":"urn:li:corpuser:jdoe","type":"DATAOWNER"}, {"owner":"urn:li:corpuser:datahub","type":"DATAOWNER"}],"lastModified":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"}}),("com.linkedin.pegasus2avro.dataset.UpstreamLineage", {"upstreams":[{"auditStamp":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"},"dataset":"urn:li:dataset:(urn:li:dataPlatform:kafka,SampleKafkaDataset,PROD)","type":"TRANSFORMED"}]}),("com.linkedin.pegasus2avro.common.InstitutionalMemory", {"elements":[{"url":"https://www.linkedin.com","description":"Sample doc","createStamp":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"}}]}), ("com.linkedin.pegasus2avro.schema.SchemaMetadata", {"schemaName":"SampleHdfsSchema","platform":"urn:li:dataPlatform:hdfs","version":0,"created":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"},"lastModified":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"},"hash":"","platformSchema":{"documentSchema":"{\"type\":\"record\",\"name\":\"SampleHdfsSchema\",\"namespace\":\"com.linkedin.dataset\",\"doc\":\"Sample HDFS dataset\",\"fields\":[{\"name\":\"field_foo\",\"type\":[\"string\"]},{\"name\":\"field_bar\",\"type\":[\"boolean\"]}]}"},"fields":[{"fieldPath":"field_foo","description":"Foo field description","nativeDataType":"string","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"field_bar","description":"Bar field description","nativeDataType":"boolean","type":{"type":{"com.linkedin.pegasus2avro.schema.BooleanType":{}}}}]})]}), "proposedDelta": None}

  MCE5: {"auditHeader": None, "proposedSnapshot": ("com.linkedin.pegasus2avro.metadata.snapshot.DatasetSnapshot", {"urn": "urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD)", "aspects": [("com.linkedin.pegasus2avro.common.Ownership", {"owners":[{"owner":"urn:li:corpuser:jdoe","type":"DATAOWNER"}, {"owner":"urn:li:corpuser:datahub","type":"DATAOWNER"}],"lastModified":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"}}),("com.linkedin.pegasus2avro.dataset.UpstreamLineage", {"upstreams":[{"auditStamp":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"},"dataset":"urn:li:dataset:(urn:li:dataPlatform:hdfs,SampleHdfsDataset,PROD)","type":"TRANSFORMED"}]}),("com.linkedin.pegasus2avro.common.InstitutionalMemory", {"elements":[{"url":"https://www.linkedin.com","description":"Sample doc","createStamp":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"}}]}), ("com.linkedin.pegasus2avro.schema.SchemaMetadata", {"schemaName":"SampleHiveSchema","platform":"urn:li:dataPlatform:hive","version":0,"created":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"},"lastModified":{"time":1581407189000,"actor":"urn:li:corpuser:jdoe"},"hash":"","platformSchema":{"documentSchema":"{\"type\":\"record\",\"name\":\"SampleHiveSchema\",\"namespace\":\"com.linkedin.dataset\",\"doc\":\"Sample Hive dataset\",\"fields\":[{\"name\":\"field_foo\",\"type\":[\"string\"]},{\"name\":\"field_bar\",\"type\":[\"boolean\"]}]}"},"fields":[{"fieldPath":"field_foo","description":"Foo field description","nativeDataType":"string","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"field_bar","description":"Bar field description","nativeDataType":"boolean","type":{"type":{"com.linkedin.pegasus2avro.schema.BooleanType":{}}}}]})]}), "proposedDelta": None}

  MCE6: {"auditHeader": None, "proposedSnapshot": ("com.linkedin.pegasus2avro.metadata.snapshot.DataProcessSnapshot", {"urn": "urn:li:dataProcess:(sqoop,DEMO,PROD)", "aspects": [{"owners":[{"owner":"urn:li:corpuser:datahub","type":"DATAOWNER"}],"lastModified":{"time":1581407189000,"actor":"urn:li:corpuser:datahub"}},{"inputs":["urn:li:dataset:(urn:li:dataPlatform:cassandra,barEarth,DEV)","urn:li:dataset:(urn:li:dataPlatform:cassandra,barMars,DEV)"],"outputs":["urn:li:dataset:(urn:li:dataPlatform:hbase,barSky,PROD)","urn:li:dataset:(urn:li:dataPlatform:hbase,barOcean,PROD)"]}]}), "proposedDelta": None}

Flushing records...

**Comment by priyanka1555** [comment]
Hi,
I am recieving this output while running this command: python3 metadata-ingestion/mce-cli/mce_cli.py consume -l metadata-events/mxe-schemas/src/renamed/avro/com/linkedin/mxe/MetadataChangeEvent.avsc

Consuming MetadataChangeEvent records from topic MetadataChangeEvent with group MetadataChangeEvent. ^c to exit.

**Comment by priyanka1555** [comment]
And I am trying to print the subscribed topic in the mce_cli.py file on line number "54"
 print(c.subscribe([topic]))
output:
None

**Comment by RealChrisL** [comment]
According to the console outputs, it looks like your Kafka settings work fine.
Besides, it is normal for the `subscribe()` to return None, otherwise, it will raise KafkaException or RuntimeError.
Would suggest you set the breakpoints in the `poll()` to see if there are messages being consumed.
Please also keep noted, starting the consumer parallelly before running the producer CLI.

**Comment by priyanka1555** [comment]
poll() method returns "None".
msg = c.poll(1)
print(msg)

Otput: None

**Comment by priyanka1555** [comment]
Hi,
I am facing this error while running this command  " python3 metadata-ingestion/mce-cli/mce_cli.py produce -l metadata-events/mxe-schemas/src/renamed/avro/com/linkedin/mxe/MetadataChangeEvent.avsc -d metadata-ingestion/mce-cli/bootstrap_mce.dat" 
Error:
bootstrap: Timed out ApiVersionRequest in flight (after 10009ms, timeout #0)
bootstrap: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests

**Comment by mars-lan** [comment]
Sounds like you're unable to reach the kafka broker. Can you make sure that the docker image is up and running using this debugging guide? https://github.com/linkedin/datahub/blob/master/docs/debugging.md

**Comment by priyanka1555** [comment]
Can you please tell me, what should be the expected output while running this command :
python3 metadata-ingestion/mce-cli/mce_cli.py consume -l metadata-events/mxe-schemas/src/renamed/avro/com/linkedin/mxe/MetadataChangeEvent.avsc

**Comment by RealChrisL** [comment]
You are supposed to see the Avro events which you produced, take the `bootstrap_mce.dat` as an example.

```
Consuming MetadataChangeEvent records from topic MetadataChangeEvent with group MetadataChangeEvent. ^c to exit.

avro_event: {'auditHeader': None, 'proposedSnapshot': {'urn': 'urn:li:corpuser:datahub', 'aspects': [{'active': True, 'displayName': 'Data Hub', 'email': 'datahub@linkedin.com', 'title': 'CEO', 'managerUrn': None, 'departmentId': None, 'departmentName': None, 'firstName': None, 'lastName': None, 'fullName': 'Data Hub', 'countryCode': None}]}, 'proposedDelta': None}
	
avro_event: {'auditHeader': None, 'proposedSnapshot': {'urn': 'urn:li:corpuser:jdoe', 'aspects': [{'active': True, 'displayName': 'John Doe', 'email': 'jdoe@linkedin.com', 'title': 'Software Engineer', 'managerUrn': None, 'departmentId': None, 'departmentName': None, 'firstName': None, 'lastName': None, 'fullName': 'John Doe', 'countryCode': None}]}, 'proposedDelta': None}
	
avro_event: {'auditHeader': None, 'proposedSnapshot': {'urn': 'urn:li:dataset:(urn:li:dataPlatform:kafka,SampleKafkaDataset,PROD)', 'aspects': [{'owners': [{'owner': 'urn:li:corpuser:jdoe', 'type': 'DATAOWNER', 'source': None}, {'owner': 'urn:li:corpuser:datahub', 'type': 'DATAOWNER', 'source': None}], 'lastModified': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}}, {'elements': [{'url': 'https://www.linkedin.com', 'description': 'Sample doc', 'createStamp': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}}]}, {'schemaName': 'SampleKafkaSchema', 'platform': 'urn:li:dataPlatform:kafka', 'version': 0, 'created': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}, 'lastModified': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}, 'deleted': None, 'dataset': None, 'cluster': None, 'hash': '', 'platformSchema': {'documentSchema': '{"type":"record","name":"SampleKafkaSchema","namespace":"com.linkedin.dataset","doc":"Sample Kafka dataset","fields":[{"name":"field_foo","type":["string"]},{"name":"field_bar","type":["boolean"]}]}'}, 'fields': [{'fieldPath': 'field_foo', 'jsonPath': None, 'nullable': False, 'description': 'Foo field description', 'type': {'type': {}}, 'nativeDataType': 'string', 'recursive': False}, {'fieldPath': 'field_bar', 'jsonPath': None, 'nullable': False, 'description': 'Bar field description', 'type': {'type': {}}, 'nativeDataType': 'boolean', 'recursive': False}], 'primaryKeys': None, 'foreignKeysSpecs': None}]}, 'proposedDelta': None}
	
avro_event: {'auditHeader': None, 'proposedSnapshot': {'urn': 'urn:li:dataset:(urn:li:dataPlatform:hdfs,SampleHdfsDataset,PROD)', 'aspects': [{'owners': [{'owner': 'urn:li:corpuser:jdoe', 'type': 'DATAOWNER', 'source': None}, {'owner': 'urn:li:corpuser:datahub', 'type': 'DATAOWNER', 'source': None}], 'lastModified': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}}, {'upstreams': [{'auditStamp': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}, 'dataset': 'urn:li:dataset:(urn:li:dataPlatform:kafka,SampleKafkaDataset,PROD)', 'type': 'TRANSFORMED'}]}, {'elements': [{'url': 'https://www.linkedin.com', 'description': 'Sample doc', 'createStamp': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}}]}, {'schemaName': 'SampleHdfsSchema', 'platform': 'urn:li:dataPlatform:hdfs', 'version': 0, 'created': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}, 'lastModified': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}, 'deleted': None, 'dataset': None, 'cluster': None, 'hash': '', 'platformSchema': {'documentSchema': '{"type":"record","name":"SampleHdfsSchema","namespace":"com.linkedin.dataset","doc":"Sample HDFS dataset","fields":[{"name":"field_foo","type":["string"]},{"name":"field_bar","type":["boolean"]}]}'}, 'fields': [{'fieldPath': 'field_foo', 'jsonPath': None, 'nullable': False, 'description': 'Foo field description', 'type': {'type': {}}, 'nativeDataType': 'string', 'recursive': False}, {'fieldPath': 'field_bar', 'jsonPath': None, 'nullable': False, 'description': 'Bar field description', 'type': {'type': {}}, 'nativeDataType': 'boolean', 'recursive': False}], 'primaryKeys': None, 'foreignKeysSpecs': None}]}, 'proposedDelta': None}
	
avro_event: {'auditHeader': None, 'proposedSnapshot': {'urn': 'urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD)', 'aspects': [{'owners': [{'owner': 'urn:li:corpuser:jdoe', 'type': 'DATAOWNER', 'source': None}, {'owner': 'urn:li:corpuser:datahub', 'type': 'DATAOWNER', 'source': None}], 'lastModified': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}}, {'upstreams': [{'auditStamp': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}, 'dataset': 'urn:li:dataset:(urn:li:dataPlatform:hdfs,SampleHdfsDataset,PROD)', 'type': 'TRANSFORMED'}]}, {'elements': [{'url': 'https://www.linkedin.com', 'description': 'Sample doc', 'createStamp': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}}]}, {'schemaName': 'SampleHiveSchema', 'platform': 'urn:li:dataPlatform:hive', 'version': 0, 'created': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}, 'lastModified': {'time': 1581407189000, 'actor': 'urn:li:corpuser:jdoe', 'impersonator': None}, 'deleted': None, 'dataset': None, 'cluster': None, 'hash': '', 'platformSchema': {'documentSchema': '{"type":"record","name":"SampleHiveSchema","namespace":"com.linkedin.dataset","doc":"Sample Hive dataset","fields":[{"name":"field_foo","type":["string"]},{"name":"field_bar","type":["boolean"]}]}'}, 'fields': [{'fieldPath': 'field_foo', 'jsonPath': None, 'nullable': False, 'description': 'Foo field description', 'type': {'type': {}}, 'nativeDataType': 'string', 'recursive': False}, {'fieldPath': 'field_bar', 'jsonPath': None, 'nullable': False, 'description': 'Bar field description', 'type': {'type': {}}, 'nativeDataType': 'boolean', 'recursive': False}], 'primaryKeys': None, 'foreignKeysSpecs': None}]}, 'proposedDelta': None}
	
avro_event: {'auditHeader': None, 'proposedSnapshot': {'urn': 'urn:li:dataProcess:(sqoop,DEMO,PROD)', 'aspects': [{'owners': [{'owner': 'urn:li:corpuser:datahub', 'type': 'DATAOWNER', 'source': None}], 'lastModified': {'time': 1581407189000, 'actor': 'urn:li:corpuser:datahub', 'impersonator': None}}, {'inputs': ['urn:li:dataset:(urn:li:dataPlatform:cassandra,barEarth,DEV)', 'urn:li:dataset:(urn:li:dataPlatform:cassandra,barMars,DEV)'], 'outputs': ['urn:li:dataset:(urn:li:dataPlatform:hbase,barSky,PROD)', 'urn:li:dataset:(urn:li:dataPlatform:hbase,barOcean,PROD)']}]}, 'proposedDelta': None}
```

Meanwhile, the consumer CLI has been verified on 
- `Red Hat Enterprise Linux Workstation release 7.6 (Maipo)` with `Python 3.6.8` 
- `macOS 10.15.5 (19F101) Darwin 19.5.0` with `Python 3.7.3`.

**Comment by priyanka1555** [comment]
Can you suggest me CLI for ubuntu 18.04

**Comment by jplaisted** [comment]
The CLI should be pretty cross platform, since it is in python. Chris isn't saying it only works on those platforms, just that it has been verified on those platforms.

I'd take a step back and verify your docker images are working correctly as Mars suggested.

**Comment by priyanka1555** [comment]
Hello,
My issue has been resolved , it was kafka broker issue.
Thanks
