### ISSUE TITLE
Make docker files more debuggable

### ISSUE THREAD

**Issue by jplaisted** [linkedin/datahub#1760]
My workflow is with an IDE. If I want to debug mce-consumer-job, I can't just launch it locally, it is missing env variables. Docker files have all of these. But they aren't set up for easy debugging. Also, even if I could launch it, launching all the other services via docker at the same time would be nice (especially services that are dependencies, e.g. kafka).

My current idea is to create a python script to make a fudged docker compose file which adds bind mounts when debugging to effectively symlink a locally built jar into a super minimal image. It can also add JVM debug flags. Then non-debug services aren't messed with and can be pulled from dockerhub if we want.

**Comment by jplaisted** [comment]
Also while we're here since if we can't consolidate these.

**Comment by jplaisted** [comment]
Also also logs aren't mounted anywhere and thus are lost when the service shuts down, which is especially annoying if it failed to start up!

**Comment by mars-lan** [comment]
Is it possible to enable debug via a environment variable? That way you can have the best of both worlds.

**Comment by liangjun-jiang** [comment]
@jplaisted I am using the following steps to run `mce-consumer-job` and `mae-consumer-job` locally. Basically, before, those environment variables are defaulted in `mce-consumer-job`'s `kafkaConfig.java` and other places. I guess now the refactoring made them gone away.
this is how it looks like before
```
@Value("${KAFKA_BOOTSTRAP_SERVER:localhost:9092}")
    private String kafkaBootstrapServer;
    @Value("${KAFKA_MCE_TOPIC_NAME:" + Topics.DEFAULT_METADATA_CHANGE_EVENT + "}") 
```

this is how it looks like now
```
public class KafkaConfig {
  @Value("${KAFKA_BOOTSTRAP_SERVER}")
  private String kafkaBootstrapServers;
  @Value("${KAFKA_SCHEMAREGISTRY_URL:http://localhost:8081}")
  private String kafkaSchemaRegistryUrl;

```

Also when you build & run `mce-consumer-job` module, the spring boot's default port: 8080 is conflicted with `gms`'s. 
So what I do is using the following, you can do other ways I assume. 
```
SpringApplication app = new SpringApplication(MceConsumerApplication.class);
        app.setDefaultProperties(Collections.singletonMap("server.port", "9090"));
        app.run(args);
```
to replace the current one:

```
SpringApplication.run(MceConsumerApplication.class, args);
```

**Comment by liangjun-jiang** [comment]
also you need to modify `logback.xml` of `mce-consumer-job`
```
<property name="LOG_DIR" value="${LOG_DIR:- /local/logs}"/>
```
change the `/local/logs` to your local location.

**Comment by jplaisted** [comment]
Thanks for the input @liangjun-jiang . Yeah, there seems to be a general issue here with the offspring defaults being out of sync from the dockerfile overrides. In theory these should be the same?

Environment variables aside, there's another issue here of easily launching all dependencies (and to test e2e, downstream services). I don't want to have to dig through dockerfiles and see what services I need to launch :) i.e. I need kafka and zookeeper and the gms up to start mce-consumer-job. And DataHub FE if I want to verify e2e. Hence my idea of basically having a giant docker-compose file, then a python script to make some small overrides for the services you want to debug. Testing it locally it is lightning fast.

I'll send out a PR so you can get a clearer idea of my proposal. We're also going to discuss this within the team Monday.

@marslan-li , not sure what you mean. The fake docker file I mentioned adds jvm debug flags via an environment variable.

**Comment by mars-lan** [comment]
@jplaisted ignore my comment. You're doing what I was suggesting already.

**Comment by liangjun-jiang** [comment]
@jplaisted I have seen some other projects which just used a giant docker-compose file. For example, Apache Griffin. 
Personally, I launch each container manually one-by-one so I can have independent terminal windows to observe logs.  
Willing to learn if there is a better approach.

**Comment by jplaisted** [comment]
Yeah, the launch every service individually seems like a pain.

I agree maybe the python script is overkill. I think we can get away with a giant docker compose file and some override docker compose files (e.g. one to use postgre or something).

I made a branch like that, and it works ok. However, there's an issue where configuring environments is still wonky. Imagine someone wants to use their AWS instance of ES; and they have difference instances for staging and prod. How do they configure docker stuff to do that? The way I did it was to have `docker/<service>/env/<env>.env` files, where the default is `dev` (specified via `ENV` variable) and we only ship `dev` (`dev` is setup to assume everything is running on a single machine with docker compose up). Then if you want to debug you can just edit the `dev.env` file to include jvm debugging flags, and the docker-compose.override.yml file to map the debug port.

https://github.com/jplaisted/datahub/tree/dockerRefactor

This just seems like a general area where Docker does not great provide support.


Also here's the branch that has the python script approach. https://github.com/jplaisted/datahub/tree/docker-compose

**Comment by jplaisted** [comment]
Also fwiw I did look at gradle docker plugins (Palantir, Avast, and bmuschko). None of them really have what I was looking for.

**Comment by liangjun-jiang** [comment]
To me, I don't expect that we can deploy datahub to a production environment out of box. Personally, it probably shouldn't have this goal. It is more like the goal for person who wants to commercialize this product.  
the `quickstart` has been very helpful for developers to get a favor of this project. The next goal is to how to help developers develop and debug easily. To me and as a backend engineer, it is how to run `gms`, `mae-consumer-job`, and `mce-consumer-job` locally. 
Just my opinion.

**Comment by jplaisted** [comment]
I've made an initial PR, I've tested it a bit but it is late so I'll do more tomorrow. But tl;dr you can now add three lines to some files and then run `docker/dev.sh` and you'll be running your local code with remote debugging enabled. Or you can just run `docker/dev.sh` to run with your local code, not remote debugging, which is still useful.

**Comment by mars-lan** [comment]
> I've made an initial PR, I've tested it a bit but it is late so I'll do more tomorrow. But tl;dr you can now add three lines to some files and then run `docker/dev.sh` and you'll be running your local code with remote debugging enabled. Or you can just run `docker/dev.sh` to run with your local code, not remote debugging, which is still useful.

Can we make debug enabled as default for dev instead of manually tweaking the files?

**Comment by jplaisted** [comment]
My only concern with that is auto assigning ports may confuse users (and also may not work if those ports are already in use). Like it may not be clear `datahub-gms` is port 5005, ubt `datahub-mce-consumer` is port 5006, etc. Plus you'd still need to edit the file to flip the suspend bit, if you wanted.

Also also it requires yet another env file (one with the JVM debug flags). Right now we're thankfully only shipping [mostly] one per service.

**Comment by mars-lan** [comment]
I'm not concerned with the arbitrary port assignments as long as it's well documented. Can we somehow hard-code the JVM flags in the debug dockerfile instead of passing it via env var?

**Comment by jplaisted** [comment]
Closing this since I think it is in a better state now.

RE logs; turns out that in docker desktop you can easily view logs. I think we should just suggest that instead.
