### ISSUE TITLE
Publish Code Quality Metrics

### ISSUE THREAD

**Issue by shakti-garg-saxo** [linkedin/datahub#1762]
**Is your feature request related to a problem? Please describe.**
Non-availability of metrics on code-coverage and vulnerabilities (SCA)

**Describe the solution you'd like**
metrics on code-coverage and vulnerabilities (SCA) published with every build

**Describe alternatives you've considered**
1. publishing code-coverage metrics (one badge on README can be added)
2. some basic level of SCA in build process, in order to prevent critical vulnerabilities

**Comment by jplaisted** [comment]
After https://github.com/linkedin/datahub/pull/1769, it seems like we can upload to CodeCov with this action. https://github.com/marketplace/actions/codecov.

However, it doesn't look like we're generating code coverage at all right now. So first step is to figure that out :p

**Comment by jjoyce0510** [comment]
Any progress on this one @jplaisted ? Has the thinking evolved?

**Comment by jplaisted** [comment]
No, this is something I never really had time to look into. At this point I'll unassign.

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
