### ISSUE TITLE
How to support Chinese browser search

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1772]
As shown below, the current dataset has the `description` . But I could not find the result through browser searching.

After I installed and enabled Smart Chinese Analysis plugin in ES, the problem still exists. But I could see the related records when I search in kibana.  What's the problem?

![2020-07-28 10-23-32屏幕截图](https://user-images.githubusercontent.com/11460848/88611804-6bd87b80-d0bc-11ea-975d-41cce8ae1572.png)

![2020-07-28 10-27-40屏幕截图](https://user-images.githubusercontent.com/11460848/88612086-fc16c080-d0bc-11ea-9d2a-ce06475fb29f.png)

![2020-07-28 11-32-37屏幕截图](https://user-images.githubusercontent.com/11460848/88616327-80ba0c80-d0c6-11ea-9417-00130ca818f3.png)

**Comment by mars-lan** [comment]
Related to https://github.com/linkedin/datahub/issues/1736

**Comment by camelliazhang2018** [comment]
@cobolbaby The description info shown in UI does not necessarily store in search index, it can be decorated after search result is returned. The problem is caused by missing description field in the search index mapping & query template, that’s why you can not search for it. I will follow up with a PR for it. 

With all that said, the quickest solution is actually to use advanced query directly: “description:cpu” in your search bar. The reason behind is ElasticSearch is schema free :)  I assumed you have ingested some data with DatasetProperties aspect already, otherwise, please ingest a dataset with that aspect. Please let me know if it fixes the issue right away. If you still get  no result coming back, we will need to investigate Smart Chinese Analysis plugin.

**Comment by cobolbaby** [comment]
As I mentioned at the beginning, the `description` field information is already stored in ES.

When I enter `description:cpu` in the browser search box, the query results are as follows:

![2020-08-06 09-15-40屏幕截图](https://user-images.githubusercontent.com/11460848/89479467-7b934680-d7c5-11ea-8415-881be6c401f6.png)

![2020-08-06 09-15-26屏幕截图](https://user-images.githubusercontent.com/11460848/89479458-7635fc00-d7c5-11ea-927a-5a8acea7aa68.png)

Use the same query statement to check the query results of kibana:

![2020-08-06 09-23-40屏幕截图](https://user-images.githubusercontent.com/11460848/89480356-b5654c80-d7c7-11ea-9343-5cb111a22309.png)

@camelliazhang2018  Obviously the gms query is not much accurate. Some records were not found, and some irrelevant records were found. This should be a bug. Could you submit a PR to fix it?

**Comment by cobolbaby** [comment]
I think the core problem now is how the gms service can better support Chinese.

**Comment by camelliazhang** [comment]
Thanks for the quick reply, @cobolbaby  It looks like you have ES expert on your side as well :) 

1. The reason you see the number 4 result is because the query template we have by default will search name field as well. The number 4 dataset’s name has cpu in it. I won’t say it is a bug, instead, each user/company needs to have their own query template to fine tune the relevance. What you can do is modify the query template and remove the ngram for name field
2.  In order to support Chinese, you probably need to apply smartcn analyzer and smartcn_tokenizer tokenizer wherever needed. We probably won’t support this anytime soon, but I can help you research & debug along the way 
3. We did not use Kibana in house, so there is no comparison for the results. 

Before we dive in more, could you please share the info about your current settings:
1. What is the ES version you are using? 
2. Run this cmd and share your current index mapping info with us: 
`curl http://localhost:9200/datasetdocument/_mapping`
3. Share the current query template (If different with the default we provided)

**Comment by cobolbaby** [comment]
Before we dive in more, could you please share the info about your current settings:

1. What is the ES version you are using?

ES: 6.8.11

> In order to verify the version of ES, I upgraded to version 6.8.11.  When I confirmed that this version can work normally (although the console will output some warnings), I did not downgrade again.

2. Run this cmd and share your current index mapping info with us:
`curl http://localhost:9200/datasetdocument/_mapping`

```
dev@ITC-180012U:~$ curl -sS http://localhost:9200/datasetdocument/_mapping | jq .
{
  "datasetdocument": {
    "mappings": {
      "doc": {
        "_all": {
          "enabled": true
        },
        "properties": {
          "browsePaths": {
            "type": "text",
            "fields": {
              "length": {
                "type": "token_count",
                "analyzer": "slash_pattern"
              }
            },
            "analyzer": "custom_browse_slash",
            "fielddata": true
          },
          "deprecated": {
            "type": "boolean"
          },
          "description": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "hasOwners": {
            "type": "boolean"
          },
          "hasSchema": {
            "type": "boolean"
          },
          "name": {
            "type": "keyword",
            "fields": {
              "dataset_pattern_ngram": {
                "type": "text",
                "analyzer": "dataset_pattern_ngram"
              },
              "delimited": {
                "type": "text",
                "analyzer": "delimit"
              },
              "ngram": {
                "type": "text",
                "analyzer": "custom_ngram"
              },
              "pattern": {
                "type": "text",
                "analyzer": "dataset_pattern"
              }
            },
            "normalizer": "my_normalizer"
          },
          "num_downstream_datasets": {
            "type": "long"
          },
          "origin": {
            "type": "keyword",
            "fields": {
              "ngram": {
                "type": "text",
                "analyzer": "custom_ngram"
              }
            },
            "normalizer": "my_normalizer"
          },
          "owners": {
            "type": "text",
            "fields": {
              "ngram": {
                "type": "text",
                "analyzer": "comma_pattern_ngram"
              }
            },
            "analyzer": "comma_pattern"
          },
          "platform": {
            "type": "keyword",
            "fields": {
              "ngram": {
                "type": "text",
                "analyzer": "custom_ngram"
              }
            },
            "normalizer": "my_normalizer"
          },
          "removed": {
            "type": "boolean"
          },
          "upstreams": {
            "type": "keyword",
            "normalizer": "my_normalizer"
          },
          "urn": {
            "type": "keyword",
            "normalizer": "my_normalizer"
          }
        }
      }
    }
  }
}
```

3. Share the current query template (If different with the default we provided)

We are currently using the default [configuration](https://github.com/linkedin/datahub/blob/master/docker/elasticsearch/dataset-index-config.json), because it is not clear how to change it.

**Comment by cobolbaby** [comment]
Question:

1. How to modify the query template ? Please show a case if possible.
2. I have installed the smartcn plugin. How to apply smartcn analyzer and smartcn_tokenizer tokenizer next?
3. Kibana is used here only to compare the query results. In this scenario, we should hope to get rid of the dependence on kibana.

**Comment by camelliazhang** [comment]
@cobolbaby Thanks for the info in details. 
1. You can modify the query template located at: https://github.com/linkedin/datahub/blob/master/gms/impl/src/main/resources/datasetESSearchQueryTemplate.json
What you want to do is to delete the "query_string" that uses ngram for name field. You can try the following template first (it will need to be refined later but let's develop this step by step)
`{
  "function_score": {
    "query": {
      "bool": {
        "should": [
          {
            "query_string": {
              "query": "$INPUT",
              "analyzer": "custom_keyword",
              "boost": 1000000,
              "default_field": "name",
              "default_operator": "AND"
            }
          }
        ]
      }
    },
    "functions": [
      {
        "filter": {
          "term": {
            "hasOwners": true
          }
        },
        "weight": 2
      },
      {
        "filter": {
          "term": {
            "deprecated": true
          }
        },
        "weight": 0.5
      },
      {
        "filter": {
          "match": {
            "origin": "EI"
          }
        },
        "weight": 0.01
      },
      {
        "filter": {
          "term": {
            "num_downstream_datasets": 0
          }
        },
        "weight": 0.5
      },
      {
        "filter": {
          "term": {
            "removed": true
          }
        },
        "weight": 0.0001
      }
    ],
    "score_mode": "multiply"
  }
}`
2. You can apply this analyzer to all the fields that have Chinese words in it. Check this article for example: https://stackoverflow.com/questions/26087072/how-to-use-smart-chinese-analysis-for-elasticsearch
You may want to change your index mapping for the description field to the following: 
`          
"description": {
            "type": "text",
            "analyzer": "smartcn"
          }
`
3. Sounds good, Kibana is not actively used by us either. 

Let me know how it works.

**Comment by cobolbaby** [comment]
I have modified the query template as you said. It's puzzled that I can see the search auto-completion results，But I could not find the result in the page.  

![2020-08-07 09-42-27屏幕截图](https://user-images.githubusercontent.com/11460848/89599510-57516b80-d892-11ea-983a-90b3865a3634.png)


![2020-08-07 09-18-45屏幕截图](https://user-images.githubusercontent.com/11460848/89598438-6682ea00-d88f-11ea-9c46-1de8e3583a04.png)

**Comment by camelliazhang** [comment]
@cobolbaby Can you try "description:cpu*" and let me know the result?  Note there is a '*' there.

**Comment by cobolbaby** [comment]
![2020-08-07 10-59-09屏幕截图](https://user-images.githubusercontent.com/11460848/89604078-190d7980-d89d-11ea-96ae-57163e09b5dd.png)

**Comment by cobolbaby** [comment]
![2020-08-07 10-59-09屏幕截图](https://user-images.githubusercontent.com/11460848/89604340-a51fa100-d89d-11ea-884e-85fc3de8f154.png)

**Comment by camelliazhang** [comment]
@cobolbaby Looks like you are looking for precise matching? And you do not want to see the 2nd item returned in the search result, is that correct?
Could you please try this command and see if the results are what you are looking for? `curl http://localhost:9200/datasetdocument/_search? -d '{"query":{"query_string":{"query":"description:cpu*"}}}'`

**Comment by cobolbaby** [comment]
Yes,  the 2nd item returned in the search result is incorrect.

```
dev@docker-build-1:/opt/datahub/docker/quickstart$ curl -sS http://10.190.81.17:9200/datasetdocument/_search? -d '{"query":{"query_string":{"query":"description:cpu*"}}}' | jq .
{
  "error": "Content-Type header [application/x-www-form-urlencoded] is not supported",
  "status": 406
}
dev@docker-build-1:/opt/datahub/docker/quickstart$ curl -sS http://10.190.81.17:9200/datasetdocument/_search? -d '{"query":{"query_string":{"query":"description:cpu*"}}}' -H 'Content-Type: Application/JSON' | jq .
{
  "took": 15,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 3,
    "max_score": 1,
    "hits": [
      {
        "_index": "datasetdocument",
        "_type": "doc",
        "_id": "urn%3Ali%3Adataset%3A%28urn%3Ali%3Adataplatform%3Abdc%2Cdw.dim_cpu_parts%2Cdev%29",
        "_score": 1,
        "_source": {
          "urn": "urn:li:dataset:(urn:li:dataPlatform:bdc,dw.dim_cpu_parts,DEV)",
          "browsePaths": [
            "/dev/bdc/dw/dim_cpu_parts"
          ],
          "origin": "DEV",
          "name": "dw.dim_cpu_parts",
          "hasSchema": true,
          "platform": "bdc",
          "hasOwners": true,
          "owners": [
            "ITC060009",
            "ITC190008"
          ],
          "upstreams": [
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.mds_parts,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.mds_parts_descr,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,batwo.imdm,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.cto_parts,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.cto_parts_descr,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,batwo.imdm,DEV)"
          ],
          "description": "CPU段维度表-Parts"
        }
      },
      {
        "_index": "datasetdocument",
        "_type": "doc",
        "_id": "urn%3Ali%3Adataset%3A%28urn%3Ali%3Adataplatform%3Abdc%2Cdw.fact_cpu_rep%2Cdev%29",
        "_score": 1,
        "_source": {
          "urn": "urn:li:dataset:(urn:li:dataPlatform:bdc,dw.fact_cpu_rep,DEV)",
          "browsePaths": [
            "/dev/bdc/dw/fact_cpu_rep"
          ],
          "origin": "DEV",
          "name": "dw.fact_cpu_rep",
          "hasSchema": true,
          "platform": "bdc",
          "hasOwners": true,
          "owners": [
            "ITC060009",
            "ITC190008"
          ],
          "upstreams": [
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.mds_rep,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.mds_rep_cause,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.mds_station,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.fis2_account,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.fis2_cause,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.fis2_defect,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.cto_rep,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.cto_rep_cause,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.cto_station,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.fis2_account,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.fis2_cause,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.fis2_defect,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.fis2_repair_action,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.fis2_repair_action,DEV)"
          ],
          "description": "CPU段维修信息"
        }
      },
      {
        "_index": "datasetdocument",
        "_type": "doc",
        "_id": "urn%3Ali%3Adataset%3A%28urn%3Ali%3Adataplatform%3Abdc%2Cdw.fact_cpu_sn%2Cdev%29",
        "_score": 1,
        "_source": {
          "urn": "urn:li:dataset:(urn:li:dataPlatform:bdc,dw.fact_cpu_sn,DEV)",
          "browsePaths": [
            "/dev/bdc/dw/fact_cpu_sn"
          ],
          "origin": "DEV",
          "name": "dw.fact_cpu_sn",
          "hasSchema": true,
          "platform": "bdc",
          "hasOwners": true,
          "owners": [
            "ITC060009",
            "ITC190008"
          ],
          "upstreams": [
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.mds_sno,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.mds_unit_log,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.mds_sfc,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.mds_dn,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.mds_parts,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.cto_sno,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.cto_unit_log,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.cto_sfc,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.cto_dn,DEV)",
            "urn:li:dataset:(urn:li:dataPlatform:bdc,fis.cto_parts,DEV)"
          ],
          "description": "CPU段机台基础信息"
        }
      }
    ]
  }
}

```

**Comment by camelliazhang** [comment]
@cobolbaby From the result shown above,  I do think they are the right results, all of three datasets has a description which starts with `cpu`.  IMO, ElasticSearch does return the correct results. The final results displayed on UI is missing the display of description info for the 2nd dataset, that needs to be debugged further (might be a bug in mid-tier or frontend)

**Comment by cobolbaby** [comment]
Indeed, the description information of the second record is not displayed. This bug can be resolved later. Now I can start to adjust the mapping configuration of the index to verify the effect of Chinese word segmentation.

Let me confirm another question, whether I can also customize the query template to support automatic matching of the information in the name and description without specifying the scope of retrieval.

**Comment by camelliazhang** [comment]
@cobolbaby Sounds a good plan. Are you looking for multi field match query? Please refer to the following documentation and create a query that suits your need: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-multi-match-query.html Let me know if you have any further questions.

**Comment by cobolbaby** [comment]
> @cobolbaby From the result shown above, I do think they are the right results, all of three datasets has a description which starts with `cpu`. IMO, ElasticSearch does return the correct results. The final results displayed on UI is missing the display of description info for the 2nd dataset, that needs to be debugged further (might be a bug in mid-tier or frontend)

It should be a bug in mid-tier. 

![2020-08-10 11-01-06屏幕截图](https://user-images.githubusercontent.com/11460848/89749114-0b543000-daf9-11ea-97db-fa87fc26e08f.png)

**Comment by cobolbaby** [comment]
After enabling Smart Chinese Analysis plugin, the datahub already supports Chinese search.

Now the remaining question is that the interface `/api/v2/search` does not response the description information of fact_cpu_rep.

**Comment by mars-lan** [comment]
> After enabling Smart Chinese Analysis plugin, the datahub already supports Chinese search.
> 
> Now the remaining question is that the interface `/api/v2/search` does not response the description information of the 2nd dataset.

I assume the description issue should be fixed by https://github.com/linkedin/datahub/pull/1791. @camelliazhang can confirm.

**Comment by cobolbaby** [comment]
It seems this is a new problem

**Comment by camelliazhang** [comment]
@cobolbaby Could you please run this command and let me know the result? 
`curl 'http://localhost:8080/datasets?q=search&input=description:cpu*'  -H 'X-RestLi-Protocol-Version:2.0.0'`

**Comment by cobolbaby** [comment]
> @cobolbaby Could you please run this command and let me know the result?
> `curl 'http://localhost:8080/datasets?q=search&input=description:cpu*' -H 'X-RestLi-Protocol-Version:2.0.0'`

```
{
  "exceptionClass": "com.linkedin.restli.server.RestLiServiceException",
  "stackTrace": "com.linkedin.restli.server.RestLiServiceException [HTTP Status:400]: Invalid query parameters syntax: /datasets?q=search&input=description:cpu*\n\tat com.linkedin.restli.server.RestLiServiceException.fromThrowable(RestLiServiceException.java:315)\n\tat com.linkedin.restli.server.BaseRestLiServer.buildPreRoutingError(BaseRestLiServer.java:158)\n\tat com.linkedin.restli.server.RestRestLiServer.buildPreRoutingRestException(RestRestLiServer.java:203)\n\tat com.linkedin.restli.server.RestRestLiServer.handleResourceRequest(RestRestLiServer.java:177)\n\tat com.linkedin.restli.server.RestRestLiServer.doHandleRequest(RestRestLiServer.java:164)\n\tat com.linkedin.restli.server.RestRestLiServer.handleRequest(RestRestLiServer.java:120)\n\tat com.linkedin.restli.server.RestLiServer.handleRequest(RestLiServer.java:132)\n\tat com.linkedin.restli.server.DelegatingTransportDispatcher.handleRestRequest(DelegatingTransportDispatcher.java:70)\n\tat com.linkedin.r2.filter.transport.DispatcherRequestFilter.onRestRequest(DispatcherRequestFilter.java:70)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:72)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.TimedNextFilter.onRequest(TimedNextFilter.java:55)\n\tat com.linkedin.r2.filter.transport.ServerQueryTunnelFilter.onRestRequest(ServerQueryTunnelFilter.java:58)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:72)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.TimedNextFilter.onRequest(TimedNextFilter.java:55)\n\tat com.linkedin.r2.filter.message.rest.RestFilter.onRestRequest(RestFilter.java:50)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:72)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.FilterChainImpl.onRestRequest(FilterChainImpl.java:96)\n\tat com.linkedin.r2.filter.transport.FilterChainDispatcher.handleRestRequest(FilterChainDispatcher.java:75)\n\tat com.linkedin.r2.util.finalizer.RequestFinalizerDispatcher.handleRestRequest(RequestFinalizerDispatcher.java:61)\n\tat com.linkedin.r2.transport.http.server.HttpDispatcher.handleRequest(HttpDispatcher.java:101)\n\tat com.linkedin.r2.transport.http.server.AbstractR2Servlet.service(AbstractR2Servlet.java:105)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat com.linkedin.restli.server.spring.ParallelRestliHttpRequestHandler.handleRequest(ParallelRestliHttpRequestHandler.java:61)\n\tat org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:73)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:494)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)\n\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.linkedin.restli.server.RoutingException: Invalid query parameters syntax: /datasets?q=search&input=description:cpu*\n\tat com.linkedin.restli.server.BaseRestLiServer.getRoutingResult(BaseRestLiServer.java:146)\n\tat com.linkedin.restli.server.RestRestLiServer.handleResourceRequest(RestRestLiServer.java:173)\n\t... 62 more\n",
  "message": "Invalid query parameters syntax: /datasets?q=search&input=description:cpu*",
  "status": 400
}
```

**Comment by cobolbaby** [comment]
@camelliazhang , Question:

- What are the main limitations of the HTTP request header `X-RestLi-Protocol-Version:2.0.0`
- What is the difference between  `/datasets?q=search&input=description:cpu*` and `/api/v2/search?input=description%3A+cpu&type=dataset`.

**Comment by cobolbaby** [comment]
I found the reason why the description of that record was not displayed is that the table `fact_cpu_rep` had comment information at the beginning, and then someone delete the comment. But it seems that the comment of this table is not updated to ES synchronously.

**Comment by camelliazhang** [comment]
> @camelliazhang , Question:
> 
> * What are the main limitations of the HTTP request header `X-RestLi-Protocol-Version:2.0.0`
> * What is the difference between  `/datasets?q=search&input=description:cpu*` and `/api/v2/search?input=description%3A+cpu&type=dataset`.

Not sure if I understand your first question, for the second, the first call is rest call to gms backend, the second is the call involves mid-tier.

**Comment by camelliazhang** [comment]
How many datasets do you have in total? Did you check if metadata_aspect table has the latest info? If the information is inconsistent, I doubt if the ES index is messed up after you changed the index mapping, you need to clean ES data & create a new index (using the way I mentioned in https://github.com/linkedin/datahub/issues/1792)

**Comment by cobolbaby** [comment]
> Not sure if I understand your first question

When I add the http header `X-RestLi-Protocol-Version:2.0.0`, the response is abnormal, otherwise, it works well. So I wonder what the request header has a impact on.

> Did you check if metadata_aspect table has the latest info?

Indeed, the data is inconsistent. And I have recreated the ES index. Thx.

> How many datasets do you have in total?

There are about 300 datasets in the dev environment.

![2020-08-11 14-35-02屏幕截图](https://user-images.githubusercontent.com/11460848/89865175-d1aa2480-dbdf-11ea-89aa-8071f212c675.png)

**Comment by cobolbaby** [comment]
I found the reason why the description of that record was not displayed is that the table fact_cpu_rep had comment information at the beginning, and then someone delete the comment.

I have reproduced it. I'm sure that the comment in ES is not deleted synchronously.

**Comment by camelliazhang** [comment]
@cobolbaby  Would you mind sharing the details on how to reproduce the issue? Thanks. 

Since the Chinese search is supported successfully and this thread is getting too long, may I suggest closing this ticket and create a new one for data inconsistency (between DB & ES)?

**Comment by cobolbaby** [comment]
Thx for all your support.
