### ISSUE TITLE
Does gms need to manually update the dependent database

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1773]
The pull request #1756 involves the addition of a [database table](https://github.com/linkedin/datahub/blob/master/metadata-dao-impl/ebean-dao/gma-create-all.sql). When upgrading from 0.4.1 to 0.4.2, do I need to consider this change?

**Comment by mars-lan** [comment]
I assume you're referring to the `metadata_index` table. This is meant for Strongly Consistent Secondary Index (SCSI) that is currently under development. We will make an announcement once the feature is complete and how to create & backfill this table. Meanwhile you can safely ignore it without causing any issue.
