### ISSUE TITLE
Support webhook notification mechanism to inform table structure changes and upstream and downstream changes

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1774]
Is it possible to implement push notifications when the table structure changes by listening to mae messages？

**Comment by cobolbaby** [comment]
Could support to push notifications when the table structure changes?

**Comment by mars-lan** [comment]
By "push notifications", do you mean push notifications in mobile apps or [Web Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API)?

**Comment by cobolbaby** [comment]
If the webhook mechanism is implemented, it is more convenient than processing mae messages

**Comment by mars-lan** [comment]
Got it. It should be fairly easy to implement a Kafka consumer that triggers specific webhooks. As we don't currently have plan to add support for this, will leave it as a feature request in the backlog.

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
