### ISSUE TITLE
Add TLS support for connecting to Elasticsearch

### ISSUE THREAD

**Issue by mars-lan** [linkedin/datahub#1779]
**Is your feature request related to a problem? Please describe.**
[`ESSearchDAO`](https://github.com/linkedin/datahub/blob/master/metadata-dao-impl/elasticsearch-dao/src/main/java/com/linkedin/metadata/dao/search/ESSearchDAO.java) doesn't support https currently. 

**Describe the solution you'd like**
Will most likely need to modify [`RestHighLevelClientFactory`](https://github.com/linkedin/datahub/blob/master/gms/factories/src/main/java/com/linkedin/common/factory/RestHighLevelClientFactory.java) with additional https-related parameters as outlined here: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_encrypted_communication.html

**Comment by mars-lan** [comment]
@shakti-garg-saxo confirmed that he won't work on this in the short term. Will assign it to @jplaisted for now.

**Comment by camelliazhang** [comment]
@mars-lan Internal ElasticsearchHighLevelRestClientFactory actually supports https already, see loadRestHttpsClient (li-restli-utils).

**Comment by mars-lan** [comment]
@camelliazhang yup I'm aware of that. So just need to open source that.
