### ISSUE TITLE
Special character in dataplatform name is not working

### ISSUE THREAD

**Issue by Manjeri-Rajan** [linkedin/datahub#1783]
I am trying to ingest data into datahub with a special character in the dataset urn like urn:li:dataPlatform:abc/xyz . The schema platform is also given with the same name. The dataset is created after ingestion but when I go inside the dataset, I am getting the attached error in the UI.

I checked mysql and elasticsearch and entries are made in both of them.
I am using docker and there was no error returned in the docker logs from datahub-frontend.
Please find the entry in elasticsearch below.
![Screenshot from 2020-07-06 10-25-54](https://user-images.githubusercontent.com/20423084/89541089-e6478080-d7cb-11ea-962b-b2503c84eb17.png)

_{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":1,"max_score":3.3414474,"hits":[{"_index":"datasetdocument","_type":"doc","_id":"urn%3Ali%3Adataset%3A%28urn%3Ali%3Adataplatform%3Atestproject%2Ftestdataset%2Ctesttable1%2Cprod%29","_score":3.3414474,"_source":{"urn":"urn:li:dataset:(urn:li:dataPlatform:TestProject/TestDataset,TestTable1,PROD)","browsePaths":["/prod/testproject/testdataset/testtable1"],"hasOwners":true,"origin":"PROD","name":"TestTable1","owners":["manjeripadmakumari"],"platform":"TestProject/TestDataset","hasSchema":true}}]}}_

**Comment by mars-lan** [comment]
Thanks for reporting. I'm not exactly sure what you meant by "special character" in this case. Could you share the MCE you sent to ingest the data?

**Comment by Manjeri-Rajan** [comment]
I meant special characters like "/" or "." in the urn name. Please find the MCE ingested below.

{"auditHeader": None, "proposedSnapshot": ("com.linkedin.pegasus2avro.metadata.snapshot.DatasetSnapshot", {"urn": "urn:li:dataset:(urn:li:dataPlatform:TestProject/TestDataset,TestTable1,PROD)", "aspects": [("com.linkedin.pegasus2avro.common.Ownership", {"owners":[{"owner":"urn:li:corpuser:manjeripadmakumari","type":"DATAOWNER"}],"lastModified":{"time":1581407189000,"actor":"urn:li:corpuser:manjeripadmakumari"}}),("com.linkedin.pegasus2avro.common.InstitutionalMemory", {"elements":[{"url":"https://www.linkedin.com","description":"Sample doc","createStamp":{"time":1581407189000,"actor":"urn:li:corpuser:manjeripadmakumari"}}]}), ("com.linkedin.pegasus2avro.schema.SchemaMetadata", {"schemaName":"SampleTestSchema1","platform":"urn:li:dataPlatform:TestProject/TestDataset","version":0,"created":{"time":1581407189000,"actor":"urn:li:corpuser:manjeripadmakumari"},"lastModified":{"time":1581407189000,"actor":"urn:li:corpuser:manjeripadmakumari"},"hash":"","platformSchema":{"documentSchema":"{\"type\":\"record\",\"name\":\"SampleKafkaSchema\",\"namespace\":\"com.linkedin.dataset\",\"doc\":\"Sample Kafka dataset\",\"fields\":[{\"name\":\"field_foo\",\"type\":[\"string\"]},{\"name\":\"field_bar\",\"type\":[\"boolean\"]}]}"},"fields":[{"fieldPath":"field_foo","description":"Foo field description","nativeDataType":"string","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"field_bar","description":"Bar field description","nativeDataType":"boolean","type":{"type":{"com.linkedin.pegasus2avro.schema.BooleanType":{}}}}]})]}), "proposedDelta": None}

**Comment by mars-lan** [comment]
Got it. You're not supposed to have "/" in the data platform portion of the URN. You're allowed to have "/" in the data name, e.g. `urn:li:dataset:(urn:li:dataPlatform:TestProject,/TestDataset/TestTable1,PROD)`

**Comment by Manjeri-Rajan** [comment]
Okay, So what should be given as the data platform name here? I was assuming it should be the same as in the data name.

**Comment by mars-lan** [comment]
Data platform name is things like `mysql`, `hdfs`, `hive` etc.

**Comment by Manjeri-Rajan** [comment]
Sorry, I was actually looking to have special character in the data platform name. Edited the issue description now.
Why is it not possible to have special character in data platform name?

**Comment by mars-lan** [comment]
Can you provide a concrete example of a platform name with special characters in it?

**Comment by Manjeri-Rajan** [comment]
Our data source is Bigquery. We have various projects in bigquery, multiple datasets under each projects and various tables under each dataset. So our requirement is to have the data platform as project name and dataset name separated by special character and dataset as table name.

**Comment by mars-lan** [comment]
Got it, in that case the URN should look like `urn:li:dataset:(urn:li:dataPlatform:bigquery,<project_name>.<dataset_name>.<table name>,PROD)`. Data platform is reserved for a particular storage system, not for namespacing within the system.

**Comment by Manjeri-Rajan** [comment]
That worked! Thanks Mars for the help. I will close the ticket.
