### ISSUE TITLE
Support the fuzzy matching for people search

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1785]
When searching for `people` through the browser, fuzzy matching is not supported, only precise matching is supported.

![2020-08-07 09-49-12屏幕截图](https://user-images.githubusercontent.com/11460848/89600000-8a482f00-d893-11ea-8488-c598d2655cad.png)

![2020-08-07 09-51-47屏幕截图](https://user-images.githubusercontent.com/11460848/89600033-9fbd5900-d893-11ea-9d11-22f50ac9a320.png)

**Comment by cobolbaby** [comment]
same as dataset search by owners

![2020-08-11 13-13-46屏幕截图](https://user-images.githubusercontent.com/11460848/89859861-90f8de00-dbd4-11ea-8e9b-9cdd8a41faed.png)

**Comment by camelliazhang** [comment]
@vidvarma we may want to introduce ngram support in the query template for corp user entity. 

@cobolbaby Please try "ldap.ngram:wang" in your search bar and see if the result is what you are looking for?

**Comment by cobolbaby** [comment]
@camelliazhang 

![2020-08-11 14-43-44屏幕截图](https://user-images.githubusercontent.com/11460848/89865836-079bd880-dbe1-11ea-8ab8-53924d0eaa89.png)

**Comment by camelliazhang** [comment]
@cobolbaby Did you populate the ldap field for corp user entities?

**Comment by cobolbaby** [comment]
Sorry, I didn't . I just populate the dataset owner information.

My Corp user entities is:

```
dev@docker-build-1:/opt/datahub/docker$ curl -sS 'http://10.191.7.21:8090/corpUsers' | jq .
{
    {
      "username": "ITC060009",
      "info": {
        "active": true,
        "fullName": "Wang.Lan-Xiang",
        "title": "DEVELOPER",
        "displayName": "Wang.Lan-Xiang",
        "email": "****"
      }
    },
    {
      "username": "ITC180016",
      "info": {
        "active": true,
        "fullName": "Guo.Shou-Jun",
        "title": "MANAGER",
        "displayName": "Guo.Shou-Jun",
        "email": "****"
      }
    },
    {
      "username": "ITC190008",
      "info": {
        "active": true,
        "fullName": "Hao.Yun",
        "title": "DEVELOPER",
        "displayName": "Hao.Yun",
        "email": "****"
      }
    }
  ],
  "paging": {
    "count": 10,
    "start": 0,
    "links": []
  }
}
```

How can I do search.

**Comment by camelliazhang** [comment]
I see. Did you try "fullName:*wang*"  or  "fullName:wang*" ?

**Comment by cobolbaby** [comment]
Yes, I could query results by "fullName:wang*".

![2020-08-12 16-09-38屏幕截图](https://user-images.githubusercontent.com/11460848/89991359-536c8180-dcb6-11ea-9af0-6c47d4c900b0.png)

**Comment by camelliazhang** [comment]
@cobolbaby Great, advanced query seems working fine. If you do want to improve the user experience, you can: 
1. Simply put default field as fullName, and in search bar, all you need is to input `wang*` This way you do not need to type in filed name `fullName` anymore, but still need to put `*`
2. Or learn ngram and other customized/advanced analyzers, similar to dataset query template. 

BTW, In Elasticsearch context, fuzzy search actually means a different thing, check out here: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html

**Comment by jjoyce0510** [comment]
Interesting. This is something that is not possible in the React UI either. Example: https://demo.datahubproject.io/search/user?page=1&query=harsha vs 
https://demo.datahubproject.io/search/user?page=1&query=harshal 

@dexter-mh-lee Thoughts on supporting this for user names?

**Comment by shirshanka** [comment]
We have fixed this now through support for no-code annotations and partial matches on user's full names. 
Please reopen if you still face this issue!
