### ISSUE TITLE
Does datahub provide a rest interface for data ingestion

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1793]
Before I used the python script under metadata-ingestion to import data.

But I found an HTTP interface in #1791 accidentally. Is this method recommended? Is there any related documentation?

```
curl 'http://localhost:8080/datasets?action=ingest' -X POST -H 'X-RestLi-Protocol-Version:2.0.0' --data '{"snapshot":{"aspects":[{"com.linkedin.dataset.DatasetProperties":{"description":"descriptionForTest2","tags":["tag1","tag2"],"customProperties":{}}}],"urn":"urn:li:dataset:(urn:li:dataPlatform:hdfs,test2,EI)"}}'
```

**Comment by mars-lan** [comment]
This is mostly a "backdoor API" used by the MCE ingestion pipeline. You can certainly use it for debugging purposes and it's mentioned here: https://github.com/linkedin/datahub/tree/master/gms

If you're after a proper CREATE API, you'll need to add one to the GMS like so: https://github.com/linkedin/datahub/blob/master/gms/impl/src/main/java/com/linkedin/metadata/resources/identity/CorpUsersEditableInfoResource.java#L25

**Comment by cobolbaby** [comment]
Got it
