### ISSUE TITLE
SQL metadata ingestion from MS SQL Database is not working

### ISSUE THREAD

**Issue by bintosebastian** [linkedin/datahub#1797]
**Describe the bug**
SQL Metadata ingestion for MS SQL is not working. We've tried using mysql_etl.py script and mssql connection string using the below code:
from common import run

URL = 'mssql+pyodbc://username:password@hostname:port/foodapp?driver=ODBC+Driver+17+for+SQL+Server&autocommit=true' 
OPTIONS = {} # e.g. {"encoding": "latin1"}
PLATFORM = 'mssql'

run(URL, OPTIONS, PLATFORM)

Is there any other ways to get metadata from MSSQL Database?

**Comment by cobolbaby** [comment]
Could you please describe the relevant exception. The question is indeed very attractive.

**Comment by mars-lan** [comment]
While we don't have an example of MS SQL crawler, it should be reasonably easy to extend sql-etl to support that. See https://github.com/linkedin/datahub/tree/master/metadata-ingestion/sql-etl for more details.

**Comment by bintosebastian** [comment]
I've used the script in [https://github.com/linkedin/datahub/tree/master/metadata-ingestion/sql-etl](https://github.com/linkedin/datahub/tree/master/metadata-ingestion/sql-etl) 
by changing the connection string but it does not work. Is there any other changes I have to make for it to work for MS SQL?

**Comment by mars-lan** [comment]
Turns on that there is a MS SQL docker image that we can use to test so I added an example here: https://github.com/linkedin/datahub/pull/1803
