### ISSUE TITLE
How to speed up the image building

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1802]
It currently takes half an hour to execute a container build of the gms service.

**Comment by mars-lan** [comment]
@jplaisted has recently added development Docker images (https://github.com/linkedin/datahub/pull/1777) so you don't need to rebuild them every time. You can read more about it here: https://github.com/linkedin/datahub/blob/master/docs/docker/development.md

**Comment by cobolbaby** [comment]
Got it. It's awesome.
