### ISSUE TITLE
Docker development flow for frontend

### ISSUE THREAD

**Issue by jplaisted** [linkedin/datahub#1807]
My recent changes to our docker images (https://github.com/linkedin/datahub/issues/1760) didn't include changes for frontend. We should add a similar lightweight, easy dev/refresh image for frontend.

@cptran777 Is this something you'd be willing to help me out with? :)

**Comment by jjoyce0510** [comment]
Has this been addressed?

**Comment by jjoyce0510** [comment]
Also, what is the scope of work here?

**Comment by jplaisted** [comment]
This has not been addressed. The scope would be making it easier to use the frontend during development with docker; e.g. edit-refresh while using docker. This makes it easy to spin up the entire stack while developing.

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
