### ISSUE TITLE
Are the helm charts reflecting latest Datahub release?

### ISSUE THREAD

**Issue by themightylaz** [linkedin/datahub#1813]
Hi,

I saw that there was a release 20 days ago and I am wondering if the Helm charts are synced with new releases?

Best regards
//Lars

**Comment by mars-lan** [comment]
Helm charts are currently maintain by the community under `/contrib`. We have plan to mainline that in the near future and have a proper release process for it.

**Comment by themightylaz** [comment]
That's great to hear.
Is it ok to interpret near future to be like in a month or so? :-)

**Comment by mars-lan** [comment]
The current ETA is Oct as per our roadmap: https://github.com/linkedin/datahub/blob/master/docs/roadmap.md

**Comment by themightylaz** [comment]
ok, thanks!

**Comment by jjoyce0510** [comment]
We've recently [mainlined the Helm Charts](https://github.com/linkedin/datahub/commit/ae4def2f256aac1c652ece4ae17c733fe76c2947) thanks to @dexter-mh-lee. 

I think that the Helm charts should now reflect the latest state of DataHub. @dexter-mh-lee to confirm.

If so, we can close the ticket!

**Comment by jjoyce0510** [comment]
@shirshanka Can we close this one? Thanks!

**Comment by shirshanka** [comment]
@themightylaz : it took us a while but we're finally there :)  Closing this ticket.

**Comment by shirshanka** [comment]
Fixing docs link: They are here -> https://datahubproject.io/docs/deploy/kubernetes
