### ISSUE TITLE
Why is there no out-of-the-box support for CorpGroups?

### ISSUE THREAD

**Issue by jsotelo** [linkedin/datahub#1822]
There are many mentions of `CorpGroup` in the [documentation](https://github.com/linkedin/datahub/search?l=Markdown&q=Group), however `CorpGroupSnapshot` is currently not included in the [Snapshot PDL ](https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/metadata/snapshot/Snapshot.pdl#L6). It seems to me that the idea of a `CorpGroup` is pretty ubiquitous. Is there a specific reason it's not part of the "standard" supported data models?

**Comment by mars-lan** [comment]
Looks like a miss on our side. We even have the endpoint for it: https://github.com/linkedin/datahub/blob/master/gms/impl/src/main/java/com/linkedin/metadata/resources/identity/CorpGroups.java

Will create a PR to fix this with update to documentation if needed.
