### ISSUE TITLE
Does the frontend page no longer display the dataset description

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1823]
The latest version of the datahub-frontend no longer displays the description information of the dataset. Is this a bug or a change in the front-end display requirements?

![2020-08-27 14-44-34屏幕截图](https://user-images.githubusercontent.com/11460848/91403612-fc4cdc00-e873-11ea-9c16-1089c5b220ae.png)

![2020-08-27 14-48-41屏幕截图](https://user-images.githubusercontent.com/11460848/91404944-5cdc1900-e874-11ea-9155-20ea1cb566c2.png)

If possible, please consider restoring the display of this information. Thanks.

**Comment by cptran777** [comment]
Hey @cobolbaby , looks like we removed that description internally because it wasn't providing any value, however this shouldn't affect the open source folks from being able to use it. Will look into restoring this back.

**Comment by cobolbaby** [comment]
The latest code commit did not fix the problem.

**Comment by cptran777** [comment]
This may be fixed by the linked PR (or at least I suspect so). Could you please check and, if not fixed, let us know and provide an example search response you're working with to better debug?

**Comment by cobolbaby** [comment]
Confirmed.
