### ISSUE TITLE
Which page will the metadata-origins menu option jump to

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1826]
![2020-08-27 15-28-47屏幕截图](https://user-images.githubusercontent.com/11460848/91410775-01148e80-e87a-11ea-88e3-e096744bf4f8.png)

In the latest version, A new menu option has been added to the page, which is not yet available. I am curious what function entry is this?

**Comment by cptran777** [comment]
Hey, looks like it's supposed to be a Q&A page. Will have an option to remove this if no such Q&A exists

**Comment by jjoyce0510** [comment]
The new React application does not have this link. 

@shirshanka Let's close this ticket?
