### ISSUE TITLE
How to delete obsolete dataset

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1846]
We have imported a lot of datasets for testing, but now they are no longer needed, so if we want to clean up the spam, how do we do it?

**Comment by mars-lan** [comment]
Please see https://github.com/linkedin/datahub/blob/4060960a15930ac7ef4847cf00e939e1ccedec4f/docs/what/entity.md#how-to-delete-an-entity

tl;dr you can only soft-delete. To perform hard-delete, you'll need to remove stuff from the DB directly and rebuild your indexes.

**Comment by cobolbaby** [comment]
Could you describe how to apply it through a case.

**Comment by cobolbaby** [comment]
Great, I understand.
