### ISSUE TITLE
Dataset name is converted to lowercase

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1847]
Some field information of the original data is uppercase, such as platform, db name. After importing, the final result displayed by the front end is converted to lowercase. 

Could datahub keep the original value of the data without case conversion?

![2020-09-03 16-59-18屏幕截图](https://user-images.githubusercontent.com/11460848/92094270-d345c180-ee06-11ea-9571-f8acf104b93d.png)

**Comment by mars-lan** [comment]
Could you check the DB to see if they're stored as upper or lower cases? While DB itself is configured to be case insensitive, it should preserve the original case when MCEs are fired.

**Comment by cobolbaby** [comment]
![2020-09-03 22-41-03屏幕截图](https://user-images.githubusercontent.com/11460848/92129814-95f92800-ee36-11ea-973f-be2190a2afa4.png)

The data stored in the database is uppercase, and the data returned by the front-end interface has been converted to lowercase. It is not sure whether it is a problem processed by the gms service or the mid layer.

**Comment by mars-lan** [comment]
Found the culprit: https://github.com/linkedin/datahub/blob/master/metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DatasetIndexBuilder.java#L32

**Comment by cobolbaby** [comment]
First of all, it should be clear that the problem is caused by improper data import. When I encounter this problem, I will first think about correcting the back-end data, rather than making compatibility programmatically. Of course it would be better if the program can maintain compatibility.

Is there no solution to the problem now? I think data consistency should be guaranteed.

**Comment by mars-lan** [comment]
Agree. The cleanest way is to make sure that the dataset name is case sensitive throughout the system. This is a potentially breaking change so we'd like to consider the implication a little bit more before jumping in.

**Comment by mars-lan** [comment]
Assigning to @nagarjunakanamarlapudi to perform the investigation internally.

**Comment by cobolbaby** [comment]
Understood. Thank you for your efforts.

**Comment by jjoyce0510** [comment]
Was there any update on this one? 

cc. @gabe-lyons We should also consider this with React, as the same behavior seems to persist. Agree that Data Platform should appear case-correct in the browse experience and beyond.

**Comment by dingobar** [comment]
This is somewhat related to this https://github.com/linkedin/datahub/issues/3615 .

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
