### ISSUE TITLE
Support SSL to mce_cli.py

### ISSUE THREAD

**Issue by fabiofilz** [linkedin/datahub#1849]
We are executing the step on https://github.com/linkedin/datahub/tree/master/metadata-ingestion, but the mce_cli.py (and other python apps) don't support SSL connection to Kafka.

A suggestion would be to use the same as kafka-topic.sh does:

kafka-topics --command-config kafka.config

Ex. kafka.config
ssl.truststore.location=./resources/keys/pt/pt.d2.aws.truststore.jks
ssl.truststore.password=XXXXXXXXXXXXX
ssl.keystore.location=./resources/keys/pt/pt.d2.aws.keystore.jks
ssl.keystore.password=XXXXXXXXXXXXXX
ssl.key.password=XXXXXXXXXXXXX
security.protocol=SSL

So the command could be:

python3 metadata-ingestion/mce-cli/mce_cli.py produce -l metadata-events/mxe-schemas/src/renamed/avro/com/linkedin/mxe/MetadataChangeEvent.avsc -d metadata-ingestion/mce-cli/bootstrap_mce.dat -b bootstrap.d2-pt.aws.com:9092 -s https://schemaregistry.d2-pt.aws.com:8443 -c kafka.config

Thank you.
Fabio

**Comment by mars-lan** [comment]
Makes sense. Would you be interested in creating a PR for this, @fabiofilz?

**Comment by jplaisted** [comment]
fyi this is moving to contrib soon anyway. I'll be sure to keep this in mind for the Java port :)

**Comment by fabiofilz** [comment]
Hi @mars-lan,

Please find the PR with SSL feature.

Thank you.
Fabio
