### ISSUE TITLE
How to extend the data model on Neo4j

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1853]
Currently I want to extend a z-index field to the neo4j model, which is mainly used to identify the business level of the dataset in the data warehouse, and to draw a complete data map later. 

I wonder to know how to customize it.

**Comment by mars-lan** [comment]
Hopefully it's covered by https://github.com/linkedin/datahub/blob/master/docs/how/graph-onboarding.md. Let us know if there's any gap in the documentation.

**Comment by cobolbaby** [comment]
After reading the relevant docs, I found that I only need to extend datasetUrn to meet biz needs. 

What else needs to be done besides modifying [DatasetUrn.pdl](https://github.com/linkedin/datahub/blob/2bd44d4243/li-utils/src/main/pegasus/com/linkedin/common/DatasetUrn.pdl) ?

**Comment by mars-lan** [comment]
I'm actually curious what sort of extension are you talking about in regards to DatasetUrn? I'd imagine adding a "z-index" field to existing/new dataset aspect seems more appropriate to me?

**Comment by cobolbaby** [comment]
My idea is to extend the properties of the existing DatasetUrn, and then set the properties in the implementation of DatasetGraphBuilder. Is there a problem with my understanding? Of course I can also call the method of the `DatasetSnapshot` class.

**Comment by mars-lan** [comment]
See my comments in https://github.com/linkedin/datahub/issues/1848. You really shouldn't be messing with the URN structure.

**Comment by cobolbaby** [comment]
Ok, I know. I will try to see which methods are provided by the current DatasetSnapshot class.

**Comment by mars-lan** [comment]
@cobolbaby can we close this now?

**Comment by cobolbaby** [comment]
Yes.

**Comment by SemanticBeeng** [comment]
> Hopefully it's covered by https://github.com/linkedin/datahub/blob/master/docs/how/graph-onboarding.md. Let us know if there's any gap in the documentation.

This link is broken.
Could not find it here https://github.com/datahub-project/datahub/tree/master/docs/how

**Comment by SemanticBeeng** [comment]
Could `DataHub` accommodate `code property graph`s
Pruned `control flow` and `data flow` graphs can be critical for lineage.

* https://twitter.com/claudiuvursache/status/1474149858470735873
* https://twitter.com/TigerGraphDB/status/1373398189714325512

@shirshanka
