### ISSUE TITLE
The purpose of the url attribute in DatasetProperties model

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1854]
Ref: https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/dataset/DatasetProperties.pdl#L18

In order to realize a specific business, it is inevitable that you need to view the real data, so the data preview function will definitely be involved. 

I wonder if the url attribute of the dataset refers to the data preview address? And what is this field generally used to identify?

**Comment by mars-lan** [comment]
The field is actually URI (a broader definition than URL) and is not currently being used in the UI. You're free to utilize the field for your own need, e.g. connection string for data access.

**Comment by cobolbaby** [comment]
Oh I see.
