### ISSUE TITLE
Custom favicon and title?

### ISSUE THREAD

**Issue by rakreek** [linkedin/datahub#1855]
Hi all! If I'm trying to just use the latest docker image and not rebuild the project from scratch, is there a straightforward way to customize the [title in index.html](https://github.com/linkedin/datahub/blob/master/datahub-web/packages/data-portal/app/index.html) and [favicon](https://github.com/linkedin/datahub/tree/master/datahub-web/packages/data-portal/public/assets) for my own organization? 

If it takes more than 5 min, it's probably not worth the effort 😅 Many thanks!

**Comment by mars-lan** [comment]
Unfortunately they're not currently settable via docker. You'll need to rebuild the image after swapping out the files. That said, we should at the minimal change the favicon from a LinkedIn logo to a DataHub logo.

**Comment by rakreek** [comment]
Yeah, imho swapping in the Data Hub logo for the LinkedIn logo would get us 90% of the way there. Thanks again!

**Comment by rakreek** [comment]
Stop me if this is scope creep, but would you also consider swapping in datahub branding in the [navbar](https://github.com/linkedin/datahub/blob/c2c6f66ca8a21f1e50c00160340c69c951784fd8/datahub-web/packages/data-portal/app/templates/components/navbar.hbs#L22)?

**Comment by mars-lan** [comment]
That's a fair ask. Will have @cptran777 look into both.

**Comment by cptran777** [comment]
We're required to use the LinkedIn logo for our internal application. Should be relatively straightforward to build with a new image just for open source, just need to add in a little config modification so that we don't create a constant conflict with using our pipeline to push our new open source code.

**Comment by rakreek** [comment]
Hi there @cptran777 . Just wanted to check in on this request. Sounds like you expected it wouldn't be too bad. Is there any update you can share with the fans? Thank you!

**Comment by cptran777** [comment]
Hey @rakreek haven't had time to go and address this issue yet because of some internal issues with our pipeline to push to open source and trying to get an earlier ask out. This is in our TODO list, though, and should be able to sit down and actually address it next week.

**Comment by rakreek** [comment]
Thanks so much! 💯
