### ISSUE TITLE
Ingest metadata from MySQL to DataHub

### ISSUE THREAD

**Issue by zzmbulldog** [linkedin/datahub#1858]
hi，why the terminal show these after I input **'python mysql_etl.py'**. And Kafka no topic
![image](https://user-images.githubusercontent.com/40566786/92294499-41050100-ef5f-11ea-89e8-c9348aacdc3e.png)

**Comment by mars-lan** [comment]
Thanks for reporting. Could you include the precise command you ran and the full output (as an attachment if it's too long) so we can better debug the issue? Note that there is also a generic RDMBS crawler that you could use: https://github.com/linkedin/datahub/tree/master/metadata-ingestion/sql-etl

**Comment by mars-lan** [comment]
Assuming this has been resolved. Feel free to reopen with follow-up information.

**Comment by jiakai908** [comment]
i also meet this preblom. how can I solve this ? I have only config kafka and run the mysql_etl.

**Comment by mars-lan** [comment]
@jiakai908 could you include the full error log to help us debug? Thanks.
