### ISSUE TITLE
http://IpAddress/api/v2/entity-configs/urn:li:dataset:(urn:li:dataPlatform:mysql,xyz_db.events,PROD)?target=appworx-deprecation gives 404

### ISSUE THREAD

**Issue by moodleexpert** [linkedin/datahub#1860]
I have ingested metadata from Mysql TO Datahub. I can see my data set in datahub UI with all the databases and tables. When I click to the table it gives "We could not find a schema for this dataset".  I have also checked the debug console found that this URL "http://IpAddress/api/v2/entity-configs/urn:li:dataset:(urn:li:dataPlatform:mysql,xyz_db.events,PROD)?target=appworx-deprecation" is giving 404. 

Whether I am missing some configuration which needs to be done before ingestion?

my Request :

{"auditHeader":null,"proposedSnapshot":["com.linkedin.pegasus2avro.metadata.snapshot.DatasetSnapshot",{"urn":"urn:li:dataset:(urn:li:dataPlatform:mysql,jioevents_db.media_uploads,PROD)","aspects":[{"owners":[{"owner":"urn:li:corpuser:datahub","type":"DATAOWNER"}],"lastModified":{"time":0,"actor":"urn:li:corpuser:datahub"}},{"schemaName":"jioevents_db.media_uploads","platform":"urn:li:dataPlatform:mysql","version":10,"created":{"time":1599558276.8473175,"actor":"urn:li:corpuser:datahub"},"lastModified":{"time":1599558276.8473175,"actor":"urn:li:corpuser:datahub"},"hash":"","platformSchema":{"tableSchema":"[('id', 'int(11)', 'NO', 'PRI', None, 'auto_increment'), ('event_id', 'int(11)', 'NO', 'MUL', None, ''), ('user_id', 'int(11)', 'NO', 'MUL', None, ''), ('created_by', 'int(11)', 'NO', '', None, ''), ('created_at', 'timestamp', 'NO', '', 'CURRENT_TIMESTAMP', 'on update CURRENT_TIMESTAMP'), ('updated_by', 'int(11)', 'NO', '', None, ''), ('updated_at', 'timestamp', 'NO', '', '0000-00-00 00:00:00', ''), ('status', 'tinyint(4)', 'NO', '', '0', ''), ('is_disabled', 'tinyint(4)', 'NO', '', '0', ''), ('type', 'varchar(100)', 'YES', '', None, ''), ('filename', 'text', 'YES', '', None, ''), ('events_uuid', 'varchar(200)', 'YES', 'MUL', None, '')]"},"fields":[{"fieldPath":"id","nativeDataType":"int(11)","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"event_id","nativeDataType":"int(11)","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"user_id","nativeDataType":"int(11)","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"created_by","nativeDataType":"int(11)","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"created_at","nativeDataType":"timestamp","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"updated_by","nativeDataType":"int(11)","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"updated_at","nativeDataType":"timestamp","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"status","nativeDataType":"tinyint(4)","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"is_disabled","nativeDataType":"tinyint(4)","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"type","nativeDataType":"varchar(100)","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"filename","nativeDataType":"text","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}},{"fieldPath":"events_uuid","nativeDataType":"varchar(200)","type":{"type":{"com.linkedin.pegasus2avro.schema.StringType":{}}}}]}]}],"proposedDelta":null}

**Comment by jplaisted** [comment]
@cptran777 is this a recent issue from our frontend upgrades?

**Comment by moodleexpert** [comment]
I am not aware of it. I have just installed it in docker and use the sql-etl and mysql-etl

**Comment by mars-lan** [comment]
The 404 is unrelated. It's an internal API that @cptran777 will clean up in the next push.

Which ETL script did you use for ingestion?

**Comment by moodleexpert** [comment]
I have used the mysql script from [metadata-ingestion] (https://github.com/linkedin/datahub/tree/master/metadata-ingestion)  and ingested the metadata. Which was successful insertion , but when i try to view schema in Ui on datahub. I was unable see it only table names are getting display

**Comment by mars-lan** [comment]
Got it. Could you give this one a try and see if it makes a difference? https://github.com/linkedin/datahub/tree/master/metadata-ingestion/sql-etl

**Comment by moodleexpert** [comment]
Below API is getting called but schema is not getting displayed,
http://IpAddress/api/v2/datasets/urn:li:dataset:(urn:li:dataPlatform:mysql,xyz_db.events,PROD)/schema

response:

{"schema":{"schemaless":false,"rawSchema":"","keySchema":null,"columns":[{"id":null,"sortID":0,"parentSortID":0,"fieldName":"id","parentPath":null,"fullFieldPath":"id","dataType":"INTEGER(display_width=11)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"name","parentPath":null,"fullFieldPath":"name","dataType":"VARCHAR(length=200)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"description","parentPath":null,"fullFieldPath":"description","dataType":"TEXT()","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"created_at","parentPath":null,"fullFieldPath":"created_at","dataType":"TIMESTAMP()","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"updated_at","parentPath":null,"fullFieldPath":"updated_at","dataType":"TIMESTAMP()","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"userid","parentPath":null,"fullFieldPath":"userid","dataType":"INTEGER(display_width=11)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"uuid","parentPath":null,"fullFieldPath":"uuid","dataType":"VARCHAR(length=100)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"is_disabled","parentPath":null,"fullFieldPath":"is_disabled","dataType":"TINYINT(display_width=4)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"event_name","parentPath":null,"fullFieldPath":"event_name","dataType":"VARCHAR(length=200)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"event_status","parentPath":null,"fullFieldPath":"event_status","dataType":"VARCHAR(length=200)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"rtmp","parentPath":null,"fullFieldPath":"rtmp","dataType":"TEXT()","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"cdn_primary","parentPath":null,"fullFieldPath":"cdn_primary","dataType":"TEXT()","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"cdn_standby","parentPath":null,"fullFieldPath":"cdn_standby","dataType":"TEXT()","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"slate_status","parentPath":null,"fullFieldPath":"slate_status","dataType":"VARCHAR(length=100)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"logo_uploaded","parentPath":null,"fullFieldPath":"logo_uploaded","dataType":"TINYINT(display_width=4)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"publisher_id","parentPath":null,"fullFieldPath":"publisher_id","dataType":"INTEGER(display_width=11)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"cdn_hls_url","parentPath":null,"fullFieldPath":"cdn_hls_url","dataType":"TEXT()","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"rtmp_client_url","parentPath":null,"fullFieldPath":"rtmp_client_url","dataType":"TEXT()","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"created_by","parentPath":null,"fullFieldPath":"created_by","dataType":"INTEGER(display_width=11)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"updated_by","parentPath":null,"fullFieldPath":"updated_by","dataType":"INTEGER(display_width=11)","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"start_date_time","parentPath":null,"fullFieldPath":"start_date_time","dataType":"TIMESTAMP()","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null},{"id":null,"sortID":0,"parentSortID":0,"fieldName":"end_date_time","parentPath":null,"fullFieldPath":"end_date_time","dataType":"TIMESTAMP()","comment":"","commentCount":null,"partitionedStr":null,"partitioned":false,"nullableStr":null,"nullable":false,"indexedStr":null,"indexed":false,"distributedStr":null,"distributed":false,"treeGridClass":null}],"lastModified":1599649090}}

**Comment by moodleexpert** [comment]
> Got it. Could you give this one a try and see if it makes a difference? https://github.com/linkedin/datahub/tree/master/metadata-ingestion/sql-etl

i have used both mysql-etl and sql-etl no difference

**Comment by moodleexpert** [comment]
![Screenshot from 2020-09-09 22-45-40](https://user-images.githubusercontent.com/1505830/92634476-fcc48880-f2f1-11ea-921a-9689759fa2f7.jpg)
for your reference

**Comment by moodleexpert** [comment]
![Screenshot from 2020-09-09 23-16-20](https://user-images.githubusercontent.com/1505830/92634890-955b0880-f2f2-11ea-8acd-7582888e6876.jpg)

**Comment by mars-lan** [comment]
@cptran777 sounds like a regression in the latest UI?

**Comment by cptran777** [comment]
@moodleexpert the main issue here is that if rawSchema is empty then the schema is presumed to not exist in the current FE logic. I think based on discussions with the community that this logic works for our internal team but seems to have some issues with other use cases at large. I have it queued up to work on a fix for this as well as a few other issues, but a workaround for now would be to make rawSchema have any non-empty value (maybe like an empty json object "{}" or something

**Comment by cptran777** [comment]
Also the appworx-deprecation 404 is unrelated, but will also be removed as it is internal configuration logic that got leaked into open source

**Comment by moodleexpert** [comment]
@cptran777 Thank for the update...i will add rawSchema and check it again

**Comment by mars-lan** [comment]
@moodleexpert can we close this now?

**Comment by moodleexpert** [comment]
Yes you can
