### ISSUE TITLE
Clicking on dataset owner links to LI internal user site

### ISSUE THREAD

**Issue by jplaisted** [linkedin/datahub#1866]
- Launch DataHub via quickstart
- Browse to a dataset with owners
- Click an owner icon

Expected behavior:
Should link to the user's page on DataHub.

Actual behavior:
Opens a link in a new tab for the user's cinco page.

**Comment by cptran777** [comment]
Can you check again? Just tried to recreate the issue and it looks like it leads to the user's profile page.

**Comment by cptran777** [comment]
Since this no longer seems to be an issue, will close.
