### ISSUE TITLE
Ownership on ES not working via mce_cli

### ISSUE THREAD

**Issue by jplaisted** [linkedin/datahub#1867]
May not be MCE CLI specific. It is just the flow I am testing with. See https://github.com/linkedin/datahub/pull/1864#issuecomment-690769170

**Comment by jplaisted** [comment]
Seems like somewhere along the lines `CorpUserUrn#ENTITY_TYPE` drifted from the data in `bootstrap_mce.dat`. `corpuser` vs `corpUser`. As a result `BuilderUtils#getCorpUserOwners` erturns an empty set of owners.

**Comment by jplaisted** [comment]
It was 7d6fde4f37d507f6c7c4cf4370f935fb31ee6dcb. Issue with the test data, not with the code :)

**Comment by jplaisted** [comment]
@mars-lan is there a reason I'm not seeing for changing the case? If not, then this is an easy fix.

**Comment by mars-lan** [comment]
> @mars-lan is there a reason I'm not seeing for changing the case? If not, then this is an easy fix.

Nope. Was trying to be consistent.
