### ISSUE TITLE
Inclusive language

### ISSUE THREAD

**Issue by andrewkantor** [linkedin/datahub#1875]
Can you address a couple of instances of language in the project where the wording can be made more inclusive? (example: whiltelist -> allowlist). We are trying to make the code in all LinkedIn projects more inclusive. Could you please examine whether or not these need to be updated, and make the changes? For suggested replacements see go/inclusivelanguage or google. THANK YOU!

Term | URL
-- | --
Whitelist | https://github.com/linkedin/datahub/blob/5072ef013ce3ccb116726fda38fefb7d8319fd11/datahub-web/@datahub/shared/types/configurator/configurator.d.ts
Whitelist | https://github.com/linkedin/datahub/blob/0116a955cbc3fe0fdba6e0effecad3c6791f8862/datahub-web/@datahub/shared/addon/components/institutional-memory/containers/tab.ts
Whitelist | https://github.com/linkedin/datahub/blob/0116a955cbc3fe0fdba6e0effecad3c6791f8862/datahub-web/@datahub/shared/addon/components/institutional-memory/containers/tab.ts
Whitelist | https://github.com/linkedin/datahub/blob/5072ef013ce3ccb116726fda38fefb7d8319fd11/datahub-web/@datahub/shared/types/configurator/configurator.d.ts

**Comment by mars-lan** [comment]
Thank you for pointing these out, @andrewkantor. We too are working on a similar initiative internally at LinkedIn. Will try to prioritize these fixes.

**Comment by cptran777** [comment]
Thanks for the callout @andrewkantor , we have this as a task to address internally (which would then rollout to open source as well) but haven't allocated time towards this task. Having it be called out gives a good push to prioritize more inclusive wording.
