### ISSUE TITLE
Ownership assignment not working correctly in the new frontend

### ISSUE THREAD

**Issue by G-nther** [linkedin/datahub#1876]
**Describe the bug**
On a dataset with less than two owners an error message is shown beside the save button to assign at least two owners. When I add two users ar owners this message is still there and the Save-Button is still not enabled. When adding more than two owners the button is also still not enabled.

When I delete owners from a dataset until thereis one owner left and the error message promps to add at least one more owner. After I add an additional owner, this message doesn't disappear and the Save-Button is not enabled.

When manually enabling the Save-Button and clicking it, everything is working as expected

**To Reproduce**
On the latest master branch, with one of the bootstrap-datasets having the ownership aspect removed.

1. Go to the ownership tab of the dataset without owners
2. Add the two sample users as owners
3. Save-Button is still not enabled. Error message to assign at least two owners is still visible

**Expected behavior**
The Save-Button should be enabled when at least two users have been added as owners.

**Screenshots**
![issue-screenshot](https://user-images.githubusercontent.com/29147666/93306100-babea980-f7ff-11ea-9750-20e2c4980417.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge Chromium
 - Version 84.0.522.63

**Comment by hgcummings** [comment]
I've also observed this issue. I traced it as far as the owners being unconfirmed (and therefore treated as invalid).

Manually added owners are supposed to be confirmed automatically inside the addOwner method of the dataset-authors component: https://github.com/linkedin/datahub/blob/c07a3a9b8f450783a8219411227202875fb652a3/datahub-web/packages/data-portal/app/components/dataset-authors.ts#L266

But for some reason the currentUser proprety of this isn't being populated properly (it's supposed to come from the current-user service) so the `addOwner` method passes an empty username to `confirmOwner` and it has no effect.

I ran out of time to investigate further, but hopefully the above is of some use.

**Comment by cptran777** [comment]
Hey debugged it further, there was a workaround we had put in for getting the logged in user's "entity" as it was different than what we have internally. Have a solution in mind while we work on a better overall fix.

**Comment by cptran777** [comment]
Fix is available here: https://github.com/linkedin/datahub/pull/1880

**Comment by mars-lan** [comment]
@G-nther & @hgcummings could you verify if the issue has been fixed at HEAD?

**Comment by cptran777** [comment]
Hey @G-nther, @hgcummings , thanks for your help with reporting and looking into this issue. The fix is in, so let me know if there's still any issue on your end. Thanks again!
