### ISSUE TITLE
Dashboard aspect ingestion demo

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1878]
The dashboard aspect has recently been added. Does the GMS service provide relevant interface support? 

Could provide some examples or test case?

**Comment by jplaisted** [comment]
I think this is actually a question on the status of dashboards. I don't think they're done :) I'll let @keremsahin1 answer fully, but I believe the current state is that we have the models, but need to do backend (GMS) and frontend work still. I think @keremsahin1 is getting the backend work done before the end of the month; frontend may be awhile.

So there's no way to ingest yet. It isn't done :)

In the future we have some vague plans to have the server be mostly codegen'd (it is a lot of copy and paste today), which would cut down on the server side work, fyi.

**Comment by keremsahin1** [comment]
PR (https://github.com/linkedin/datahub/pull/1884) for backend work is in review @cobolbaby. Hopefully, we'll merge it soon.

**Comment by cobolbaby** [comment]
Close the issue.

Ref: https://github.com/linkedin/datahub/tree/master/gms#create-dashboards
