### ISSUE TITLE
datahub quickstart:ERROR: for kafka-topics-ui  failed to register layer

### ISSUE THREAD

**Issue by yjbupt** [linkedin/datahub#1879]
when i run the command quickstart.sh,this issue happened.
[root@master datahub]# ./docker/quickstart.sh 
Pulling mysql                ... done
Pulling elasticsearch        ... done
Pulling neo4j                ... done
Pulling elasticsearch-setup  ... done
Pulling kibana               ... done
Pulling zookeeper            ... done
Pulling broker               ... done
Pulling schema-registry      ... done
Pulling kafka-rest-proxy     ... done
Pulling kafka-topics-ui      ... download complete
Pulling kafka-setup          ... done
Pulling datahub-mae-consumer ... done
Pulling datahub-gms          ... done
Pulling datahub-mce-consumer ... done
Pulling datahub-frontend     ... done
Pulling schema-registry-ui   ... done

ERROR: for kafka-topics-ui  failed to register layer: devmapper: Unknown device b8e06f1b08e6f840cc6200811e115246f82026ae4a0ce69fbc1b30d810c403fb
ERROR: failed to register layer: devmapper: Unknown device b8e06f1b08e6f840cc6200811e115246f82026ae4a0ce69fbc1b30d810c403fb

**Comment by mars-lan** [comment]
Looks like a docker issue. Could you try to [start from a clean slate](https://github.com/linkedin/datahub/blob/master/docs/debugging.md#ive-messed-up-my-docker-setup-how-do-i-start-from-scratch) and see if the problem still persists?

**Comment by yjbupt** [comment]
> Looks like a docker issue. Could you try to [start from a clean slate](https://github.com/linkedin/datahub/blob/master/docs/debugging.md#ive-messed-up-my-docker-setup-how-do-i-start-from-scratch) and see if the problem still persists?

It seems to be due to the lack of storage space in the Docker,  I switched machines and this problem is solved。

**Comment by mars-lan** [comment]
Thanks for letting us know. Updated the [debugging guide](https://github.com/linkedin/datahub/blob/master/docs/debugging.md) accordingly.
