### ISSUE TITLE
Soft deletion of aspect

### ISSUE THREAD

**Issue by nagarjunakanamarlapudi** [linkedin/datahub#1887]
Toady we support soft deletion of entities using aspects like Status. 

WDYT on soft deletion of aspect ? 

Say, today I fill up aspect `DatasetProperties` for one dataset `D1`. And, tomorrow I want to remove aspect `DatasetProperties` for dataset `D1` ( in other words, this aspect is no more valid for `D1`)

How do we model this?

**Comment by mars-lan** [comment]
My original thought is to have the aspect owner add custom fields (say `removed`) in their aspects and self interpret it. However, I do see value having a consistent way to represent this. One method I can think of is to use a sentinel value (e.g. empty JSON `{}`) to represent deleted aspect. This should be fairly easy to implement such logic in LocalDAO but may require storage-system-specific logics.

**Comment by mars-lan** [comment]
Another RFC? :P

**Comment by camelliazhang** [comment]
+1 on RFC (Naga, lol) 
This is interesting. Some initial thoughts about it. I am working on getting away from soft deletion for secondary indices. If an aspect is soft deleted, we need to think whether the relationship derived from it needs to hard or soft deleted.  Also, status itself is an aspect, need to clarify what does it mean if Status aspect is soft deleted? Lastly, should the derived aspect that is built on top of other aspects be marked as deleted if one of the underlying aspect is deleted?

**Comment by jplaisted** [comment]
I think there are some cases for querying soft deleted entities from secondary indexes, but it probably isn't the 90% use case.

Example: "Find all my removed upstream datasets" (good indication my pipeline is broken)

Another example maybe "find all datasets with inactive owners". Granted, "inactive" users (left the company) are not the exact same thing as "removed" datasets, but it's sort of the same, right? Some bit of the metadata.

**Comment by jplaisted** [comment]
I'm not saying those are good use cases / enough to justify only soft deletion, I'm just playing devil's advocate.

**Comment by nagarjunakanamarlapudi** [comment]
> we need to think whether the relationship derived from it needs to hard or soft deleted

I believe yes. We should invalidate the relationships in graph . Relations exist only when the aspect is present.  If the aspect powering the relations is invalid, then the relations created as a result of this aspect should be invalid too.  

How we invalidate those relations, whether soft or hard deletes depends on the use case.  I believe @jplaisted  is right on the point, individual use cases drive hard/soft deletions in the graph relations (or secondary indices)

Or, we could take a generic stance and say we support only soft deletions. But, that can mean bloating up the indices.

> Lastly, should the derived aspect that is built on top of other aspects be marked as deleted if one of the underlying aspect is deleted?

No, I don't think so. Derived value should change based on the status of the underlying aspect. My derived aspect can be referring to more than one aspects and the logic of how I compute the derived value can account for (in)activeness of the underlying aspects.

**Comment by nagarjunakanamarlapudi** [comment]
Marking this as feature request.

**Comment by jjoyce0510** [comment]
Curious to understand why one would want to purge a particular aspect, but not an entity? 

If its because the data is incorrect, it should suffice to emit a new aspect version that represents a cleanse, right? (ie a new ownership aspect with an empty owners array) 

In what cases does this approach _not_ suffice?

**Comment by nagarjunakanamarlapudi** [comment]
>If its because the data is incorrect, it should suffice to emit a new aspect version that represents a cleanse, right? (ie a new ownership aspect with an empty owners array)

Think of a case where I don't know the correct owners here. Hence, I want to invalidate all previously said metadata. 

GMA has never been designed keeping such use cases. But, we have seen increasing number of such use cases where one wants to invalidate the previously said metadata. Fortunately, we have a way to invalidate an entity via Status aspect. But there is no way to invalidate further at the aspect level.

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
