### ISSUE TITLE
I'm having error with LinkedIn.com search "See all people results"

### ISSUE THREAD

**Issue by MiChaelinzo** [linkedin/datahub#1891]
**Describe the bug**
It won't show all people results, it would just display 2 people out of About 4,540,000 results
It's empty af
**To Reproduce**
1. Search 
2. Click on "See all people results"

**Expected behavior**
 "See all people results" out of 4,540,000 results
**Screenshots**
![linkedinlol](https://user-images.githubusercontent.com/68110223/93947130-a6b90180-fd43-11ea-85e6-84a0cf514492.GIF)

**Desktop (please complete the following information):**
 - OS: Windows 10 home 
 - Browser Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
It happend a 2 weeks ago expected for fix but nothing happened

**Comment by jplaisted** [comment]
Hey @MiChaelinzo thanks for the feedback, but this GitHub repo isn't for linkedin.com (that is not open sourced).

This is for another product, DataHub, made by LinkedIn, the company.

This help article explains how to file feedback for search linkedin.com: https://www.linkedin.com/help/linkedin/answer/118778/provide-feedback-on-linkedin-search-results?lang=en
