### ISSUE TITLE
Default KAFKA_BOOTSTRAP_SERVER Value 

### ISSUE THREAD

**Issue by liangjun-jiang** [linkedin/datahub#1892]
curious why there is no default `KAFKA_BOOTSTRAP_SERVER` in either [gms]( https://github.com/linkedin/datahub/blob/master/gms/factories/src/main/java/com/linkedin/common/factory/KafkaEventProducerFactory.java#L21), or not in related file in `mce-consumer-job` and `mae-consumer-job`, but 
the `[KAFKA_SCHEMAREGISTRY_URL:http://localhost:8081](https://github.com/linkedin/datahub/blob/master/gms/factories/src/main/java/com/linkedin/common/factory/KafkaEventProducerFactory.java#L24)` and all other places for neo4j, elasticsearch and  so on.

The reason I am asking is that I am running `gms`, `mae-consumer-job` and `mce-consumer-job` directly with their war/jar files. I don't want to either set those default by changing the code, or specify them in `jave jar` parameters.

**Comment by mars-lan** [comment]
Makes sense. Most likely we just forgot to add them in the first place. Mind to create a PR?

**Comment by liangjun-jiang** [comment]
If we look at the comment [here](https://github.com/linkedin/datahub/blob/master/gms/factories/src/main/java/com/linkedin/common/factory/KafkaEventProducerFactory.java#L34), it said
```
// KAFKA_BOOTSTRAP_SERVER has precedence over SPRING_KAFKA_BOOTSTRAP_SERVERS
    if (kafkaBootstrapServers != null && kafkaBootstrapServers.length() > 0) {
      producerProps.setBootstrapServers(Arrays.asList(kafkaBootstrapServers.split(",")));
    } // else we rely on KafkaProperties which defaults to localhost:9092
```

but unfortunately, the bean of `kafkaEventProducer` can not be instantiated if we don't set `KAFKA_BOOTSTRAP_SERVER` 
A PR will be sent.
