### ISSUE TITLE
Does Datahub use H2 database?

### ISSUE THREAD

**Issue by liangjun-jiang** [linkedin/datahub#1907]
I am using Skywalking App Performance monitor tool to play with Datahub,  Skywalking topology gives me a H2 database.
Wonder if it actually exits and get used.

Best,
![Screen Shot 2020-09-30 at 2 29 02 PM](https://user-images.githubusercontent.com/356347/94730794-618b6580-0329-11eb-9ffe-0ef00b79a5f3.png)

**Comment by mars-lan** [comment]
We do use it for [ImmutableLocalDAO](https://github.com/linkedin/datahub/blob/master/metadata-dao-impl/ebean-dao/src/main/java/com/linkedin/metadata/dao/ImmutableLocalDAO.java), which is leveraged by `/dataPlatforms` endpoint: https://github.com/linkedin/datahub/blob/master/gms/impl/src/main/java/com/linkedin/metadata/resources/dataplatform/DataPlatforms.java#L28

**Comment by mars-lan** [comment]
Closing this assuming the question has been answered. Feel free to reopen otherwise.
