### ISSUE TITLE
Handle entity ES indexing in the code 

### ISSUE THREAD

**Issue by liangjun-jiang** [linkedin/datahub#1910]
**Is your feature request related to a problem? Please describe.**
Currently, we create ES index for each entity by `curl` in the [ES docker setup](https://github.com/linkedin/datahub/tree/master/docker/elasticsearch-setup). Moving to the code level has been on the roadmap. 

**Describe the solution you'd like**
Handle entity ES indexing in the code level

**Describe alternatives you've considered**
n/a

**Additional context**
Before I jump into a RFC, I'd like to give a brief about a possible implementation. We use `dataset` as an example
step 1: 
change `com.linkedin.metadata.dao.search.ESSearchDAO` constructor to take one more parameter, the `JsonObject` of  `dataset-index-config.json`, 
```
public ESSearchDAO(@Nonnull RestHighLevelClient esClient, @Nonnull Class<DOCUMENT> documentClass,
      @Nonnull BaseSearchConfig<DOCUMENT> config, @Nonnull JsonObject indexJsonObject)
```
Step 2: Query to check if `dataset Index` if existing in Constructor above, if no, create index, 
check if an index
```
public boolean isExistsIndex(String indexName) throws IOException {
        indexName = formatIndexName(indexName);
        GetIndexRequest request = new GetIndexRequest();
        request.indices(indexName);
        return client.indices().exists(request);
    }
```
create an index
```
CreateIndexRequest request = new CreateIndexRequest(indexName);
        request.mapping(TYPE, indexJsonObject*, XContentType.JSON);
        CreateIndexResponse response = client.indices().create(request);
        log.debug("create {} index finished, isAcknowledged: {}", indexName, response.isAcknowledged());
```

~~We might have to set `indexName` at one point, probably add a new getter of `DatasetSearchConfig`~~
```
@Override
  @Nonnull
  public String getDefaultIndexName() {
    return "dataset";
  }
```

**Comment by mars-lan** [comment]
@jplaisted has been playing with this internally. Will let him comment here. Let's not rush to a RFC first until we've figured out the best approach in this thread first.

**Comment by jplaisted** [comment]
I haven't really done any work, just thought about it. I don't have the context as to why we have these json "templates" today. I would certainly prefer in code; it may be more verbose but it is at least type safe. @camelliazhang or @mars-lan may have more context on why we use json.

Maybe we can provide it as an option.

**Comment by liangjun-jiang** [comment]
OK. I had this feature working for the reference. It still reads json index files but we don't have to create the index using `cUrl` against ES server directly. 

https://github.com/liangjun-jiang/datahub/tree/es-indexing has the implementation. The gotcha is that it works with ES 6.3.2 & ES 7.

**Comment by jplaisted** [comment]
Also, that is another tagent to talk about. We are thinking of adding ES7 support this quarter. I'll look at your branch to see how you did it, but we probably have to support 5 for a bit (so we don't break existing datahub users with the upgrade). I'm hoping we can avoid having multiple jars on our end, like a elasticseach5-dao and elasticsearch7-dao.. but idk.

**Comment by liangjun-jiang** [comment]
probably multiple support are unavoidable if plan to support multiple version of ES. there are tiny syntax diff. between ES 6 & ES 7 for what Datahub is using. just FYI. 
I leave you to decide the direction.

**Comment by jjoyce0510** [comment]
@liangjun-jiang What is your use case for registering indexes at runtime?

**Comment by liangjun-jiang** [comment]
> @liangjun-jiang What is your use case for registering indexes at runtime?
I tried to remove unnecessary docker building process. I think the purpose of [`/elasticsearch-setup` ](https://github.com/linkedin/datahub/tree/master/docker/elasticsearch-setup) is solely for creating indexes after ES service is up.
In the real life, we will need to update the `mappings` quite often. To do that, you need to either work with ES directly or use ES API to do so.

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
