### ISSUE TITLE
Bulk metadata export

### ISSUE THREAD

**Issue by hgcummings** [linkedin/datahub#1915]
**Is your feature request related to a problem? Please describe.**
The motivation here is primarily "vendor lock-in" anxiety. If an organisation builds up a rich set of metadata in DataHub, could this easily be migrated to another tool?

This might be less of an issue at the moment while metadata is expected to be gathered by some kind of automated script (like the examples under `metadata-ingest`). An organisations ingestion scripts could be adapted and executed against a new system. However, it becomes more of an issue as features are added to edit or create more metadata within DataHub itself. I think currently only ownership and deprecation can be edited via the UI, but upcoming items in the roadmap (such as Social features) will add more to this.

**Describe the solution you'd like**
An easy way to export all metadata from the system in some standard format (e.g. CSV).

**Describe alternatives you've considered**
Is it the case that all metadata stored in ES and Neo4j can be inferred from the metadata stored in MySQL? If so, then extracting directly from MySQL might be sufficient, although the use of JSON-within-SQL makes this a bit less useful as an intermediate format for migrating into another system.

**Comment by mars-lan** [comment]
All info stored in ES & Neo4j should be derivable from the metadata aspects stored in MySQL/Postgres so a simple dump of those DB should suffice. Agree that JSON-within-SQL isn't the best format though. Note that we do plan to start supporting other NoSQL DBs (e.g. MongoDB) in the near future. It'd be nice to have a way to export the metadata aspects in a portable way so one can migrate from one system to another seamlessly.

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
