### ISSUE TITLE
Docker configurable Auth

### ISSUE THREAD

**Issue by samatspothero** [linkedin/datahub#1917]
**Is your feature request related to a problem? Please describe.**
Was looking into Auth for Datahub. It seemed to imply in the quickstart that there was some username/password auth built in. https://github.com/linkedin/datahub/blob/master/docs/quickstart.md#datahub-quickstart-guide

However, there was no password configured in any of the startup scripts. Mars pointed out to me that in fact the default auth was dummy auth, with no password verification, and different auth backends were pluggable via config.
https://github.com/linkedin/datahub/tree/master/datahub-frontend#authentication

**Describe the solution you'd like**
We're running datahub in k8s, and would like to have a pluggable auth that we could setup without code modifications, i.e. docker env variables. Also moving this piece of documentation out of the datahub frontend section and into some more administrative section would be helpful for discoverability of this functionality.

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
