### ISSUE TITLE
Add metrics for MAE service

### ISSUE THREAD

**Issue by grantatspothero** [linkedin/datahub#1919]
**Is your feature request related to a problem? Please describe.**
The MAE service periodically lost connectivity to neo4j and writes to neo4j got dropped. These errors got logged in the MAE service like:
```
16:57:36.061 [mae-consumer-job-client-0-C-1] ERROR c.l.m.k.MetadataAuditEventsProcessor - com.linkedin.metadata.dao.exception.RetryLimitReached: Failed to execute Neo4j write transaction after 3 retries
...
```

However, there were no metrics around these errors so we did not know anything went wrong. We only found out this error happened later when we noticed downstream lineage was getting dropped and did some debugging. 

**Describe the solution you'd like**
Metrics endpoint for the MAE service to monitor failed processing of MAE events. Right now the error gets logged and then recorded nowhere else. 

JMX is standard for java services and there exist converters from JMX to prometheus or other formats that different teams use. SpotHero uses prometheus but not sure what other people use.

**Describe alternatives you've considered**
Alternatively, could publish some sort of failed metadata audit event into kafka. But IMO the metric makes more sense for alerting purposes.  

**Additional context**
None

**Comment by mars-lan** [comment]
@arunvasudevan @liangjun-jiang I believe Expedia implemented something like this? Is it possible to upstream those changes?

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
