### ISSUE TITLE
Broken links on User Avatar

### ISSUE THREAD

**Issue by maggiehays** [linkedin/datahub#1923]
**Describe the bug**
Clicking on a user avatar for a Dataset entity routes the user to `https://cinco.linkedin.biz/people/[username]`. 

**To Reproduce**
1. Go to a Dataset entity with an associated owner
2. Click on the user icon/avatar
3. Page redirects to `cinco.linkedin.biz`
4. Recieve error

**Expected behavior**
I would expect to be routed to the user's DataHub profile, although I am uncertain of what the navigation experience is meant to be.

**Screenshots**
Clicking on this user icon routes to `https://cinco.linkedin.biz/people/[username]`

![Screen Shot 2020-10-06 at 4 50 15 PM](https://user-images.githubusercontent.com/15873986/95264639-52a72600-07f5-11eb-8674-f8fcca395fc5.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 85.0

**Comment by jplaisted** [comment]
I filed this as https://github.com/linkedin/datahub/issues/1866. Seems like it was closed as not reproducible but snuck back in?

**Comment by maggiehays** [comment]
> I filed this as #1866. Seems like it was closed as not reproducible but snuck back in?

@grantatspothero @samatspothero curious if we are seeing this issue because we're running a forked version?

**Comment by cptran777** [comment]
Ah I see the issue. This is the result of some overdue tech debt, but now that I can spot the issue properly I can start refactoring for the fix. Please stand by.

**Comment by cobolbaby** [comment]
Same issue.

**Comment by mars-lan** [comment]
Should be fixed in #1935
