### ISSUE TITLE
About  the problem that "mysql | 2020-10-17T01:19:30.151603Z 1007 [Note] Bad handshake"

### ISSUE THREAD

**Issue by HondaHsu2020** [linkedin/datahub#1946]
I can see the status of datahub, 
"fsets-32 -> Vector(1), __consumer_offsets-40 -> Vector(1))) (kafka.controller.KafkaController)
broker                  | [2020-10-17 01:17:41,876] DEBUG [Controller id=1] Topics not in preferred replica for broker 1 Map() (kafka.controller.KafkaController)
broker                  | [2020-10-17 01:17:41,876] TRACE [Controller id=1] Leader imbalance ratio for broker 1 is 0.0 (kafka.controller.KafkaController)
**mysql                   | 2020-10-17T01:19:30.151603Z 1007 [Note] Bad handshake
mysql                   | 2020-10-17T01:21:30.153907Z 1009 [Note] Bad handshake**"

but ,I run the command: docker exec -it mysql /usr/bin/mysql datahub -udatahub -pdatahub ,I can access the mysql :
" [root@localhost datahub-0.5.0]# docker exec -it mysql /usr/bin/mysql datahub -udatahub -pdatahub
mysql: [Warning] Using a password on the command line interface can be insecure.
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1268
Server version: 5.7.31 MySQL Community Server (GPL)

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement."

**I want to know the impact of this problem  that "mysql                   | 2020-10-17T01:19:30.151603Z 1007 [Note] Bad handshake"**

**Comment by mars-lan** [comment]
Seems to do with TLS negotiation and it's completely benign as explained here: https://github.com/mysql-net/MySqlConnector/issues/726
