### ISSUE TITLE
Why  the file "MetadataChangeEvent.avsc"  is not exist

### ISSUE THREAD

**Issue by HondaHsu2020** [linkedin/datahub#1951]
[root@localhost kafka-etl]# python3 metadata-ingestion/mce-cli/mce_cli.py produce -l metadata-events/mxe-schemas/src/renamed/avro/com/linkedin/mxe/MetadataChangeEvent.avsc -d metadata-ingestion/mce-cli/bootstrap_mce.dat
**python3: can't open file 'metadata-ingestion/mce-cli/mce_cli.py': [Errno 2] No such file or directory**
[root@localhost kafka-etl]# pwd
/root/datahub-0.4.3/metadata-ingestion/kafka-etl
[root@localhost kafka-etl]# **ls
kafka_etl.py  requirements.txt**

**In fact, it's the file that doesn't exist，as follows:**
/root/datahub-0.4.3/metadata-events/mxe-schemas
[root@localhost mxe-schemas]# ls
build.gradle  rename-namespace.sh

 **I know the file "metadata-events/mxe-schemas/src/renamed/avro/com/linkedin/mxe/MetadataChangeEvent.avsc " is not exist.
this file does not exist now. Do I want to know if this file is temporary?**  Will the data be cleaned up after  loading  data？

**Comment by mars-lan** [comment]
The file is generated as part of the build and hence the step 2 in https://github.com/linkedin/datahub/tree/master/metadata-ingestion

**Comment by NiravLangaliya** [comment]
#step-1
cd ~/datahub
#step-2
./gradlew :metadata-events:mxe-schemas:build

**Comment by mars-lan** [comment]
Assuming this has been answered. Feel free to reopen otherwise.
