### ISSUE TITLE
Why  is there no the table structure metadata, after run mysql_etl.py

### ISSUE THREAD

**Issue by HondaHsu2020** [linkedin/datahub#1953]
I configure the connection information for connecting to MySQL in the file "mysql_etl.py", Then I executed this python script,
The execution process fragment information is as follows：

{'auditHeader': None, 'proposedSnapshot': ('com.linkedin.pegasus2avro.metadata.snapshot.DatasetSnapshot', {'urn': 'urn:li:dataset:(urn:li:dataPlatform:mysql,ec_oms.virtual_manage_store,PROD)', 'aspects': [{'owners': [{'owner': 'urn:li:corpuser:datahub', 'type': 'DATAOWNER'}], 'lastModified': {'time': 0, 'actor': 'urn:li:corpuser:datahub'}}, {'schemaName': 'ec_oms.virtual_manage_store', 'platform': 'urn:li:dataPlatform:mysql', 'version': 10, 'created': {'time': 1603370741.888741, 'actor': 'urn:li:corpuser:datahub'}, 'lastModified': {'time': 1603370741.888741, 'actor': 'urn:li:corpuser:datahub'}, 'hash': '', 'platformSchema': {'tableSchema': "[('store_id', 'varchar(64)', 'NO', 'PRI', None, ''), ('protocol_id', 'varchar(64)', 'NO', '', '', ''), ('enable_at', 'datetime', 'NO', '', '2030-01-01 00:00:00', ''), ('disable_at', 'datetime', 'NO', '', 'CURRENT_TIMESTAMP', ''), ('created_stamp', 'datetime', 'NO', '', None, ''), ('created_by','varchar(64)', 'NO', '', '', ''), ('last_updated_stamp', 'datetime', 'NO', '', None, ''), ('last_updated_by', 'varchar(64)', 'NO', '','', '')]"}, 'fields': [{'fieldPath': 'store_id', 'nativeDataType': 'varchar(64)', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'protocol_id', 'nativeDataType': 'varchar(64)', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'enable_at', 'nativeDataType': 'datetime', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'disable_at', 'nativeDataType': 'datetime', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType':{}}}}, {'fieldPath': 'created_stamp', 'nativeDataType': 'datetime', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'created_by', 'nativeDataType': 'varchar(64)', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'last_updated_stamp', 'nativeDataType': 'datetime', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'last_updated_by', 'nativeDataType': 'varchar(64)', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}]}]}), 'proposedDelta': None} **has been successfully produced!**
[root@localhost mysql-etl]#

**However, I only see the list of tables on the datahub web, as follows: ** 
![image](https://user-images.githubusercontent.com/72068448/96873873-138cfc00-14a8-11eb-8c5f-db8cd3890ec2.png)

**but there is no the table structure metadata , as follows:** 

![image](https://user-images.githubusercontent.com/72068448/96874158-65358680-14a8-11eb-90e1-817adf49721c.png)

**How I can do it ?**

**Comment by NiravLangaliya** [comment]
are you able to access your database using API Calles? 

Here are  examples

https://github.com/linkedin/datahub/blob/928444928a1618d0a861cfff371d12951d39a3ab/gms/README.md

**Comment by nagarjunakanamarlapudi** [comment]
What does get api of schema return ? 

https://github.com/linkedin/datahub/blob/928444928a1618d0a861cfff371d12951d39a3ab/gms/README.md#get-dataset-schema

**Comment by HondaHsu2020** [comment]
**I tried several times, but I still couldn't，Is there any missing step：**

**1：build the mxe-schemas module：**
     ./gradlew :metadata-events:mxe-schemas:build

**2：check my python version ** 
    [root@localhost ~]# python3 --version
    Python 3.6.8

**3: install requirements ** 
    [root@localhost mysql-etl]# cat requirements.txt
     avro-python3==1.8.2
     confluent-kafka[avro]==1.4.0
     mysql-connector==2.2.9
    [root@localhost mysql-etl]# pip3 install -r requirements.txt

**4:Config my MySQL environmental variable in **mysql_etl.py****

5. run mysql_etl.py
 [root@localhost mysql-etl]# python3 mysql_etl.py

**Then ,the result of runing mysql_etl.py  is the above，In addition to the above four steps, what else needs to be done？**

**Comment by mars-lan** [comment]
@HondaHsu2020 Please provide the result of the schema API call as suggested by @nagarjunakanamarlapudi.

**Comment by HondaHsu2020** [comment]
@mars-lan 
[root@localhost mysql-etl]# **curl -H 'X-RestLi-Protocol-Version:2.0.0' -H 'X-RestLi-Method: get' 'http://10.118.71.181:8080/datasets/($params:(),name:ec_order.purchasing,origin:PROD,platform:urn%3Ali%3AdataPlatform%3Amysql)/schema/0' | jq**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7163  100  7163    0     0  1109k      0 --:--:-- --:--:-- --:--:-- 1399k
{
  "exceptionClass": "com.linkedin.restli.server.RestLiServiceException",
  "stackTrace": "com.linkedin.restli.server.RestLiServiceException [HTTP Status:404]\n\tat com.linkedin.metadata.restli.RestliUtils.resourceNotFoundException(RestliUtils.java:61)\n\tat com.linkedin.metadata.restli.RestliUtils.resourceNotFoundException(RestliUtils.java:56)\n\tat java.util.Optional.orElseThrow(Optional.java:290)\n\tat com.linkedin.metadata.restli.BaseVersionedAspectResource.lambda$get$0(BaseVersionedAspectResource.java:85)\n\tat com.linkedin.metadata.restli.RestliUtils.toTask(RestliUtils.java:27)\n\tat com.linkedin.metadata.restli.BaseVersionedAspectResource.get(BaseVersionedAspectResource.java:82)\n\tat com.linkedin.metadata.resources.dataset.SchemaResource.get(SchemaResource.java:26)\n\tat sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat com.linkedin.restli.internal.server.RestLiMethodInvoker.doInvoke(RestLiMethodInvoker.java:172)\n\tat com.linkedin.restli.internal.server.RestLiMethodInvoker.invoke(RestLiMethodInvoker.java:326)\n\tat com.linkedin.restli.internal.server.filter.FilterChainDispatcherImpl.onRequestSuccess(FilterChainDispatcherImpl.java:47)\n\tat com.linkedin.restli.internal.server.filter.RestLiFilterChainIterator.onRequest(RestLiFilterChainIterator.java:86)\n\tat com.linkedin.restli.internal.server.filter.RestLiFilterChain.onRequest(RestLiFilterChain.java:55)\n\tat com.linkedin.restli.server.BaseRestLiServer.handleResourceRequest(BaseRestLiServer.java:218)\n\tat com.linkedin.restli.server.RestRestLiServer.handleResourceRequestWithRestLiResponse(RestRestLiServer.java:242)\n\tat com.linkedin.restli.server.RestRestLiServer.handleResourceRequest(RestRestLiServer.java:211)\n\tat com.linkedin.restli.server.RestRestLiServer.handleResourceRequest(RestRestLiServer.java:181)\n\tat com.linkedin.restli.server.RestRestLiServer.doHandleRequest(RestRestLiServer.java:164)\n\tat com.linkedin.restli.server.RestRestLiServer.handleRequest(RestRestLiServer.java:120)\n\tat com.linkedin.restli.server.RestLiServer.handleRequest(RestLiServer.java:132)\n\tat com.linkedin.restli.server.DelegatingTransportDispatcher.handleRestRequest(DelegatingTransportDispatcher.java:70)\n\tat com.linkedin.r2.filter.transport.DispatcherRequestFilter.onRestRequest(DispatcherRequestFilter.java:70)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:72)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.TimedNextFilter.onRequest(TimedNextFilter.java:55)\n\tat com.linkedin.r2.filter.transport.ServerQueryTunnelFilter.onRestRequest(ServerQueryTunnelFilter.java:58)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:72)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.TimedNextFilter.onRequest(TimedNextFilter.java:55)\n\tat com.linkedin.r2.filter.message.rest.RestFilter.onRestRequest(RestFilter.java:50)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:72)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.FilterChainImpl.onRestRequest(FilterChainImpl.java:96)\n\tat com.linkedin.r2.filter.transport.FilterChainDispatcher.handleRestRequest(FilterChainDispatcher.java:75)\n\tat com.linkedin.r2.util.finalizer.RequestFinalizerDispatcher.handleRestRequest(RequestFinalizerDispatcher.java:61)\n\tat com.linkedin.r2.transport.http.server.HttpDispatcher.handleRequest(HttpDispatcher.java:101)\n\tat com.linkedin.r2.transport.http.server.AbstractR2Servlet.service(AbstractR2Servlet.java:105)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat com.linkedin.restli.server.spring.ParallelRestliHttpRequestHandler.handleRequest(ParallelRestliHttpRequestHandler.java:61)\n\tat org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:73)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:494)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)\n\tat java.lang.Thread.run(Thread.java:748)\n",
  "status": 404
}

**Comment by mars-lan** [comment]
The curl call looks correct to me. The fact that it returned 404 means your MCE wasn't ingested correctly. Check the docker log to see if there's any error?
```
docker logs datahub-mce-consumer
```

**Comment by HondaHsu2020** [comment]
@mars-lan 

I get good news today, The curl call dataset ,It was successful， as follow:

[root@localhost datahub-0.4.3]# curl -H 'X-RestLi-Protocol-Version:2.0.0' -H 'X-RestLi-Method: get' 'http://10.118.71.181:8080/datasets/($params:(),name:ec_order.purchasing_status,origin:PROD,platform:urn%3Ali%3AdataPlatform%3Amysql)/schema/0' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1393  100  1393    0     0   233k      0 --:--:-- --:--:-- --:--:--  340k
{
  "created": {
    "actor": "urn:li:corpuser:etl",
    "time": 1603869810
  },
  "platformSchema": {
    "com.linkedin.schema.OracleDDL": {
      "tableSchema": ""
    }
  },
  "lastModified": {
    "actor": "urn:li:corpuser:etl",
    "time": 1603869810
  },
  "schemaName": "ec_order.purchasing_status",
  "fields": [
    {
      "fieldPath": "id",
      "nullable": false,
      "type": {
        "type": {
          "com.linkedin.schema.NumberType": {}
        }
      },
      "nativeDataType": "BIGINT(display_width=64)",
      "recursive": false
    },
    {
      "fieldPath": "purchasing_id",
      "description": "采购单ID",
      "nullable": false,
      "type": {
        "type": {
          "com.linkedin.schema.StringType": {}
        }
      },
      "nativeDataType": "VARCHAR(length=64)",
      "recursive": false
    },
    {
      "fieldPath": "status",
      "description": "采购单状态",
      "nullable": false,
      "type": {
        "type": {
          "com.linkedin.schema.EnumType": {}
        }
      },
      "nativeDataType": "ENUM('NOT_SUBMITTED', 'CHECK_PENDING', 'AUDIT_FAILED', 'ORDER_PLACED')",
      "recursive": false
    },
    {
      "fieldPath": "created_by",
      "description": "变更人",
      "nullable": false,
      "type": {
        "type": {
          "com.linkedin.schema.StringType": {}
        }
      },
      "nativeDataType": "VARCHAR(length=64)",
      "recursive": false
    },
    {
      "fieldPath": "change_reason",
      "description": "变更备注",
      "nullable": false,
      "type": {
        "type": {
          "com.linkedin.schema.StringType": {}
        }
      },
      "nativeDataType": "VARCHAR(length=512)",
      "recursive": false
    },
    {
      "fieldPath": "created_stamp",
      "nullable": false,
      "type": {
        "type": {
          "com.linkedin.schema.NullType": {}
        }
      },
      "nativeDataType": "DATETIME()",
      "recursive": false
    }
  ],
  "version": 0,
  "platform": "urn:li:dataPlatform:mysql",
  "hash": ""
}

**But ,there is no the table structure metadata on the datahub web ,as follow:**

![image](https://user-images.githubusercontent.com/72068448/97530960-2777b700-19ee-11eb-820c-992a9600e490.png)

**Comment by mars-lan** [comment]
Interesting. Could you open "Developer Tools" in Chrome > "Network" tab and share the result of the `/api/v2/datasets/<urn>/schema` API call?

**Comment by jjoyce0510** [comment]
@shirshanka  Can we close this issue due to inactivity? 

This question is based on the legacy ingestion scripts.

**Comment by shirshanka** [comment]
Closing as this is no longer relevant.
