### ISSUE TITLE
A short description of the question

### ISSUE THREAD

**Issue by NiravLangaliya** [linkedin/datahub#1954]
Hello All, I am getting this error and I have deleted all docker containers https://github.com/linkedin/datahub/blob/master/docs/debugging.md#ive-messed-up-my-docker-setup-how-do-i-start-from-scratch   and starting docker again as given in step#4 https://github.com/linkedin/datahub/blob/master/docs/quickstart.md

![image](https://user-images.githubusercontent.com/13895686/96923209-8e690d80-14ce-11eb-9e19-be6854813a4b.png)

**Comment by mars-lan** [comment]
Did you make any changes to the docker files? Could you also try manually remove `datahub_network` (See https://docs.docker.com/engine/reference/commandline/network_rm/)

**Comment by NiravLangaliya** [comment]
It is working, we can close this question, thank you for helping me out.

**Comment by mars-lan** [comment]
Cool. Updated https://github.com/linkedin/datahub/blob/master/docs/debugging.md#ive-messed-up-my-docker-setup-how-do-i-start-from-scratch accordingly
