### ISSUE TITLE
Use PlatformInfo to better compose browse paths

### ISSUE THREAD

**Issue by jsotelo** [linkedin/datahub#1956]
**Is your feature request related to a problem? Please describe.**
Dataset names that have `.` in them are split by the browse endpoint regardless of the [Platform delimiter](https://github.com/linkedin/datahub/blob/f0485a490e08445d1459de3cd697c6cc0b2189d5/metadata-models/src/main/pegasus/com/linkedin/dataplatform/DataPlatformInfo.pdl#L72). See the bread crumbs in the image below:

![image](https://user-images.githubusercontent.com/448465/96947652-8d1cee00-1498-11eb-8c8f-3a34a8e86641.png)

I didn't expect to see the last two crumbs to be `a` and `test`. Instead I expected to see one unified crumb `a.test`. 

**Describe the solution you'd like**
It seems like we always split on `.` [here](https://github.com/linkedin/datahub/blob/master/metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DatasetIndexBuilder.java#L32) but perhaps we can use the the [Platform delimiter](https://github.com/linkedin/datahub/blob/f0485a490e08445d1459de3cd697c6cc0b2189d5/metadata-models/src/main/pegasus/com/linkedin/dataplatform/DataPlatformInfo.pdl#L72) to be smarter about this?

The desired end result would be to treat `.` in dataset names as any other alphanumeric character for platforms that use a different delimiter.

**Describe alternatives you've considered**
No alternatives have been considered

**Additional context**
Using `.` in names is not very uncommon. Supporting them properly would facilitate DataHub adoption.

**Comment by mars-lan** [comment]
Makes sense. Internally we do use `Platform delimiter` to build the browse path. Somehow it didn't flow into OSS correctly.

**Comment by gabe-lyons** [comment]
Hey there @jsotelo - you can emit a custom BrowsePaths aspect to avoid the splitting on `.`

**Comment by jsotelo** [comment]
Yep, this is what we did. I'll close this.
