### ISSUE TITLE
Getting Error while running gradlew build

### ISSUE THREAD

**Issue by NiravLangaliya** [linkedin/datahub#1957]
Getting below error while running gradlew build command as per  https://github.com/linkedin/datahub/tree/master/metadata-ingestion step#2 

`./gradlew :metadata-events:mxe-schemas:build`

![image](https://user-images.githubusercontent.com/13895686/97013371-9b394000-1566-11eb-811f-44dcdcdfecae.png)

![image](https://user-images.githubusercontent.com/13895686/97013381-9ffdf400-1566-11eb-87d3-7c2d4a5aee08.png)

**Comment by nagarjunakanamarlapudi** [comment]
Looks like the build is happening on a windows machine. 

I was able to replicate similar error on a windows machine.

@mars-lan is this the first use case of building on windows ??

**Comment by mars-lan** [comment]
Most likely https://github.com/linkedin/rest.li/issues/287

**Comment by mars-lan** [comment]
Unfortunately, it seems that rest.li team has little interest in supporting Windows (see https://github.com/linkedin/rest.li/issues/287). Will close this for now and encourage DataHub users to build on Mac & Linux instead.
