### ISSUE TITLE
 what data types does the "pegasus2avro" supports?

### ISSUE THREAD

**Issue by HondaHsu2020** [linkedin/datahub#1963]
in bootstrap_mce.dat :
"type": {
	      "type": {
			   "com.linkedin.pegasus2avro.schema.**StringType**": {}
			 }

the   "varchar" type  in  mysql  map  the "String" type of pegasus2avro，so, I want to know  what data types does the "pegasus2avro" supports?

**Comment by mars-lan** [comment]
You can see all the types here: https://github.com/linkedin/datahub/blob/master/metadata-models/src/main/pegasus/com/linkedin/schema/SchemaFieldDataType.pdl

**Comment by jplaisted** [comment]
Better yet, use the Java version of the CLI, which consumes a json file rather than avro. Much easier to use.

I should've moved the old python version to contrib as part of #1871, not sure why I didn't. Let me move it.

**Comment by jjoyce0510** [comment]
@HondaHsu2020 Hopefully the responses above helped to answer your questions. 

cc. @shirshanka to close the ticket
