### ISSUE TITLE
associated dataset with user

### ISSUE THREAD

**Issue by flyingtosy** [linkedin/datahub#1967]
I add a dataset 'SampleTestDataset' and how can I associated it with user datahub?
![datahub](https://user-images.githubusercontent.com/44353347/97296726-fed7ac00-188b-11eb-9750-dea851c1c16a.png)

{
  "events": [
    {
      "proposedSnapshot": {
        "com.linkedin.metadata.snapshot.DatasetSnapshot": {
          "urn": "urn:li:dataset:(urn:li:dataPlatform:hdfs,SampleTestDataset,PROD)",
          "aspects": [
            {
              "com.linkedin.common.Ownership": {
                "owners": [
                  {
                    "owner": "urn:li:corpuser:jdoe",
                    "type": "DATAOWNER"
                  },
                  {
                    "owner": "urn:li:corpuser:datahub",
                    "type": "DATAOWNER"
                  }
                ],
                "lastModified": {
                  "time": 1581407189000,
                  "actor": "urn:li:corpuser:jdoe"
                }
              }
            },
......
}

**Comment by mars-lan** [comment]
@flyingtosy could you use the API to verify that the sample dataset is created correctly? 

```
curl -H 'X-RestLi-Protocol-Version:2.0.0' -H 'X-RestLi-Method: get' 'http://localhost:8080/datasets/($params:(),name: SampleTestDataset,origin:PROD,platform:urn%3Ali%3AdataPlatform%3Ahdfs)' | jq

```

**Comment by flyingtosy** [comment]
@mars-lan 
curl -H 'X-RestLi-Protocol-Version:2.0.0' -H 'X-RestLi-Method: get' 'http://localhost:8080/datasets/($params:(),name:SampleTestDataset,origin:PROD,platform:urn%3Ali%3AdataPlatform%3Ahdfs)'
i get the output 
{"urn":"urn:li:dataset:(urn:li:dataPlatform:hdfs,SampleTestDataset,PROD)","ownership":{"owners":[{"owner":"urn:li:corpuser:jdoe","type":"DATAOWNER"},{"owner":"urn:li:corpuser:datahub","type":"DATAOWNER"}],"lastModified":{"actor":"urn:li:corpuser:jdoe","time":1581407189000}},"origin":"PROD","name":"SampleTestDataset","institutionalMemory":{"elements":[{"createStamp":{"actor":"urn:li:corpuser:jdoe","time":1581407189000},"description":"Sample doc","url":"https://www.linkedin.com"}]},"schemaMetadata":{"created":{"actor":"urn:li:corpuser:jdoe","time":1581407189000},"platformSchema":{"com.linkedin.schema.KafkaSchema":{"documentSchema":"{\"type\":\"record\",\"name\":\"SampleHdfsSchema\",\"namespace\":\"com.linkedin.dataset\",\"doc\":\"Sample HDFS dataset\",\"fields\":[{\"name\":\"field_foo\",\"type\":[\"string\"]},{\"name\":\"field_bar\",\"type\":[\"boolean\"]}]}"}},"lastModified":{"actor":"urn:li:corpuser:jdoe","time":1581407189000},"schemaName":"SampleHdfsSchema","fields":[{"fieldPath":"field_foo","description":"Foo field description","nullable":false,"type":{"type":{"com.linkedin.schema.StringType":{}}},"nativeDataType":"string","recursive":false},{"fieldPath":"field_bar","description":"Bar field description","nullable":false,"type":{"type":{"com.linkedin.schema.BooleanType":{}}},"nativeDataType":"boolean","recursive":false}],"version":0,"platform":"urn:li:dataPlatform:hdfs","hash":""},"platform":"urn:li:dataPlatform:hdfs"}

**Comment by mars-lan** [comment]
Okay looks like the ownership has been set correctly. Are you not seeing that under "Datasets I owned" page? Your original screenshot got cut off so I can't tell what the other 2 datasets are in the table.

**Comment by mars-lan** [comment]
@flyingtosy now that https://github.com/linkedin/datahub/pull/1970 has gotten in, could you verify if the issue has been fixed?

**Comment by flyingtosy** [comment]
@mars-lan thanks, it works
