### ISSUE TITLE
Ability to restrict editing access for certain users

### ISSUE THREAD

**Issue by shubhamg931** [linkedin/datahub#1983]
**Is your feature request related to a problem? Please describe.**
Currently, there is no access control over user activity, and any new inexperienced user can change/add the dataset's owner, docs, depreciation status, etc. 
This could be quite troublesome for even small startups and easily become unmanageable for larger organizations. 

**Describe the solution you'd like**
It would be nice even to have basic read-write access level control over users. For e.g. Only dataset owners should be allowed to edit any information pertaining to the dataset, and other users should only be allowed to read the same.

**Describe alternatives you've considered**
As a quick hacky resolution, I can think of maintaining a list of read-only users in the back-end and skip their API requests to edit anything completely. This will be increasing latency for users with edit access a bit, but since the number of users is expected to be less, that might not be much of an issue.

**Additional context**

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
