### ISSUE TITLE
Dataset Previews

### ISSUE THREAD

**Issue by maggiehays** [linkedin/datahub#1992]
**Problem**
During data discovery, dataset naming conventions and/or documentation do not always provide enough context to understand the relevance of a given dataset. Analysts and Data Scientists frequently run simple `select * from ... limit 10` queries to get a better understanding of the shape of data and to determine if it is relevant to their use case. 

This requires them to execute further discovery in their querying environment, thus requiring them to navigate to & from DataHub during research.

**Proposed Solution**
Datasets should have "data preview" results available in the UI so users do not have to navigate outside of DataHub to execute these common queries. 

My assumption is that owners of DataHub will not want to schedule & publish updates for _all_ datasets - this would cause unnecessary querying load on datasets that may not actually be relevant to their DataHub users;  worth considering if there is a way to configure a connection directly to the db to execute simple profiling queries on demand, then caching those results in the UI until there's a requested refresh by DH users. 

**Additional Context** 
This will likely require some sort of configurable obfuscation of field/column content to protect PII, but I don't have a well-formed opinion about what that should look like just yet.

**Comment by cobolbaby** [comment]
Refer: #1854
