### ISSUE TITLE
Enable Field/Column-level Search

### ISSUE THREAD

**Issue by maggiehays** [linkedin/datahub#1993]
**Problem**
Users can't search for a specific field or fuzzy-match a field name across datasets and/or platforms. This requires them to know the full domain of potentially relevant datasets where they might find that field.

**Proposed Soultion**
Enable field/column-level search.

**Comment by nagarjunakanamarlapudi** [comment]
Yeah, we have been thinking of this for a while now. Let me get on to this.

**Comment by shubhamg931** [comment]
I guess fuzzy-match is still not working.. Can we keep this issue open?

**Comment by mars-lan** [comment]
@shubhamg931 instead of re-opening, could you please create a new ticket?

**Comment by shubhamg931** [comment]
Sure
