### ISSUE TITLE
link broken in the code in-line comment

### ISSUE THREAD

**Issue by yhjyoon** [linkedin/datahub#2017]
Link provided in the code in-line comment is broken.  Is there any other link I can take a look into?

Code:
https://github.com/linkedin/datahub/blob/1283dd3ff49ea169ff5b8b24eec7952bd3f70e09/metadata-models/src/main/pegasus/com/linkedin/dataset/SchemaFieldPath.pdl

Link:
http://go/tms-schema

**Comment by mars-lan** [comment]
Sorry this is for an internal link. @nagarjunakanamarlapudi can we move some of those info to OSS?

**Comment by nagarjunakanamarlapudi** [comment]
Yes. This is also in the roadmap of field level lineage. There is a need for standardizing the field paths in OSS

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if you need additional support!
