### ISSUE TITLE
Enable CRUD on DataPlatform entity

### ISSUE THREAD

**Issue by nagarjunakanamarlapudi** [linkedin/datahub#2018]
**Is your feature request related to a problem? Please describe.**
DataPlatforms information is coded in [a static file](https://github.com/linkedin/datahub/blob/master/gms/impl/src/main/resources/DataPlatformInfo.json) and read using Immutable DAO. 

Refer [comment here](https://github.com/linkedin/datahub/pull/2000#discussion_r530046945)
>For open source, there is a plethora of platforms out there that makes it infeasible to track in a single code file (AWS' S3 comes to mind). My outsider (and perhaps implementation-naive) perspective makes me think this should be a user PUT-able endpoint so that users have full flexibility to define any given platform.

**Describe the solution you'd like**
Change the store  Dataflatform info from static file to KV store and read using EbenaLocalDAO

**Describe alternatives you've considered**
NONE

**Additional context**
https://github.com/linkedin/datahub/pull/2000#discussion_r530046945

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
