### ISSUE TITLE
Fuzzy match support for searching over fieldpaths

### ISSUE THREAD

**Issue by shubhamg931** [linkedin/datahub#2019]
**Is your feature request related to a problem? Please describe.**
Fuzzy match is not supported for newly added Field level search ( https://github.com/linkedin/datahub/issues/1993 ). One needs to type the full field name or add an asterisk after the partial search to search for datasets based on field names.

**Describe the solution you'd like**
It would be nice to have fuzzy matching or auto-completion supported since people tend to forget the exact field names

**Describe alternatives you've considered**
Auto-completion can be an alternative to fuzzy match just like it is available for other filters( dataorigin, name, owners )

**Comment by nagarjunakanamarlapudi** [comment]
Are you referring to advanced search with query like `fieldPaths:foo*`  ?

**Comment by shubhamg931** [comment]
yes

**Comment by camelliazhang** [comment]
@nagarjunakanamarlapudi , based on @shubhamg931 's description, looks like auto completion for filedPaths is not successfully enabled? Some support in mid-tier might be missing. It can follow the same pattern for owners field.

**Comment by nagarjunakanamarlapudi** [comment]
Didn't get time to simulate this behaviour. But, it should follow the similar approach as owners and I thought it was working.

**Comment by nagarjunakanamarlapudi** [comment]
Looks like the field paths index and mapping settings of dataset document introduced in this https://github.com/linkedin/datahub/pull/2001 is overriden later by https://github.com/linkedin/datahub/pull/2028/ 

cc: @jplaisted
