### ISSUE TITLE
Version in docker-compose.yml is unsupported

### ISSUE THREAD

**Issue by th0ger** [linkedin/datahub#2020]
When following the [quick-start guide](https://github.com/linkedin/datahub/blob/master/docs/quickstart.md), at step `./docker/quickstart.sh` I get:

`
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
`

The compose files are `3.8`, so I upgraded my docker to `19.03.13` to ensure [compatibility](https://docs.docker.com/compose/compose-file/). This didn't work.

Possible resulution: Downgrade `docker-compose.yml` and `docker-compose.override.yml` to `3.7`, this worked for me (so far).

**Comment by nagarjunakanamarlapudi** [comment]
Interesting ...  I am using docker `19.03.13`  and compose files with `3.8`. It works for me

```
% docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.1
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

```

**Comment by th0ger** [comment]
```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
```
$ docker-compose -v
docker-compose version 1.25.0, build unknown
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
Runnning inside Windows 10 / WSL2.

**Comment by jplaisted** [comment]
Can you also file this on docker? Based on that compatibility matrix from the OP this sounds like a bug on them?

**Comment by th0ger** [comment]
@jplaisted I think you are right, here's a minimal example `docker.compose.yml`:
```
version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
```
```
$ docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
version: `3.7` works.

**Comment by th0ger** [comment]
The issue was caused by too low version of `docker-compose` = `1.25.0`, which is unfortunately the highest version Ubuntu supports on [any of their current releases](https://packages.ubuntu.com/search?keywords=docker-compose&searchon=names&suite=all&section=all), including `focal (20.04LTS)`, `groovy (20.10)` and `hirsute`.

For reference if anyone needs it:
I'm on `focal (20.04LTS)` with `docker-ce` installed from `deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable` and `docker-compose` installed from Ubuntu universe.
```
$ dpkg -l | grep ii | grep docker
ii  docker-ce                                                   5:19.03.13~3-0~ubuntu-focal
ii  docker-ce-cli                                               5:19.03.13~3-0~ubuntu-focal
ii  docker-compose                                              1.25.0-1
```
Upgraded `docker-compose` the [official docker](https://docs.docker.com/compose/install/)/non-Debian-way:
```
$ sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
$ sudo chmod +x /usr/local/bin/docker-compose
$ which docker-compose
/usr/local/bin/docker-compose
$ docker-compose -v
docker-compose version 1.27.4, build 40524192
```
Note that `/usr/bin/docker-compose` is still the old version.

**Comment by p17m0** [comment]
Спасибо!

**Comment by Mai-Saad** [comment]
Still can see the same error while using docker `Docker version 20.10.21, build baeda1f` and `docker-compose version 1.17.1, build unknown` .. Any ideas?
```
> lib-sass@1.0.0 wp-env
> wp-env start

✖ Error while running docker-compose command.
Version in "/../../wp-env/9de8fdea95474b95a0d40af1ded3691c/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

**Comment by johmedina** [comment]
> Still can see the same error while using docker `Docker version 20.10.21, build baeda1f` and `docker-compose version 1.17.1, build unknown` .. Any ideas?
> 
> ```
> > lib-sass@1.0.0 wp-env
> > wp-env start
> 
> ✖ Error while running docker-compose command.
> Version in "/../../wp-env/9de8fdea95474b95a0d40af1ded3691c/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
> For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
> ```
> 
> The version inside docker-compose.yml is `3.7`

I have the same environment versions as this, did you find a fix for it?

**Comment by dancunogenda-omondi** [comment]
The solution would be to remove the docker-compose you have installed (sudo apt autoremove —purge docker-compose) and then:-
  $ sudo apt-get update
  $ sudo apt-get install docker-compose-plugin

This will install the latest docker compose (docker compose version (Docker Compose version v2.15.1)). You will then never see the error again.

**Comment by LoneDuckie** [comment]
> 

Hello, I have to ask about this. When I do the sudo apt-get install docker-compose-plugin I get a message saying:
E: Unable to locate package docker-compose-plugin
Instead when I use sudo apt-get install docker-compose it says that I am on the newest version already, being 1.17.1... is there something that Im missing? Thank you

**Comment by WonderfulDev0810** [comment]
I also had the same error, but when I burned the docker2aci package, it worked normally.
I hope you fix the error with this method

**Comment by LoneDuckie** [comment]
> I also had the same error, but when I burned the docker2aci package, it worked normally. I hope you fix the error with this method

Sorry but Im totally new to Linux, let alone docker... we had an issue with our application at work so I had to step up and I am afraid I dont understand. Can you please explain what you mean? Thank you :)

**Comment by dancunogenda-omondi** [comment]
Follow this :- 

sudo apt-get update
sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

sudo mkdir -m 0755 -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update

sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

After those then it should work. The problem you had with package not found was that we did not set up where to fetch the repo.

**Comment by bellaj** [comment]
Upgrade both docker and Docker-compose.

sudo cd /usr/local/bin && sudo rm -rf docker-compose
sudo sudo curl -SL https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
sudo chmod +x docker-compose

**Comment by Daniellundin048** [comment]
- name: Setup Node.js environment
  uses: actions/setup-node@v4.0.4
  with:
    # Set always-auth in npmrc.
    always-auth: # optional, default is false
    # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
    node-version: # optional
    # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
    node-version-file: # optional
    # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec.
    check-latest: # optional
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.
    registry-url: # optional
    # Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).
    scope: # optional
    # Used to pull node distributions from node-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
    cache: # optional
    # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
    cache-dependency-path: # optional

**Comment by Munawarmoja** [comment]
Dokaky
