### ISSUE TITLE
UI: Why nativeSchema tab is called JSON?

### ISSUE THREAD

**Issue by shakti-garg** [linkedin/datahub#2037]
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/5525521/102062859-481f9300-3e1b-11eb-8fe0-a1ddbabdbe32.png">

In the above page, the content in JSON tab is being populated from following aspect of dataset MCE(DatasetSnapshot-> SchemaMetadata-> platformSchema) which has structure like below:
```
{
              "name" : "platformSchema",
              "type" : [ {
                "type" : "record",
                "name" : "EspressoSchema",
                "doc" : "Schema text of an espresso table schema.",
                "fields" : [ {
                  "name" : "documentSchema",
                  "type" : "string",
                  "doc" : "The native espresso document schema."
                }, {
                  "name" : "tableSchema",
                  "type" : "string",
                  "doc" : "The espresso table schema definition."
                } ]
              }, ..
}
```

Now the questions is:
Is it compulsory to provide platform schema in JSON format(as in schema docs and also the name of tab in UI)?
My understanding is that platformSchema (or native schema) may or may not be available in json format depending on source type. for example, if schema is in avro, it is by-default JSON. if it is Protobuf, not exactly in JSON.

**Comment by nagarjunakanamarlapudi** [comment]
You are correct. Ideally, we should have called it as RAW schema. 

@cptran777, @igbopie  FYI

**Comment by shakti-garg-saxo** [comment]
If we have a consensus on the same, should I proceed with doing the changes and contribute back?

**Comment by mars-lan** [comment]
> If we have a consensus on the same, should I proceed with doing the changes and contribute back?

Please do.
