### ISSUE TITLE
Feature to provide snapshot of current/active entities and aspects and their properties; and, relationships among them

### ISSUE THREAD

**Issue by yhjyoon** [linkedin/datahub#2038]
**Is your feature request related to a problem? Please describe.**
My team goes through a manual exercise of mapping entities, aspects, and their properties manually to help us understand what's available now to assess the need for customization
https://datahubspace.slack.com/archives/CV2KB471C/p1607709607286700

**Describe the solution you'd like**
A feature to:
1. list out all entities and aspects; and their properties and active status (true/false)
2. list out or visualize relationships among them

**Describe alternatives you've considered**
Semi-manual process to scrape all pdls in the repo and map them

**Additional context**
I think this would be one of the most powerful feature to help new users/organizations to reduce time spent on learning Datahub and enrich customization and feature requests - I'm sure it'll reduce amount of questions asked in the slack channel about existing entities and aspects as well.

**Comment by jplaisted** [comment]
We have the graph visualization for lineage. We could potentially repurpose that for displaying the lineage flow of entities in the ecosystem.

fyi @woodyzhou

**Comment by camelliazhang** [comment]
This needs PDL schema onboarding & relationships built between entity & aspect models. Internally we had similar thoughts as well, with larger scope (the meta graph will involve other components such as the events that used to ingest data for a particular aspect, etc). FYI. + @nagarjunakanamarlapudi @vidvarma

**Comment by gabe-lyons** [comment]
Hey @yhjyoon you can view the metadata model on the datahub demo site here: https://demo.datahubproject.io/dataset/urn:li:dataset:(urn:li:dataPlatform:datahub,Dataset,PROD)/Schema?is_lineage_mode=false

**Comment by maggiehays** [comment]
Hi folks!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
