### ISSUE TITLE
https://github.com/login/oauth/authorize

### ISSUE THREAD

**Issue by riyad-hub** [linkedin/datahub#2039]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jplaisted** [comment]
Hey @riyad-hub 

This bug has the default description and a non descriptive title. As it stands it is not clear what this bug is for. I'm going to close this for now, but feel free to open a new one with a descriptive title and good description of the issue :)
