### ISSUE TITLE
‘?’ hyperlink in the Ownership tab pointing to invalid URL

### ISSUE THREAD

**Issue by shakti-garg** [linkedin/datahub#2051]
**Describe the bug**
"?" points to an invalid url, `https://iwww.corp.linkedin.com/wiki/cf/display/DWH/Metadata+Acquisition#ProjectOverview-ownership`

**To Reproduce**
1. Go to 'Ownership tab.'
2. Click on '?'
3. See error

**Expected behavior**
Fix the hyperlink with the correct url.

**Screenshots**
<img width="1530" alt="Screenshot 2021-01-12 at 7 14 42 PM" src="https://user-images.githubusercontent.com/5525521/104322834-69070100-550b-11eb-890d-b15b46e377fa.png">

**Comment by jplaisted** [comment]
This might be a duplicate.

**Comment by shirshanka** [comment]
Closing as we will not be fixing issues in the Ember frontend going forward.
