### ISSUE TITLE
Missing Upstream & Downstream table under Relationships tab

### ISSUE THREAD

**Issue by arpanm96** [linkedin/datahub#2056]
**Describe the bug**
The upstream and downstream table is not being displayed under the relationships tab, although there exists lineage information which has both upstream and downstream dataset.

**To Reproduce**
1. Startup LDH v0.6.1 using the docker quickstart guide.
2. Go to http://localhost:9001/#/datasets/urn:li:dataset:(urn:li:dataPlatform:hdfs,SampleHdfsDataset,PROD)/relationships
3. See error

**Expected behavior**
One should be able to see the upstream and downstream datasets in the tabular view.

**Screenshots**
![image](https://user-images.githubusercontent.com/17992485/104440657-a2497a80-55b8-11eb-9f3d-405b4d83cc63.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.4.6
 - Browser: chrome
 - Version: 87.0.4280.141

**Additional context**
The issue seems to be that the component PendulumEllipsisAnimation was deleted in v0.6.1 release and is still in use in lineage containers. 

Will raise the PR against this with the fix.

**Comment by hshahoss** [comment]
@igbopie fyi

**Comment by grantatspothero** [comment]
Confirming we are experiencing the same issue, thanks for opening the PR.
