### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by shubham49** [linkedin/datahub#2062]
Are we not going to support IE 11?
https://github.com/linkedin/datahub/blob/550cdc51eecce9c5185c7d6713c9b9d6253703e4/datahub-web/configs/tsconfig-base.json#L3

**Comment by jplaisted** [comment]
IE 11 is hitting its end of life later this year. I don't think it is worth going out of our way to support it.

**Comment by shubham49** [comment]
And edge?

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 1yr without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if you need additional support!
