### ISSUE TITLE
Auto-generation of GMS clients, GQL DataLoaders + DataFetchers, GQL schema

### ISSUE THREAD

**Issue by jjoyce0510** [linkedin/datahub#2068]
**Is your feature request related to a problem? Please describe.**
This is related to the new GraphQL API being introduced to DataHub. (https://github.com/linkedin/datahub/pull/2066) 

**Describe the solution you'd like**
Automatically generate the following from GMS models: 

- Generation of the primary entities on the GQL graph 
- Generation of Pegasus->GQL mapper logic
- Generation of DataLoaders
- Generatation of DataFetchers (Resolvers)

**Describe alternatives you've considered**
Hand-maintain the GraphQL schema, loaders, fetchers. 

**Additional context**
N/A

**Comment by jjoyce0510** [comment]
(I can be assigned this) 

cc. @shirshanka

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
