### ISSUE TITLE
connection reused 

### ISSUE THREAD

**Issue by longnsl1998** [linkedin/datahub#2070]
erorr when run by quickstart help me:
datahub-gms             | 2021/01/26 08:30:47 Problem with dial: dial tcp 172.26.0.5:3309: connect: connection refused. Sleeping 1s
datahub-gms             | 2021/01/26 08:30:48 Problem with dial: dial tcp 172.26.0.5:3309: connect: connection refused. Sleeping 1s
datahub-gms             | 2021/01/26 08:30:49 Problem with dial: dial tcp 172.26.0.5:3309: connect: connection refused. Sleeping 1s

**Comment by jjoyce0510** [comment]
Please keep waiting until all containers are up and running. At that point, this error should go away.

Please confirm if this solves it @longnsl1998

**Comment by longnsl1998** [comment]
> Please keep waiting until all containers are up and running. At that point, this error should go away.
> 
> Please confirm if this solves it @longnsl1998

Tks
