### ISSUE TITLE
failed to "run pip install --user -r common.txt -r mysql_etl.txt"

### ISSUE THREAD

**Issue by atlantisor** [linkedin/datahub#2079]
**Describe the bug**
when Ingest metadata from SQL-based data systems to DataHub, according to README.md, it's failed to "run pip install --user -r common.txt -r mysql_etl.txt".
ERROR: Cannot install avro-python3 and confluent-kafka[avro]==1.4.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested avro-python3
    confluent-kafka[avro] 1.4.0 depends on avro-python3==1.9.2.1; python_version > "3.0" and extra == "avro"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**To Reproduce**
1. cd "metadata-ingestion/sql-etl"
2. run pip install --user -r common.txt -r mysql_etl.txt
3. See error
ERROR: Cannot install avro-python3 and confluent-kafka[avro]==1.4.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested avro-python3
    confluent-kafka[avro] 1.4.0 depends on avro-python3==1.9.2.1; python_version > "3.0" and extra == "avro"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Expected behavior**
related python modules are installed.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by atlantisor** [comment]
it's one fixing solution as below:
1. edit the file /metadata-ingestion/sql-etl/common.txt and then
change 
confluent-kafka[avro]==1.4.0 
as 
confluent-kafka[avro]

in addition, if remove the specified version(1.8.2) of avro-python3 on common.txt, it will cause the following error when run "python mysql_etl.py".
TypeError: Object of type 'mappingproxy' is not JSON serializable

**Comment by hsheth2** [comment]
As per https://github.com/confluentinc/confluent-kafka-python/issues/610, it seems we have a hard dependency on avro-python3 version 1.8.2. 

I think we should loosen the confluent-kafka[avro] requirement to `>=1.5`, which should allow everything the dependencies to be resolved by pip.

**Comment by hsheth2** [comment]
@atlantisor can you let me know if this fixes the issue for you?

**Comment by atlantisor** [comment]
> it's still not working. as i mentioned above, one fixing way to remove package versions to allow pip attempt to solve the dependency conflict.
>pip install --user -r common.txt -r mysql_etl.txt
Requirement already satisfied: avro-python3==1.8.2 in /root/.local/lib/python3.7/site-packages (from -r common.txt (line 1)) (1.8.2)
Collecting confluent-kafka[avro]>=1.5
  Using cached confluent_kafka-1.5.0-cp37-cp37m-manylinux1_x86_64.whl (8.1 MB)
Requirement already satisfied: SQLAlchemy==1.3.17 in /root/.local/lib/python3.7/site-packages (from -r common.txt (line 5)) (1.3.17)
Requirement already satisfied: PyMySQL==0.9.3 in /root/.local/lib/python3.7/site-packages (from -r mysql_etl.txt (line 1)) (0.9.3)
INFO: pip is looking at multiple versions of sqlalchemy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pymysql to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of avro-python3 to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install avro-python3==1.8.2 and confluent-kafka[avro]==1.5.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested avro-python3==1.8.2
    confluent-kafka[avro] 1.5.0 depends on avro-python3==1.10.0; python_version > "3.0" and extra == "avro"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

> @atlantisor can you let me know if this fixes the issue for you?
