### ISSUE TITLE
Graphical tool for viewing & editing data models

### ISSUE THREAD

**Issue by pedro93** [linkedin/datahub#2080]
**Is your feature request related to a problem? Please describe.**
To define a data model for DataHub it is up to the developer to write down the pegasus files for every [entity](https://github.com/linkedin/datahub/tree/master/metadata-models/src/main/pegasus/com/linkedin/metadata/entity), [relationship](https://github.com/linkedin/datahub/tree/master/metadata-models/src/main/pegasus/com/linkedin/metadata/relationship) and [aspect](https://github.com/linkedin/datahub/tree/master/metadata-models/src/main/pegasus/com/linkedin/metadata/aspect) in pdl.
I.e: As seen [here](https://github.com/linkedin/datahub/tree/master/metadata-models/src/main/pegasus/com/linkedin/metadata/relationship) for the relationships defined in the [out-of-the box data model](https://github.com/linkedin/datahub/blob/master/docs/what/entity.md).

This is a manual process, spanning multiple files which makes it error-prone & hard to grok when trying to adapt or extend.

**Describe the solution you'd like**
A visual editing tool akin to UML diagram tools for DataHub's Data Model that serves 3 related purposes:
1. Understand the current data model a given DataHub deployment has.
2. Update/extend an existing model without having to directly edit pegasus files, which can be a significant number making it  hard to grok the underlying model.
3. Create Data Models from scratch and generate the associated pegasus records, making it an easier & less prone task.

**Describe alternatives you've considered**
An option could be: https://mermaid-js.github.io/mermaid/#/ integrated into an Admin UI.

Thank you for taking the time to read.

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
