### ISSUE TITLE
Ability to edit/maintain dataset information & relationships via UI

### ISSUE THREAD

**Issue by maggiehays** [linkedin/datahub#2114]
**Is your feature request related to a problem? Please describe.**
In our organization, dataset- & field-level descriptions are not centrally located. Depending on the team, it may exist in database comments, the team's codebase, wiki pages, Google Sheets, LookML, Slack messages... the list goes on. It's not realistic that we will be able to build a scraper to collect & maintain this across such disparate interfaces.

We want to be able to collect dataset- & field-level descriptions from stakeholders across the company, so we need a low barrier of entry for folks to contribute.

Additionally, building out scrapers to extract relationships from bespoke processes will be a very large undertaking; the ability to assign relationships manually would add a simple step for developers creating one-off jobs as part of their documentation. 

**Describe the solution you'd like**
Ability for users to edit/update the following via the UI:
* Dataset descriptions
* Field descriptions 
* Dataset relationships

Ideally, we would be able to see detail of who made the update & when so we can have an understanding of recency & who to contact if there are follow-up questions.

Longer-term, it would be great if we could alert owners of datasets when their assets are missing descriptions to enforce some level of accountability.

**Describe alternatives you've considered**
* Collaborate up with Engineering, Analytics, Data Science, Business Intelligence, Business Stakeholders to create team-specific (and skill-specific) processes so we can easily scrape their documentation in the long-run -- this would require an immense amount of stakeholder buy-in, team-specific training, and months of implementation.
* Building out a minimalist flask app, external to DataHub, for all stakeholders to manually insert records; ingest that metadata into DataHub

**Additional context**
Ability to edit/maintain lineage via UI may relate to this feature request https://github.com/linkedin/datahub/issues/2080

**Comment by jplaisted** [comment]
> It's not realistic that we will be able to build a scraper to collect & maintain this across such disparate interfaces.

:( This is an interesting use case, but I do wonder if this just makes an N+1 problem (https://xkcd.com/927/).

I feel like descriptions are totally ok here, even with the n+1 problem. My bigger concern is around allowing users to specify relationships. I think we want to be able to trust the lineage data we to have to a good degree, at LI we use it to help with data governance and GDPR. I feel like allowing users to manually edit things could reduce that trust, potentially. Maybe only allow adding relationships, not removing them (unless said relationship was manual to begin with)? This is just an immediate reaction though, I haven't thought it through too much. I'll let product people figure that out :)

> Longer-term, it would be great if we could alert owners of datasets when their assets are missing descriptions to enforce some level of accountability.

We might be able to lump this into "health". I'm not actually sure what goes into it today :p

**Comment by maggiehays** [comment]
Closing this out - Descriptions & documentation is well supported! Thank you, wonderful DataHub team :bestfriendsclub:
