### ISSUE TITLE
Make use of tagged releases

### ISSUE THREAD

**Issue by pedro93** [linkedin/datahub#2162]
**Describe the bug**
Right now there is no concept of releases for the docker images that are pushed to [docker hub](https://hub.docker.com/r/linkedin/datahub-ingestion). If a user wants to use a specific version they have to copy and maintain the source codebase on their side. 
This makes deployments inconsistent, brittle and a moving target.
The last datahub release was in December last year. In the meantime a significant number of changes have occurred both in the datahub codebase and it's component docker images.

**To Reproduce**
 - Deploy datahub (as docker-compose or k8s) today.
 - Wait 1 work day.
 - Redeploy.
 - Deployed code is different.

**Expected behavior**
Expected there to be a clearer, consistent way to deploy datahub and work on a particular version. This is tied to having a stable and periodic release process, not sure whether that is what is done in practice.

**Comment by jplaisted** [comment]
We do tag the docker images. We should probably have a more regular release cadence, but when we make a release they are tagged. You should be able to depend on these versions directly.

https://hub.docker.com/r/linkedin/datahub-frontend/tags?page=1&ordering=last_updated

**Comment by shirshanka** [comment]
Closing this, now that @dexter-mh-lee 's PR is in. 
Tags for dockerhub: https://hub.docker.com/r/linkedin/datahub-gms/tags?page=1&ordering=last_updated
You'll always have latest, and you'll additionally have the sha-short-hash

Tags for github docker: https://github.com/linkedin/datahub/packages/341715/versions
You'll always have latest, and you'll additionally have the sha-short-hash

**Comment by jplaisted** [comment]
Ah, ok, that makes sense. Thanks @shirshanka and @dexter-mh-lee !
