### ISSUE TITLE
Support data replay + data scan capabilities on metadata in DataHub

### ISSUE THREAD

**Issue by shirshanka** [linkedin/datahub#2170]
**Is your feature request related to a problem? Please describe.**
Data Replay is not trivial in DataHub.

> as reported by @liangjun-jiang  
> For example, in our case, we need to calculate the dataset's data quality. The data quality is calculated based on the aspects of a dataset. Since all datasets are already in datastore (MySQL, Neo4j and Elastic Search), we need to one way to pull data and do the calculation. Right now we are pulling data from MySQL using Python script. 
> 
> Another use case might be that, for example, I add a new property for an aspect, `number of schema fields`, and need ES index this property.  I need to replay all data to do so.
> 

There must be a better way. 

**Describe the solution you'd like**
Support a mechanism to "backfill" all derived indexes (ES + neo4j) without affecting the live stream. 
The same mechanism should support scanning the metadata snapshot for any other processing needs. 

**Solution ideas**
Could be based on k-v compaction in Kafka or driven off of the snapshot in MySQL or something else (see alternatives section). 

Bonus goals: 
* Use batch-API-s to speed up backfill instead of one-event-at-a-time writes. 

**Describe alternatives you've considered**

ETL the Kafka stream to the data lake or the data warehouse and run processing there

**Additional context**

**Comment by maggiehays** [comment]
@shirshanka is this still relevant?

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
