### ISSUE TITLE
Migrate master to Elasticsearch-7

### ISSUE THREAD

**Issue by shirshanka** [linkedin/datahub#2210]
Based on polling the community, no one seems to have hard production dependencies on Elastic-5. 
Filing this issue to migrate master to the elastic-7 changes that have already been tested out in production at LI. 

Some mitigation: 
1. We will create an es-5 branch, just in case someone wants to stay on it
2. We will provide a "use-at-your-own-risk" migration guide based on scripts that have worked for others

**Comment by jplaisted** [comment]
@dexter-mh-lee will create the migration guide, then we can swap master and the `es-7-support` branch.

**Comment by shirshanka** [comment]
Resolved via #2263
