### ISSUE TITLE
feat(react): Ability to configure custom menu options in the main dropdown menu

### ISSUE THREAD

**Issue by gabe-lyons** [linkedin/datahub#2211]
**Describe the solution you'd like**
The dropdown should be easily configurable the same way theming is done in react

**Describe alternatives you've considered**
Alternatively, we could make these menu items server-driven. However, that seems to add an extra, unnecessary layer of indirection since we don't imagine these will be dynamic.

**Comment by shirshanka** [comment]
Closed via #2250
