### ISSUE TITLE
Expose operational metrics 

### ISSUE THREAD

**Issue by pedro93** [linkedin/datahub#2214]
**Is your feature request related to a problem? Please describe.**
Once datahub is deployed, regardless of method (docker-compose, K8s, bare-bones, etc...) there is no way to obtain metrics & alerts related to the health of the deployed components. 
I.e: There is no endpoint I can poll to retrieve the health of GMS. Should it fail, I have no way to automate alerts to notify me.

**Describe the solution you'd like**
Given that DataHub is a mostly java project it should be relatively easy to expose [JMX metrics](https://www.appdynamics.com/blog/engineering/just-how-useful-is-jmx-monitoring/) such that they can then be consumed by a Prometheus instance or similar.
Ideally there should exist operational metrics for each component of Datahub with associated documentation on how to use it.

**Comment by shakti-garg** [comment]
Agree for need of exposing JMX/Prometheus(which is widely used nowadays) metrics. For MCE and MAE, it is pretty-much out-of-box using Spring actuator APIs. For GMS also, can also be done using JMX exporter.

In case you agree it to be relevant for datahub, happy to contribute to this feature.

**Comment by pedro93** [comment]
I think it is very relevant but I'm not a maintainer or contributor to the overall project. I simply created this issue as a request from a slack thread in the official channel.
