### ISSUE TITLE
AWS MSK - Error too many colons in address

### ISSUE THREAD

**Issue by fabiofilz** [linkedin/datahub#2225]
**Describe the bug**
We are migrating to AWS MSK and gms, mae and mce are returning the errors below:

The MSK has 3 brokers so the kafka.bootstrap.server needs to contain the list of all brokers.

2021/03/11 20:23:16 Problem with dial: dial tcp: address b-1.msk-cluster-pt.c2.kafka.eu-central-1.amazonaws.com:9094,b-3.msk-cluster-pt.c2.kafka.eu-central-1.amazonaws.com:9094,b-2.msk-cluster-pt.c2.kafka.eu-central-1.amazonaws.com:9094: too many colons in address. Sleeping 1s

It is also necessary to declare JAVA_OPTS with Djavax.net.ssl.trustStore and Djavax.net.ssl.trustStorePassword because of the TLS with MSK.

I tried to use extraEnvs (helm charts), but it is not working.

Can you please check it?

Thank you.
Fabio

**Comment by andfadeev** [comment]
Hi, I was able to connect to MSK recently, just used a single broker url: ex. b-1.msk-cluster-pt.c2.kafka.eu-central-1.amazonaws.com:9094
for certs there is envs like: SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_LOCATION, SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_LOCATION etc

**Comment by fabiofilz** [comment]
Hi @andfadeev,

Thanks for your suggestion.

I did in this way as well, but all requests are going to the same LB. It would be good to have more than one in case there is an issue with this LB.

Did you manage to use the extraEnvs? I tried to use extraEnvs (helm charts), but it is not working.

**Comment by dexter-mh-lee** [comment]
Hi I created a PR to fix the issue. The start script was not handling comma separated list of brokers well. Thanks for flagging!
