### ISSUE TITLE
elasticsearch failed to start

### ISSUE THREAD

**Issue by knightchong** [linkedin/datahub#2273]
elasticsearch failed to start

 kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:48Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:48Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"No living connections"}
datahub-gms               | 2021/03/22 05:38:48 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-mae-consumer      | 2021/03/22 05:38:49 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-gms               | 2021/03/22 05:38:49 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-mae-consumer      | 2021/03/22 05:38:50 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:50Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:50Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"No living connections"}
datahub-gms               | 2021/03/22 05:38:50 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-mae-consumer      | 2021/03/22 05:38:51 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-gms               | 2021/03/22 05:38:51 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-mae-consumer      | 2021/03/22 05:38:52 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-gms               | 2021/03/22 05:38:53 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:53Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:53Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"No living connections"}
datahub-mae-consumer      | 2021/03/22 05:38:54 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-gms               | 2021/03/22 05:38:54 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-mae-consumer      | 2021/03/22 05:38:55 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-gms               | 2021/03/22 05:38:55 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:55Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:55Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"No living connections"}
datahub-mae-consumer      | 2021/03/22 05:38:56 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-gms               | 2021/03/22 05:38:56 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-mae-consumer      | 2021/03/22 05:38:57 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
datahub-gms               | 2021/03/22 05:38:57 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:58Z","tags":["warning","elasticsearch","monitoring"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:58Z","tags":["warning","elasticsearch","monitoring"],"pid":6,"message":"No living connections"}
kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:58Z","tags":["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch due to Error: No Living connections error"}
kibana                    | {"type":"log","@timestamp":"2021-03-22T05:38:58Z","tags":["warning","elasticsearch","data"],"pid":6,"message":"Unable to revive connection: http://elasticsearch:9200/"}

**Comment by shirshanka** [comment]
@knightchong : Did you try the debugging guide here? https://datahubproject.io/docs/debugging

**Comment by knightchong** [comment]
The elasticsearch container did not start successfully
Below is the running container




CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                      NAMES

4478712fbe9f        linkedin/datahub-mce-consumer:latest          "/bin/sh -c /datahub…"   16 hours ago        Up 18 seconds       0.0.0.0:9090->9090/tcp                                     datahub-mce-consumer

7f5fa38270b5        linkedin/datahub-frontend-react:latest        "datahub-frontend/bi…"   16 hours ago        Up 18 seconds       0.0.0.0:9002->9002/tcp                                     datahub-frontend-react

f1f46bd7e4a3        linkedin/datahub-mae-consumer:latest          "/bin/sh -c /datahub…"   16 hours ago        Up 18 seconds       9090/tcp, 0.0.0.0:9091->9091/tcp                           datahub-mae-consumer

bbf8d66534fd        linkedin/datahub-gms:latest                   "/bin/sh -c /datahub…"   16 hours ago        Up 18 seconds       0.0.0.0:8616->8080/tcp                                     datahub-gms

0247c936aca1        landoop/kafka-topics-ui:0.9.4                 "/run.sh"                16 hours ago        Up 18 seconds       0.0.0.0:18000->8000/tcp                                    kafka-topics-ui

ae5d468754a0        landoop/schema-registry-ui:latest             "/run.sh"                16 hours ago        Up 19 seconds       0.0.0.0:8000->8000/tcp                                     schema-registry-ui

3ad4add4b2c2        confluentinc/cp-kafka-rest:5.4.0              "/etc/confluent/dock…"   16 hours ago        Up 19 seconds       0.0.0.0:8072->8082/tcp                                     kafka-rest-proxy

23681baf017f        confluentinc/cp-schema-registry:5.4.0         "/etc/confluent/dock…"   16 hours ago        Up 19 seconds       0.0.0.0:8011->8081/tcp                                     schema-registry

032f62d8043d        confluentinc/cp-kafka:5.4.0                   "/etc/confluent/dock…"   16 hours ago        Up 20 seconds       0.0.0.0:29092->29092/tcp, 0.0.0.0:9099->9092/tcp           broker

b6e292faab51        linkedin/datahub-elasticsearch-setup:latest   "dockerize /bin/sh -…"   16 hours ago        Up 20 seconds                                                                  elasticsearch-setup

1bc54cc9982d        kibana:7.9.3                                  "/usr/local/bin/dumb…"   16 hours ago        Up 20 seconds       0.0.0.0:5601->5601/tcp                                     kibana

71b99e439e66        neo4j:4.0.6                                   "/sbin/tini -g -- /d…"   16 hours ago        Up 20 seconds       0.0.0.0:7474->7474/tcp, 7473/tcp, 0.0.0.0:7687->7687/tcp   neo4j

1600855643cf        mysql:5.7                                     "docker-entrypoint.s…"   16 hours ago        Up 20 seconds       33060/tcp, 0.0.0.0:3377->3306/tcp                          mysql

5c40aeac313c        confluentinc/cp-zookeeper:5.4.0               "/etc/confluent/dock…"   16 hours ago        Up 20 seconds       2888/tcp, 3888/tcp, 0.0.0.0:2188->2181/tcp                 zookeeper







At 2021-03-23 07:52:41, "Shirshanka Das" ***@***.***> wrote:

@knightchong : Did you try the debugging guide here? https://datahubproject.io/docs/debugging

**Comment by knightchong** [comment]
> @knightchong : Did you try the debugging guide here? https://datahubproject.io/docs/debugging

The elasticsearch container did not start successfully
Below is the running container


CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                      NAMES

4478712fbe9f        linkedin/datahub-mce-consumer:latest          "/bin/sh -c /datahub…"   16 hours ago        Up 18 seconds       0.0.0.0:9090->9090/tcp                                     datahub-mce-consumer

7f5fa38270b5        linkedin/datahub-frontend-react:latest        "datahub-frontend/bi…"   16 hours ago        Up 18 seconds       0.0.0.0:9002->9002/tcp                                     datahub-frontend-react

f1f46bd7e4a3        linkedin/datahub-mae-consumer:latest          "/bin/sh -c /datahub…"   16 hours ago        Up 18 seconds       9090/tcp, 0.0.0.0:9091->9091/tcp                           datahub-mae-consumer

bbf8d66534fd        linkedin/datahub-gms:latest                   "/bin/sh -c /datahub…"   16 hours ago        Up 18 seconds       0.0.0.0:8616->8080/tcp                                     datahub-gms

0247c936aca1        landoop/kafka-topics-ui:0.9.4                 "/run.sh"                16 hours ago        Up 18 seconds       0.0.0.0:18000->8000/tcp                                    kafka-topics-ui

ae5d468754a0        landoop/schema-registry-ui:latest             "/run.sh"                16 hours ago        Up 19 seconds       0.0.0.0:8000->8000/tcp                                     schema-registry-ui

3ad4add4b2c2        confluentinc/cp-kafka-rest:5.4.0              "/etc/confluent/dock…"   16 hours ago        Up 19 seconds       0.0.0.0:8072->8082/tcp                                     kafka-rest-proxy

23681baf017f        confluentinc/cp-schema-registry:5.4.0         "/etc/confluent/dock…"   16 hours ago        Up 19 seconds       0.0.0.0:8011->8081/tcp                                     schema-registry

032f62d8043d        confluentinc/cp-kafka:5.4.0                   "/etc/confluent/dock…"   16 hours ago        Up 20 seconds       0.0.0.0:29092->29092/tcp, 0.0.0.0:9099->9092/tcp           broker

b6e292faab51        linkedin/datahub-elasticsearch-setup:latest   "dockerize /bin/sh -…"   16 hours ago        Up 20 seconds                                                                  elasticsearch-setup

1bc54cc9982d        kibana:7.9.3                                  "/usr/local/bin/dumb…"   16 hours ago        Up 20 seconds       0.0.0.0:5601->5601/tcp                                     kibana

71b99e439e66        neo4j:4.0.6                                   "/sbin/tini -g -- /d…"   16 hours ago        Up 20 seconds       0.0.0.0:7474->7474/tcp, 7473/tcp, 0.0.0.0:7687->7687/tcp   neo4j

1600855643cf        mysql:5.7                                     "docker-entrypoint.s…"   16 hours ago        Up 20 seconds       33060/tcp, 0.0.0.0:3377->3306/tcp                          mysql

5c40aeac313c        confluentinc/cp-zookeeper:5.4.0               "/etc/confluent/dock…"   16 hours ago        Up 20 seconds       2888/tcp, 3888/tcp, 0.0.0.0:2188->2181/tcp                 zookeeper

**Comment by jjoyce0510** [comment]
Please try to bump your Docker settings to permit 8GB of ram... If the elastic container doesn't have enough it will have trouble starting. Here are my Docker resource settings for reference: 

<img width="1246" alt="Screen Shot 2021-03-23 at 7 35 15 AM" src="https://user-images.githubusercontent.com/17549204/112163555-63343880-8baa-11eb-9d8d-bef02600ed76.png">

**Comment by tekumara** [comment]
Same issue here. My elasticsearch container logs when running with 6GB RAM:

```
elasticsearch             | Exception in thread "main" java.nio.file.FileSystemException: /tmp/elasticsearch-7193571174037736422: No space left on device
elasticsearch             | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
elasticsearch             | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
elasticsearch             | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
elasticsearch             | 	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:388)
elasticsearch             | 	at java.base/java.nio.file.Files.createDirectory(Files.java:694)
elasticsearch             | 	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:135)
elasticsearch             | 	at java.base/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:172)
elasticsearch             | 	at java.base/java.nio.file.Files.createTempDirectory(Files.java:1011)
elasticsearch             | 	at org.elasticsearch.tools.launchers.Launchers.createTempDirectory(Launchers.java:66)
elasticsearch             | 	at org.elasticsearch.tools.launchers.TempDirectory.main(TempDirectory.java:54)
elasticsearch exited with code 1
```

So I bumped up to 8GB RAM and now see:

```
java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes/0/node.lock
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:181)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:125)
	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)
	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)
	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:216)
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:271)
	at org.elasticsearch.node.Node.<init>(Node.java:344)
	at org.elasticsearch.node.Node.<init>(Node.java:277)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/docker-cluster.log
```

**Comment by tekumara** [comment]
Here are the volume mounts on my container (I'm running on macOS):
```
docker inspect elasticsearch | jq '.[0].Mounts[]'
{
  "Type": "volume",
  "Name": "datahub_esdata",
  "Source": "/var/lib/docker/volumes/datahub_esdata/_data",
  "Destination": "/usr/share/elasticsearch/data",
  "Driver": "local",
  "Mode": "rw",
  "RW": true,
  "Propagation": ""
}
```

**Comment by vlavorini** [comment]
Same issue here. Ram topped to 10 GB, swap to 2.5 GB, Docker on a mac.

    2021/04/23 12:36:27 Waiting for: http://elasticsearch:9200

    2021/04/23 12:36:27 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s

    2021/04/23 12:36:28 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if you need additional support!
