### ISSUE TITLE
Hive metadata does not display comments

### ISSUE THREAD

**Issue by knightchong** [linkedin/datahub#2281]
Hive metadata does not display comments

![image](https://user-images.githubusercontent.com/38711439/112097909-d5714100-8bdb-11eb-969a-4b18f0a932e2.png)

**Comment by jjoyce0510** [comment]
Hi @knightchong! A couple questions:

1. Are you ingesting from Hive using the ingestion framework? 
2. Which metadata would you expect to show in the description? I'm assuming the Hive column comments? (Result of "describe <tablename>")

**Comment by knightchong** [comment]
hi @jjoyce0510 
1.Yes, I use ingestion framework to import metadata into datahub,But the comment of the hive table is not shown in the description

2.The comment of the hive table is not displayed here

![image](https://user-images.githubusercontent.com/38711439/112242370-afed4180-8c86-11eb-9acd-4c1fe29fe009.png)

![image](https://user-images.githubusercontent.com/38711439/112242555-0b1f3400-8c87-11eb-8d73-d033d0e04125.png)

![image](https://user-images.githubusercontent.com/38711439/112242645-3e61c300-8c87-11eb-9c2e-f0fad74b7a4f.png)

**Comment by hsheth2** [comment]
This seems like an issue in the underlying `PyHive` library. Specifically, it's not populating the "comment" field: https://github.com/dropbox/PyHive/blob/master/pyhive/sqlalchemy_hive.py#L326.

**Comment by josh7** [comment]
I meet the same problem.Do you get the solution? Thanks!
@hsheth2 @knightchong @jjoyce0510

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if you continue facing this issue!
