### ISSUE TITLE
how to import metadata into datahub except ingestion method

### ISSUE THREAD

**Issue by knightchong** [linkedin/datahub#2292]
hi everyone
Now I have a question to ask everyone, how to import metadata into datahub except ingestion method,Thanks everyone for helping

**Comment by hsheth2** [comment]
Hi @knightchong! You can use the emitter APIs to push metadata into datahub - there’s a bit of documentation here: https://datahubproject.io/docs/metadata-ingestion#using-as-a-library.

**Comment by shirshanka** [comment]
Hi @knightchong did that resolve your question?

**Comment by shirshanka** [comment]
Resolving this question since I believe this was answered.
