### ISSUE TITLE
How to solve abnormal datahub-gms startup

### ISSUE THREAD

**Issue by knightchong** [linkedin/datahub#2293]
datahub-gms startup is abnormal

![image](https://user-images.githubusercontent.com/38711439/112263230-eee0be80-8ca9-11eb-8ff2-5602a3f11f10.png)

**Comment by hsheth2** [comment]
This should be fixed by #2291. Let me know if the issue persists.

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if you need additional support!
