### ISSUE TITLE
Tags applied to schema fields are not indexed

### ISSUE THREAD

**Issue by shirshanka** [linkedin/datahub#2311]
Reporting on behalf of a community member. 

**Describe the bug**
I was trying to use the latest tagging feature introduced in v7. Wanted to check whether the tag indexing is done both on the dataset level as well as on the attribute level?
I applied the same tag on both dataset and attribute. But when I searched with tag filter, it returned just the dataset linked to it. This states the indexing happened just on the dataset level and not on attribute. Is my understanding correct?

**To Reproduce**
1. Add a tag to a schema field on a dataset
2. Search for the tag
3. Notice that dataset is not returned in list of results

**Expected behavior**
Datasets with their fields tagged should be searchable through the tag. 

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/906477/112937252-2f8e6c80-90dc-11eb-8316-3aa83d0be9c9.png)
![image (1)](https://user-images.githubusercontent.com/906477/112937253-30270300-90dc-11eb-9397-7f7a1b814219.png)

**Comment by gabe-lyons** [comment]
Solved!

**Comment by shirshanka** [comment]
fixed via #2491
