### ISSUE TITLE
data-source-onboarding.md has broken links. Could not find ETL examples.

### ISSUE THREAD

**Issue by empiricalZone** [linkedin/datahub#2326]
**Describe the bug**
Most of the links to this page
https://github.com/linkedin/datahub/blob/master/docs/how/data-source-onboarding.md

are broken and I get 404 Page not found.

In particular, I could not find the linked examples to :

- hive-etl
- mysql-etl
- rdbms-etl

I could not find them at all in the master branch 
https://github.com/linkedin/datahub/tree/master/metadata-ingestion

Where are these ETL examples located?

**To Reproduce**
1. Go to 'https://github.com/linkedin/datahub/blob/master/docs/how/data-source-onboarding.md'
2. Click on any links. e.g. RDBMS link
3. See error '404 Page not found'

**Comment by hsheth2** [comment]
That doc is outdated - you're probably looking for this: https://datahubproject.io/docs/metadata-ingestion

I'll leave this issue open so we can update/remove the outdated doc
