### ISSUE TITLE
Support categorization of tags

### ISSUE THREAD

**Issue by gabe-lyons** [linkedin/datahub#2344]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to group tags together. For example: I may want to distinguish tags that indicate quality from tags that classify a data type. 

**Describe the solution you'd like**
Modelling:
- Create a tag category concept
- Add a property to tags that lets tags be linked to a tag category
- Index tag <> tag category relationships in the graph database

UX:
- when creating a tag, add an option to add a category to a tag or create a new category
- from a tag's page, option to add or change the category of a tag
- a tag's badge color is determined by its category
- the tag category linked to on a tags entity page
- a tag category page that lists all tags in that category

**Describe alternatives you've considered**
1) Allow categorization by tagging tags. We considered this because it simplifies the data model. However, it may cause additional confusion when a tag is used as both a tag category and a standard tag.

**Additional context**
Tags rfc: https://github.com/linkedin/datahub/pull/2112

**Comment by shtusha** [comment]
In my opinion tag categories/groups/types is something that users don't get to control via UX... they only get to assign them to tags in UX a list of categories should be predefined especially since categories are be mapped to styles in UI.

**Comment by maggiehays** [comment]
Hi folks,

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
