### ISSUE TITLE
Jobs.

### ISSUE THREAD

**Issue by Kipkurui-mutai** [linkedin/datahub#2354]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to apply for a job and I see someone has already been promoted but it is still on your open jobs list.

**Describe the solution you'd like**
Is it possible for you to just put open jobs and the ones people have been promoted or chosen for the job to be removed in real time.

**Describe alternatives you've considered**
Or you can group the jobs in real time and get the people  who are employed using Linkedin or promoted using Linkedin.

**Additional context**
![linkedin](https://user-images.githubusercontent.com/62174033/113820021-d8933200-9782-11eb-88e8-9886763103b1.PNG)

**Comment by maggiehays** [comment]
Hello! This repository does not have any influence on the linkedin.com user experience.
