### ISSUE TITLE
User Profile Editing

### ISSUE THREAD

**Issue by mhaley-miovision** [linkedin/datahub#2420]
**Is your feature request related to a problem? Please describe.**
The old emver UI allowed you to edit your own profile to add things like skills, teams and a summary of yourself to your profile. These are all nice features to have in a data catalogue, and makes it easier for the users to network with eachother.

**Describe the solution you'd like**
Creat an edit user profile page in the react frontend similar to what the ember UI had.

**Describe alternatives you've considered**
I currently run the ember and react UI side by side to test this functionality, but is not something I would want to have in our final deployment.

**Additional context**

**Comment by maggiehays** [comment]
Hi @mhaley-miovision!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
