### ISSUE TITLE
How can I add custom key-value pairs tags/metadata to each field in my dataset

### ISSUE THREAD

**Issue by yongyct** [linkedin/datahub#2428]
I have a requirement to add custom key-value pairs tags to each field in my dataset.

E.g. 
I have a BigQuery Table named (Users), with fields of (Name, ID, Phone Number, etc.)
I would like to tag each field with custom key-value pair tags (e.g. tag Phone Number with "{PII: true, Source_System: abc, Length: 100, Nullable: true, Last_Update_Date: somedate, Last_Update_By: someone, Last_Update_Value: Mobile Number}"

How can I achieve this in LinkedIn Datahub?

Thanks

**Comment by hsheth2** [comment]
Hi @yongyct - where do you expect those custom key-value pairs to come from? e.g. do you have an external service which can produce those annotations?

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if you need additional support!
