### ISSUE TITLE
Ingesting groups to LDAP source for metadata-ingestion.

### ISSUE THREAD

**Issue by adriaanslechten** [linkedin/datahub#2432]
We would like to ingest LDAP groups using the metadata-ingestion library.
For this, a small addition is needed to the code.

**Comment by jjoyce0510** [comment]
Hi @adriaanslechten. Thanks for raising this issue. Do you have any interest in contributing the changes to the Metadata Ingestion framework?

**Comment by hsheth2** [comment]
This was actually merged in #2434 - I guess we just forgot to close this issue

@shirshanka can you close this?

**Comment by adriaanslechten** [comment]
I think I mistagged the PR, so indeed should be closed.

**Comment by shirshanka** [comment]
Closed via #2434
