### ISSUE TITLE
How to setup datahub user account

### ISSUE THREAD

**Issue by akbar-septriyan-acn** [linkedin/datahub#2437]
Hi, how to create or setup a datahub account so that I can logged in?
![image](https://user-images.githubusercontent.com/80252898/115665577-af22fa80-a36d-11eb-9ebd-4705646ed7f9.png)
I couldn't find way to do it in datahub docs (https://datahubproject.io/docs/)

Thanks

**Comment by hsheth2** [comment]
The default username is `datahub` with any password (no password validation by default)

Are you following the quickstart guide https://datahubproject.io/docs/quickstart?

**Comment by akbar-septriyan-acn** [comment]
Hi @hsheth2,
I've tried to use `datahub` user but it still can't login.
Nope, I am not following the quickstart guide, actually I am deploying datahub in kubernetes based on this guide
https://github.com/linkedin/datahub/tree/master/contrib/kubernetes

**Comment by akbar-septriyan-acn** [comment]
Hi @hsheth2 
Here is the log from datahub-frontend pods 
![datahub-datahub-frontend](https://user-images.githubusercontent.com/80252898/115690300-1f8a4580-a387-11eb-97af-7917756eea85.png)
and here is the log from datahub-gms pods
![datahub-datahub-gms](https://user-images.githubusercontent.com/80252898/115690392-3761c980-a387-11eb-89cf-c501037e39d0.png)
Hope this help investigate and resolve the issue.
Thanks

**Comment by dexter-mh-lee** [comment]
Hi. Seems like pods didn't fully start up. Can you list the result of running `kubectl get pods` ? Also a full log from GMS would help! 

Feel free to join our slack to get more real-time support!

**Comment by akbar-septriyan-acn** [comment]
Hi @dexter-mh-lee, sure here is the list of pods
![Screen Shot 2021-04-23 at 10 14 44](https://user-images.githubusercontent.com/80252898/115814718-d0dcba00-a41f-11eb-8af4-22c823c1c263.png)
Please also find the full log from GMS attached
[datahub-gms.log](https://github.com/linkedin/datahub/files/6362560/datahub-gms.log)

Cool! Will check the slack, thank you :)
