### ISSUE TITLE
Add custom properties to Dashboards

### ISSUE THREAD

**Issue by thomasplarsson** [linkedin/datahub#2439]
**Is your feature request related to a problem? Please describe.**
Dashboard sources such as Qliksense applications often come with a set of key-value properties on them which would be nice to have in DataHub. This seems missing at the moment. 

**Describe the solution you'd like**
Support for custom properties, similar to how it exists for Datasets already.

**Describe alternatives you've considered**
Haven't really seen any alternatives.

**Additional context**

**Comment by thomasplarsson** [comment]
Fixed in https://github.com/linkedin/datahub/commit/851e00ba9fd3ddb8d703007a7c7db02db682d4fb

**Comment by thomasplarsson** [comment]
Re-opening since the UI is still lacking support for this feature.

**Comment by topwebtek7** [comment]
@shirshanka sure!

**Comment by RickardCardell** [comment]
@topwebtek7 @shirshanka  I got some code ready for a PR

**Comment by thomasplarsson** [comment]
Fixed in #2469
