### ISSUE TITLE
Public view of element in the catalog

### ISSUE THREAD

**Issue by vlavorini** [linkedin/datahub#2441]
**Is your feature request related to a problem? Please describe.**
As public institution, we also would like to publish some OpenData

**Describe the solution you'd like**
Allow people without authentication to see selected elements (a dataset, a dashboard, etc)

**Describe alternatives you've considered**
Another ad-hoc service.

Also, I see that there are other public institutions that are testing DataHub, maybe they are also would like such a feature.

Thanks+

**Comment by jjoyce0510** [comment]
Data sharing is an interesting use case!

In my mind, this depends on role-based access control, which is slotted on our Roadmap but has not yet been implemented. Once it is, we can continue to explore this use case!

John

**Comment by maggiehays** [comment]
Hi all!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
