### ISSUE TITLE
Entities with long lineage lists cause 414 errors in rest.li

### ISSUE THREAD

**Issue by gabe-lyons** [linkedin/datahub#2447]
**Describe the bug**
When an entity attempts to fetch its lineage, datahub-frontend issues a batch-get call to gms with each entity urn in the url.  If the entity has too many downstream or upstream dependencies, this URI can exceed rest.li's limit.

There is a way to send batch gets to rest.li via post:
https://linkedin.github.io/rest.li/Send-Rest_li-Request-Query-In-Request-Body

However, this does not seem to be supported by the generated rest.li client. We have opened an issue on rest.li's github to resolve this: https://github.com/linkedin/rest.li/issues/603

**To Reproduce**
1. Create an entity with 100+ downstream dependencies
2. Attempt to view that entity in the react app

**Expected behavior**
This should load as expected

**Comment by shirshanka** [comment]
Fixed by #2462
