### ISSUE TITLE
Render URL Link Found in Dataset Description

### ISSUE THREAD

**Issue by taufiqibrahim** [linkedin/datahub#2450]
**Is your feature request related to a problem? Please describe.**
Some dataset may have URLs inside their description. Such as shown in https://demo.datahubproject.io/dataset/urn:li:dataset:(urn:li:dataPlatform:bigquery,bigquery-public-data.covid19_google_mobility.mobility_report,PROD)/schema

**Describe the solution you'd like**
It would be super helpful if the front end able to render it automatically, so we don't need to copy-paste the URL.

**Describe alternatives you've considered**
Found a great library called Linkify https://soapbox.github.io/linkifyjs/

**Additional context**
I tried to copy and paste the description body to this link https://soapbox.github.io/linkifyjs/ and surprisingly it renders.
Tried to click on the generated link and it open new tab!

![Screenshot from 2021-04-24 19-36-19](https://user-images.githubusercontent.com/9822060/115959043-71240300-a534-11eb-9678-2d600a44ff8c.png)

**Comment by shirshanka** [comment]
Fixed in the new UX.
