### ISSUE TITLE
Cleanup datahub-web references

### ISSUE THREAD

**Issue by jjoyce0510** [linkedin/datahub#2452]
**Is your feature request related to a problem? Please describe.**
It's confusing that we have datahub-web and datahub-web-react. Let's remove reference to the deprecated Ember app.

**Describe the solution you'd like**
- remove datahub-web module
- revisit datahub-frontend to remove Ember endpoints
- update documentation in datahub-frontend to reflect changes

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by maggiehays** [comment]
@jjoyce0510 is this still relevant?

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
