### ISSUE TITLE
Can I customize the data model, and if so, how do I do it?

### ISSUE THREAD

**Issue by zqw961025** [linkedin/datahub#2454]

**Comment by jjoyce0510** [comment]
Hi there! How were you hoping to customize?

Were you looking to: 

1. Add new entities? For example, adding a "Stream" Entity 
2. Extend existing entities? For example, adding custom fields to the "Dataset" Entity

We are scoping work to make customization of the data model easier. Would love to understand more about your use case!

**Comment by zqw961025** [comment]
We might have such a metadata table, how do I define its model?

Name:         hive_table
TypeCategory: Entity
SuperTypes:   DataSet
Attributes:
    name:             string
    db:               hive_db
    owner:            string
    createTime:       date
    lastAccessTime:   date
    comment:          string
    retention:        int
    sd:               hive_storagedesc
    partitionKeys:    array<hive_column>
    aliases:          array<string>
    columns:          array<hive_column>
    parameters:       map<string>
    viewOriginalText: string
    viewExpandedText: string
    tableType:        string
    temporary:        boolean

**Comment by hsheth2** [comment]
For Hive, you probably want to map those fields to the types of DataHub's dataset entity. Our data model has support for a fair percentage of those fields, and the rest you can keep in the "customProperties" field.

Is there a reason you're looking to extend/customize the data model, versus simply using what's already defined?

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) for support!
