### ISSUE TITLE
Metadata ingestion from Trino

### ISSUE THREAD

**Issue by youngwookim** [linkedin/datahub#2482]
I'm trying to ingest metadata from Trino(f.k.a PrestoSQL) using sqlalchemy and [sqlalchemy-trino](https://pypi.org/project/sqlalchemy-trino/) but I got a `validation error` like following:
```
$ datahub ingest -c ./trino.yaml 
[2021-05-02 01:22:07,863] INFO     {datahub.entrypoints:68} - Using config: {'source': {'type': 'sqlalchemy', 'config': {'connect_uri': 'trino://localhost:18089/tpcds'}}, 'sink': {'type': 'datahub-rest', 'config': {'server': 'http://localhost:18080'}}}
1 validation error for SQLAlchemyGenericConfig
platform
  field required (type=value_error.missing)

```

Hope to find out how can I configure the field.

**Comment by shirshanka** [comment]
Should be resolved if you provide the value for the `platform` field. 

e.g. 
source:
   type: sqlalchemy
   config:
         platform: trino
         connect_uri: trino://localhost:18089/tpcds
...

**Comment by jjoyce0510** [comment]
Thanks for the quick reply @shirshanka. Can we close the issue?

**Comment by youngwookim** [comment]
@jjoyce0510 Will close this shortly.
