### ISSUE TITLE
Frontend: search on custom properties 

### ISSUE THREAD

**Issue by RickardCardell** [linkedin/datahub#2488]
Are there any plans to make custom properties searchable?

We would like to be able to find entities based their custom properties.
It may be useful to search both for the key of the custom property and a combination of key and value

One idea would be to add search-ability in the existing search box.

Example search on a high level:
 > Give me all entities that has a customProperties field named "fruit" with value "banana"

Some examples of custom property key-values are:
'owner_system_uid=foo-system'
'reload_interval=daily'
'compressionType=gzip'

A naive search text could be: "customproperty.fruit=banana"
However, it's a bit verbose, so maybe just 'fruit=banana'. Optionally a filter on the search page 'is_custom_property', to narrow it down to only custom-properties.

A possible useful option to avoid indexing uninteresting fields is to have a property on each custom property which can be set upon ingestion whether that property should be searchable or not.

**Comment by maggiehays** [comment]
Hi @RickardCardell!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
