### ISSUE TITLE
searching for nothing... displays error rather than 0 results

### ISSUE THREAD

**Issue by dougallaninthecloud** [linkedin/datahub#2490]
**Describe the bug**
if the user clicks the search box and then return it seems to run a search and return the following message 'Exception while fetching data (/search) : 'query' parameter cannot be null or empty'

**To Reproduce**
1. Go to Search bar
2. Hit Return
3. See error

**Expected behavior**
Id expect it to either show all results or 0 results..

**Screenshots**

![image](https://user-images.githubusercontent.com/31058686/117100667-a68fe280-adb7-11eb-8f9b-90287cd85486.png)

**Desktop (please complete the following information):**
 - OS:MacOs
 - Browser Safari
 - Version 14

**Additional context**

**Comment by jjoyce0510** [comment]
Thanks for reporting @dougallaninthecloud  - this is definitely a bug!

Let us take care of this. cc. @gabe-lyons @topwebtek7

**Comment by shirshanka** [comment]
Fixed via #2556

**Comment by dougallaninthecloud** [comment]
Nice to see both the fix and tests updated thanks :)
