### ISSUE TITLE
Managing access for users

### ISSUE THREAD

**Issue by iremi** [linkedin/datahub#2494]
Is it possible to limit access to certain datasets or data within the application?
For example I'd want for some users to only have access to the data in certain environments (env - "DEV", "EI", "PROD" or "CORP")

Is this functionality already supported?

**Comment by xiphl** [comment]
hi @iremi, I'm just a user on the Datahub Slack channel, but I asked this question a couple of days back and the answer is not at the moment, RBAC is on the development roadmap for this quarter Apr-Jun.

**Comment by shirshanka** [comment]
Thanks for responding @xiphl 
You are right!
@iremi : Our roadmap is here: https://datahubproject.io/docs/roadmap/
Do drop into our Slack space if you have any further questions at: https://slack.datahubproject.io

**Comment by iremi** [comment]
Thank you very much
