### ISSUE TITLE
Label edited descriptions clearly in the UI

### ISSUE THREAD

**Issue by gabe-lyons** [linkedin/datahub#2506]
**Is your feature request related to a problem? Please describe.**
If you see an edited description, the only way to know if it was edited or not is to click the edit icon and compare the current version with the original.

**Describe the solution you'd like**
We should append an _(edited)_ suffix to edited descriptions so that is obvious which descriptions have been edited and which are from the source.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by shirshanka** [comment]
Fixed via #2583
