### ISSUE TITLE
Highlight the column that was matched when arriving on Dataset page via column_name or column_description match

### ISSUE THREAD

**Issue by gabe-lyons** [linkedin/datahub#2507]
**Is your feature request related to a problem? Please describe.**
If I search for a column name or description, I will see entities in the results that have columns matching the column name or description. However, especially for large schemas, when I click into the result it may be difficult to find which column I was looking for.

**Describe the solution you'd like**
We should highlight the row representing the matched column in the schema table. In the case that the matched column has an edited and a non-edited description, we should display both. This way the user can quickly access all the information of the column without having to search for it.

**Describe alternatives you've considered**

**Additional context**

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
