### ISSUE TITLE
Json ingestion: including nested array information (without flattening)

### ISSUE THREAD

**Issue by iremi** [linkedin/datahub#2511]
I am ingesting json files which have nested arrays with additional information. Ingesting them only gives me the top level metadata. I want to know if it's possible to also include second level information from the arrays.

For example the following file:
```
{
	"Product": "Reporting Server",
	"ProductType": "Database/ Web application",
	"Description": "qwe",
	"Location": [{
		"Environment": "qwe",
		"Server": "qwe",
		"Database": "qwe",
		"Url": "https://qwe.com/Reports"
	}],
	"Roles": {
		"Team": "qwe",
		"Product Owner": ["qwe"],
		"IT Support": "qwe"
	},
...
```
is ingested to datahub like this 
![Capture](https://user-images.githubusercontent.com/25979063/117459230-75e0b200-af4b-11eb-9957-2c3cb0ad7072.PNG)

I also want to include second level information from the arrays (Location.Environment, Location.Server, Roles.Team,...) and have those display in Datahub.

In my case I have these json files in AWS S3, transforming them to AWS Glue with a crawler and ingesting the resulting table to Datahub.

Is it possible to include the nested data without first flattening the json data?
If it is possible to do it with a different supported source (doesn't have to be Glue) in a relatively simple way I'd appreciate the suggestions.

**Comment by iremi** [comment]
I have to do this with hundreds of files so I'd prefer to do it with an automated process. 
If there's not another way I can always flatten the files.

**Comment by jjoyce0510** [comment]
You'd likely want to write a utility that flattens JSON schemas automatically into the format display in the example above^ I agree you wouldn't want to do this manually. 

Does that seem feasible?

**Comment by iremi** [comment]
Yes, that's what I'm going to do.
