### ISSUE TITLE
Make sortable heading in 'Properties' by name

### ISSUE THREAD

**Issue by youngwookim** [linkedin/datahub#2537]
**Is your feature request related to a problem? Please describe.**
As of now, There is no sortable option in 'Datasets' > .... > 'Properties' by property's name.
It would be nice to have a sortable heading to 'Name'

**Describe the solution you'd like**
Add a sortable heading to 'Name'. i.e., ascending or descending toggle on 'Name'

**Comment by maggiehays** [comment]
Hi folks!

We are now managing feature requests through our new portal to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to reach out to me on DataHub Slack with any questions!
