### ISSUE TITLE
Is there a visualization for Field Mapping?

### ISSUE THREAD

**Issue by Light310** [linkedin/datahub#2551]
Good day!
Looks like field mapping feature is already merged in, I've managed to send some MCEs containing DatasetFieldMappingClass, but I can't see anything in the UI. 
Is there any visualization of field-level lineage?

**Comment by shirshanka** [comment]
@Light310 we don't have visualization of field-level lineage in the UI yet. Expect it to land in June / July.

**Comment by Light310** [comment]
> @Light310 we don't have visualization of field-level lineage in the UI yet. Expect it to land in June / July.

That's great! We're looking forward to this feature.
