### ISSUE TITLE
Is it possible to ingest s3 data with the cli

### ISSUE THREAD

**Issue by deichbrise** [linkedin/datahub#2569]
Hi, 

I am exploring datahub for usage in our company and wonder if it is possible to use a s3 sink with the datahub python cli. Would be very nice if it's possible :)

**Comment by shirshanka** [comment]
@deichbrise did you mean s3 source?

**Comment by maggiehays** [comment]
Please refer to S3 Source docs [here](https://datahubproject.io/docs/metadata-ingestion/source_docs/s3/).

This issue has been open for more than 3 months without activity so we will close it out for now. Feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if you need additional support!
