### ISSUE TITLE
Update base docker image

### ISSUE THREAD

**Issue by RickardCardell** [linkedin/datahub#2576]
We’ve noticed that curl in the base image ([openjdk:8-jre-alpine](https://hub.docker.com/layers/openjdk/library/openjdk/8-jre-alpine/images/sha256-f7a292bbb70c4ce57f7704cc03eb09e299de9da19013b084f138154421918cb4)) contains a vulnerability that we would like to be mitigated. However, the newest version of the base image is 2 years old so maybe time to switch out that one?

https://github.com/linkedin/datahub/blob/master/docker/datahub-frontend/Dockerfile#L4

**Comment by shirshanka** [comment]
@RickardCardell Looks like openjdk has moved away from publishing alpine images. Maybe we need to move to debian? (`openjdk:8-jre-buster` seems like the equivalent for that). Can you check if the `curl` in that image also has the vulnerability you are trying to avoid?

**Comment by RickardCardell** [comment]
Regarding using `openjdk:8-jre-buster`. OpenJDK doesn't seem to maintain their images very well. The bundled curl is an old version from 2019 having multiple vulnerabilities:

    > docker pull openjdk:8-jre-buster
    docker run -it openjdk:8-jre-buster /bin/bash -c "curl --version"
        curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 ...
        Release-Date: 2019-02-06

So it uses `7.64` while latest is `7.77`: https://curl.se/docs/vulnerabilities.html
Just updating curl is not an option either since the Debian installation is old.

**Comment by RickardCardell** [comment]
A better option in my opinion is to use an image from [Adoptium](https://adoptium.net/) (previously AdoptOpenDK) which are providing up to date images. The crux is that Adoptium is still in startup phase, so not sure if this is the right time to do this.

Regarding compatibility etc, the `openjdk:8-jre-buster` uses the java binaries from AdoptOpenDK, so not much of a choice there:

If we would go with Adoptium/AdoptOpenDK a suitable image is [adoptopenjdk/openjdk8:alpine-jre](https://hub.docker.com/layers/adoptopenjdk/openjdk8/alpine-jre/images/sha256-a5b0e97c5c04b696e8612e72831d4c7cc68958278e3f0e0dc3a51a7163f28cc6?context=explore). It would be simple to switch since it's also Alpine, but then again, will it be supported by Adoptium?

We solved the vulnerability in the short term by adding steps that updated the packages and lastly removed curl, since it couldn't be updated.

**Comment by RickardCardell** [comment]
Fixed in https://github.com/linkedin/datahub/pull/2746
