### ISSUE TITLE
Related entities module does not work when a tag has multiple words in its name

### ISSUE THREAD

**Issue by gabe-lyons** [linkedin/datahub#2588]
**Describe the bug**
See title

**To Reproduce**
1. Create a tag like "Some Tag"
2. Tag an entity with that tag
3. Visit that tags entity page- see its related entities module does not work as expected

**Expected behavior**
The related entity count should be correct

**Screenshots**
n/a

**Desktop (please complete the following information):**

**Additional context**

**Comment by RickardCardell** [comment]
Same problem when tag contains Elasticsearch's reserved characters, e.g colon or brackets

Example tags: 
- "urn:foobar"
- "[foo]bar"

**Comment by shirshanka** [comment]
Fixed via #2623 
@RickardCardell please re-open if this is still an issue. @gabe-lyons FYI.
