### ISSUE TITLE
Questions regarding installation and features

### ISSUE THREAD

**Issue by pranayrai** [linkedin/datahub#2608]
Hi,

I would like to know if:
1. There is a guide to host DataHub on a windows server?
2. Does DataHub have features to implement user roles, access and permissions?
3. Can the properties tab for datasets be modified to have a pre-configured schema, so that when a user uploads a new dataset, it is automatically synced up to that particular schema domain?

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if this is a recurring problem you're facing!
