### ISSUE TITLE
Analytics module doesn't support authenticated or encrypted Kafka connections

### ISSUE THREAD

**Issue by thomasplarsson** [linkedin/datahub#2611]
**Describe the bug**
The Datahub backend for the analytics module uses Kafka to track user events, but the Kafka producer cannot be configured with authentication at the moment. See https://github.com/linkedin/datahub/blob/master/datahub-frontend/app/react/controllers/TrackingController.java#L72

**To Reproduce**
N/A

**Expected behavior**
Authenticated and encrypted connections should be possible to use.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by jjoyce0510** [comment]
Thanks for raising this! Certainly an important one to get to.

**Comment by thomasplarsson** [comment]
It looks like encryption support was added in https://github.com/linkedin/datahub/commit/4d82ff8b62cf70dbc59677d48391b5e47bd7caf1 but no authentication support. Just wanted to make sure it isn't overlooked.
