### ISSUE TITLE
Syntax highlighting of raw schema

### ISSUE THREAD

**Issue by havramar** [linkedin/datahub#2613]
**Is your feature request related to a problem? Please describe.**
When `platformSchema` is provided for given source within MCE, user can click `Raw` button and see raw DDL.
![image](https://user-images.githubusercontent.com/3067172/119733680-2ae6fa00-be7a-11eb-81a5-14effef0591f.png)

**Describe the solution you'd like**
Would be great to see syntax highlighting of DDL. 

**Additional context**
Hard to tell if there is one easy solution for all source types and their related platform schemas but JSON and SQL would be a good starting point.

**Comment by maggiehays** [comment]
Hi @havramar!

We are now managing feature requests through our new portal to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to reach out to me on DataHub Slack with any questions!
