### ISSUE TITLE
datahub can't genarate lineage?

### ISSUE THREAD

**Issue by gwk-dot** [linkedin/datahub#2631]
question one: 
  datahub can supports dataset level lineage, I use an extensible Python-based metadata ingestion system for DataHub. but not dataset lineage, so I execute ` lineage_emitter_rest.py`  the file and can genarate lineage,is that right?  Is there any other way?

question two:
  Field Level Lineage can not be supported now ,is that right?  
 
I'm not sure I understand rightly. Hope to get reply, thank you.

**Comment by anthonyhungnguyen** [comment]
**First question:** There are two ways to generate data lineage

- Through a custom emitter like what you mentioned
- Through Airlfow's lineage backend [`Here`](https://datahubproject.io/docs/metadata-ingestion#using-datahubs-airflow-lineage-backend-recommended)

**Second question:** Currently, I don't see DataHub really support Field Level Lineage in the open-source version (might already be done in the Internal version)

**Comment by hsheth2** [comment]
To add on a bit:
- In addition to the Airflow lineage backend, the dbt and superset ingestion sources also automatically produce lineage information
- DataHub has already merged an RFC for field-level lineage (https://datahubproject.io/docs/rfc/active/1841-lineage/field_level_lineage/), and implementation work is ongoing.

**Comment by maggiehays** [comment]
Hi folks, our column-level lineage work is being tracked in our roadmap [here](https://feature-requests.datahubproject.io/roadmap/541); please refer to that post & we'll close out this issue in the meantime!

**Comment by gwk-dot** [comment]
ok,thanks



---Original---
From: "Maggie ***@***.***&gt;
Date: Wed, Jan 26, 2022 02:02 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [linkedin/datahub] datahub can't genarate lineage? (#2631)




 
Hi folks, our column-level lineage work is being tracked in our roadmap here; please refer to that post &amp; we'll close out this issue in the meantime!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
