### ISSUE TITLE
Analytics link not working

### ISSUE THREAD

**Issue by xiphl** [linkedin/datahub#2673]
**Describe the bug**
Clicking on the analytics[beta] link results in failure. 
`Caused by: org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=index_not_found_exception, reason=no such index [datahub_usage_event]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1892)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1869)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1626)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1069)
	at react.analytics.AnalyticsService.executeAndExtract(AnalyticsService.java:207)
`
Kibana also confirmed that there is no such index datahub_usage_event

**To Reproduce**
1. launch the quickstart
2. run the ingestion.sh from docker/ingestion
3. login as datahub
4. click around the site, then click on analytics link

**Expected behavior**
should see the analytics panel with dashboards.

**Comment by dexter-mh-lee** [comment]
Hi. Can you check whether elasticsearch-setup-job ran correctly? We have a change coming up soon to improve the quickstart experience so that this kind of issue is caught and fixed automatically!

**Comment by xiphl** [comment]
this is what i have in docker logs:
`creating index chartdocument
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4196  100    72  100  4124     11    649  0:00:06  0:00:06 --:--:--    17
{"acknowledged":true,"shards_acknowledged":true,"index":"chartdocument"}
creating index corpuserinfodocument
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2470  100    79  100  2391     95   2898 --:--:-- --:--:-- --:--:--  2993
{"acknowledged":true,"shards_acknowledged":true,"index":"corpuserinfodocument"}
creating index dashboarddocument
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4099  100    76  100  4023     63   3369  0:00:01  0:00:01 --:--:--  3430
{"acknowledged":true,"shards_acknowledged":true,"index":"dashboarddocument"}
creating index datajobdocument
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4680  100    74  100  4606     91   5686 --:--:-- --:--:-- --:--:--  5777
{"acknowledged":true,"shards_acknowledged":true,"index":"datajobdocument"}
creating index dataflowdocument
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4854  100    75  100  4779    111   7090 --:--:-- --:--:-- --:--:--  7191
{"acknowledged":true,"shards_acknowledged":true,"index":"dataflowdocument"}
creating index dataprocessdocument
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5120  100    78  100  5042    123   7952 --:--:-- --:--:-- --:--:--  8075
{"acknowledged":true,"shards_acknowledged":true,"index":"dataprocessdocument"}
creating index datasetdocument
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7344  100    74  100  7270    126  12448 --:--:-- --:--:-- --:--:-- 12575
{"acknowledged":true,"shards_acknowledged":true,"index":"datasetdocument"}
creating index mlmodeldocument
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6011  100    74  100  5937    110   8847 --:--:-- --:--:-- --:--:--  8971
{"acknowledged":true,"shards_acknowledged":true,"index":"mlmodeldocument"}
creating index tagdocument
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1787  100    70  100  1717    107   2641 --:--:-- --:--:-- --:--:--  2745
{"acknowledged":true,"shards_acknowledged":true,"index":"tagdocument"}
creating index glossaryterminfodocument
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2563  100    83  100  2480    140   4210 --:--:-- --:--:-- --:--:--  4344
{"acknowledged":true,"shards_acknowledged":true,"index":"glossaryterminfodocument"}
creating index glossarynodeinfodocument
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1636  100    83  100  1553    163   3057 --:--:-- --:--:-- --:--:--  3220
{"acknowledged":true,"shards_acknowledged":true,"index":"glossarynodeinfodocument"}
creating datahub_usage_event_policy
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   271  100    21  100   250    106   1262 --:--:-- --:--:-- --:--:--  1368
{"acknowledged":true}
creating datahub_usage_event_index_template
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   541  100    21  100   520    106   2639 --:--:-- --:--:-- --:--:--  2732
2021/06/10 01:23:05 Command finished successfully.
2021/06/10 01:23:05 Command finished successfully.
`

**Comment by xiphl** [comment]
this bug seems to be resolved in v0.8.3. I'll close it.
