### ISSUE TITLE
Indexing property and description values

### ISSUE THREAD

**Issue by iremi** [linkedin/datahub#2682]
Hello, I am wondering if it is possible to enable that property names and property values are indexed.

I'd like to use the applications main search bar to find ingested property and description data.
e.g. from the sample data:
If I search for "prop1" or "fakeprop", I want it to find `SampleKafkaDataset`.

**Comment by maggiehays** [comment]
Hello! We have this request captured in our feature request portal [here](https://feature-requests.datahubproject.io/b/User-Experience/p/index-properties-for-search-ability-to-search-on-property-name-description-separately); if this is still something you are interested in, please upvote/subscribe to that post so we can gauge community interest! We'll close out this issue in the meantime.
