### ISSUE TITLE
Searching through ingested data

### ISSUE THREAD

**Issue by iremi** [linkedin/datahub#2683]
Is it possible to search through all of the ingested data? 
I'm assuming it's possible with neo4j, elasticsearch, zookeeper or something else.

I want to be able to have an overview of all of the data I ingested in json or other format and access it with a script language.
Is this supported?

**Comment by hsheth2** [comment]
Yep there's a few ways to do this. 

We discussed it in decent depth in this Slack thread: https://datahubspace.slack.com/archives/CUMUWQU66/p1623825264291900.

**Comment by iremi** [comment]
Thank you for the answer
