### ISSUE TITLE
Add in-UI User Survey

### ISSUE THREAD

**Issue by MelindaCardenas** [linkedin/datahub#2685]
Is your feature request related to a problem? Please describe.
Yes, as of now, it doesn’t seem as if there’s any easy way to get user feedback. Adding a user experience survey to DataHub would enable the collection of feedback from users and thus, give insight into the efficacy of DataHub for our respective organizations.  

Describe the solution you'd like
NYT DGE proposes creating a user experience survey which asks users 
1) How’s your experience so far with DataHub? 
2) Were you able to find what you were looking for?
3) Leave us any feedback
[See Figma design here](https://www.figma.com/file/slcjP197EJUthWM5q7od3n/DataHub-Survey?node-id=0%3A1)
The first iteration of this survey would appear at random times, although in the future we plan to use cookies to more strategically time the appearance of the survey. Cookies could be used to keep track of how many times a user has seen the survey, note whether users don’t want to be asked to answer at all, or to strategize what questions to ask.  

Describe alternatives you've considered
Instead of an in UI pop up survey, there could also be a feedback section of DataHub. We are also considering having a persistent tab available, so users can always have the option to click on the tab to take the survey. 

Additional context
Survey answers are planned to be saved in MySQL. The survey questions will be configurable so that different questions of the same type (ie. yes/no, free form, rate on a scale) can be easily swapped out in the frontend. 

Whatever feedback you have is appreciated!

**Comment by shirshanka** [comment]
Google doc for RFC is here: https://docs.google.com/document/d/19XZOM7hGV03ruwhzcFA0wN-58is6Lq5-Go9Kalt_HpU/

**Comment by aseembansal-gogo** [comment]
To see the results we will be querying the database directly for now?

**Comment by MelindaCardenas** [comment]
@aseembansal-gogo Yes! Unfortunately, I don't think I'll have enough time to show results in the Analytics section (I'm doing this project as part of an internship), but maybe this is something someone can add in the future.

**Comment by maggiehays** [comment]
Hi folks! 

We are now managing feature requests through our new portal to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to reach out to me on DataHub Slack with any questions!
