### ISSUE TITLE
Browse aspect versions for /entities Rest.LI endpoint 

### ISSUE THREAD

**Issue by amorskoy** [linkedin/datahub#2696]
**Is your feature request related to a problem? Please describe.**
# Story 1
As an API user, given I have  entity URN and aspect name, I want to have posibility to:

- get a list of aspect versions
- get a specific version of aspect

# Story 2
As an API user, given I have entity URN, I want to get history of entity changes across all snapshots. Something like:
```
 select urn,aspect,version,metadata,createdon from metadata_aspect_v2 order by createdon;
``` 

**Describe the solution you'd like**
I see no easy way to retrieve non-latest aspects while it is useful for a lot of needs

**Comment by shirshanka** [comment]
@gabe-lyons : FYI since your latest PR might have addressed this.

**Comment by maggiehays** [comment]
Hi folks!

We are now managing feature requests through our new portal to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to reach out to me on DataHub Slack with any questions!
