### ISSUE TITLE
Datahub User Authentication

### ISSUE THREAD

**Issue by andrzpg12** [linkedin/datahub#2720]
**Is your feature request related to a problem? Please describe.**
When we launched datahub in kubernetes cluster and prompt the login, any string can access. I mean, there is no validation of users or OAuth system to ensure who is accessing datahub.

**Describe the solution you'd like**
An OAuth support or mechanism to authenticate users

**Describe alternatives you've considered**
Google LDAP, OAuth Proxy

**Comment by jjoyce0510** [comment]
Hi @andrzpg12. Thanks for raising! 

Here are the docs pertaining the integrating our frontend UI service (datahub-frontend) with an OIDC Identity Provider: https://datahubproject.io/docs/how/configure-oidc-react

Please take a look and let me know if you have questions! Note that currently OIDC is the only protocol we officially support.
