### ISSUE TITLE
All action methods (specified via 'action' in URI) must be submitted as a POST (was GET)

### ISSUE THREAD

**Issue by zcw5116** [linkedin/datahub#2724]
From Doc: https://datahubproject.io/docs/metadata-modeling/metadata-model#primary-key-query

When I submit http request:
http://192.168.118.200:8080/entities?action=get&urn=urn:li:dataPlatform:mysql

An Error throw:
`
 "exceptionClass": "com.linkedin.restli.server.RestLiServiceException",
  "stackTrace": "com.linkedin.restli.server.RestLiServiceException [HTTP Status:400]: All action methods (specified via 'action' in URI) must be submitted as a POST (was GET)\n\tat com.linkedin.restli.server.RestLiServiceException.fromThrowable(RestLiServiceException.java:315)\n\tat com.linkedin.restli.server.BaseRestLiServer.buildPreRoutingError(BaseRestLiServer.java:158)\n\tat com.linkedin.restli.server.RestRestLiServer.buildPreRoutingRestException(RestRestLiServer.java:203)\n\tat com.linkedin.restli.server.RestRestLiServer.handleResourceRequest(RestRestLiServer.java:177)\n\tat com.linkedin.restli.server.RestRestLiServer.doHandleRequest(RestRestLiServer.java:164)\n\tat com.linkedin.restli.server.RestRestLiServer.handleRequest(RestRestLiServer.java:120)\n\tat com.linkedin.restli.server.RestLiServer.handleRequest(RestLiServer.java:132)\n\tat com.linkedin.restli.server.DelegatingTransportDispatcher.handleRestRequest(DelegatingTransportDispatcher.java:70)\n\tat
...

om.linkedin.restli.server.RestRestLiServer.handleResourceRequest(RestRestLiServer.java:173)\n\t... 62 more\n",
  "message": "All action methods (specified via 'action' in URI) must be submitted as a POST (was GET)",
  "status": 400
`

I'm using Docker.

**Comment by shirshanka** [comment]
@jjoyce0510 FYI

**Comment by jjoyce0510** [comment]
Unfortunately this is just an outdated doc issue. Fixing

**Comment by jjoyce0510** [comment]
Docs have been updated to reflect the latest. @shirshanka please close!
