### ISSUE TITLE
MongoDB logo not shown on UI

### ISSUE THREAD

**Issue by anthonyhungnguyen** [linkedin/datahub#2738]
**Describe the bug**
No Mongo logo appears when browsing datasets on datahub-frontend

**To Reproduce**
1. Ingest some mongo datasets
2. Goto Datahub's Frontend
3. Pick random Mongo dataset

**Expected behavior**
Mongo logo should appear like other type of data sources

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: Latest

**Comment by remisalmon** [comment]
I am having the same issue with Snowflake in DataHub v0.8.3.

This is showing instead:
<img width="71" alt="image" src="https://user-images.githubusercontent.com/26257211/123181289-4a0d8300-d44a-11eb-8d3a-4c4c365f3092.png">

**Comment by kevinhu** [comment]
Thanks for filing this! Which versions of DataHub and the CLI are you running on?

**Comment by anthonyhungnguyen** [comment]
I'm running on the Datahub 0.8.3. Currently still don't see the logo appear for Mongo (maybe other datasources) @remisalmon

**Comment by kevinhu** [comment]
@anthonyhungnguyen I've located the source of the bug for Mongo – turns out we had coded our DataPlatform as `mongodb` instead of `mongo` 😅 . Will open a PR right now to fix!

@remisalmon Can you elaborate on where you're seeing the icon for Snowflake?

**Comment by anthonyhungnguyen** [comment]
@kevinhu  Do I have to ingest schemas again with the right keyword?

**Comment by kevinhu** [comment]
@anthonyhungnguyen We've updated the DataPlatform schemas to fix the bug – can you try ingesting [data_platforms.json](https://github.com/linkedin/datahub/blob/master/metadata-ingestion/examples/mce_files/data_platforms.json) and then restart to clear any caches?

**Comment by remisalmon** [comment]
@kevinhu I opened another issue about the Snowflake logo since it seems unrelated to this one: https://github.com/linkedin/datahub/issues/2795

**Comment by shirshanka** [comment]
Closing this one since it has been fixed via #2783 
Please reopen if this is still a problem.
