### ISSUE TITLE
Missing task linkages in UI for DAGs imported using LineageBackend

### ISSUE THREAD

**Issue by egzj** [linkedin/datahub#2755]
**Describe the bug**
Using [LineageBackend](https://datahubproject.io/docs/metadata-ingestion/#using-datahubs-airflow-lineage-backend-recommended) which automates the sending of Airflow's DAG info to DataHub, results in missing task linkages under the 'task' section in the UI. However, the tasks could be found individually using search.

**Missing task linkages**
![image](https://user-images.githubusercontent.com/30767127/123206666-aaee9700-d4ee-11eb-8634-3a9cc5a5683d.png)
**DAG's tasks in Airflow**
![image](https://user-images.githubusercontent.com/30767127/123206583-87c3e780-d4ee-11eb-9b08-b0caf103dcdb.png)
**DAG's task could be found individually**
![image](https://user-images.githubusercontent.com/30767127/123206815-edb06f00-d4ee-11eb-8ec9-7511d030119a.png)

**To Reproduce**
1. Enable DataHub LineageBackend
2. Run a DAG
3. Go to UI
4. See missing tasks under the DAG

**Expected behavior**
Using [bootstrap_mce.json](https://github.com/linkedin/datahub/blob/master/metadata-ingestion/examples/mce_files/bootstrap_mce.json), which imports the DAG **dag_abc**, had its tasks appear under 'task' section, but not in the case of DAGs which are imported using LineageBackend
![image](https://user-images.githubusercontent.com/30767127/123200868-2bf46100-d4e4-11eb-9116-bf9db054d2fc.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome

**Additional context**

missing entities from my DAG **D_DATA_CATALOG_DATAHUB** 
![Screenshot 2021-06-24 at 1 29 15 PM](https://user-images.githubusercontent.com/30767127/123207852-9d3a1100-d4f0-11eb-9ee8-d42fc558ec95.png)

as opposed to the sample DAG **dag_abc**
![image](https://user-images.githubusercontent.com/30767127/123208913-754bad00-d4f2-11eb-8dfd-37d0bd4bcf85.png)

Is anyone facing the same issue?

**Comment by gabe-lyons** [comment]
Hey @egzj - thank you for raising this. I suspect this is related to some changes we just reverted here: https://github.com/linkedin/datahub/pull/2754.

Trying pulling from master now and see if things are resolved.

**Comment by egzj** [comment]
Hi @gabe-lyons, the DAG's tasks are now appearing after I pulled the latest update. Thanks!
