### ISSUE TITLE
Field Columns not rendered in the same order as stored schema

### ISSUE THREAD

**Issue by xiphl** [linkedin/datahub#2756]
**Describe the bug**
Referring to a example in the bootstrap_mce, (urn:li:dataPlatform:kafka,SampleKafkaDataset,PROD), there was an order in the field columns:
1. field_foo_2
2. field_bar  
However, in UI, it is rendered field_bar and field_foo_2.  
This is a problem for my project because we're looking into ingesting some flat files as datasets; having the columns out of order would give the user problems when they read the schema, thinking it was in the correct order.  
I agree that it is a non-issue for other databases, ie RDBMS where users can freely specify columns and the database takes care of it. Just raising a bug report to see if you guys think it needs fixing.  

**To Reproduce**
1. quickstart a Datahub instance (tested on most current DH version)
2. ingest sample data
3. compare the order of the data shown vs the bootstrap MCE, found at datahub/metadata-ingestion/examples/mce_files/bootstrap_mce.json

**Comment by shirshanka** [comment]
@topwebtek7 : could you take a look at this?

**Comment by topwebtek7** [comment]
> @topwebtek7 : could you take a look at this?

Sure.

**Comment by xiphl** [comment]
it renders the field names in alphabetical order.

**Comment by topwebtek7** [comment]
yes, it renders alphabetically to groupby and visualize hierarchy by field names (ref: https://github.com/linkedin/datahub/pull/2443)
@shirshanka do you think it's a bug sorting in alphabetical order by field column?

**Comment by xiphl** [comment]
If there was a field hierarchy in place, would that order have already been captured naturally during ingestion?

**Comment by 1ambda** [comment]
Hi, One of our use case of datahub is for Hive (and Presto generated table). Users usually created their table considering field names and orders. So would be nice to preserve original orders. Otherwise it would be hard to read / find columns since the order is different w/ other systems such as HIVE CLI, Datagrip, Redash, etc.

**Comment by 1ambda** [comment]
I think this is fixed in 0.8.12.

**Comment by shirshanka** [comment]
Yes fixed in 0.8.12. Closing!
