### ISSUE TITLE
MongoDB ingestion framework speed on large collections?

### ISSUE THREAD

**Issue by anthonyhungnguyen** [linkedin/datahub#2777]
Hi folks, I recently used Mongodb ingestion framework to ingest some collections that have the size > 10 Million. What I found out is the speed of ingestion would be superb slow and the reason for that might be because of $sample usage in the framework. I think this is logical to ensure the schema is correctly inferred. However, by switching to taking head documents (instead of randomly pick), I saw a tremendous ingestion speedup. Could we switch to using fetching head documents or provide options for inferring schema (random/head). 

Thanks

**Comment by kevinhu** [comment]
Had no idea MongoDB's sampling was so slow – will add an option to use head instead!
