### ISSUE TITLE
datahub-gms container exits after ingesting via Kafka Emitter

### ISSUE THREAD

**Issue by Light310** [linkedin/datahub#2791]
**Describe the bug**

I've created some ingestion scripts (using Kafka Emitter) a month ago, and they were working fine, but after I've pulled the latest version of repository and launched the docker-compose, I'm getting the following errors.

After ingesting some datasets data I went to the UI and got the following error:
Exception while fetching data (/browse) : java.lang.RuntimeException: Failed to execute browse: entity type: DATASET, path: [], filters: null, start: 0, count: 10

It appeared, that datahub-gms container exited during ingestion.

Last lines of the datahub-gms container log:
10:29:04.150 [I/O dispatcher 1] INFO  c.l.m.s.e.update.BulkListener - Successfully fed bulk request. Number of events: 1 Took time ms: -1
10:29:04.154 [I/O dispatcher 1] INFO  c.l.m.s.e.update.BulkListener - Successfully fed bulk request. Number of events: 1 Took time ms: -1
2021/06/29 10:29:13 Command exited with error: signal: killed

Ingesting some of the datasets is working fine, and some of them make the container crush, I could not recognize the consistent pattern.
Any idea on how to find out, what is going wrong? "Signal: killed" does not give a clue. All the scripts were working with the previous version of datahub.
Were there any critical changes in the ingestion code?

**Desktop (please complete the following information):**
Ubuntu 20.04 LTS

**Comment by remisalmon** [comment]
I am having the same issue with DataHub v0.8.4.

**Comment by remisalmon** [comment]
@Light310 adding this line that was missing from the datahub-frontend docker.env file fixed it for me: https://github.com/linkedin/datahub/blob/eb60da975dce1f855883e628541cdbcef89717af/docker/datahub-frontend/env/docker.env#L6

**Comment by jasgok** [comment]
I met this issue with linkedin/datahub-gms, IMAGE ID: 9e5d2e06a91b.
I fixed by modified docker-compose.yml, for datahub-gms, mem_limit: 512m > mem_limit: 1g

**Comment by Light310** [comment]
> I met this issue with linkedin/datahub-gms, IMAGE ID: 9e5d2e06a91b.
> I fixed by modified docker-compose.yml, for datahub-gms, mem_limit: 512m to mem_limit: 1g

Indeed, that was the problem, thank you!
Previously I fixed memory limit, but looks like when I use command "python -m datahub docker quickstart" it pulls the initial version with 512m memory limit, overriding the values from my local version. 
But after I spinned up compose with "docker-compose -p datahub -f docker/quickstart/docker-compose-without-neo4j.quickstart.yml up -d" it used the correct memory limit and everything is working fine now. 'datahub-gms' container using around 600Mb, so I guess it might be a good idea to fix memory limit to at least 1Gb in master.

**Comment by shirshanka** [comment]
@Light310 thanks for reporting the issue and the solution that fixed it for you. We'll bump up the limits.

**Comment by Light310** [comment]
@shirshanka looks like https://github.com/linkedin/datahub/pull/3009 was supposed to fix that, but still there is a problem.
I think it is on the line 66 of https://github.com/linkedin/datahub/blob/master/docker/quickstart/docker-compose-without-neo4j.quickstart.yml:
`mem_limit: 512m`

When running quickstart I'm watching docker stats and I can see that datahub-gms starts with 512Mbs and crashes quickly, which results in an error:

Unable to run quickstart - the following issues were detected:
- datahub-gms is not running

**Comment by Light310** [comment]
https://github.com/linkedin/datahub/pull/3064 fixed the issue
