### ISSUE TITLE
Missing logo on Snowflake datasets with DataHub 0.8

### ISSUE THREAD

**Issue by remisalmon** [linkedin/datahub#2795]
**Describe the bug**

With DataHub v0.8.4 and v0.8.3, Snowflake datasets are missing the Sowflake logo from the UI:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/26257211/123836238-b531dc00-d8c6-11eb-8490-237c91d839c5.png">

**To Reproduce**

1. Nuke & quickstart DataHub v0.8.4
2. Ingest Snowflake metadata
3. Browse Snowflake datasets from the UI

Reproduced on MacOS and Linux & with Firefox and Chrome.

**Expected behavior**

What it looks like in DataHub v0.7:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/26257211/123836180-a3e8cf80-d8c6-11eb-8293-a55bacba0696.png">

**Comment by remisalmon** [comment]
Same issue with lookml datasets in Datasets/prod/looker.

Looker dashboard in Dashboards/looker are showing the right logo as expected.

**Comment by jameslamb** [comment]
I just upgraded to 0.8.8 and can see the datasets with the following are missing logos in the lineage view in the UI.

* `dataPlatform:hive`
* `dataPlatform:looker`
* `dataPlatform:postgres`
* `dataPlatform:redshift`

Those are all platforms with `logoUrl` defined in https://github.com/linkedin/datahub/blob/7083de9b4f9740b1c47535c909619fe40487471f/gms/impl/src/main/resources/DataPlatformInfo.json, so I'm not sure why they aren't showing up.

Logos are showing up correctly for Airflow pipelines / tasks and Looker dashboards / charts .

If maintainers could point me in the general direction of where "look up the logo from the `dataPlatform`" code lives, I'd be happy to try fixing this.

#2783 fixed one such issue (#2738, about mongoDB logos) but I can't tell from that diff how this mechanism works.

**Comment by remisalmon** [comment]
Fixed with DataHub v0.8.13: https://github.com/linkedin/datahub/releases/tag/v0.8.13
