### ISSUE TITLE
Improve docs on docker images and how to configure them

### ISSUE THREAD

**Issue by dingobar** [linkedin/datahub#2808]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a better description of the containers needed to run data hub and how to use them, because not everyone uses kubernetes (swarm, ecs...). Even for a kubernetes user, some customization could be necessary depending on kubernetes cluster configuration (very common in enterprise setups to have some limitations), and a helm chart becomes like a puzzle that has to be reverse-engineered to figure out which parts are needed and how to stitch them together in the way your SRE team wants.

**Describe the solution you'd like**
A clear and concise description of:
- Which images are requried
- The configuration options for all images as well as ports
- Which data-stores are required
- The init scripts for all data-stores

**Describe alternatives you've considered**
A simple drawing would be a good starting point. Then, the configuration options should be documented either in the docs or on docker hub.

**Comment by maggiehays** [comment]
Hi @dingobar!

We are now managing feature requests through our new portal to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to reach out to me on DataHub Slack with any questions!
