### ISSUE TITLE
OIDC Authentication not working with AWS cognito

### ISSUE THREAD

**Issue by snagpure-infocepts** [linkedin/datahub#2815]
We are trying to enable the OIDC (AWS cognito) authentication for dockerized Datahub

We followed the instructions given in the below link

https://datahubproject.io/docs/how/configure-oidc-react/

We have configured following properties from datahub/docker/datahub-frontend/env/docker.env

# Required OIDC configs
AUTH_OIDC_ENABLED=true
AUTH_OIDC_CLIENT_ID=XXXXXXXX
AUTH_OIDC_CLIENT_SECRET=
#AUTH_OIDC_DISCOVERY_URI=https://xxxxxxxxxxxxxxxxxxxxxxxx/.well-known/openid-configuration
AUTH_OIDC_DISCOVERY_URI=https://xxxxxxxxxxxx.xxxxxxxxxxxxxxxx/openid-configuration
AUTH_OIDC_BASE_URL=https://XXXXXXXXX.com
# Optional OIDC configs
AUTH_OIDC_USER_NAME_CLAIM=email
AUTH_OIDC_USER_NAME_CLAIM_REGEX=([^@]+)
AUTH_OIDC_SCOPE=openid

# Uncomment to disable JAAS username / password authentication (enabled by defau                                                                                   lt)
**AUTH_JAAS_ENABLED=false**

But for some reasons redirection is not happening, instead it is taking us to default datahub login page 
when we hit the base url.

Please let us know, if we are missing something

Thanks in advance.

**Comment by jjoyce0510** [comment]
@snagpure-infocepts Did you folks manage to get this worked out?

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if this is a recurring problem you're facing!
