### ISSUE TITLE
Documentation for Java API (Dao, Service layers maybe)

### ISSUE THREAD

**Issue by amorskoy** [linkedin/datahub#2819]
There are 2 things which I would like to perform with the DataHub as Java/Scala user:
1. Perform CRUD, Search, Graph queries using DAO directly
2. Ingest directly bypassing REST.LI - using DAO or Services

This will allow keep GMS simplicity, allowing any complex queries to be executed via low-level api.

**Describe the solution you'd like**
Document how to use LinkedIn artifactory. Provide Java code sample on doc portal
At this moment, analyzing https://linkedin.jfrog.io/artifactory/open-source/com/linkedin/, I do not understand how to do it easely, not guessing artifact names.

**Comment by maggiehays** [comment]
Hi @amorskoy,

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
