### ISSUE TITLE
datahub check local-docker is not a command

### ISSUE THREAD

**Issue by dingobar** [linkedin/datahub#2820]
**Describe the bug**
In [the docs](https://datahubproject.io/docs/debugging), it says that I can use `datahub check local-docker` to check that everything is running as it should. This returns `Error: No such command 'local-docker'.` Seems to me the command was removed, and that the docs should be updated.

```plantext
datahub check --help
.../lib/python3.8/site-packages/datahub/ingestion/source/metadata_common.py:7: UserWarning: importing from datahub.ingestion.source.metadata_common is deprecated; use datahub.ingestion.api.workunit instead
  warnings.warn(
Usage: datahub check [OPTIONS] COMMAND [ARGS]...

  Helper commands for checking various aspects of DataHub.

Options:
  --help  Show this message and exit.

Commands:
  mce-file  Check the schema of a MCE JSON file.
  plugins   List the enabled ingestion plugins.
```

**To Reproduce**
1. Install datahub CLI
2. `datahub check local-docker`
3. ???

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 0.8.4.0

**Comment by hsheth2** [comment]
Sorry about that @dingobar - the command should be `datahub docker check`. Will fix this soon
