### ISSUE TITLE
Model RDBMS databases / Hive schemas as separate top-level entities (Dataset Container)

### ISSUE THREAD

**Issue by HarveyLeo** [linkedin/datahub#2838]
**Is your feature request related to a problem? Please describe.**
In our case, Hive schemas (aka database in RDBMS world, the two terms are used interchangeably below) are associated with important metadata, such as access groups, data stewards. Ownership at schema level allows us to define access policies and manage approval flow.  In a data-mesh setup that we are moving towards, federated data governance will require us to distribute the ownership. Schema owners become important to collaborate the policies within a schema, which could be a sub-domain.

**Describe the solution you'd like**
Define a new top-level entity that denotes a container of datasets (probably could name it `Dataset Container`). Existing SQLAlchemy-based plugins (e.g. Hive) should be able to ingest databases / schemas into DataHub as dataset containers. The UI should allow browsing of these dataset containers and editing ownership / properties associated with these dataset containers. The UI should also provide linkage from a dataset container to all datasets underneath, and vice versa.

**Describe alternatives you've considered**
For now we find a workaround to model schemas as Dataset and ingest into DataHub using the emitter interfaces directly. But the UX is subpar for this.

Alation is currently in use at our company, which has native support for schema / database metadata.

**Additional context**
Nil

**Comment by maggiehays** [comment]
Hi @HarveyLeo, Data Containers is currently being addressed with [this initiative](https://feature-requests.datahubproject.io/roadmap/542)! Please subscribe to that post for email updates as we move along! We'll close out this issue in the meantime to minimize confusion :)
