### ISSUE TITLE
Flatten nested schema from Trino

### ISSUE THREAD

**Issue by egzj** [linkedin/datahub#2854]
Hi guys, I would like to ask if it’s possible that the nested hive schemas from Trino be separated into its own fields? Right now they are all cluttered under the same field.

**Example**
![datahub_nested](https://user-images.githubusercontent.com/30767127/125015102-698ae980-e0a1-11eb-8f0d-6ecf27c6ffad.png)

**Code for ingestion**
```
pipeline = Pipeline.create(
        {
            "source": {
                "type": "sqlalchemy",
                "config": {
                    "platform": "trino",
                    "connect_uri": f"trino://{trino_host}/{trino_database}"
                },
            },
            "sink": {
                "type": "datahub-rest",
                "config": {"server": f"http://{datahub_rest}"},
            },
        }
   )
```

**Comment by shirshanka** [comment]
Thanks for reporting this @egzj. We'll take a look at this.

**Comment by maggiehays** [comment]
Hi all, 

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
