### ISSUE TITLE
Make URN namespace configurable

### ISSUE THREAD

**Issue by jjoyce0510** [linkedin/datahub#2863]
**Is your feature request related to a problem? Please describe.**
Currently, urns have the namespace "li". We've received requests to make this configurable on a per-company basis. 

**Describe the solution you'd like**
A way to configure a valid URN namespace.

Places we'd need to change:

- GMS
- Metadata Ingestion framework

This change should be sequenced after the cleanup GMS PR.

**Describe alternatives you've considered**
- Continuing to disallow configurability. 
- Removing namespace from the URN

**Additional context**

**Comment by jjoyce0510** [comment]
Update:

The ideal solution is to remove the "li" portion of URNs altogether (instead have "urn:dataset:<dataset-key>"), but unfortunately that would require a data migration for all existing deployments without supporting multiple concurrent code paths (although this is an option). 

After consulting with the team, we've decided to de-pri this for now. Will come back to it in some time

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
