### ISSUE TITLE
Enhancement of business glossary implementation to support the business term relationship

### ISSUE THREAD

**Issue by hesesx** [linkedin/datahub#2864]
**Is your feature request related to a problem? Please describe.**
Its an enhancement to #2142 

**Describe the solution you'd like**
Businessterms can be composed to create a new business term. We need a feature in business glossary to depict this association/relationship. Business Terms can have a structure, which can be depicted through a schema. Hence need a provision to capture the schema of a business term as an attribute

**Describe alternatives you've considered**
The alternative is - scan through the schema attached to business glossary, to check the association/relationship, however its not user friendly. 

**Additional context**
Short description around two different personas and their activity on UI. 1/ domain owner - to navigate the term and understand the composition 2/ developer - to see the structure of the term 

[Business.Term.Relationship.pptx](https://github.com/linkedin/datahub/files/6866496/Business.Term.Relationship.pptx)

**Comment by hesesx** [comment]
Updated the UI mockup for business glossary

**Comment by maggiehays** [comment]
Hi folks,

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
