### ISSUE TITLE
Provide doc how to change default port numbers for all DataHub Components

### ISSUE THREAD

**Issue by amorskoy** [linkedin/datahub#2870]
Using GMS service as an example. At this moment, it is not obvious how to reliably change 8080 to something other - seems that I need to touch multiple places (like `GMS_PORT` env var and `start.sh` script to change default netty port).

We need some to have this process documented

**Comment by maggiehays** [comment]
Hi @amorskoy!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
