### ISSUE TITLE
Flatten Hive Schema 

### ISSUE THREAD

**Issue by egzj** [linkedin/datahub#2885]
**Is your feature request related to a problem? Please describe.**
Hi guys, I tried to ingest metadata from a Hive table, and the data types for array and struct became NullType(). 

![image](https://user-images.githubusercontent.com/30767127/125750763-6ee7462b-54e3-49bb-be47-7994bb7156f3.png)

**Code for inserting data**
```
CREATE TABLE json_data_3(id int, reports array<string>, address struct<country: string, state: string>);

0: jdbc:hive2://> DESCRIBE json_data_3;
OK
+-----------+--------------------------------------+----------+
| col_name  |              data_type               | comment  |
+-----------+--------------------------------------+----------+
| id        | int                                  |          |
| reports   | array<string>                        |          |
| address   | struct<country:string,state:string>  |          |
+-----------+--------------------------------------+----------+
0: jdbc:hive2://> SELECT * FROM json_data_3;
OK
+-----------------+----------------------+-------------------------------------------+
| json_data_3.id  | json_data_3.reports  |            json_data_3.address            |
+-----------------+----------------------+-------------------------------------------+
| 1               | ["a","b"]            | {"country":"thailand","state":"bangkok"}  |
+-----------------+----------------------+-------------------------------------------+
```

**Describe the solution you'd like**
Could the schema from Hive be shown like how it is for HDFS?
![image](https://user-images.githubusercontent.com/30767127/125750739-390fe187-8244-4830-bfa6-9cc0b6db61f5.png)

**Comment by serefacet** [comment]
+1 :)

**Comment by gumartinm** [comment]
+1 :P

**Comment by maggiehays** [comment]
Hi folks,

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
