### ISSUE TITLE
Clear edited descriptions

### ISSUE THREAD

**Issue by gabe-lyons** [linkedin/datahub#2895]
**Is your feature request related to a problem? Please describe.**
After adding a custom description, there is no way to clear it

**Describe the solution you'd like**
A Clear button on the edit description modal that allows clearing of the description. This would then have the UI show the system description instead.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by 1ambda** [comment]
Would be nice to have this feature in terms of managing column descriptions. Currently only "adding description" is supported. It means, If administrator or user wants to rollback into original description (from dataset source), it's impossible for now.

**Comment by aseembansal-gogo** [comment]
It would be good to be able to just clear the description totally. We had a situation where some tables had bad descriptions in source tables. Now, we are stuck with those descriptions. The best I could do was replace it with a `.` so it does not show up in search results. But would be good to be able to set an empty description which does not show up in `hasDescription: true` either.

**Comment by maggiehays** [comment]
Hi all,

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
