### ISSUE TITLE
Adding additional categories to the UI - changing the metadata model

### ISSUE THREAD

**Issue by iremi** [linkedin/datahub#2897]
I'm trying to add an additional category to the front page of the UI and I'm having trouble completing a gradlew build after changing the metadata-model according to the instructions (https://datahubproject.io/docs/metadata-modeling/extending-the-metadata-model/#optional-step-6-extend-the-datahub-frontend-to-view-your-entity-in-graphql--react)

I'm trying to recreate the dashboard category with a different name - what I did was add a new key.pdl file, created a dasboard2info.pdl, dashboard2aspect.pdl and dashboard2snapshot.pdl where the code is the same, just all of the references to dashboard are changed to dashboard2.

Here is the pastebin of the error I'm getting: https://pastebin.com/kKzj71cP and the index.html file from the report: https://drive.google.com/file/d/1bbk79S_BZjpigVdsmF27_R4veXQSNxiF/view?usp=sharing

If anyone has experience with adding categories to the UI, I'd really appreciate some help.

**Comment by iremi** [comment]
Closed for now, solved by starting from scratch and changing some variables.

**Comment by jjoyce0510** [comment]
@shirshanka can we close this one?

**Comment by iremi** [comment]
Yes
