### ISSUE TITLE
avro-python3 dependency

### ISSUE THREAD

**Issue by ms32035** [linkedin/datahub#2919]
The `acryl-datahub` Python package depends on `avro-python3` which is now deprecated and superseded by `avro`. Unfortunately these 2 cannot coexist as they overwrite files in the same namespace. I also noticed that there's a dependency on some fork of `avro-gen3`, which has similar issues with deprecated avro libraries, and seems to be maintained only for usage in Datahub.  Is there a plan for these dependencies to be updated soon?

**Comment by hsheth2** [comment]
This will be addressed soon. I have a PR up that will update the `avro-gen3` library https://github.com/hsheth2/avro_gen/pull/2 - once we merge that, we can update `acryl-datahub` accordingly.
