### ISSUE TITLE
double quotes in ingestion config lead to incorrect lineage for Looker dashboards / charts

### ISSUE THREAD

**Issue by jameslamb** [linkedin/datahub#2936]
**Describe the bug**

Given an ingestion recipe like the following:

```yaml
source:
  type: "looker"
  config:
    client_id: ${LOOKER_CLIENT_ID} 
    client_secret: ${LOOKER_CLIENT_SECRET} 
    base_url: ${LOOKER_API_URL}
    platform_name: "looker"
    actor: "urn:li:corpuser:etl" 
    env: "PROD" 

sink:
  type: "datahub-kafka"
  config:
     ... all the typical kafka config stuff ...
```

`datahub ingest` creates Metadata Change Event (MCE) messages for Looker charts with input URNs that are unlikely to match the URNs of the corresponding datasets those charts rely on.

* chart MCE input: `urn:li:dataset:(urn:li:dataPlatform:str = \"looker\",some_dataset,PROD)`
* dataset MCE URN: `urn:li:dataset:(urn:li:dataPlatform:looker,some_dataset,PROD)`

**To Reproduce**

I've been struggling to create a simple reproducible example of this, which makes me suspect that the issue might not be happening in `load_config_file()` but somewhere between that and running the ingestion.

Using `pip install 'acryl-datahub[looker,datahub-kafka]==0.8.6.0'`.

<details><summary>output of `conda info` (click me)</summary>

```text

     active environment : pycharm-repos
    active env location : /Users/James.Lamb/miniconda3/envs/pycharm-repos
            shell level : 1
       user config file : /Users/James.Lamb/.condarc
 populated config files : 
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/James.Lamb/miniconda3  (writable)
      conda av data dir : /Users/James.Lamb/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/James.Lamb/miniconda3/pkgs
                          /Users/James.Lamb/.conda/pkgs
       envs directories : /Users/James.Lamb/miniconda3/envs
                          /Users/James.Lamb/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.5 Darwin/20.5.0 OSX/10.16
                UID:GID : 504:20
             netrc file : None
           offline mode : False

```

</details>

Given a config like this

```yaml
source:
  type: "looker"
  config:
    client_id: ${LOOKER_CLIENT_ID} 
    client_secret: ${LOOKER_CLIENT_SECRET} 
    base_url: ${LOOKER_API_URL}
    platform_name: "looker" 
    actor: "urn:li:corpuser:etl" 
    env: "PROD" 
```

`load_config_file()` produces the values I'd expect.

```python
from datahub.configuration.config_loader import load_config_file
import os

for env_var in ["LOOKER_CLIENT_ID", "LOOKER_CLIENT_SECRET", "LOOKER_API_URL"]:
    os.environ[env_var] = "abc"

load_config_file("test.yaml")

# {'source': {'type': 'looker', 'config': {'client_id': 'abc', 'client_secret': 'abc', 'base_url': 'abc', 'platform_name': 'looker', 'actor': 'urn:li:corpuser:etl', 'env': 'PROD'}}}
```

However, using `datahub ingest -c $(pwd)/test.yaml`, I see messages produced with the wrong URN (that `str = \"looker\"` thing mentioned above).

If I remove the quotes in the config, the URNs look how I'd expect them to.

**Expected behavior**

I expected that double quotes in recipe YAML files would not be interpreted as string literals. In other words, I expected that `platform_name: "looker"` and `platform_name: looker` would resolve to identical values.

**Screenshots**

N/A

**Desktop (please complete the following information):**

Observed on macOS and in a docker container using the `python:3.7-slim` image.

**Additional context**

* YAML 1.1 (the version used by PyYAML, which this project uses), docs on double-quoted scalar values: https://yaml.org/spec/current.html#double%20quoted%20style/syntax
* while trying to reproduce this, I traced out the path of how a recipe value makes it into the code creating MCE messages. Pasting that below in case it's helpful.

<details><summary>code path from MCE message generation backwards to when the config file is loaded (click me)</summary>

* which is passed a `platform_name` from the config passed into `LookerDashboardSource` (https://github.com/linkedin/datahub/blob/84a1486b89d683ef96b2f665583125e2b7089969/metadata-ingestion/src/datahub/ingestion/source/looker.py#L315)
* that `LookerDashboardSourceConfig`'s source is at https://github.com/linkedin/datahub/blob/84a1486b89d683ef96b2f665583125e2b7089969/metadata-ingestion/src/datahub/ingestion/source/looker.py#L315
* that instance of `LookerDashboardSource` is created by the `Pipeline` constructor, at https://github.com/linkedin/datahub/blob/84a1486b89d683ef96b2f665583125e2b7089969/metadata-ingestion/src/datahub/ingestion/run/pipeline.py#L71
* that gets its `config` dict from `PipelineConfig.pars_obj()` in `Pipeline.create()`, here: https://github.com/linkedin/datahub/blob/84a1486b89d683ef96b2f665583125e2b7089969/metadata-ingestion/src/datahub/ingestion/run/pipeline.py#L102
* which is created here in the `ingest` entrypoint, https://github.com/linkedin/datahub/blob/84a1486b89d683ef96b2f665583125e2b7089969/metadata-ingestion/src/datahub/entrypoints.py#L79
* that config is loaded with `datahub.configuration.config_loader.load_config_file()`, at https://github.com/linkedin/datahub/blob/84a1486b89d683ef96b2f665583125e2b7089969/metadata-ingestion/src/datahub/entrypoints.py#L75
* which will use `datahub.configuration.yaml.YamlConfigurationMechanism.load_config()`, https://github.com/linkedin/datahub/blob/84a1486b89d683ef96b2f665583125e2b7089969/metadata-ingestion/src/datahub/configuration/config_loader.py#L12
* which will use `yaml.safe_load()`, at https://github.com/linkedin/datahub/blob/84a1486b89d683ef96b2f665583125e2b7089969/metadata-ingestion/src/datahub/configuration/yaml.py#L12
    - where `yaml` is PyYAML

</details>

**Comment by hsheth2** [comment]
This is quite odd

When you run with `datahub --debug ingest ...`, it should dump the config that it loaded prior to validation - could you paste that log line here as well?

**Comment by jameslamb** [comment]
> This is quite odd
> 
> When you run with `datahub --debug ingest ...`, it should dump the config that it loaded prior to validation - could you paste that log line here as well?

sure! I did that this morning. For a recipe with `platform_name: "looker"`, I don't see anything problematic in the config. *(I added the "REDACTED"s below)*.

> [2021-07-23 14:56:07,972] DEBUG    {datahub.entrypoints:78} - Using config: {'source': {'type': 'looker', 'config': {'client_id': 'REDACTED', 'client_secret': 'REDACTED', 'base_url': 'REDACTED', 'platform_name': 'looker', 'actor': 'urn:li:corpuser:etl', 'env': 'PROD'}}, 'sink': {'type': 'datahub-kafka', 'config': {'connection': {'bootstrap': 'REDACTED', 'producer_config': {'security.protocol': 'SSL', 'ssl.ca.location': '/etc/service/keys/ca', 'ssl.certificate.location': '/etc/service/keys/cert', 'ssl.key.location': '/etc/service/keys/key'}, 'schema_registry_url': 'REDACTED', 'schema_registry_config': {'basic.auth.user.info': 'REDACTED'}}}}}

I also noticed that the MCE messages produced now have the expected URN structure.

```json
"inputs": {
  "array": [
    {
      "string": "urn:li:dataset:(urn:li:dataPlatform:looker,reporting_market,PROD)"
    },
    {
      "string": "urn:li:dataset:(urn:li:dataPlatform:looker,sfdc_case,PROD)"
    },
    {
      "string": "urn:li:dataset:(urn:li:dataPlatform:looker,rental,PROD)"
    }
  ]
}
```

Since I can't reproduce this, I think it's ok to close it. Sorry for the noise 😕

**Comment by shirshanka** [comment]
Closing as this seems to have been resolved now.
