### ISSUE TITLE
Support flexibility in origin (environment/fabric) options for identifying Datasets etc. 

### ISSUE THREAD

**Issue by shirshanka** [linkedin/datahub#3001]
**Is your feature request related to a problem? Please describe.**
DataHub's metadata model uses hard to evolve enums to identify environments that entities are in. 
e.g. For DatasetKey, currently supports a specific enum FabricType in the origin field, which is limited to: [“DEV”, “EI”, “PROD” or “CORP”]
This works well for LinkedIn (because this is exactly how they name their environments), but does not work for other companies that might want to identify their environments differently (e.g. "stage", "pre-prod", "testing" ...) 

**Describe the solution you'd like**
The metadata models should not prescribe a limiting set of valid identifiers. Perhaps a free-form string for the environment is good enough. 

**Describe alternatives you've considered**
An alternative could be supporting dropping in your own enum specification for FabricType, so that you get the benefits of validation for the identifiers that you are emitting. Unfortunately this kind of class-swizzling is not supported today. 

**Additional context**
Since this solution will affect keys, we must ensure backwards compatibility with previously created metadata that used the static enum.

**Comment by DM1145** [comment]
This represents a hard requirement for us, as our ‘prod’; environment is actually a source, and the ‘dw-prod’ environment represents production data warehousing which data consumers use as a primary source.

**Comment by DSchmidtDev** [comment]
+1 for this requirement.
I think this limits the flexibility when using Datahub. We also have different environment names and would need to map them.

**Comment by serefacet** [comment]
👍

**Comment by panoptikum** [comment]
+1

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
