### ISSUE TITLE
Restli compatibility checks warn in cases where backwards compatibility is not a concern.

### ISSUE THREAD

**Issue by gabe-lyons** [linkedin/datahub#3013]
**Describe the bug**
Rest.li compatibility check warns when extending enums, which shouldn't be a backwards incompatible case: https://linkedin.github.io/rest.li/modeling/compatibility_check

**To Reproduce**
1. extend an enum
2. run :gms:impl:checkRestModel

**Expected behavior**
This should not cause an issue.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jjoyce0510** [comment]
I think this can be forwards incompatible, wherein _old_ readers cannot read data written by new writers

**Comment by gabe-lyons** [comment]
Closing- with the move to MCP we no longer need to build aspect and entity unions in pdl
