### ISSUE TITLE
hasDescription: true does not work as a user might expect it

### ISSUE THREAD

**Issue by aseembansal-gogo** [linkedin/datahub#3024]
**Is your feature request related to a problem? Please describe.**
When using the search filter `hasDescription: true` it only shows datasets which had descriptions originally. If some description is added later on to a dataset those datasets do not show up in search results. 

**Describe the solution you'd like**
Datasets that have descriptions in the UI should show up in search results when using "hasDescription: true"

**Describe alternatives you've considered**
Searched code to find something to search with. Could not find anything.

**Additional context**
This helps in finding what datasets people have added descriptions on. Helps to see what is being documented

**Comment by aseembansal-gogo** [comment]
If https://github.com/linkedin/datahub/issues/2895 is done. Please don't show descriptions which have been cleared in search results.

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!

**Comment by cbeauch** [comment]
I think this is back... I'm on 0.11
