### ISSUE TITLE
Add ping endpoint on both frontend and gms service

### ISSUE THREAD

**Issue by aseembansal-gogo** [linkedin/datahub#3025]
**Is your feature request related to a problem? Please describe.**
To check connectivity to service there is no easy way other than find out APIs and try to call them. It would be good for checking basic connectivity

**Describe the solution you'd like**
A `/ping` endpoint on both frontend and gms service. 

**Describe alternatives you've considered**
Using `/health` endpoint mentioned in slack. But that did not seem to work on frontend application

**Context**
This will also help the team in debugging issues related to connectivity that people report here and there.

**Comment by dexter-mh-lee** [comment]
Leaving comment here for reference! We have health check end points for each container, but they have slightly different endpoint names due to the different frameworks they use. 

For gms it is /health
For mae/mce-consumers it is /actuator/health
For frontend it is /admin
