### ISSUE TITLE
(feat)  Add field level glossary term in elasticsearch and search result

### ISSUE THREAD

**Issue by saxo-lalrishav** [linkedin/datahub#3047]
**Is your feature request related to a problem? Please describe.**

Field level glossary term should be created and make an entry in elastic search. Also should show result while searching dataset associated with a glossary term

**Comment by maggiehays** [comment]
Hi @saxo-lalrishav!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
