### ISSUE TITLE
Add support for Dgraph as the graph database backend

### ISSUE THREAD

**Issue by EnricoMi** [linkedin/datahub#3084]
I would like to replace the Neo4j dependency with an alternative graph database, in particular Dgraph.

I have identified relevant interfaces that need to be implemented. Can you confirm or complete that list please?

- datahub / metadata-io: com.linkedin.metadata.graph.GraphService
- datahub-gma / dao-api: com.linkedin.metadata.dao.BaseQueryDAO
- datahub-gma / dao-api: com.linkedin.metadata.dao.internal.BaseGraphWriterDAO 

I could not find any places where the latter two interfaces or their neo4j implementations are used anywhere in datahub or datahub-gma. Maybe you can point me to those places.

**Comment by gabe-lyons** [comment]
@EnricoMi - all you need to do is implement `com.linkedin.metadata.graph.GraphService`- the datahub-gma classes are no longer referenced by Datahub

**Comment by EnricoMi** [comment]
@gabe-lyons Excellent, that is good news. The datahub-gma APIs are complex and my `GraphService` is already feature complete. It passes all tests in #3011.

Are you happy with contributing an alpha-version Dgraph implementation of `GraphService`, that will get gradually improved as we use it ourselves?

**Comment by gabe-lyons** [comment]
@EnricoMi - yes, we would be happy with that. We can mark it as alpha in the docs and warn folks that it is still be incubated.

**Comment by EnricoMi** [comment]
I will create a PR once #3011 has landed.
