### ISSUE TITLE
OIDC Authentication not working with Keycloak.org

### ISSUE THREAD

**Issue by mhensley-cls** [linkedin/datahub#3100]
**Describe the bug**
Keycloak, an OIDC provider does not work with datahub.

**To Reproduce**
1. Configure OIDC against out of the box keycloak well known config target
2. attempt to visit datahub, redirect to OIDC provider takes place properly
3. successful login into provider
4. 500 error returned from datahub

**Expected behavior**
Expect Datahub to work with OIDC providers.

**Screenshots**
```
2021-08-11 20:21:53	
00:21:53 [application-akka.actor.default-dispatcher-371] WARN  o.p.o.profile.creator.TokenValidator - Preferred JWS algorithm: null not available. Using all metadata algorithms: [PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512]
2021-08-11 20:21:53	
00:21:53 [application-akka.actor.default-dispatcher-371] WARN  o.p.o.profile.creator.TokenValidator - Preferred JWS algorithm: null not available. Using all metadata algorithms: [PS384, ES384, RS384, HS256, HS512, ES256, RS256, HS384, ES512, PS256, PS512, RS512]
2021-08-11 20:21:53	
00:21:53 [application-akka.actor.default-dispatcher-371] ERROR react.auth.AuthModule$2 - Unable to renew the session. The session store may not support this feature
2021-08-11 20:21:53	
00:21:53 [application-akka.actor.default-dispatcher-371] ERROR react.auth.AuthModule$2 - Unable to renew the session. The session store may not support this feature
2021-08-11 20:21:53	
00:21:53 [application-akka.actor.default-dispatcher-371] ERROR akka.actor.ActorSystemImpl - Internal server error, sending 500 response
2021-08-11 20:21:53	
00:21:53 [application-akka.actor.default-dispatcher-371] ERROR akka.actor.ActorSystemImpl - Internal server error, sending 500 response
```

**Comment by jjoyce0510** [comment]
Hi @mhensley-cls. Thanks for reporting!

Can you provide the OIDC configurations that are shown at your .well-known config URL? It seems there is some issue with validation of the token due to an unsupported algo. 

Would love to see what KeyCloak is supporting by default!

**Comment by mhensley-cls** [comment]
@jjoyce0510 - can't share the exact endpoint, but here's a redacted version...

```
{
"issuer": "https://REDACTED.com/auth/realms/REDACTED",
"authorization_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/auth",
"token_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/token",
"introspection_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/token/introspect",
"userinfo_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/userinfo",
"end_session_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/logout",
"jwks_uri": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/certs",
"check_session_iframe": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/login-status-iframe.html",
"grant_types_supported": [
"authorization_code",
"implicit",
"refresh_token",
"password",
"client_credentials",
"urn:ietf:params:oauth:grant-type:device_code",
"urn:openid:params:grant-type:ciba"
],
"response_types_supported": [
"code",
"none",
"id_token",
"token",
"id_token token",
"code id_token",
"code token",
"code id_token token"
],
"subject_types_supported": [
"public",
"pairwise"
],
"id_token_signing_alg_values_supported": [
"PS384",
"ES384",
"RS384",
"HS256",
"HS512",
"ES256",
"RS256",
"HS384",
"ES512",
"PS256",
"PS512",
"RS512"
],
"id_token_encryption_alg_values_supported": [
"RSA-OAEP",
"RSA-OAEP-256",
"RSA1_5"
],
"id_token_encryption_enc_values_supported": [
"A256GCM",
"A192GCM",
"A128GCM",
"A128CBC-HS256",
"A192CBC-HS384",
"A256CBC-HS512"
],
"userinfo_signing_alg_values_supported": [
"PS384",
"ES384",
"RS384",
"HS256",
"HS512",
"ES256",
"RS256",
"HS384",
"ES512",
"PS256",
"PS512",
"RS512",
"none"
],
"request_object_signing_alg_values_supported": [
"PS384",
"ES384",
"RS384",
"HS256",
"HS512",
"ES256",
"RS256",
"HS384",
"ES512",
"PS256",
"PS512",
"RS512",
"none"
],
"request_object_encryption_alg_values_supported": [
"RSA-OAEP",
"RSA-OAEP-256",
"RSA1_5"
],
"request_object_encryption_enc_values_supported": [
"A256GCM",
"A192GCM",
"A128GCM",
"A128CBC-HS256",
"A192CBC-HS384",
"A256CBC-HS512"
],
"response_modes_supported": [
"query",
"fragment",
"form_post",
"query.jwt",
"fragment.jwt",
"form_post.jwt",
"jwt"
],
"registration_endpoint": "https://REDACTED.com/auth/realms/REDACTED/clients-registrations/openid-connect",
"token_endpoint_auth_methods_supported": [
"private_key_jwt",
"client_secret_basic",
"client_secret_post",
"tls_client_auth",
"client_secret_jwt"
],
"token_endpoint_auth_signing_alg_values_supported": [
"PS384",
"ES384",
"RS384",
"HS256",
"HS512",
"ES256",
"RS256",
"HS384",
"ES512",
"PS256",
"PS512",
"RS512"
],
"introspection_endpoint_auth_methods_supported": [
"private_key_jwt",
"client_secret_basic",
"client_secret_post",
"tls_client_auth",
"client_secret_jwt"
],
"introspection_endpoint_auth_signing_alg_values_supported": [
"PS384",
"ES384",
"RS384",
"HS256",
"HS512",
"ES256",
"RS256",
"HS384",
"ES512",
"PS256",
"PS512",
"RS512"
],
"authorization_signing_alg_values_supported": [
"PS384",
"ES384",
"RS384",
"HS256",
"HS512",
"ES256",
"RS256",
"HS384",
"ES512",
"PS256",
"PS512",
"RS512"
],
"authorization_encryption_alg_values_supported": [
"RSA-OAEP",
"RSA-OAEP-256",
"RSA1_5"
],
"authorization_encryption_enc_values_supported": [
"A256GCM",
"A192GCM",
"A128GCM",
"A128CBC-HS256",
"A192CBC-HS384",
"A256CBC-HS512"
],
"claims_supported": [
"aud",
"sub",
"iss",
"auth_time",
"name",
"given_name",
"family_name",
"preferred_username",
"email",
"acr"
],
"claim_types_supported": [
"normal"
],
"claims_parameter_supported": true,
"scopes_supported": [
"openid",
"email",
"phone",
"microprofile-jwt",
"groups",
"offline_access",
"profile",
"roles",
"web-origins",
"address"
],
"request_parameter_supported": true,
"request_uri_parameter_supported": true,
"require_request_uri_registration": true,
"code_challenge_methods_supported": [
"plain",
"S256"
],
"tls_client_certificate_bound_access_tokens": true,
"revocation_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/revoke",
"revocation_endpoint_auth_methods_supported": [
"private_key_jwt",
"client_secret_basic",
"client_secret_post",
"tls_client_auth",
"client_secret_jwt"
],
"revocation_endpoint_auth_signing_alg_values_supported": [
"PS384",
"ES384",
"RS384",
"HS256",
"HS512",
"ES256",
"RS256",
"HS384",
"ES512",
"PS256",
"PS512",
"RS512"
],
"backchannel_logout_supported": true,
"backchannel_logout_session_supported": true,
"device_authorization_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/auth/device",
"backchannel_token_delivery_modes_supported": [
"poll",
"ping"
],
"backchannel_authentication_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/ext/ciba/auth",
"backchannel_authentication_request_signing_alg_values_supported": [
"PS384",
"ES384",
"RS384",
"ES256",
"RS256",
"ES512",
"PS256",
"PS512",
"RS512"
],
"require_pushed_authorization_requests": false,
"pushed_authorization_request_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/ext/par/request",
"mtls_endpoint_aliases": {
"token_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/token",
"revocation_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/revoke",
"introspection_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/token/introspect",
"device_authorization_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/auth/device",
"registration_endpoint": "https://REDACTED.com/auth/realms/REDACTED/clients-registrations/openid-connect",
"userinfo_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/userinfo",
"pushed_authorization_request_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/ext/par/request",
"backchannel_authentication_endpoint": "https://REDACTED.com/auth/realms/REDACTED/protocol/openid-connect/ext/ciba/auth"
}
}

```

**Comment by donatas-jocas** [comment]
Hi @mhensley-cls @jjoyce0510 hope below might help - I was able to successfully configure Datahub v0.8.12 OIDC Authentication with Keycloak default installation (as far as I can tell). Here is my .well-known config:

`{
    "issuer": "https://******/auth/realms/*****",
    "authorization_endpoint": "https://******/auth/realms/*****/protocol/openid-connect/auth",
    "token_endpoint": "https://******/auth/realms/*****/protocol/openid-connect/token",
    "introspection_endpoint": "https://******/auth/realms/*****/protocol/openid-connect/token/introspect",
    "userinfo_endpoint": "https://******/auth/realms/*****/protocol/openid-connect/userinfo",
    "end_session_endpoint": "https://******/auth/realms/*****/protocol/openid-connect/logout",
    "jwks_uri": "https://******/auth/realms/*****/protocol/openid-connect/certs",
    "check_session_iframe": "https://******/auth/realms/*****/protocol/openid-connect/login-status-iframe.html",
    "grant_types_supported": [
        "authorization_code",
        "implicit",
        "refresh_token",
        "password",
        "client_credentials",
        "urn:ietf:params:oauth:grant-type:device_code",
        "urn:openid:params:grant-type:ciba"
    ],
    "response_types_supported": [
        "code",
        "none",
        "id_token",
        "token",
        "id_token token",
        "code id_token",
        "code token",
        "code id_token token"
    ],
    "subject_types_supported": [
        "public",
        "pairwise"
    ],
    "id_token_signing_alg_values_supported": [
        "PS384",
        "ES384",
        "RS384",
        "HS256",
        "HS512",
        "ES256",
        "RS256",
        "HS384",
        "ES512",
        "PS256",
        "PS512",
        "RS512"
    ],
    "id_token_encryption_alg_values_supported": [
        "RSA-OAEP",
        "RSA-OAEP-256",
        "RSA1_5"
    ],
    "id_token_encryption_enc_values_supported": [
        "A256GCM",
        "A192GCM",
        "A128GCM",
        "A128CBC-HS256",
        "A192CBC-HS384",
        "A256CBC-HS512"
    ],
    "userinfo_signing_alg_values_supported": [
        "PS384",
        "ES384",
        "RS384",
        "HS256",
        "HS512",
        "ES256",
        "RS256",
        "HS384",
        "ES512",
        "PS256",
        "PS512",
        "RS512",
        "none"
    ],
    "request_object_signing_alg_values_supported": [
        "PS384",
        "ES384",
        "RS384",
        "HS256",
        "HS512",
        "ES256",
        "RS256",
        "HS384",
        "ES512",
        "PS256",
        "PS512",
        "RS512",
        "none"
    ],
    "response_modes_supported": [
        "query",
        "fragment",
        "form_post"
    ],
    "registration_endpoint": "https://******/auth/realms/*****/clients-registrations/openid-connect",
    "token_endpoint_auth_methods_supported": [
        "private_key_jwt",
        "client_secret_basic",
        "client_secret_post",
        "tls_client_auth",
        "client_secret_jwt"
    ],
    "token_endpoint_auth_signing_alg_values_supported": [
        "PS384",
        "ES384",
        "RS384",
        "HS256",
        "HS512",
        "ES256",
        "RS256",
        "HS384",
        "ES512",
        "PS256",
        "PS512",
        "RS512"
    ],
    "introspection_endpoint_auth_methods_supported": [
        "private_key_jwt",
        "client_secret_basic",
        "client_secret_post",
        "tls_client_auth",
        "client_secret_jwt"
    ],
    "introspection_endpoint_auth_signing_alg_values_supported": [
        "PS384",
        "ES384",
        "RS384",
        "HS256",
        "HS512",
        "ES256",
        "RS256",
        "HS384",
        "ES512",
        "PS256",
        "PS512",
        "RS512"
    ],
    "claims_supported": [
        "aud",
        "sub",
        "iss",
        "auth_time",
        "name",
        "given_name",
        "family_name",
        "preferred_username",
        "email",
        "acr"
    ],
    "claim_types_supported": [
        "normal"
    ],
    "claims_parameter_supported": true,
    "scopes_supported": [
        "openid",
        "profile",
        "groups",
        "email",
        "phone",
        "offline_access",
        "web-origins",
        "roles",
        "address",
        "microprofile-jwt"
    ],
    "request_parameter_supported": true,
    "request_uri_parameter_supported": true,
    "require_request_uri_registration": true,
    "code_challenge_methods_supported": [
        "plain",
        "S256"
    ],
    "tls_client_certificate_bound_access_tokens": true,
    "revocation_endpoint": "https://******/auth/realms/*****/protocol/openid-connect/revoke",
    "revocation_endpoint_auth_methods_supported": [
        "private_key_jwt",
        "client_secret_basic",
        "client_secret_post",
        "tls_client_auth",
        "client_secret_jwt"
    ],
    "revocation_endpoint_auth_signing_alg_values_supported": [
        "PS384",
        "ES384",
        "RS384",
        "HS256",
        "HS512",
        "ES256",
        "RS256",
        "HS384",
        "ES512",
        "PS256",
        "PS512",
        "RS512"
    ],
    "backchannel_logout_supported": true,
    "backchannel_logout_session_supported": true,
    "device_authorization_endpoint": "https://******/auth/realms/*****/protocol/openid-connect/auth/device",
    "backchannel_token_delivery_modes_supported": [
        "poll"
    ],
    "backchannel_authentication_endpoint": "https://******/auth/realms/*****/protocol/openid-connect/ext/ciba/auth"
}`

and custom properties in Helm deployment values file

`datahub-frontend:
  extraEnvs:
    - name: AUTH_OIDC_ENABLED
      value: "true"
    - name: AUTH_OIDC_CLIENT_ID
      value: "datahub"
    - name: AUTH_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: "datahub-keycloack-client"
          key: "client-secret"
    - name: AUTH_OIDC_DISCOVERY_URI
      value: "https://***************/auth/realms/******/.well-known/openid-configuration"
    - name: AUTH_OIDC_BASE_URL
      value: "http://****************"
    - name: AUTH_OIDC_SCOPE
      value: "openid profile email groups"
    - name: AUTH_OIDC_JIT_PROVISIONING_ENABLED
      value: "true"
    - name: AUTH_OIDC_PRE_PROVISIONING_REQUIRED
      value: "false"
    - name: AUTH_OIDC_EXTRACT_GROUPS_ENABLED
      value: "true"
    - name: AUTH_OIDC_GROUPS_CLAIM
      value: "groups"
    - name: AUTH_JAAS_ENABLED
      value: "false"`
      
      @mhensley-cls maybe there are some client properties you need to adjust? I myself used all the default for "Fine Grain OpenID Connect Configuration" and etc.

**Comment by mhensley-cls** [comment]
@donatas-jocas I got it working, we had an upstream issue where our LDAP provider flowing into keycloak made the usernames in keycloak "LAST_NAME, FIRST_NAME" ... the comma messed up some parsing.

Going to close this issue. @jjoyce0510 indicated in slack that they have improved logging in some recent versions (which helped us track this down)
