### ISSUE TITLE
Button to switch from graph to table view in lineages is absent

### ISSUE THREAD

**Issue by Light310** [linkedin/datahub#3104]
**Describe the bug**
There was a button to get back from graph view in lineages, looks like in the last version it disappeared.

**Comment by gabe-lyons** [comment]
Hey there @Light310 -  can you share a screenshot of what you are seeing? I cannot reproduce this and do not know of a change that would have introduced the issue.

**Comment by Light310** [comment]
Sure!
1st screenshot - an old version of Datahub, you can switch back to table views.

2nd screenshot - the latest version, buttons are missing.

![lineage_button_bug](https://user-images.githubusercontent.com/13537643/129859171-ba9a6716-5f53-4f23-9562-14a3c747e30b.png)

**Comment by Light310** [comment]
Ok, it appeared that I was using older version of acryl-datahub for ingestion. Several issues were fixed after I started using the correct package, including this one.

**Comment by jjoyce0510** [comment]
Thanks for the update, @Light310. The project is still evolving quite quickly, so at times this may be the case.


@shirshanka please close this ticket!
