### ISSUE TITLE
Add RelationshipDirection.UNDIRECTED support to ElasticSearchGraphService

### ISSUE THREAD

**Issue by EnricoMi** [linkedin/datahub#3114]
The `com.linkedin.metadata.graph.GraphService` API contains two methods `findRelatedEntities` and `removeEdgesFromNode` that allow to set a `RelationshipDirection` via `RelationshipFilter`. The current ElasticSearch implementation supports directions `INCOMING` and `OUTGOING`, but `UNDIRECTED` is [not supported](https://github.com/linkedin/datahub/pull/3011#issuecomment-895602175).

Implement `UNDIRECTED` or clearly document this is not implemented and throw a respective exception.

There are tests in #3011 that test the undirected relationships case.

**Comment by gabe-lyons** [comment]
@EnricoMi, I agree- we should articulate it is not supported at the moment.

**Comment by maggiehays** [comment]
Hi @EnricoMi! 

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
