### ISSUE TITLE
Neo4jGraphService should not return duplicates

### ISSUE THREAD

**Issue by EnricoMi** [linkedin/datahub#3118]
The `GraphService` API provides method `findRelatedEntities` that is expected to [not return duplicate related entities](https://github.com/linkedin/datahub/pull/3011#issuecomment-895602175). The current Neo4J implementation returns such duplicates. Duplicates occur when there are multiple paths to the same related entity.

There are tests in #3011 that reproduce this behaviour.

**Comment by maggiehays** [comment]
Hi @EnricoMi!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
