### ISSUE TITLE
Neo4jGraphService should not handle empty type as any but literally

### ISSUE THREAD

**Issue by EnricoMi** [linkedin/datahub#3119]
The current Neo4J implementation of `GraphService` interprets source and destination types `""` in `findRelatedEntities` as "any" type but should consider it literally as the empty string type (or throw an `IllegalArgumentException`). For "any" types the GraphService API [defines the `null` value](https://github.com/linkedin/datahub/pull/3011#issuecomment-895602175).

There are tests in #3011 that reproduce this behaviour.

**Comment by maggiehays** [comment]
Hi @EnricoMi!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
