### ISSUE TITLE
Neo4jGraphService should work with no relationship types

### ISSUE THREAD

**Issue by EnricoMi** [linkedin/datahub#3120]
The `GraphService` API provides two methods `findRelatedEntities` and `removeEdgesFromNode` that allow to provide a list of relationship types. When that list is empty, [the methods should no-op and return immediately](https://github.com/linkedin/datahub/pull/3011#issuecomment-895602175).

The current Neo4J implementation does not show this behaviour.

There are tests in #3011 that test this behaviour.

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
