### ISSUE TITLE
Configurable prefix for all kafka topics

### ISSUE THREAD

**Issue by dingobar** [linkedin/datahub#3125]
**Is your feature request related to a problem? Please describe.**
Because of ACLs in Kafka, it is often required that the topics that the user interacts with has some sort of prefix that a regex matches with. This is in order for the cluster admins to control which users can read and write to which topic. For example, there could be ACLs such that the user `john_snow` can write to topic `john_snow.events`, but not to `harry_potter.events`.

**Describe the solution you'd like**
There are a number of topics in datahub, and it would be nice to be able to add a prefix to them in one setting. I imagine it could be something like
- Topic name configuration is set? Use that, else
- Prefix is set? Use default topic name with prefix, otherwise
- Use default topic name

**Describe alternatives you've considered**
The confluent kafka services such as schema registry and connect solve this with a configuration option (environmental variable). Could just follow their example.

**Comment by maggiehays** [comment]
Hi @dingobar!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
