### ISSUE TITLE
Support ingest lineage from Flink sql.

### ISSUE THREAD

**Issue by wangqinghuan** [linkedin/datahub#3127]
One very common use case for Apache Flink is to implement ETL  pipelines  using Flink sql. We could extract lineage metadata from Flink sql and ingest into datahub to explore Flink etl flow.

**Comment by maggiehays** [comment]
Hi @wangqinghuan! 

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
