### ISSUE TITLE
Allow listing multiple databases in the MSSQL Recipe

### ISSUE THREAD

**Issue by man715** [linkedin/datahub#3128]
**Is your feature request related to a problem? Please describe.**

We have MSSQL instances which have dozens of databases and it is cumbersome to have several different ingestion yaml files for one MSSQL instance.

**Describe the solution you'd like**

It would be nice to have the ability to list several databases in one ingestion yaml file instead of being limited to one database per config.

**Describe alternatives you've considered**

**Additional context**

**Comment by maggiehays** [comment]
Hi @man715! 

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. Your request should be addressed [here](https://feature-requests.datahubproject.io/b/User-Experience/p/support-multiple-platfrom-instances), which is currently underway. If we missed something, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
