### ISSUE TITLE
Code using GraphService should use null instead of ""

### ISSUE THREAD

**Issue by EnricoMi** [linkedin/datahub#3143]
The `GraphService.findRelatedEntities` method expects `null` values for `sourceType` and `destinationType` to refer to _any_ type but some places call this method with `""` instead. This should be fixed.

Currently, `ElasticSearchGraphService` and `Neo4jGraphService` implement both, but the latter is going away (#3116 and #3119).

**Comment by maggiehays** [comment]
Hi @EnricoMi!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
