### ISSUE TITLE
Exception about "Haskell Avro bindings does not support default for aliased or recursive types at this time"

### ISSUE THREAD

**Issue by wangqinghuan** [linkedin/datahub#3147]
Hi
  Using [datahub Ingestion Tool](https://github.com/linkedin/datahub/tree/master/contrib/metadata-ingestion/haskell) to ingest etl-lineage, when I  execute command,

> cat sample/mce.json.dat | bin/datahub-producer.hs config

some exception  prints,

> confDir:/home/wangqh/IdeaProjects/datahub/contrib/metadata-ingestion/haskell/config
> datahub-producer.hs: Haskell Avro bindings does not support default for aliased or recursive types at this time.
> CallStack (from HasCallStack):
> error, called at src/Data/Avro/Schema.hs:402:15 in avro-0.4.6.0-90fndwdwivS7qublrWWZcJ:Data.Avro.Schema

I am newbie to Haskell, what should I  do  to go ahead?

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if this is a recurring problem you're facing!
