### ISSUE TITLE
Ability to render html links in the `Properties` field of an object

### ISSUE THREAD

**Issue by simon-streamotion** [linkedin/datahub#3149]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to provide a url in the `Properties` field of an object and have it rendered as a link in the UI so users can follow that link. In the following image, the `Value` field for `Experiments` should be rendered as a link and clickable.
![image](https://user-images.githubusercontent.com/82419780/130550908-e17c52ef-eb86-4169-ac39-256bc7faa772.png)

**Describe the solution you'd like**
Either the UI should automatically recognise an html link, or it should be possible to embed `"<a href="..">` in the `Value` field when it is being defined.

**Describe alternatives you've considered**
Only those 2 solutions discussed above.

**Additional context**
None

**Comment by maggiehays** [comment]
Hello @simon-streamotion! 

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
