### ISSUE TITLE
Do we have plan ingest metadata from Elasticsearch source?

### ISSUE THREAD

**Issue by wangqinghuan** [linkedin/datahub#3155]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maggiehays** [comment]
Hello! Elasticsearch is now available as an ingestion connector [as of v0.8.23](https://github.com/linkedin/datahub/releases/tag/v0.8.23).
