### ISSUE TITLE
Why can't ingest the metadata of foreign table in postgresql?

### ISSUE THREAD

**Issue by Echelon77** [linkedin/datahub#3202]
When run metadata-ingestion on postgreSQL,  it couldn't ingest the metadata of foreign table in postgresql. I can't found where could config it.

**Comment by maggiehays** [comment]
Hi @Echelon77 - we introduced Foreign Key support in late September - here are some resources that might help!

- [FK demo](https://www.loom.com/share/79f27c2d9f6c4a3b8aacbc48c19add18)
- [DataHub Docs- Schema Metadata](https://datahubproject.io/docs/graphql/objects/#schemametadata)
- [DataHub Docs - ForeignKeyConstraint](https://datahubproject.io/docs/graphql/objects#foreignkeyconstraint)
