### ISSUE TITLE
Retrieve Facets on Browse results

### ISSUE THREAD

**Issue by Falci** [linkedin/datahub#3205]
**Is your feature request related to a problem? Please describe.**
I'd like to add filters to the browse page. It seems to be already supported by the [browse query](https://github.com/linkedin/datahub/blob/f0fff0c8aeba5b3c64fb93de9fee89bdd58f74b4/datahub-web-react/datahub-frontend.graphql#L351).

But, differently from the [SearchResults](https://github.com/linkedin/datahub/blob/f0fff0c8aeba5b3c64fb93de9fee89bdd58f74b4/datahub-web-react/datahub-frontend.graphql#L315), there's no facets for [BrowseResults](https://github.com/linkedin/datahub/blob/f0fff0c8aeba5b3c64fb93de9fee89bdd58f74b4/datahub-web-react/datahub-frontend.graphql#L355-L361)

I tested the browse query using the facets from `SearchResults` and it worked fine. But it seems wrong to make a search just to retrieve those values. Also, the facets are filtered by the search (could exclude facets if there's no results for the search)

**Describe the solution you'd like**
Something like:
```diff
# Browse Output
type BrowseResults {
    entities: [BrowseResultEntity!]!
    start: Int!
    count: Int!
    total: Int!
    metadata: BrowseResultMetadata!
+   facets: [FacetMetadata!]
}
```

**Describe alternatives you've considered**
As said, I tried the `search query`.

This is a feature request slash question. Is there any alternative way to get the facets?

**Comment by maggiehays** [comment]
Hi @Falci!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
