### ISSUE TITLE
Support markdown for glossary term descriptions

### ISSUE THREAD

**Issue by gabe-lyons** [linkedin/datahub#3217]
**Describe the solution you'd like**
I would like to be able view glossary term descriptions in mardkown

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by maggiehays** [comment]
Hi folks! I've added this to our new feature request portal - https://feature-requests.datahubproject.io/b/User-Experience/p/business-glossary-markdown-support

**Comment by maggiehays** [comment]
We'll close out this issue in GitHub & rely on engagement with the request portal post above. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
