### ISSUE TITLE
Show glossary node descriptions

### ISSUE THREAD

**Issue by gabe-lyons** [linkedin/datahub#3218]
**Describe the solution you'd like**
I would like to be able to view glossary node descriptions while navigating the business glossary hierarchy. 

**Describe alternatives you've considered**

**Additional context**

**Comment by maggiehays** [comment]
hi @gabe-lyons 👋 

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
