### ISSUE TITLE
Add support for Dremio datasource

### ISSUE THREAD

**Issue by chulucninh09** [linkedin/datahub#3226]
**Is your feature request related to a problem? Please describe.**
Currently we are using Dremio to load data from sources and also consume data directly on Dremio. Since Dremio has the same SQL interface and also provides built-in lineage feature, we can crawl datasets, sources, and also lineage graph from Dremio to ingest to Datahub so we can consolidate our metadata into Datahub.

**Describe the solution you'd like**
Add a few implementation for Dremio source:
- Source ingestion (suggest `dremio.py` in `datahub/metadata-ingestion/src/datahub/ingestion/source/sql/`)
- Lineage emitter (implement directly in `dremio.py`)
- Reactjs UI to display Dremio source

Also, I would like to make a PR for Dremio source, please advise if I need to propose RFC or just simply direct PR. And also which files I need to implement to get end-to-end result.

**Describe alternatives you've considered**
Self-implement Dremio as sqlAlchemy source and separately implement lineage emitter.

**Additional context**
No additional context

**Comment by shirshanka** [comment]
@chulucninh09 : thanks for the issue! feel free to send us the PR directly :) We generally don't do RFC-s for connectors.

**Comment by shirshanka** [comment]
You should hopefully not need any specific changes to UI for the Dremio source. Let us know why you were thinking of changing it.

**Comment by chulucninh09** [comment]
@shirshanka I just skimmed through the code base and seeing that reactjs front-end needs somewhere to get Dremio logo.

Please advise which places should I put changes, as I understand from reading PR #2918, there are:
- Add `metadata-ingestion/src/datahub/ingestion/source/sql/dremio.py` for source implementation
- Update `datahub-web-react/src/app/shared/getLogoFromPlatform.ts` and add add `datahub-web-react/src/images/dremioLogo.png` for logo
- Add `etadata-ingestion/tests/unit/test_dremio_source.py` for tests
- Update `metadata-ingestion/setup.py` for packaging
- Update `metadata-ingestion/README.md` for docs
- Update `metadata-ingestion/examples/` for examples and recipes
- Add `metadata-ingestion/source_docs/dremio.md` for detailed docs

**Comment by QKotel** [comment]
Is there perhaps already progress for the feature request? 

Since I very urgently need the metadata ingestion for Dremio. Is there any possibility that this request will be impemented or at least the insight into the pull-request files?

**Comment by maggiehays** [comment]
Hi folks, 

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime; @QKotel - if this is still an urgent request, please [reach out to me on DataHub Slack](https://slack.datahubproject.io/) so I can help escalate.
