### ISSUE TITLE
Custom task/pipeline/dataset

### ISSUE THREAD

**Issue by guzmo** [linkedin/datahub#3228]
Hi!

I’ve been looking through the docs and code too try to figure out if it’s possible to add custom pipelines or systems. Lets say microservices are pushing data and we would like to see the lineage all the way from the microservice itself. Couldn’t find anything, sorry if I’m obviously missing something :)

Also, if we would like to add GCP pubsub (or lets say any homemade message system or whatever) as a dataset for streaming data, how do add this? Didn’t find any api documentation on how to add these custom datasets/pipelines

cheers!

**Comment by maggiehays** [comment]
Hi @guzmo!

Apologies for such a delayed response - if these use cases are still relevant to you, please add them to our [feature request portal](https://feature-requests.datahubproject.io/) so we can gauge interest from the community! We'll close this out in the meantime; feel free to reach out to me on [DataHub Slack](slack.datahubproject.io) with any follow-up questions!
