### ISSUE TITLE
lookml ingestion plugin doesn't work correctly for nested includes 

### ISSUE THREAD

**Issue by przemekd** [linkedin/datahub#3239]
**Describe the bug**
If there is a LookML project with files that include other files creating a nested structure `lookml` plugin cannot ingest views properly.

**To Reproduce**
1. Clone git repository https://github.com/przemekd/lookml-ingestion
2. `cd` into the directory
3. Run `datahub ingest -c ingest_lookml.yml`
4. See that no views are scanned.

**Expected behavior**
The plugin should go through looker `includes` in a recursive manner detecting all views used in a project.

**Comment by remisalmon** [comment]
I confirm that the lookml ingestion is broken with acryl-datahub>=0.8.13.1 (probably from this commit: https://github.com/linkedin/datahub/pull/3255, used to work fine with previous versions).

Upstream lookml views are now ingested as platform datasets instead of lookml views.
