### ISSUE TITLE
Add support for Apache Doris datasource

### ISSUE THREAD

**Issue by CraftLCL** [linkedin/datahub#3246]
Please help support Apache Doris, Thanks.

**Comment by maggiehays** [comment]
Hi @CraftLCL! 

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
