### ISSUE TITLE
lookml ingestion broken for cascading derived tables

### ISSUE THREAD

**Issue by remisalmon** [linkedin/datahub#3260]
**Describe the bug**
Cascading derived tables are no longer ingested properly in DataHub.

When cascading derived tables are used in lookml views (see https://docs.looker.com/data-modeling/learning-lookml/derived-tables#cascading_derived_tables), they now get ingested as datasets from the upstream platform/connection instead of views from the same platform (`looker`).

This bug was introduced here in `lookml.py`: https://github.com/linkedin/datahub/pull/3255/files#diff-49de7c0eb38108e88215470de34a7d77a8d4ca25878877a2670e55864532341eL546-R683

**To Reproduce**
1. Define a lookml view using cascading derived tables (i.e. refer a table defined in another view)
2. Ingest lookml
3. The lineage tab of the UI shows the wrong upstream platform

**Expected behavior**
The proper upstream platform (in this case the same platform, looker) should be shown.

**Additional context**
DataHub version: 0.8.13
acryl-datahub version: 0.8.13.1

**Comment by shirshanka** [comment]
@remisalmon: could you verify if #3262 fixes the issue for you?

**Comment by remisalmon** [comment]
It does, thank you!
