### ISSUE TITLE
Tags on field get removed if field description is edited

### ISSUE THREAD

**Issue by aseembansal-gogo** [linkedin/datahub#3265]
**Describe the bug**
Tags on field get removed if field description is edited

**To Reproduce**
1. Go to https://demo.datahubproject.io/dataset/urn:li:dataset:(urn:li:dataPlatform:bigquery,bigquery-public-data.covid19_geotab_mobility_impact.airport_traffic,PROD)/Schema?is_lineage_mode=false
2. Add a tag on a field `aggregation_method`
3. Edit description of the field `aggregation_method`
4. See field tag is still present or missing

**Expected behavior**
Tag added in step 2 should be present. But as soon as description is saved the field tag gets removed. 

**Screenshots**
Steps should be enough to reproduce

**Desktop**
 - OS: Windows 10
 - Browser: chrome
 - Version: v0.8.12 datahub (self-hosted) as well as demo datahub on https://demo.datahubproject.io/

**Additional context**
Did this in 
Checking in database for the dataset's aspect `editableSchemaMetadata` the tag is present in the second latest version (i.e. max(version)) but is missing in latest version (i.e. version = 0) for the field

**Comment by aseembansal-gogo** [comment]
Note I checked on the hosted project and it seems the business terms also get removed when field description is edited

**Comment by gabe-lyons** [comment]
Fixed via https://github.com/linkedin/datahub/pull/3280

**Comment by shirshanka** [comment]
Thanks @gabe-lyons, closing.
