### ISSUE TITLE
datahub docker quickstart should not fetch from master

### ISSUE THREAD

**Issue by EnricoMi** [linkedin/datahub#3266]
The DataHub CLI fetches YAML files from DataHub's GitHub master in https://github.com/linkedin/datahub/blob/fef2ea7126b41405aea935c572450a03c4780e8a/metadata-ingestion/src/datahub/cli/docker.py#L28

This means, changing filenames (rename or delete) in a new version of DataHub will break all earlier released versions of the Datahub CLI (quickstart command only).

To avoid this in the future, the quickstart command should not fetch from `master` but from the same release tag that the Python CLI gets released from.

A similar issue might exist for `CorpUserEditableInfoClass.pictureLink` in https://github.com/linkedin/datahub/blob/fef2ea7126b41405aea935c572450a03c4780e8a/metadata-ingestion/src/datahub/metadata/schema_classes.py#L3630-L3632

**Comment by maggiehays** [comment]
Hi @EnricoMi!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
