### ISSUE TITLE
Docker compose file does not exist at given URL

### ISSUE THREAD

**Issue by rahulbaid** [linkedin/datahub#3281]
I was trying to run airflow locally (https://datahubproject.io/docs/docker/airflow/local_airflow/#step-1-set-up-your-airflow-area) and downloading the docker compose file (https://raw.githubusercontent.com/acryldata/datahub-fork/airflow-local-docker/docker/airflow/docker-compose.yaml?token=AAG5J3NA2ZJRVLS3XB3C3RTBG7BAM). But the file cannot be found at the given URL.

**Comment by shirshanka** [comment]
Looks like an error in our documentation. 

Please use the docker compose file [here](https://raw.githubusercontent.com/linkedin/datahub/master/docker/airflow/docker-compose.yaml)
