### ISSUE TITLE
amd64 docker release

### ISSUE THREAD

**Issue by pixie79** [linkedin/datahub#3282]
Hi,

It would be good to be able to run the datahub suite locally in docker on osx M1 in  native setup.

I have been trying the latest images but they have been giving a qemu core dump.

Whilst I know confluent do not issue amd64 images for kafka/zookeeper you can fairly easily grab their jars and run them in an amd64 image. 

Thanks

Mark

**Comment by maggiehays** [comment]
Hi @pixie79 - this was addressed as of [v0.8.17](https://github.com/linkedin/datahub/releases#:~:text=Compare-,v0.8.17,-Notable%20Changes); we'll close this one out!
