### ISSUE TITLE
A short description of the question

### ISSUE THREAD

**Issue by KaiHavert** [linkedin/datahub#3295]
Same here. I followed this quickstart guide and got an error when I run the command:

 `  datahub docker quickstart  `

Logs:
`
$ datahub docker quickstart
Fetching docker-compose file from GitHub
No Datahub Neo4j volume found, starting with elasticsearch as graph service.
To use neo4j as a graph backend, run
`datahub docker quickstart --quickstart-compose-file ./docker/quickstart/docker-compose.quickstart.yml`
from the root of the datahub repo

Microsoft.VC90.CRT.manifest could not be extracted!
[2021-09-24 12:23:57,253] ERROR    {datahub.entrypoints:99} - File "E:\work\tool\Python39\lib\site-packages\datahub\entrypoints.py", line 91, in main
    88   def main(**kwargs):
    89       # This wrapper prevents click from suppressing errors.
    90       try:
--> 91           sys.exit(datahub(standalone_mode=False, **kwargs))
    92       except click.exceptions.Abort:
    ..................................................
     kwargs = {}
     datahub = <Group datahub>
     click.exceptions.Abort = <class 'click.exceptions.Abort'>
    ..................................................

File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    1135  def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:
    1136      """Alias for :meth:`main`."""
--> 1137      return self.main(*args, **kwargs)
    ..................................................
     self = <Group datahub>
     args = ()
     t.Any = typing.Any
     kwargs = {'standalone_mode': False}
     self.main = <method 'BaseCommand.main' of <Group datahub> core.py:990>
    ..................................................

File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 1062, in main
    990  def main(
    991      self,
    992      args: t.Optional[t.Sequence[str]] = None,
    993      prog_name: t.Optional[str] = None,
    994      complete_var: t.Optional[str] = None,
    995      standalone_mode: bool = True,
    996      windows_expand_args: bool = True,
    997      **extra: t.Any,
    998  ) -> t.Any:
 (...)
    1058
    1059      try:
    1060          try:
    1061              with self.make_context(prog_name, args, **extra) as ctx:
--> 1062                  rv = self.invoke(ctx)
    1063                  if not standalone_mode:
    ..................................................
     self = <Group datahub>
     args = ['docker', 'quickstart', ]
     t.Optional = typing.Optional
     t.Sequence = typing.Sequence
     prog_name = 'datahub'
     complete_var = None
     standalone_mode = False
     windows_expand_args = True
     extra = {}
     t.Any = typing.Any
     self.make_context = <method 'BaseCommand.make_context' of <Group datahub> core.py:887>
     ctx = <click.core.Context object at 0x000001BADCE8B430>
     self.invoke = <method 'MultiCommand.invoke' of <Group datahub> core.py:1634>
    ..................................................

File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 1668, in invoke
    1634  def invoke(self, ctx: Context) -> t.Any:
 (...)
    1664              ctx.invoked_subcommand = cmd_name
    1665              super().invoke(ctx)
    1666              sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
    1667              with sub_ctx:
--> 1668                  return _process_result(sub_ctx.command.invoke(sub_ctx))
    1669
    ..................................................
     self = <Group datahub>
     ctx = <click.core.Context object at 0x000001BADCE8B430>
     Context = <class 'click.core.Context'>
     t.Any = typing.Any
     ctx.invoked_subcommand = 'docker'
     cmd_name = 'docker'
     sub_ctx = <click.core.Context object at 0x000001BADC4463D0>
     cmd.make_context = <method 'BaseCommand.make_context' of <Group docker> core.py:887>
     args = ['quickstart', ]
     _process_result = <function 'MultiCommand.invoke.<locals>._process_result' core.py:1635>
     sub_ctx.command.invoke = <method 'MultiCommand.invoke' of <Group docker> core.py:1634>
    ..................................................

File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 1668, in invoke
    1634  def invoke(self, ctx: Context) -> t.Any:
 (...)
    1664              ctx.invoked_subcommand = cmd_name
    1665              super().invoke(ctx)
    1666              sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
    1667              with sub_ctx:
--> 1668                  return _process_result(sub_ctx.command.invoke(sub_ctx))
    1669
    ..................................................
     self = <Group docker>
     ctx = <click.core.Context object at 0x000001BADC4463D0>
     Context = <class 'click.core.Context'>
     t.Any = typing.Any
     ctx.invoked_subcommand = 'quickstart'
     cmd_name = 'quickstart'
     sub_ctx = <click.core.Context object at 0x000001BAD9C2DAF0>
     cmd.make_context = <method 'BaseCommand.make_context' of <Command quickstart> core.py:887>
     args = []
     _process_result = <function 'MultiCommand.invoke.<locals>._process_result' core.py:1635>
     sub_ctx.command.invoke = <method 'Command.invoke' of <Command quickstart> core.py:1393>
    ..................................................

File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    1393  def invoke(self, ctx: Context) -> t.Any:
 (...)
    1400          ).format(name=self.name)
    1401          echo(style(message, fg="red"), err=True)
    1402
    1403      if self.callback is not None:
--> 1404          return ctx.invoke(self.callback, **ctx.params)
    ..................................................
     self = <Command quickstart>
     ctx = <click.core.Context object at 0x000001BAD9C2DAF0>
     Context = <class 'click.core.Context'>
     t.Any = typing.Any
     self.name = 'quickstart'
     self.callback = <function 'quickstart' docker.py:110>
     ctx.invoke = <method 'Context.invoke' of <click.core.Context object at 0x000001BAD9C2DAF0> core.py:714>
     ctx.params = {'version': 'head',
                   'build_locally': False,
                   'quickstart_compose_file': (),
                   'dump_logs_on_failure': False,
                   'graph_service_impl': None}
    ..................................................

File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 763, in invoke
    714  def invoke(
    715      __self,  # noqa: B902
    716      __callback: t.Union["Command", t.Callable[..., t.Any]],
    717      *args: t.Any,
    718      **kwargs: t.Any,
    719  ) -> t.Any:
 (...)
    759          ctx = __self
    760
    761      with augment_usage_errors(__self):
    762          with ctx:
--> 763              return __callback(*args, **kwargs)
    ..................................................
     t.Union = typing.Union
     t.Callable = typing.Callable
     t.Any = typing.Any
     args = ()
     kwargs = {'version': 'head',
               'build_locally': False,
               'quickstart_compose_file': (),
               'dump_logs_on_failure': False,
               'graph_service_impl': None}
     ctx = <click.core.Context object at 0x000001BAD9C2DAF0>
    ..................................................

File "E:\work\tool\Python39\lib\site-packages\datahub\cli\docker.py", line 196, in quickstart
    145  def quickstart(
    146      version: str,
    147      build_locally: bool,
    148      quickstart_compose_file: List[pathlib.Path],
    149      dump_logs_on_failure: bool,
    150      graph_service_impl: Optional[str],
    151  ) -> None:
 (...)
    192          "datahub",
    193      ]
    194
    195      # Pull and possibly build the latest containers.
--> 196      subprocess.run(
    197          [
    ..................................................
     quickstart = <Command quickstart>
     version = 'head'
     build_locally = False
     quickstart_compose_file = [WindowsPath('C:/Users/wzc/AppData/Local/Temp/tmpz7lqa5kr.yml'), ]
     List = typing.List
     pathlib.Path = <class 'pathlib.Path'>
     dump_logs_on_failure = False
     graph_service_impl = None
     Optional = typing.Optional
     subprocess.run = <function 'run' subprocess.py:464>
    ..................................................

File "E:\work\tool\Python39\lib\subprocess.py", line 528, in run
    464  def run(*popenargs,
    465          input=None, capture_output=False, timeout=None, check=False, **kwargs):
 (...)
    524              # We don't call process.wait() as .__exit__ does that for us.
    525              raise
    526          retcode = process.poll()
    527          if check and retcode:
--> 528              raise CalledProcessError(retcode, process.args,
    529                                       output=stdout, stderr=stderr)
    ..................................................
     popenargs = (['docker-compose', '-f', 'C:\\Users\\wzc\\AppData\\Local\\Temp\\tmpz7lqa5kr.yml', '-p', 'datahub', 'pull', ], )
     input = None
     capture_output = False
     timeout = None
     check = True
     kwargs = {}
     retcode = 4294967295
     process.poll = <method 'Popen.poll' of <Popen: returncode: 4294967295 args: ['docker-compose', '-f', 'C:\\Users\\汪志...> subprocess.py:1
                     158>
     CalledProcessError = <class 'subprocess.CalledProcessError'>
     process.args = ['docker-compose', '-f', 'C:\\Users\\wzc\\AppData\\Local\\Temp\\tmpz7lqa5kr.yml', '-p', 'datahub', 'pull', ]
     stdout = None
     stderr = None
    ..................................................

---- (full traceback above) ----
File "E:\work\tool\Python39\lib\site-packages\datahub\entrypoints.py", line 91, in main
    sys.exit(datahub(standalone_mode=False, **kwargs))
File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
File "E:\work\tool\Python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
File "E:\work\tool\Python39\lib\site-packages\datahub\cli\docker.py", line 196, in quickstart
    subprocess.run(
File "E:\work\tool\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,

CalledProcessError: Command '['docker-compose', '-f', 'C:\\Users\\wzc\\AppData\\Local\\Temp\\tmpz7lqa5kr.yml', '-p', 'datahub', 'pull']' returned non-zero exit status 4294967295.

`
My environment:

`Python 3.9.6
OS: windows 10`

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if you have issues with running quickstart in the future!

**Comment by maggiecandyland** [comment]
I have the same error message as above. Do you have some fix for this? 
Thanks
