### ISSUE TITLE
Support custom npm/yarn registry for building Docker containers

### ISSUE THREAD

**Issue by mihaitodor** [linkedin/datahub#3349]
**Is your feature request related to a problem? Please describe.**
While trying to build the Docker containers using `COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -p datahub build` as described [here](https://github.com/linkedin/datahub/tree/master/docker#building-images), `yarnSetup` fails because under my organisation's Enterprise Security ™, direct access to `https://registry.npmjs.org` is forbidden. Instead, we have to use a custom Artifactory registry for both `npm` and `yarn`.

**Describe the solution you'd like**
It looks like this project needs only `yarn`, so it should be enough to allow users to configure the `yarn` registry through some environment variable.

**Describe alternatives you've considered**
N/A

**Additional context**
I was able to build the images by applying the following hack, which was inspired from [this](https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/faq.md#how-do-i-specify-a-registry-for-the-npm-setup-task) documentation:
```diff
diff --git a/datahub-web-react/build.gradle b/datahub-web-react/build.gradle
index bafe671ec..0dd6cfa94 100644
--- a/datahub-web-react/build.gradle
+++ b/datahub-web-react/build.gradle
@@ -77,3 +77,9 @@ if (!gradle.startParameter.taskNames.any { it in ["idea"] }) {
     assets distZip
   }
}
+
+tasks.yarnSetup {
+  doFirst {
+      args.addAll(['--registry', '<our custom registry URL>'])
+  }
+}
```
The reason why I ended up placing this inside `datahub-web-react/build.gradle` is because it refused to find the `yarnSetup` task if I added it in the `build.gradle` from the root of the repo and I guess it has to be in the same scope as `apply plugin: 'com.github.node-gradle.node'` [here](https://github.com/linkedin/datahub/blob/9590c29ea33c77bea2890165e3958f920c70235a/datahub-web-react/build.gradle#L2) but I have 0 experience with Gradle and I'll defer to an expert for a proper implementation.

**Comment by maggiehays** [comment]
Hi @mihaitodor!

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
