### ISSUE TITLE
why hive without defined a clear meta model in datahub?

### ISSUE THREAD

**Issue by Tan-JiaLiang** [linkedin/datahub#3395]
As you see, like apache atlas it has a clear meta model in it's system, but not in datahub. what the purpose of without it?

**Comment by shirshanka** [comment]
@Tan-JiaLiang : sorry I don't think I'm understanding your question correctly. Could you point us to the Atlas model that you are referring to?

**Comment by Tan-JiaLiang** [comment]
@shirshanka such as the hive metamodel in apache atlas, it has a clear define on it. Is datahub has a clear metamodel define for hive or for hbase? If not, it is has something new idea on datahub?

**Comment by jjoyce0510** [comment]
Hi there - we do have a general purpose Metadata Model which is platform (hive, hbase) agnostic. You can check out the model details here: https://datahubproject.io/docs/metadata-modeling/metadata-model#exploring-datahubs-metadata-model
