### ISSUE TITLE
metadata ingest not in time cause metadata not credible

### ISSUE THREAD

**Issue by Tan-JiaLiang** [linkedin/datahub#3396]
For now, datahub support ingest database metadata by a schedule job, but it can't make metadata credible if metadata had changed before schedule start. How linkedin to govern the uncredible metadata?

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io).
