### ISSUE TITLE
When will this version of Q3 be released？

### ISSUE THREAD

**Issue by gglinux** [linkedin/datahub#3399]
When will this version of ‘Q3 2021 [Jul - Sept 2021]’ be released?

https://datahubproject.io/docs/roadmap#q3-2021-jul---sept-2021

![image](https://user-images.githubusercontent.com/7273957/137304778-ae8ce642-3ca0-45a8-a374-d436317f0b87.png)

**Comment by kuangye098** [comment]
It's been more than a month since the fourth quarter. When will the major version be released?

**Comment by maggiehays** [comment]
Hi @gglinux! I'm in the process of migrating all existing feature requests into our new portal -- https://feature-requests.datahubproject.io/

We will be using the Roadmap feature within that portal to maintain our public-racing Roadmap. Please keep an eye there!

@kuangye098 we pushed out our latest release last Friday -- see the full notes [here](https://github.com/linkedin/datahub/releases/tag/v0.8.17)

**Comment by kuangye098** [comment]
OK。Thanks！ @maggiehays

**Comment by maggiehays** [comment]
Hi folks, just a reminder that our quarterly roadmap is publically available [here](https://feature-requests.datahubproject.io/roadmap)! We'll close out this issue for now; please feel free to reach out to me on DataHub Slack with any questions at all.

**Comment by shirshanka** [comment]
Closing out this issue; please feel free to reference
