### ISSUE TITLE
User Groups page group list shows 0 members

### ISSUE THREAD

**Issue by aseembansal-gogo** [linkedin/datahub#3440]
**Describe the bug**
See steps to reproduce and screenshot

**To Reproduce**
1. Go to https://demo.datahubproject.io/user/urn:li:corpuser:gabe/groups
2. Notice 0 members in the group

**Expected behavior**
Correct number of group members

**Screenshots**
![image](https://user-images.githubusercontent.com/69132220/138395898-7d20c6ca-c1c6-4166-82fb-4e9a6795ead7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version Hosted datahub (Should be v0.8.16)

**Additional context**
NA

**Comment by jjoyce0510** [comment]
Resolved!
