### ISSUE TITLE
Add group members dialogue - we should be able to remove users added to the dialogue

### ISSUE THREAD

**Issue by aseembansal-gogo** [linkedin/datahub#3441]
**Is your feature request related to a problem? Please describe.**
Go to group page. Click Add Members. Add name of a member. Try using backspace to remove the user from dialog. Does not work. There is no x to remove the user. We can accidentally add user twice. The dialog will show two users with same name.

**Describe the solution you'd like**
A way to use add user dialog in an easier way.

**Describe alternatives you've considered**

**Additional context**
NA

**Comment by maggiehays** [comment]
We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
