### ISSUE TITLE
'GlossaryTerm' support searching custom propertie

### ISSUE THREAD

**Issue by Huyueeer** [linkedin/datahub#3442]
For example, I think that after providing 'custom properties', supporting' custom properties' search will make the use of glossary term more friendly. For example, in many scenarios, after the term description contains more meaning, you need to search for a specific 'custom properties' to locate a series of terms.

![image](https://user-images.githubusercontent.com/40758588/138408435-17004103-f561-444a-9397-e036f3a5a282.png)

**Comment by Huyueeer** [comment]
Hi @dexter-mh-lee Excuse me，I want to know, if custom properties search is supported, in addition to @searchable, where else should we pay attention to model construction?

**Comment by maggiehays** [comment]
Hi @Huyueeer! 

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
