### ISSUE TITLE
add task description from airflow operator

### ISSUE THREAD

**Issue by JesseWeiFJ** [linkedin/datahub#3499]
**Is your feature request related to a problem? Please describe.**

Now only dag has its description when using airflow lineage. Tasks does not.

**Describe the solution you'd like**

modify datahub_provider/_lineage_core.py at line 251 like this

    doc = operator.doc or operator.doc_md or operator.doc_json or operator.doc_yaml or operator.doc_rst
    models.DataJobInfoClass(name=task.task_id, description=doc)

then task would have its description from airflow

**Comment by shirshanka** [comment]
Thanks for the suggestion @JesseWeiFJ ! Were you planning to send a PR for this? or hoping we take this up?

**Comment by JesseWeiFJ** [comment]
Hi @shirshanka, thank you for you reply. 

You can take this up. it is just 2 lines of code change. 

<img width="649" alt="截屏2021-11-03 下午11 41 00" src="https://user-images.githubusercontent.com/19567255/140094085-0e4eda01-186f-424c-abf3-d8e44260b16c.png">

**Comment by maggiehays** [comment]
Hi @JesseWeiFJ

We are now managing feature requests through our [new portal](https://feature-requests.datahubproject.io) to improve visibility & prioritize work into our public roadmap. If this request is still relevant, please create a new issue so we can gauge current interest from the Community & prioritize work accordingly.

We'll close out this issue in the meantime. Feel free to [reach out to me on DataHub Slack](https://slack.datahubproject.io/) with any questions!
