### ISSUE TITLE
OwnershipType is usefully for ETL. Maybe we can make full use of it instead of deprecating it?

### ISSUE THREAD

**Issue by JesseWeiFJ** [linkedin/datahub#3505]
I found this word in [doc](https://datahubproject.io/docs/graphql/enums/#ownershiptype)

> The type of the ownership relationship between a Person and a Metadata Entity Note that this field will soon become deprecated due to low usage (DEVELOPER, PRODUCER, CONSUMER and etc)

I thought it is good to mark ownership of data set when combined with etl framework.

For example, Foo has a task producing some data from table A to table B. Then Foo will become the consumer of A and producer of B with datahub lineage module to add it automatically. And you will know that you should notify Foo before changing the schema of table A.

 This information is important for feature iterations. Maybe we should consider not to deprecate it?

**Comment by maggiehays** [comment]
Hi @JesseWeiFJ!

The good news is that we are not planning to deprecate this - I'm going to be polling the DataHub Slack community within the next week to get a better sense of what types of ownership & consumer relationships are useful for folks so we can update the metadata model & UI 😁

Apart from Producer and Consumer, are there other types of relationships that you would find useful?

**Comment by JesseWeiFJ** [comment]
hi @maggiehays thanks for you reply. It sounds great that this features would not be deprecated! 

Nearly all the types of relationships provided now are useful. 
We mainly use Producer and Consumer in our data platform. In the future, we would add DEVELOPER to clarify who maintains the app and STAKEHOLDER to clarity which business apartment uses the data. But DATAOWNER is kind of ambiguous for me. it sound like both DEVELOPER and STAKEHOLDER :-/

**Comment by maggiehays** [comment]
Hi @JesseWeiFJ! 

Apologies for the delayed response - we are tracking interest for supporting OwnershipTypes [here](https://feature-requests.datahubproject.io/b/User-Experience/p/ui-support-data-owner-types); I've gone ahead and added your feedback in that post for us to keep in mind! I encourage you to upvote/subscribe to updates in that post so you can receive notifications as we move through prioritization & dev. We'll close out this issue in the meantime!
