### ISSUE TITLE
How can I extend an ES data source

### ISSUE THREAD

**Issue by liyuhui666** [linkedin/datahub#3517]
We want to get metadata information from ES
How can I extend an ES data source？
Hive data sources have plug-ins acryl-datahub[hive]，but Es data sources have no plug-ins
I see the SQL_common file, what else do I need to do besides override this

**Comment by shirshanka** [comment]
Hello, closing out this issue now that we support Elasticsearch as a source; you can see docs [here](https://datahubproject.io/docs/metadata-ingestion/source_docs/elastic_search/).
