### ISSUE TITLE
Glossary Term on Dataset Columns doesn't show in Related Entities

### ISSUE THREAD

**Issue by jjoyce0510** [linkedin/datahub#3540]
**Describe the bug**
When you add Glossary Terms to a Dataset column, the Dataset does not appear in the Related Entities tab of the Glossary Term. 

**To Reproduce**
1. Go to Dataset page
2. Add a glossary term to a column
3. View the glossary term profile page 
4. View that related entities does not contain the dataset from step 1

**Expected behavior**
Show the dataset in the related entities tag 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by shirshanka** [comment]
This issue has been fixed!
