### ISSUE TITLE
Kafka pipeline completed successfully but metadata is not in datahub

### ISSUE THREAD

**Issue by cl8790** [linkedin/datahub#3544]
I am using and Oracle to Kafka recipe. Kafka pipeline successfully completed, however, i cannot find any metadata in datahub. Do i need to run additional processes? 
Thanks,
Nitin

**Comment by cl8790** [comment]
i had to restart the docker service and it worked. Thanks.

**Comment by shirshanka** [comment]
Closing it out, please reopen if this issue re-occurs
