### ISSUE TITLE
MySQL ingestion brings wrong BrowsePath for dataset

### ISSUE THREAD

**Issue by JesseWeiFJ** [linkedin/datahub#3548]
**Describe the bug**

MySQL ingestion brings wrong BrowsePath for dataset

**To Reproduce**
1. run ingestion with official example recipe: `datahub ingest -c metadata-ingestion/examples/recipes/mysql_to_datahub.yml`
2. then you would find the browse path contains the platform urn like this
![image](https://user-images.githubusercontent.com/19567255/141088138-923c8c38-e9d3-44a0-97af-83bf71aa1417.png)
(`mysql` is enough, `urn:li:dataplatform:mysql` is tedious)

**Expected behavior**

Expect the browse path is clear like what postgres ingestion did. (no urn in browse path)
![image](https://user-images.githubusercontent.com/19567255/141088591-5d0c5f23-95be-4416-9b71-a1afc7167333.png)

**Desktop (please complete the following information):**
 - OS: Centos 7.6
 - Browser Chrome 95
 - Version 0.8.16

**Comment by jjoyce0510** [comment]
@JesseWeiFJ Which version are you running? We did see this issue sometime ago but we had a[ PR to fix it ](https://github.com/linkedin/datahub/commit/dda2078dd79aae034a518008504345712ad0c49f)recently.

**Comment by JesseWeiFJ** [comment]
hi @jjoyce0510, thanks for your reply. 
I used version 0.8.16.2 and started datahub with docker images two weeks ago. It is earlier than the PR you provided. After pulling the latest images, this bug was solved in my machine ;)
