### ISSUE TITLE
Installtion issue from master branch

### ISSUE THREAD

**Issue by resulraveendran** [linkedin/datahub#3565]
When trying to deploy from the master branch there is no docker-compose.ember.yml.when install from the elastic search branch we got 9001  running but logout suddenly. Which branch do we want to take to deploy this?

**Comment by dexter-mh-lee** [comment]
Hi @resulraveendran Ember is no longer supported for datahub. Are you currently running a system with ember frontend? We have completely moved to the react UI. Let us know if you run into any issues. 

Also for the elasticsearch branch, are you using the es5 branch and not the latest master?

For quickstart, take a look at our docs here! https://datahubproject.io/docs/quickstart

**Comment by maggiehays** [comment]
Hi @resulraveendran - we will be closing out this issue due to inactivity.
