### ISSUE TITLE
About Mae module debug

### ISSUE THREAD

**Issue by Huyueeer** [linkedin/datahub#3601]
Hi ,I don't know how to trigger the module code of Mae consumer. I want to know the process of building mapping in ES. The debug mode of GMS and pure Mae consumer module code has been built. What should I start from.

**Comment by dexter-mh-lee** [comment]
Hi! You can either start up a local instance of mae-consumer with debug-jvm turned on by running
`MAE_CONSUMER_ENABLED=true ./gradlew :metadata-jobs:mae-consumer-job:bootRun`

or you can turn on mae consumer module within the metadata-service local run. 
`MAE_CONSUMER_ENABLED=true ./gradlew :metadata-service:war:run --debug-jvm`

Doing the above will wait for you to add a remote debugger to 5005. If you set up the break points on the MappingsBuilder and SettingsBuilder, and then start the debugger, you should be able to get there. 

Let us know if you have any more issues.

**Comment by Huyueeer** [comment]
@dexter-mh-lee Thank you very much for your reply. I succeeded because I lacked `MAE_ CONSUMER_  ENABLED=true`
