### ISSUE TITLE
Does datahub has plan to surpport internationalization?

### ISSUE THREAD

**Issue by dawsongzhao** [linkedin/datahub#3612]
Does datahub has plan to surpport internationalization?

**Comment by maggiehays** [comment]
Hi @dawsongzhao! We don't have it on our immediate roadmap, but it's a fantastic suggestion. I've added it to our feature request portal; you can subscribe to the request & get notifications as we move through review & planning stages.
https://feature-requests.datahubproject.io/b/User-Experience/p/support-internaltionalization

**Comment by shirshanka** [comment]
Closing out this issue; please refer to the feature request linked above for ongoing conversation & prioritization.
