### ISSUE TITLE
mysql ingest database_alias Not effective

### ISSUE THREAD

**Issue by crazy2323** [linkedin/datahub#3622]
**Describe the bug**
yml：
  type: mysql
  config:
    host_port: ******
    database: apache_airflow_181
    username: *****
    password: *****
    database_alias: "airflow_alias"

"aspects": [
                {
                    "com.linkedin.pegasus2avro.schema.SchemaMetadata": {
                        "schemaName": "apache_airflow_181.xcom",
                        "platform": "urn:li:dataPlatform:mysql",

**Comment by maggiehays** [comment]
Hi @crazy2323 - thanks for the bug report! We are planning to address this in upcoming months with Container support; you can follow the feature request here https://feature-requests.datahubproject.io/b/User-Experience/p/container-support
