### ISSUE TITLE
MongoDB metadata ingest doesn't work with MongoDB 4.2

### ISSUE THREAD

**Issue by ivbeg** [linkedin/datahub#3633]
**Describe the bug**
Attempt to ingest MongoDB metadata for MongoDB 4.2 with fail with error "Unrecognized expression '$bsonSize'".

**To Reproduce**
1. Install or get working instance of MongoDB 4.2
2. Configure MongoDB source .yml file to ingest (mongodb.yml)
3. Make sure "enableSchemaInference" set True
4. Run "datahub ingest -c mongodb.yml"
5. See error "Unrecognized expression '$bsonSize'".

**Expected behavior**
1. Data should be ingested into Datahub instance without error.
2. Documentation should include minimal MongoDB version requirement.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python: 3.8.10
 - Browser: Not applicable
 - Version: 0.8.17.2

**Additional context**
Mongodb.yml example attached in zip file and mongodb_ingest.log include full error description
[mongodb.yml.zip](https://github.com/linkedin/datahub/files/7621508/mongodb.yml.zip)
[mongodb_ingest.log](https://github.com/linkedin/datahub/files/7621521/mongodb_ingest.log)

**Comment by yuanzhihao-0606** [comment]
> 嗨@ivbeg，
> 非常感谢报告这个问题。我有一个正在修复程序，并将尝试推出它，并将更新此线程。
Hello, I have the same problem. Will you let me know when the repair is completed?? Where can I see the message of successful modification😊

**Comment by yuanzhihao-0606** [comment]
> Hi @ivbeg ,
> Thanks a lot for reporting the issue. I have a fix for this in progress and will try to push it out soon and will update this thread.

Hello, I have the same problem. Will you let me know when the repair is completed?? Where can I see the message of successful modification😊
