### ISSUE TITLE
Support modeling "enum" values in Schemas

### ISSUE THREAD

**Issue by jjoyce0510** [linkedin/datahub#3636]
**Is your feature request related to a problem? Please describe.**
Currently, there is the ability to capture that a field is of enum type in the SchemaMetadata model. However, there's no ability to capture the "valid values" of the enum. We should update our SchemaMetadata model to include this! 

**Describe the solution you'd like**
Model and display the valid enum values from a schema. 

**Describe alternatives you've considered**
None

**Additional context**
Originally reported here: https://datahubspace.slack.com/archives/CUMUWQU66/p1637134131431900

**Comment by maggiehays** [comment]
Hi @jjoyce0510 - please migrate this to our feature request board :)

**Comment by maggiehays** [comment]
This has been migrated to our [feature request portal ](https://feature-requests.datahubproject.io/b/Developer-Experience/p/support-modeling-enum-calues-in-schemas). This can be closed.
