### ISSUE TITLE
Rest.li + GraphQL Entity "exists" API

### ISSUE THREAD

**Issue by jjoyce0510** [linkedin/datahub#3637]
**Is your feature request related to a problem? Please describe.**
Currently, the Metadata Service layer returns a key aspect when given a valid URN even in the case that there are no other aspects about the Entity stored in the store. The benefit of this is that order of ingestion is more forgiving - even if you ingest say lineage links between to a data assets before details about it have been ingested, things won't break. The con is that callers can be deceived into thinking that assets exist in DataHub that in reality do not.

This phenomena rears its head in owner ingestion, tag ingestion, and more. 

**Describe the solution you'd like**
Either change this behavior, or add an "exists" API to determine whether an entity really exists. 

**Additional context**
Original discussions: https://datahubspace.slack.com/archives/CUMUWQU66/p1637771488059000

**Comment by maggiehays** [comment]
Hi @jjoyce0510! reminder to pls migrate this over to our request portal :)  https://feature-requests.datahubproject.io/

**Comment by maggiehays** [comment]
This has been migrated to our [feature request portal](https://feature-requests.datahubproject.io/b/Developer-Experience/p/rest-li-graphql-entity-exists-api). This issue can be closed out.
