### ISSUE TITLE
Hope Simple sample data of mongodb can appear on https://demo.datahubproject.io/

### ISSUE THREAD

**Issue by yuanzhihao-0606** [linkedin/datahub#3641]
Hope Simple sample data of mongodb can appear on https://demo.datahubproject.io/

reason：Currently, it is not feasible to ingest mongodb through YML files
               The question has been raised 💪🏻

**Comment by shirshanka** [comment]
Hi @yuanzhihao-0606 : we have fixed the issue with mongodb < 4.4. Please take a look and let us know if it looks good.
