### ISSUE TITLE
Airflow use Problem

### ISSUE THREAD

**Issue by liyuhui666** [linkedin/datahub#3642]
Airflow_install_airflow -webserver_1 docker user password, I installed hive plugin in there without GCC, install GCC without permission

**Comment by jjoyce0510** [comment]
Hi there ! I'm going to redirect you to the [Airflow Issues](https://github.com/apache/airflow/issues) to report this. We typically don't handle these type of issues :)

**Comment by liyuhui666** [comment]
thank you
