### ISSUE TITLE
Metadata Ingestion from Azure Data Lake Gen 2 Storage containers to Data Hub

### ISSUE THREAD

**Issue by girishkumaar** [linkedin/datahub#3691]
I was testing with the metadata-ingestion feature in Datahub, and was not able to find the documentation or .yml file to ingest the metadata from the Azure Data Lake Gen 2 storage container? And also is there any way I can use the model.json CDM (Common Data Model) folder to ingest metadata into Datahub? Kindly help me with these two questions or any other sources which can explain the answers to these questions would be really appreciated. Thanks for your time and support!

**Comment by maggiehays** [comment]
Hi @girishkumaar! We don't currently have a connector for Azure Data Lake Gen2; I've created a feature request for you [here](https://feature-requests.datahubproject.io/admin/p/azure-data-lake-storage-gen2) - I encourage you to add more context if you have any and/or to subscribe to the post for updates on progress! We'll close out this issue & address your other question in [this issue ](https://github.com/linkedin/datahub/issues/3692).
