### ISSUE TITLE
sqlalchemy does not support the mysql data type: geometry

### ISSUE THREAD

**Issue by iduanyingjie** [linkedin/datahub#3704]
**Describe the bug**
When I am performing the integration operation with the datahub command, an error is reported：
`lib/python3.8/site-packages/sqlalchemy/dialects/mysql/reflection.py:192: SAWarning: Did not recognize type 'geometry' of column 'GeoShape'`

**To Reproduce**
1. datahub ingest -c

**Screenshots**
![图片](https://user-images.githubusercontent.com/8772749/145414952-0f0059a7-c895-430f-a6ff-ebc198502eb9.png)
![图片](https://user-images.githubusercontent.com/8772749/145414978-3e5fbbea-e9f6-45e8-b91e-9f0e8726c64a.png)

**Desktop (please complete the following information):**
 - DataHub Version [0.8.17]
 - MySQL Version [4.7]

**Comment by treff7es** [comment]
@iduanyingjie the fix was just merged, can you check it now?

**Comment by shirshanka** [comment]
Closing this issue as fixed via #3726. 
pip `acryl-datahub>=0.8.19.0` should have the fix.
Please re-open if this is still an issue.
