### ISSUE TITLE
Connector/Plugin for Azure Blob storage or Azure Data Lake (Gen 2)

### ISSUE THREAD

**Issue by girishkumaar** [linkedin/datahub#3705]
It would be great if there is a feature for plugging in data from Azure Blob storage or Azure Data lake gen 2 storage containers!

**Comment by maggiehays** [comment]
Hi @girishkumaar! We have this feature request captured in our new portal - please subscribe for updates there & feel free to add additional details/context in the comments! 
https://feature-requests.datahubproject.io/b/feedback/p/azure-data-lake-storage-gen2

We'll close out this issue on the GitHub side 😄
