### ISSUE TITLE
Superset: ingestion of the empty dashboard fails

### ISSUE THREAD

**Issue by grumbler** [linkedin/datahub#3713]
When dashboard is empty and doesn't contain any charts ingestion fails here:

```
        raw_position_data = dashboard_data.get("position_json", "{}")
        position_data = json.loads(raw_position_data)
```
position_json is None in this case

**Expected behavior**

Import empty dashboard without charts

**Comment by shirshanka** [comment]
Fixed via #3714 thank you!
