### ISSUE TITLE
tags with spaces do not correctly show related entities 

### ISSUE THREAD

**Issue by jjoyce0510** [linkedin/datahub#3718]
**Describe the bug**
when you create a tag with spaces, say "my tag" and then navigate to its profile page, it does not correctly show the assets it is associated with. 

**To Reproduce**
1. navigate to dataset page
2. click add tag
3. create new tag with spaces
4. navigate to tag profile
5. see "no enities" linked to the tag

think this may have to do with name encoding? also doesn't work for search filtering. 

**Expected behavior**
tag should clearly point back to the asset

**Comment by maggiehays** [comment]
This has also been reported with Glossary Terms

**Comment by jjoyce0510** [comment]
I there! I believe this should have been fixed.
