### ISSUE TITLE
elasticsearch-setup v0.8.18 job is failed. base64 --wrap option is not working.

### ISSUE THREAD

**Issue by develinu** [linkedin/datahub#3722]
**Describe the bug**
I tried installing with the latest release version v0.8.18. The wrap option of the base64 command does not work in the Elasticsearch setup stage. My guess is it's a version issue with busybox and should be replaced with the w option.
The source code is here : https://github.com/linkedin/datahub/blob/master/docker/elasticsearch-setup/create-indices.sh#L15

**To Reproduce**
I installed using the v0.8.18 version of Helmchart provided by Datahub.
1. install prerequisites
2. helm upgrade --install datahub datahub/datahub --values values.yaml 

**Screenshots**
error : **base64: unrecognized option: wrap**
![image](https://user-images.githubusercontent.com/49314154/145737778-bf5c18a0-8378-4445-8766-dd4366d66b2c.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 11.3.1

**Comment by dingobar** [comment]
Facing this exact issue. It is critical for us to upgrade as soon as possible because of the log4j vulnerability.

Source code: https://github.com/dfds-data/datahub-infrastructure

**Comment by dingobar** [comment]
Just saw this, I guess a fix is on its way! https://github.com/linkedin/datahub/pull/3723

**Comment by maggiehays** [comment]
Hi @develinu & @dingobar! The fix for this has been merged & helm charts for 0.8.18 went out this afternoon :) we'll close out this issue shortly

**Comment by dingobar** [comment]
Does this mean that the images for 0.8.18 will be updated, or will there be a 0.8.19 or 0.8.18.1 release with this fix?

**Comment by shirshanka** [comment]
`0.8.19` has been released with this fix.
