### ISSUE TITLE
Symlinks for docker compose yml files break the datahub quickstart command

### ISSUE THREAD

**Issue by IanHopkinson** [linkedin/datahub#3736]
**Describe the bug**
The `datahub docker quickstart` command fails on at least Windows 10 on a Git Bash prompt and also on Powershell with an error message after "Fetching docker-compose..." which starts:

Top level object in 'C:\Users\IHOPKI~1\AppData\Local\Temp\tmp77b9jylw.yml' needs to be an object not '<class 'str'>'.

This appears to be because the files docker-compose.quickstart.yml and docker-compose-without-neo4j.quickstart.yml in https://github.com/linkedin/datahub/tree/master/docker/quickstart have been replaced with symlinks.

**To Reproduce**
1. Ensure Docker Desktop is running
2. Attempt to run `datahub docker quickstart` 
3. See error

**Expected behavior**
After some time the console should show that datahub is running.

**Desktop (please complete the following information):**
 - Windows 10
 - Git Bash and Powershell

**Additional context**
This appears to be a change introduced in the last 12 or so hours, it may not effect non-Windows machines.

**Comment by alongadotvatbox** [comment]
I have earlier reproduced this issue on my Mac machine with similar results.

**Comment by KedarWaval** [comment]
This issue is affecting non-Windows machines too.
A workaround, till the issue gets fixed, is to manually download the compose file and use it with the quickstart-compose-file option:
datahub docker quickstart --quickstart-compose-file docker-compose-with-elasticsearch.quickstart.yml

**Comment by maggiehays** [comment]
Hi folks, this has been resolved with this PR https://github.com/linkedin/datahub/pull/3740. We'll close out this Issue :)
