### ISSUE TITLE
Allow use of Markdown in Group descriptions

### ISSUE THREAD

**Issue by thomasplarsson** [linkedin/datahub#3768]
**Is your feature request related to a problem? Please describe.**
We would like to visualize a number of properties for a group (which we use to emulate a Team). Example could be team manager, link to a slack channel, link to the same entity in another inventory tool etc. We would like to avoid having to make a custom react component for this as each customisation adds a burden when keeping the code base in sync with the upstream.

**Describe the solution you'd like**
A possibility to use Markdown text in a Groups description.

**Describe alternatives you've considered**
Making a custom group React component.

**Additional context**

**Comment by maggiehays** [comment]
Hi @thomasplarsson! We're in the process of consolidating all feature requests in our new portal; I've created [this ](https://feature-requests.datahubproject.io/b/User-Experience/p/allow-use-of-markdown-in-group-descriptions) on your behalf. Please feel free to upvote/subscribe to updates as we progress though review! We'll close out this GH issue in the mean time.
