### ISSUE TITLE
The question of table level lineage

### ISSUE THREAD

**Issue by liyuhui666** [linkedin/datahub#3797]
Hooks are used to update metadata changes automatically for data source metadata changes of Atlas, while metadata intake of DataHub cannot automatically obtain metadata after being used once. Do we need to use scheduling tools for scheduling each time? As for how to use metadata kinship of DataHub, I see that in the example, all data tables are manually updated for upstream and downstream data, shouldn't this be automatically obtained？

**Comment by maggiehays** [comment]
Hi @liyuhui666! Currently it is required to schedule scrapers to keep upstream & downstream dataset lineage up to date. For Redshift, Snowflake, & BigQuery, DataHub automatically infers lineage via the source connector. It sounds like you're looking for Hive-based hooks to push lineage changes; if that's the case, would you mind creating a feature request [here](https://feature-requests.datahubproject.io/) so we can get a better sense of community interest/use cses?

**Comment by shirshanka** [comment]
Closing this out for now, but feel free to route additional questions in our [Community Slack](https://slack.datahubproject.io/)!
