### ISSUE TITLE
Association was not checked before deleting / rolling back glossary term

### ISSUE THREAD

**Issue by Huyueeer** [linkedin/datahub#3798]
When testing the term association, I found that if there is a dataset and term association, the deletion and rollback of the term can continue normally, but theoretically, this operation should be checked when there is an association, otherwise an error will be reported when querying the association, And it has broken the relationship.

**Comment by maggiehays** [comment]
Hi @Huyueeer! We're in the process of migrating to a new Feature Request portal so I have created [this request](https://feature-requests.datahubproject.io/admin/p/associations-should-be-checked-before-deleting-glossary-terms) on your behalf. Please feel to upvote/subscribe for updates as we go through the review/triage process!

**Comment by Huyueeer** [comment]
Hi @maggiehays , Thank you very much for your reply. I have subscribed to this request.
