### ISSUE TITLE
About glossary node

### ISSUE THREAD

**Issue by Huyueeer** [linkedin/datahub#3800]
I'm confused about the concept of glossary node. I don't understand what the team thinks about node. My understanding is: a series of term parent nodes, but what is the relationship between this and path? Or how can I reasonably define node?

**Comment by dannylee8** [comment]
Hi @Huyueeer I found a description of the GlossaryNode here [https://datahubproject.io/docs/metadata-ingestion/source_docs/business_glossary](https://datahubproject.io/docs/metadata-ingestion/source_docs/business_glossary )  

Also, there is a sample business glossary yml file here [https://github.com/linkedin/datahub/blob/master/metadata-ingestion/examples/bootstrap_data/business_glossary.yml](https://github.com/linkedin/datahub/blob/master/metadata-ingestion/examples/bootstrap_data/business_glossary.yml).  

I hope this helps.

**Comment by Huyueeer** [comment]
Hi @dannylee8 Thank you for your reply. I understand that in the structure of GlossaryNode and GlossaryTerm, urn and browsepaths will be affected. Therefore, browsepaths will be determined according to the layer of YML file. Secondly, urn will also be defined. 
In fact, GlossaryNode has been bothering me. I don't know how to reasonably define them. I often define it as a parent directory.

**Comment by gabe-lyons** [comment]
Hey @Huyueeer - the browse path and parent structure should match up. Part of the reason this is confusing is that Datahub doesn't currently show glossary nodes in the UI, just the browse path. This is an improvement that will hopefully come in Q1 2022. Defining them as a parent directory is exactly correct.

**Comment by Huyueeer** [comment]
OK @gabe-lyons .Thank you for your reply. I see.
