### ISSUE TITLE
Recipe configuration and cron scheduling through front end

### ISSUE THREAD

**Issue by cl8790** [linkedin/datahub#3801]
Through this feature request, I am proposing a user interface to configure recipes and metadata ingestion sources. A cron scheduling interface can also be provided for pull-type integrations.

**Comment by maggiehays** [comment]
Hi @cl8790! We have this work in-flight; you can [subscribe to this feature](https://feature-requests.datahubproject.io/b/User-Experience/p/ui-based-ingestion-82fd2c65-11b6-48e3-921c-249dd1c753f7) request to stay up to date with progress!
