### ISSUE TITLE
Docker package could not find start.sh

### ISSUE THREAD

**Issue by Huyueeer** [linkedin/datahub#3818]
I tried to package the image in the master branch method. No error occurred during the packaging process, but the following error was found when starting the image:
![image](https://user-images.githubusercontent.com/40758588/147999991-9e2bedf8-0418-449b-a23e-655a7e511ff9.png)
Then I tried to package the new version under tag, but I also found the same problem. I don't understand the problem in that link?
My packaging environment is WSL2 under windows，Secondly, the following are some logs when I packed, and no exceptions were found.
![image](https://user-images.githubusercontent.com/40758588/148000283-18c2b74b-cc13-4914-bbc8-3c352aa88f95.png)

**Comment by HarveyLeo** [comment]
Hi @Huyueeer , have you resolved the issue? I also encountered same problem

**Comment by Huyueeer** [comment]
@HarveyLeo It's solved. I verified it on version 0.8.23 and found that this problem does not exist. I think it's caused by the merging of new branches of local code. You can try to modify the code in the new version and then package it.
