### ISSUE TITLE
Add support for schema and table filtering in `redshift-usage` ingestor.

### ISSUE THREAD

**Issue by cbuffevant** [linkedin/datahub#3820]
**Is your feature request related to a problem? Please describe.**
I was giving a try to the new `redshift-usage` ingestor and I realised that all schemas and tables were processed. I tried to apply the same filtering settings than my regular `redshift` ingestor and these seem to have no effect.

I tried the following attributes:
* schema_pattern
* table_pattern
* database_alias 

**Describe the solution you'd like**
I would like to be able to use these settings in the same way they are used in the `redshift` ingestor.

**Comment by maggiehays** [comment]
Hi @cbuffevant, I've migrated this to our new Feature Request portal - please upvote & subscribe to the post for automated updates as we move through review & development! We'll close out this issue in the meantime.
https://feature-requests.datahubproject.io/b/feedback/p/redshift-usage-support-table-and-schema-filtering
