### ISSUE TITLE
Where do I get this "stats" and how can I generate it

### ISSUE THREAD

**Issue by liyuhui666** [linkedin/datahub#3822]
![image](https://user-images.githubusercontent.com/71497399/148171551-ff7a6c4a-8849-475d-b193-7b389c538b8a.png)

**Comment by maggiehays** [comment]
Hi @liyuhui666 - you can find details about SQL Profiling [here](https://datahubproject.io/docs/metadata-ingestion/source_docs/sql_profiles/#setup)
