### ISSUE TITLE
I want to automatically obtain the table lineage of the Hive data source

### ISSUE THREAD

**Issue by liyuhui666** [linkedin/datahub#3839]
**Is your feature request related to a problem? Please describe.**
I heard that it is required to schedule scrapers to keep upstream & downstream dataset lineage up to date。I want to  automatically infers lineage  of hive data sources using the ingestion metadata of DataHub. I don't like to manually set "Inlets Outlets" via airflow.

**Describe the solution you'd like**
I'm looking for Hive-based hooks to push lineage changes。
And，Elasticsearch，clickhouse ，mysql，oracle

**Comment by maggiehays** [comment]
Hi @liyuhui666, I've migrated this to our new Feature Request portal - [please upvote & subscribe to the post](https://feature-requests.datahubproject.io/b/feedback/p/automatic-dataset-lineage-for-hive-datasets) for automated updates as we move through review & development. We'll close out this issue in the meantime.

**Comment by puzzor2016** [comment]
@liyuhui666 ，我也在研究datahub的lineage,也遇到一些问题，我留个微信联系方式：15110107370。可以的话线下交流。
