### ISSUE TITLE
(docs) Documentation on Glossary source config is wrong

### ISSUE THREAD

**Issue by cccs-eric** [linkedin/datahub#3844]
**Describe the bug**
When reading this page (https://datahubproject.io/docs/metadata-ingestion/source_docs/business_glossary/#config-details), it says that `owners` and `url` are supposed to be optional for `Glossary`.  But when trying to ingest a file without those fields, I get the following error:

```
    glossary_cfg = BusinessGlossaryConfig.parse_obj(config)
File "pydantic/main.py", line 578, in pydantic.main.BaseModel.parse_obj
File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__

ValidationError: 2 validation errors for BusinessGlossaryConfig
url
  field required (type=value_error.missing)
owners
  field required (type=value_error.missing)
```

I think the documentation should be modified to state that those fields are mandatory.

**Comment by anshbansal** [comment]
URL Part was fixed by https://github.com/linkedin/datahub/pull/3817
