### ISSUE TITLE
DataHub CLI Import Error

### ISSUE THREAD

**Issue by liangjun-jiang** [linkedin/datahub#3855]
**Describe the bug**
An error when run `datahub version` after went through the steps for using DataHub CLI
```
from avro.schema import make_avsc_object
ImportError: cannot import name 'make_avsc_object' from 'avro.schema' (/Users/username/opt/anaconda3/envs/py37/lib/python3.7/site-packages/avro/schema.py)
```

**To Reproduce**
1. Go to 'https://datahubproject.io/docs/cli'
2. Install DataHub CLI by following the online instruction
3. Run 'datahub version'

**Expected behavior**
the correct version of datahub

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: n/a
 - Version: latest
 - Python version: 3.7

**Comment by liangjun-jiang** [comment]
seems most likely it is my local py37 environment. A fresh py36 env seems working.

**Comment by katerina-glushko** [comment]
It worked this way:
```
pip install avro==1.11.0
pip install confluent-kafka
pip uninstall avro
pip install acryl-datahub
```
It seems that there's some conflicting versions of dependencies for `avro` and `acryl-datahub`.
I hope this problem would be fixed - it causes so much pain to create correct env.

**Comment by hsheth2** [comment]
I know this is an old issue, but leaving this for posterity:

The actual issue is an incompatibility between `avro` and `avro-python3` - they end up overwriting each others files when both are installed. The workaround is to uninstall avro-python3 and then reinstall avro.
