### ISSUE TITLE
(frontend) Improve table stats readability in UI

### ISSUE THREAD

**Issue by cccs-eric** [linkedin/datahub#3878]
**Is your feature request related to a problem? Please describe.**
When table profiling is enabled, often the number of rows is large and hard to read.  
<img width="1898" alt="image" src="https://user-images.githubusercontent.com/56447460/149145988-8f56af4a-ff12-412b-a309-bd7b963b7cd1.png">

**Describe the solution you'd like**
We could improve the readability of those numbers by:
1. Adding thousands separators:  59876432  -> 59,876,432
2. Rounding the value in blue (see screenshot): 59876432 -> 60M or 59.9M and leaving the value in red as-is (plus thousands separators).  A tooltip for the rounded value label would show the real value, so nothing would be lost in terms of features.  And it would improve greatly the usability in my opinion, especially when you are having a quick look at the stats.  

<img width="1698" alt="image" src="https://user-images.githubusercontent.com/56447460/149148359-e6dabf06-4c40-4081-9aeb-fb52f5678361.png">

**Comment by maggiehays** [comment]
Hey @cccs-eric! This is a great call out - I migrated this over to our new [feature request portal](https://feature-requests.datahubproject.io/b/User-Experience/p/improve-table-stats-readability-in-ui) (we're in the process of consolidating all of our request pipelines there) - you can subscribe to that post for updates as we move through development & review!

**Comment by tha23rd** [comment]
Going to plus 1 this:
![Screen Shot 2022-01-13 at 9 59 26 AM](https://user-images.githubusercontent.com/54587508/149354398-67e532e2-5f70-48dd-9258-2b9b90d2d6e0.png)

**Comment by cccs-eric** [comment]
> Going to plus 1 this: ![Screen Shot 2022-01-13 at 9 59 26 AM](https://user-images.githubusercontent.com/54587508/149354398-67e532e2-5f70-48dd-9258-2b9b90d2d6e0.png)

I think this one got fixed in the latest release (0.8.22).

**Comment by tha23rd** [comment]
> > Going to plus 1 this: ![Screen Shot 2022-01-13 at 9 59 26 AM](https://user-images.githubusercontent.com/54587508/149354398-67e532e2-5f70-48dd-9258-2b9b90d2d6e0.png)
> 
> I think this one got fixed in the latest release (0.8.22).

I took this screenshot on the latest version of the UI - `0.8.22`

**Comment by shirshanka** [comment]
Hi @cccs-eric & @tha23rd - this has been addressed here https://github.com/linkedin/datahub/pull/3889. We will be cutting a release early next week; closing out out this issue.
