### ISSUE TITLE
Datahub rest API status return

### ISSUE THREAD

**Issue by Huyueeer** [linkedin/datahub#3903]
### Usage scenario:
I use `/entities?action=ingest` writes a GlossaryTerm and then calls `/entities?action=browse` after the interface returns, and the time difference between calls is about 2ms.
### Problems found:
Browse did not return the Term that I created before.

Therefore, I want to confirm that after calling the ingest interface and returning normally, I call the browse interface (browse should query from ES). One is to write DB and the other is to query ES, so is it caused by some delay between DB and ES?

**Comment by shirshanka** [comment]
Hi @Huyueeer, yes there is a small delay between writing to the primary store and it being available for querying through the search index as the Kafka stream processing completes. Out of curiosity, what is the use-case for creating a term and then immediately calling browse?

**Comment by Huyueeer** [comment]
@shirshanka Thank you for your reply. I guess it's the same, because I found that graphql does not contain CRUD operations on term (this may be because the datahub front end does not need such an interface), so I write a single piece of our term data for the rest interface, and then render it through the browse interface,In order to display on the page in time,because Python import alone is not applicable to most scenarios.
