### ISSUE TITLE
About supporting Chinese glossaryterm full text retrieval

### ISSUE THREAD

**Issue by Huyueeer** [linkedin/datahub#3914]
There are many words of glossaryterm in Chinese, but in the current `browse`, `autoplete` and `search`, there are great restrictions on Chinese glossaryterm and do not support word segmentation retrieval.

**Comment by maggiehays** [comment]
Hello, @Huyueeer! Thanks so much for the suggestion. I don't have a clear sense of when we would be able to prioritize this; would you be interested in contributing it back to the community? I'd be more than happy to make sure we're available to provide guidance & code review as necessary!

**Comment by Huyueeer** [comment]
@maggiehays It's a great honor. I'll sort out, test and merge in the near future.

**Comment by maggiehays** [comment]
@Huyueeer that sounds great! We'll close out this issue in the meantime; please feel free to reach out to me via Slack if you need any support!
