### ISSUE TITLE
Validation issue at UI.

### ISSUE THREAD

**Issue by shashionline** [linkedin/datahub#3980]
**Describe the bug**

**To Reproduce**
1. Go to Landing page
2. Click on datasets
3. See error "Validation error of type FieldUndefined: Field 'platform' in type 'Dashboard' is undefined @ 'browse/entities/platform' Validation error of type FieldUndefined: Field 'platform' in type 'Chart' is undefined @ 'browse/entities/platform' Validation error of type FieldUndefined: Field 'platform' in type 'DataFlow' is undefined @ 'browse/entities/platform' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities' Validation error of type FieldsConflict: platform: fields have different nullability shapes @ 'browse/entities'

https://demo.datahubproject.io/browse/dataset

![image](https://user-images.githubusercontent.com/7637810/151185739-9c1ae4a4-4744-4fed-8c46-4f0b42488242.png)

**Comment by maggiehays** [comment]
Hi @shashionline! Thanks for reporting the bug - if you're running quickstart, this should be resolved. Otherwise, please pin to v0.8.23. We'll be keeping the community updated in [Slack](https://datahubspace.slack.com/archives/CUMV92XRQ/p1643217554026900) as we get this resolved! We'll close out this issue in the meantime.
