### ISSUE TITLE
https://datahubproject.io/docs/deploy/aws deployment issue

### ISSUE THREAD

**Issue by braest** [linkedin/datahub#4044]
Dears,

I've followed the setup guide on AWS and everything is working fine until the login page.
Here I do the login and I see for 2 seconds the interface ; after that everything changes to a blank screen.
When I hit F5 very fast I see the interface...

the pods are running
kubectl get pods
NAME                                               READY   STATUS      RESTARTS   AGE
datahub-datahub-frontend-69d47f4796-6mvml          1/1     Running     0          27m
datahub-datahub-gms-58655fd759-6x4tj               1/1     Running     0          34m
datahub-datahub-upgrade-job-cv5z4                  0/1     Completed   0          27m
datahub-elasticsearch-setup-job-vm7bl              0/1     Completed   0          28m
datahub-kafka-setup-job-9jbrk                      0/1     Completed   0          28m
datahub-mysql-setup-job-fpsmr                      0/1     Completed   0          27m
elasticsearch-master-0                             1/1     Running     0          46m
elasticsearch-master-1                             1/1     Running     0          46m
elasticsearch-master-2                             1/1     Running     0          46m
prerequisites-cp-schema-registry-cf79bfccf-hchmf   2/2     Running     1          46m
prerequisites-kafka-0                              1/1     Running     0          46m
prerequisites-mysql-0                              1/1     Running     0          46m
prerequisites-neo4j-community-0                    1/1     Running     0          46m
prerequisites-zookeeper-0                          1/1     Running     0          46m

Ingress is up and functioning ; login page shows for that

when I ask for logs of the frontend container I get this ;
Caused by: com.linkedin.r2.message.rest.RestException: Received error 404 from server for URI http://datahub-datahub-gms:8080/corpUsers
        at com.linkedin.r2.transport.http.common.HttpBridge$1.onResponse(HttpBridge.java:76)
        ... 4 common frames omitted

Caused by: com.linkedin.r2.message.rest.RestException: Received error 404 from server for URI http://datahub-datahub-gms:8080/dataJobs
        at com.linkedin.r2.transport.http.common.HttpBridge$1.onResponse(HttpBridge.java:76)

any pointers?

thanks,

T.

**Comment by braest** [comment]
Dears ; this is the json output of the said error. HTH

{
    "exceptionClass": "com.linkedin.restli.server.RestLiServiceException",
    "stackTrace": "com.linkedin.restli.server.RestLiServiceException [HTTP Status:404]: No root resource defined for path '/dataJobs'\n\tat com.linkedin.restli.server.RestLiServiceException.fromThrowable(RestLiServiceException.java:315)\n\tat com.linkedin.restli.server.BaseRestLiServer.buildPreRoutingError(BaseRestLiServer.java:158)\n\tat com.linkedin.restli.server.RestRestLiServer.buildPreRoutingRestException(RestRestLiServer.java:203)\n\tat com.linkedin.restli.server.RestRestLiServer.handleResourceRequest(RestRestLiServer.java:177)\n\tat com.linkedin.restli.server.RestRestLiServer.doHandleRequest(RestRestLiServer.java:164)\n\tat com.linkedin.restli.server.RestRestLiServer.handleRequest(RestRestLiServer.java:120)\n\tat com.linkedin.restli.server.RestLiServer.handleRequest(RestLiServer.java:132)\n\tat com.linkedin.restli.server.DelegatingTransportDispatcher.handleRestRequest(DelegatingTransportDispatcher.java:70)\n\tat com.linkedin.r2.filter.transport.DispatcherRequestFilter.onRestRequest(DispatcherRequestFilter.java:70)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:72)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.TimedNextFilter.onRequest(TimedNextFilter.java:55)\n\tat com.linkedin.r2.filter.transport.ServerQueryTunnelFilter.onRestRequest(ServerQueryTunnelFilter.java:58)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:72)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.TimedNextFilter.onRequest(TimedNextFilter.java:55)\n\tat com.linkedin.r2.filter.message.rest.RestFilter.onRestRequest(RestFilter.java:50)\n\tat com.linkedin.r2.filter.TimedRestFilter.onRestRequest(TimedRestFilter.java:72)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:146)\n\tat com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnRequest(FilterChainIterator.java:132)\n\tat com.linkedin.r2.filter.FilterChainIterator.onRequest(FilterChainIterator.java:62)\n\tat com.linkedin.r2.filter.FilterChainImpl.onRestRequest(FilterChainImpl.java:96)\n\tat com.linkedin.r2.filter.transport.FilterChainDispatcher.handleRestRequest(FilterChainDispatcher.java:75)\n\tat com.linkedin.r2.util.finalizer.RequestFinalizerDispatcher.handleRestRequest(RequestFinalizerDispatcher.java:61)\n\tat com.linkedin.r2.transport.http.server.HttpDispatcher.handleRequest(HttpDispatcher.java:101)\n\tat com.linkedin.r2.transport.http.server.AbstractR2Servlet.service(AbstractR2Servlet.java:105)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat com.linkedin.restli.server.spring.ParallelRestliHttpRequestHandler.handleRequest(ParallelRestliHttpRequestHandler.java:63)\n\tat org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:73)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)\n\tat com.datahub.authentication.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:77)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:494)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)\n\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.linkedin.restli.server.RoutingException: No root resource defined for path '/dataJobs'\n\tat com.linkedin.restli.internal.server.RestLiRouter.process(RestLiRouter.java:139)\n\tat com.linkedin.restli.server.BaseRestLiServer.getRoutingResult(BaseRestLiServer.java:139)\n\tat com.linkedin.restli.server.RestRestLiServer.handleResourceRequest(RestRestLiServer.java:173)\n\t... 65 more\n",
    "message": "No root resource defined for path '/dataJobs'",
    "status": 404
}

**Comment by pedro93** [comment]
Hello @braest,

What version of DataHub did you deploy and how did you deploy it (helm)? 
`datahub-datahub-frontend-69d47f4796-6mvml 1/1 Running 0 27m` is a strange pod name, typically it's called datahub-frontend-**react**. 

`datahub-frontend` leads to me think you deployed an old version of Datahub frontend which was built in emberJS if I recall correctly and which was deprecated almost a year ago in favor of react. It is almost guaranteed to not be compatible with latter versions of DataHub's backend (GMS)

**Comment by braest** [comment]
@pedro93 ; I guess I shouldn't have used the latest version, I've read there is a problem ;
by what should I replace the tag to get a good version? seems I'm getting a wrong container for this right?

datahub-frontend:
  enabled: true
  image:
    repository: linkedin/datahub-frontend-react
    tag: "**latest**"

**Comment by pedro93** [comment]
Can you try with a tagged version? Say 0.8.23

**Comment by braest** [comment]
yes; not it works fine ; I thought it was only the GMS which had to be 0.8.23 ?
so it's everything?

**Comment by pedro93** [comment]
Is it working? If so, and if you don't mind, explain what was wrong for others to see in the future if they hit the same problem and close the issue.

**Comment by MadisLemsalu** [comment]
Installing with `helm install datahub datahub/datahub` indeed installs deprecated datahub-datahub-frontend. If it is not pulling the latest version automatically with that command, how to do it manually with helm @pedro93 ?

**Comment by pedro93** [comment]
@MadisLemsalu Are you installing datahub through this helm chart: https://artifacthub.io/packages/helm/datahub/datahub?
What is the output when you run `helm repo list` in your terminal?

**Comment by MadisLemsalu** [comment]
`helm repo list` and logs match, so it is automatically pulling the latest version of 0.8.24. 

`kubectl get pods` returns:

![image](https://user-images.githubusercontent.com/29818602/152525542-c1c87825-5b05-48a4-9ae9-69dcf6549a10.png)


..with the pod name of datahub-datahub-frontend. Is that OK as it is also in  [kubernetes development guide?](https://datahubproject.io/docs/deploy/kubernetes/)

**Comment by pedro93** [comment]
`..with the pod name of datahub-datahub-frontend. Is that OK as it is also in [kubernetes development guide?](https://datahubproject.io/docs/deploy/kubernetes/)`

Yes that is ok, what matters is the image running in that pod is frontend-react.

You can check by running: `kubectl get pods datahub-datahub-frontend-bc5649c99-x92sx -o yaml | grep image`

**Comment by pedro93** [comment]
If there is nothing else, can we close this issue?
Thanks!

**Comment by braest** [comment]
Sorry for the delay, I reverted all to version 8.23 and it's working fine. Should I try with 8.26?
Appreciate your help in this.

**Comment by RyanHolstien** [comment]
v8.26 should be fine as well, as long as you update all of the containers to be on the same version. Our frontend and backend versioning are tightly coupled.

**Comment by shirshanka** [comment]
Hi @braest, I'm going to close this out for now, but please feel free to create a new issue if anything else comes up.
