### ISSUE TITLE
Link to the Slack channel on datahubproject.io is expired

### ISSUE THREAD

**Issue by andrewpcone** [linkedin/datahub#4071]
**Describe the bug**
Link to the Slack channel on datahubproject.io is expired.

**To Reproduce**
1. Go to datahubproject.io 
2. Click on the slack link

**Comment by shirshanka** [comment]
Fixed now, please retry!
In case DNS isn't refreshed yet, here is the [link](https://join.slack.com/t/datahubspace/shared_invite/zt-133bvhig2-Q6kCm9ZHfypP8ACvvIR3pA)

**Comment by shirshanka** [comment]
We'll close this out for now; please let us know if there are any additional issues.
