### ISSUE TITLE
Select the text box when adding the Owner and Domain.

### ISSUE THREAD

**Issue by eburairu** [linkedin/datahub#4105]
**Describe the bug**
When adding Owner and Domain, the text box is not selected.
When adding Tag and Term, the text box is selected.

**To Reproduce**
1. Go to 'entity page'
2. Click on 'Set Domain'
3. See the text box is not selected

**Expected behavior**
The text box should be selected like Tag and Term.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 98.0.4758.80

**Additional context**
[Slack Link](https://datahubspace.slack.com/archives/CV2UXSE9L/p1644307075283389)

**Comment by jjoyce0510** [comment]
This is fixed on master!

**Comment by eburairu** [comment]
Thank you very much. I've confirmed it.
