### ISSUE TITLE
[Feature Request] Read Airflow Kwargs Config via Env variable

### ISSUE THREAD

**Issue by rodolfo-picoreti** [linkedin/datahub#4115]
Hey,

Currently the official Airflow helm chart do not support configuring the airflow.cfg directly. The recommended way is to configure it using env variables. (https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-set-airflow-configs)

Would it be possible to change the config load logic to also load from env variables? (
https://github.com/linkedin/datahub/blob/9bdc9af7b90c6a97194eceb898543360b4eb105c/metadata-ingestion/src/datahub_provider/lineage/datahub.py#L27)

Something like: AIRFLOW__LINEAGE__DATAHUB_KWARGS

If the feature makes sense I can submit a PR.

Best Regards

**Comment by rodolfo-picoreti** [comment]
Apparently Airflow can already do it https://github.com/apache/airflow/blob/8e81615edb7e0bc07cbba4d94fa802c44a3b4e6a/airflow/configuration.py#L317

Sorry for that. Closing the issue.

**Comment by khgould** [comment]
Hey @rodolfo-picoreti , could you detail how best to configure this env: AIRFLOW__LINEAGE__DATAHUB_KWARGS?

**Comment by jibrilhp** [comment]
@khgould you can write like this on yml , "AIRFLOW__LINEAGE__DATAHUB_KWARGS={\"datahub_conn_id\": \"datahub_rest_default\"}"

**Comment by khgould** [comment]
Yes you're right. Please close this issue.
