### ISSUE TITLE
Custom metadata build issue

### ISSUE THREAD

**Issue by ishtiaque1994** [linkedin/datahub#4137]
I was attempting to create a custom metadata type and was following the [dataQualityRule](https://datahubproject.io/docs/metadata-models-custom/) example. But I was unable to complete the build process, as I faced a lot of dependency issues (listed below). Moreover, I didn't find any documentation explaining the build process. It would be helpful to get a complete specification for the build.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':metadata-service:restli-client:compileJava'.
> Could not resolve all task dependencies for configuration ':metadata-service:restli-client:compileClasspath'.
   > Could not resolve project :metadata-service:restli-servlet-impl.
     Required by:
         project :metadata-service:restli-client
      > Unable to find a matching variant of project :metadata-service:restli-servlet-impl:
          - Variant 'apiElements' capability datahub-master.metadata-service:restli-servlet-impl:unspecified:
              - Incompatible attribute:
                  - Required org.gradle.jvm.version '8' and found incompatible value '11'.
              - Other attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.libraryelements 'classes' and found compatible value 'jar'.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
          - Variant 'runtimeElements' capability datahub-master.metadata-service:restli-servlet-impl:unspecified:
              - Incompatible attribute:
                  - Required org.gradle.jvm.version '8' and found incompatible value '11'.
              - Other attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.libraryelements 'classes' and found compatible value 'jar'.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.

**Comment by dexter-mh-lee** [comment]
Hi. Our project requires java8, but seems like your default java version is on 11. https://datahubproject.io/docs/developers/#getting-unsupported-class-file-major-version-57 Can you try setting your env to use Java 8? 

i.e. running ```java -version``` should return something like 
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
```

**Comment by shirshanka** [comment]
Hi. Have you tried the above? If the issue still persists, let us know. Otherwise, we will close this issue.

**Comment by ishtiaque1994** [comment]
I have solved this issue. It can be closed.

**Comment by shirshanka** [comment]
Thanks for the update!
