### ISSUE TITLE
bug for UI Ingestion

### ISSUE THREAD

**Issue by kizy008** [linkedin/datahub#4187]
**Describe the bug**
DataHub version v0.8.26 (the newest)
Today I install datahub on my linux server with command:
 datahub docker quickstart --dump-logs-on-failure  --quickstart-compose-file ./docker-compose-without-neo4j.quickstart.yml
The app runs well, but wen I use UI ingestion, I found no ingestion status returned back.
![image](https://user-images.githubusercontent.com/12572997/154694137-081450da-bb0f-46f2-a8d9-49b3f5e084ad.png)
I search the aspect of 【dataHubExecutionRequestResult】 for this excution but no record found.
![image](https://user-images.githubusercontent.com/12572997/154695815-f93060fb-edd3-466a-9971-54e5076be742.png)

I am confused. 3 days ago, I install datahub with the same command on my windows computer, and use UI Ingestion as well.
It worked so good.
![image](https://user-images.githubusercontent.com/12572997/154694849-670367dc-072b-42c7-a4cf-ce07c4a7d11c.png)

So I want to know what happened. And How can I get ingestion execution result on my linux server.

**Expected behavior**
Get correct UI ingestion execution result on linux

**Comment by jjoyce0510** [comment]
Hi there! It looks like your `datahub-actions` container may not be up & running. Can you verify that this container is running using `docker ps`? 

This guide may also help in debugging.. https://datahubproject.io/docs/ui-ingestion/

**Comment by kizy008** [comment]
您的邮件我已收到，我会尽快给您回复，谢谢！

**Comment by kizy008** [comment]
> Hi there! It looks like your `datahub-actions` container may not be up & running. Can you verify that this container is running using `docker ps`?
> 
> This guide may also help in debugging.. https://datahubproject.io/docs/ui-ingestion/

Thanks for your reply. I think it's the answer for my problem. I did miss `datahub-actions` part in my quickstart yml file.
I'll add this part and try again.  It really do me a favor. Thanks for your help.

**Comment by kizy008** [comment]
The problem is solved after `datahub-actions` started， Thanks!
