### ISSUE TITLE
Kafka Metadata Source Ingestion use Platform Instance failed

### ISSUE THREAD

**Issue by kizy008** [linkedin/datahub#4207]
**Describe the bug**
I read the Metadata Ingestion document here https://datahubproject.io/docs/metadata-ingestion/source_docs/kafka
And it is said [Kafka Metadata] is supported Platform Instance. But When I set paltform_instance in my yaml file and run datahub ingest, the error occurs.

**To Reproduce**
1. Here is my yaml file:
![image](https://user-images.githubusercontent.com/12572997/155093551-39e7fc01-a136-4b52-885c-ce270e602be5.png)
2.  Here is my CLI command:
python3 -m datahub ingest -c examples/recipes/syncKafka.yml
3. Here is the error:
![image](https://user-images.githubusercontent.com/12572997/155093768-85566666-f8dc-4fd5-952c-9a0b32b7ff84.png)

**Expected behavior**
I think this means Kafka Metadata Source Ingestion is not support platform_instance. Or is there something wrong with my yaml ?

**Comment by anshbansal** [comment]
This was recently added. If you are not using the latest version please update to latest version of the CLI.

You can check version through
```
python3 -m datahub version
```

This is how you upgrade https://datahubproject.io/docs/cli/#installation

**Comment by kizy008** [comment]
I think my version is 0.8.26.

**Comment by kizy008** [comment]
I learn that v0.8.24+ releases have been supported platform_instance, so I think my version is ok. 
And I have use thie feature in mysql and hive source, and it works well.
Is there something wrong with my configure?

**Comment by kizy008** [comment]
I update datahub CLI version  to v0.8.26.6 then it works. So I guess it is supported between v0.8.26.1 and v0.8.26.6.
