### ISSUE TITLE
Lineage - Creates dummy dataset when the given input/output dataset not present

### ISSUE THREAD

**Issue by keerthiis** [linkedin/datahub#4213]
When emitting lineages, when an Input/ Output Dataset does not exist, it creates a dummy dataset and adds lineage information using the dummy dataset. Instead, since the dataset does not exist, we should error it out to indicate the same.

**Comment by maggiehays** [comment]
Hi @keerthiis! This behavior is currently expected to support out-of-order ingestion (ie. BigQuery can be ingested before Looker & the lineage will be defined). We're always open to new feature requests - feel free to add it [here](https://feature-requests.datahubproject.io/) so we can gauge community interest! 

We'll close out this issue in the meantime.
