### ISSUE TITLE
datahub-gms quick start sink not working 

### ISSUE THREAD

**Issue by pavanmallepudi** [linkedin/datahub#4229]
Hi All,

I am trying to ingest data from mysql 

tried using console sink and everything working fine . 

But with datahub-rest facing error as below .

Failed to "
           "establish a new connection: [Errno 111] Connection refused')': /api/gms/config\n"

and I am using sink configuration as below.

sink: 
    type: datahub-rest 
    config: 
        server: "http://localhost:9002/api/gms"

please help me if am missing anything

**Comment by analiticar85** [comment]
@pavanmallepudi  have you found a solution? I have a same issue

**Comment by putnam120** [comment]
@pavanmallepudi I am now also encountering this error. Can you please share the solution that you found.

**Comment by brunofaustino** [comment]
I have an identical issue.
In my case, I'm doing deploy in Kubernetes.
The documentation says the 'server' parameter must be the accessible GMS endpoint. (https://datahubproject.io/docs/metadata-ingestion/sink_docs/datahub)

I needed to change the type of GMS Kubernetes pod to 'LoadBalancer' and replace the 'server' parameter 'localhost' for the address of the LoadBalancer.

config:
    server: "http://LOAD_BALANCER_ENDPOINT_HERE:9002/api/gms"

And it's worked for me.

**Comment by JGDallas** [comment]
I am encountering the same error as those above. Current Config: 
1. Running the Quickstart on my localhost:9002. 
2. Attempting to connect to SAMPLE snowflake DB with all Roles and privs granted to user account. 
RECIPE = source:
    type: snowflake
    config:
        account_id: MY_ACCOUNT
        warehouse: MY_WAREHOUSE
        username: MY_USERNAME
        password: '${SNOWFLAKE_PASSWORD}'
        role: PUBLIC
        ignore_start_time_lineage: true
sink:
    type: datahub-rest
    config:
        server: 'http://localhost:9002/api/gms'


>>>PARTIAL LOG

RUN_INGEST - {'errors': [],
 'exec_id': '54b2173a-cc87-4bc1-a09a-f8d438784026',
 'infos': ['2022-05-29 14:31:24.781571 [exec_id=54b2173a-cc87-4bc1-a09a-f8d438784026] INFO: Starting execution for task with name=RUN_INGEST',
           '2022-05-29 14:32:03.979285 [exec_id=54b2173a-cc87-4bc1-a09a-f8d438784026] INFO: stdout=Requirement already satisfied: pip in '
           '/tmp/datahub/ingest/venv-54b2173a-cc87-4bc1-a09a-f8d438784026/lib/python3.9/site-packages (21.2.4)\n'
           'Collecting pip\n'
           '  Using cached pip-22.1.1-py3-none-any.whl (2.1 MB)\n'
           'Collecting wheel\n'
           '  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)\n'
           'Requirement already satisfied: setuptools in /tmp/datahub/ingest/venv-54b2173a-cc87-4bc1-a09a-f8d438784026/lib/python3.9/site-packages '
           '(58.1.0)\n'
           'Collecting setuptools\n'
           '  Using cached setuptools-62.3.2-py3-none-any.whl (1.2 MB)\n'
           'Installing collected packages: wheel, setuptools, pip\n'
           '  Attempting uninstall: setuptools\n'
           '    Found existing installation: setuptools 58.1.0\n'
           '    Uninstalling setuptools-58.1.0:\n'
           '      Successfully uninstalled setuptools-58.1.0\n'
           '  Attempting uninstall: pip\n'
           '    Found existing installation: pip 21.2.4\n'
           '    Uninstalling pip-21.2.4:\n'
           '      Successfully uninstalled pip-21.2.4\n'
           'Successfully installed pip-22.1.1 setuptools-62.3.2 wheel-0.37.1\n'

...
...

"ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/gms/config (Caused by "
           "NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff8d19a040>: Failed to establish a new connection: [Errno 111] "
           "Connection refused'))\n"
           '[2022-05-29 14:32:02,715] INFO     {datahub.entrypoints:176} - DataHub CLI version: 0.8.35 at '
           '/tmp/datahub/ingest/venv-54b2173a-cc87-4bc1-a09a-f8d438784026/lib/python3.9/site-packages/datahub/__init__.py\n'


Any help here is greatly appreciated.
