### ISSUE TITLE
Question: How to search database or table under a platform instance?

### ISSUE THREAD

**Issue by kizy008** [linkedin/datahub#4240]
This is not a bug issue.  I have a question about searching.
If I have a mysql platorm instance, and I have thundsands of database in this instance.  I have a keyword about a database I wanted.
If I want to search for it,  what should I do? 
There may be same database name in diffrent platform instances. And I want to fetch the right database in one certain platform instance with `platform_instance` params.
Similary, if there are thounds of tables in one database and I want to fetch one certain table with keyword.  And table name may be the same in diffrent database. How can I search for the table in one certain platform instance and database ?

![企业微信截图_16456855207245](https://user-images.githubusercontent.com/12572997/155473436-a5f24e65-1278-4c93-a2f9-b57b775358a1.png)

**Comment by maggiehays** [comment]
Hi @kizy008!

We recommend leveraging our faceted Search - you can filter by platform, environment, & more. [Here's an overview](https://datahubproject.io/docs/how/search/) of some key functionality of Search.

We'll close this out for now; feel free to [join us in Slack](https://slack.datahubproject.io/) if you have additional questions!

**Comment by kizy008** [comment]
Oh, it's a new document, and I will learn it. Thanks for your reply!

**Comment by kizy008** [comment]
It is solved by using [name] fields in search bar.
![企业微信截图_16460196388132](https://user-images.githubusercontent.com/12572997/155920236-20943894-2e7f-421f-8624-92440846b2ed.png)
