### ISSUE TITLE
Getting Error "KeyError: 'source'" while trying to ingest sample business_glossary through CLI

### ISSUE THREAD

**Issue by jieni0123** [linkedin/datahub#4257]
I have both created the business_glossary.yml file and glossary_to_datahub.yml based on the sample in the repo.
This is how my files look like:
_**business_glossary.yml**_
![image](https://user-images.githubusercontent.com/90783708/155670429-dfa9d5c6-0607-4cb1-9de3-8ae92f378bb7.png)

_**glossary_to_datahub.yml**_
![image](https://user-images.githubusercontent.com/90783708/155670496-858444f1-4129-46fb-9e9e-e9122d6b2f60.png)

When I run the command **_'datahub ingest -c ./my/recipes/dir/glossary_to_datahub.yml'_**, I end up getting the error below:
![image](https://user-images.githubusercontent.com/90783708/155670721-3121c2ba-52cc-4c63-b68a-f4461dac5476.png)

**Comment by anshbansal** [comment]
Please check indentation in `glossary_to_datahub.yml` as per https://datahubproject.io/docs/metadata-ingestion/source_docs/business_glossary/#quickstart-recipe. `file` should be indented.

**Comment by jieni0123** [comment]
@anshbansal Thank you for notifying my error and it is fixed! I will now close the issue.
