### ISSUE TITLE
How to import s3 file metadata without ingesting file content

### ISSUE THREAD

**Issue by anthfm** [linkedin/datahub#4392]
Hello, I am interested in importing metadata of files from S3 storage into DataHub in order to track their lineage, but not import file contents. For example, is it possible to use the REST-API to create metadata that denotes that file_1 was moved from one S3 bucket to another or that file_1 was processed with a particular pipeline to create file_2? However, I do not want to ingest the files themselves into the platform, but rather allow the user to use the REST-API to manually create these metadata entities and lineages. I understand that Apache Atlas currently supports this, but DataHub seems to be a more intuitive for metadata management. I went through the DataHub documentation, but couldn't find a concrete answer to my use-case. 

Thank you for your help

**Comment by jabplana** [comment]
Hello,

I see this issue was closed and I am interested in the answer.  Do you have any insight?

Thanks
